'use strict';

const { nextOccurrence } = require('../../config/audit-schedule.registry');

class AuditSchedulerService {
  constructor({
    scopeModel,
    occurrenceModel,
    dispatcher = null,
    logger = console,
    now = () => new Date(),
  } = {}) {
    if (!scopeModel || !occurrenceModel) throw new Error('scopeModel and occurrenceModel required');
    this.scopeModel = scopeModel;
    this.occurrenceModel = occurrenceModel;
    this.dispatcher = dispatcher;
    this.logger = logger;
    this.now = now;
  }

  async _emit(name, payload) {
    if (!this.dispatcher || typeof this.dispatcher.emit !== 'function') return;
    try {
      await this.dispatcher.emit(name, payload);
    } catch (err) {
      this.logger.warn(`[AuditSched] dispatch ${name} failed: ${err.message}`);
    }
  }

  // ── scope CRUD ───────────────────────────────────────────────────

  async createScope(data, userId) {
    if (!data || !data.name)
      throw Object.assign(new Error('name required'), { code: 'VALIDATION' });
    const doc = await this.scopeModel.create({
      name: data.name,
      description: data.description || null,
      department: data.department || null,
      standardCode: data.standardCode || null,
      clauseCodes: data.clauseCodes || [],
      riskLevel: data.riskLevel || 'medium',
      leadAuditorUserId: data.leadAuditorUserId || null,
      branchId: data.branchId || null,
      tenantId: data.tenantId || null,
      active: data.active !== false,
      notes: data.notes || null,
      createdBy: userId,
    });
    return doc;
  }

  async listScopes({ branchId, riskLevel, active } = {}) {
    const q = { deleted_at: null };
    if (branchId) q.branchId = branchId;
    if (riskLevel) q.riskLevel = riskLevel;
    if (active !== undefined) q.active = active;
    return this.scopeModel.find(q).sort({ nextScheduledDate: 1 });
  }

  // ── auto-generate the next occurrence per scope ──────────────────

  /**
   * For every active scope without a pending (planned/scheduled/in_progress)
   * occurrence, create the next planned one. Returns the list of newly-created
   * occurrences. Idempotent — running twice produces no duplicates.
   */
  async generateUpcoming({ branchId, userId } = {}) {
    const q = { deleted_at: null, active: true };
    if (branchId) q.branchId = branchId;
    const scopes = await this.scopeModel.find(q);
    const created = [];
    for (const scope of scopes) {
      const pending = await this.occurrenceModel.findOne({
        scopeId: scope._id,
        status: { $in: ['planned', 'scheduled', 'in_progress'] },
        deleted_at: null,
      });
      if (pending) continue;
      const plannedFor = nextOccurrence(scope.lastAuditedAt || this.now(), scope.riskLevel);
      const occ = await this.occurrenceModel.create({
        scopeId: scope._id,
        type: 'internal',
        plannedFor,
        leadAuditorUserId: scope.leadAuditorUserId || null,
        branchId: scope.branchId || null,
        tenantId: scope.tenantId || null,
        autoGenerated: true,
        status: 'planned',
        createdBy: userId || scope.createdBy,
      });
      scope.nextScheduledDate = plannedFor;
      await scope.save();
      created.push(occ);
      await this._emit('quality.audit.scheduled', {
        scopeId: String(scope._id),
        occurrenceId: String(occ._id),
        plannedFor,
        riskLevel: scope.riskLevel,
      });
    }
    return created;
  }

  async scheduleOccurrence(id, scheduledFor, userId) {
    const occ = await this.occurrenceModel.findOne({ _id: id, deleted_at: null });
    if (!occ) throw Object.assign(new Error('Audit not found'), { code: 'NOT_FOUND' });
    occ.scheduledFor = new Date(scheduledFor);
    if (occ.status === 'planned') occ.status = 'scheduled';
    occ.updatedBy = userId;
    await occ.save();
    return occ;
  }

  async startOccurrence(id, userId) {
    const occ = await this.occurrenceModel.findOne({ _id: id, deleted_at: null });
    if (!occ) throw Object.assign(new Error('Audit not found'), { code: 'NOT_FOUND' });
    if (!['planned', 'scheduled'].includes(occ.status)) {
      throw Object.assign(new Error('Audit not pending'), { code: 'INVALID_PHASE' });
    }
    occ.status = 'in_progress';
    occ.startedAt = this.now();
    occ.updatedBy = userId;
    await occ.save();
    return occ;
  }

  async recordFinding(id, finding, userId) {
    if (!finding || !finding.type || !finding.description) {
      throw Object.assign(new Error('type and description required'), { code: 'VALIDATION' });
    }
    const occ = await this.occurrenceModel.findOne({ _id: id, deleted_at: null });
    if (!occ) throw Object.assign(new Error('Audit not found'), { code: 'NOT_FOUND' });
    if (!['in_progress', 'reported'].includes(occ.status)) {
      throw Object.assign(new Error('audit not active'), { code: 'INVALID_PHASE' });
    }
    occ.findings.push({
      type: finding.type,
      description: finding.description,
      clauseRef: finding.clauseRef || null,
      evidence: finding.evidence || null,
      ownerUserId: finding.ownerUserId || null,
    });
    occ.updatedBy = userId;
    await occ.save();
    if (finding.type === 'major_nc' || finding.type === 'minor_nc') {
      await this._emit('quality.audit.nc_recorded', {
        occurrenceId: String(occ._id),
        type: finding.type,
        clauseRef: finding.clauseRef || null,
      });
    }
    return occ;
  }

  async closeOccurrence(id, payload, userId) {
    const occ = await this.occurrenceModel.findOne({ _id: id, deleted_at: null });
    if (!occ) throw Object.assign(new Error('Audit not found'), { code: 'NOT_FOUND' });
    if (occ.status !== 'in_progress' && occ.status !== 'reported') {
      throw Object.assign(new Error('audit not closable'), { code: 'INVALID_PHASE' });
    }
    occ.summary = payload.summary || null;
    const hasMajor = occ.findings.some(f => f.type === 'major_nc');
    const hasMinor = occ.findings.some(f => f.type === 'minor_nc');
    occ.overallOutcome = hasMajor ? 'major_nc' : hasMinor ? 'minor_nc' : 'conform';
    occ.endedAt = this.now();
    occ.status = 'closed';
    occ.updatedBy = userId;
    await occ.save();

    // Mark scope as audited.
    const scope = await this.scopeModel.findById(occ.scopeId);
    if (scope) {
      scope.lastAuditedAt = occ.endedAt;
      scope.nextScheduledDate = nextOccurrence(occ.endedAt, scope.riskLevel);
      await scope.save();
    }

    await this._emit('quality.audit.closed', {
      occurrenceId: String(occ._id),
      auditNumber: occ.auditNumber,
      outcome: occ.overallOutcome,
      findingsCount: occ.findings.length,
    });
    return occ;
  }

  // ── queries ──────────────────────────────────────────────────────

  async listOccurrences({ branchId, status, scopeId, limit = 50, skip = 0 } = {}) {
    const q = { deleted_at: null };
    if (branchId) q.branchId = branchId;
    if (status) q.status = status;
    if (scopeId) q.scopeId = scopeId;
    return this.occurrenceModel
      .find(q)
      .sort({ plannedFor: -1 })
      .skip(skip)
      .limit(Math.min(limit, 200));
  }

  async findOccurrenceById(id) {
    return this.occurrenceModel.findOne({ _id: id, deleted_at: null });
  }

  async getDashboard({ branchId } = {}) {
    const q = { deleted_at: null };
    if (branchId) q.branchId = branchId;
    const now = this.now();
    const [total, byStatus, overdue, dueIn30, openMajorNc] = await Promise.all([
      this.occurrenceModel.countDocuments(q),
      this.occurrenceModel.aggregate([
        { $match: q },
        { $group: { _id: '$status', count: { $sum: 1 } } },
      ]),
      this.occurrenceModel.countDocuments({
        ...q,
        status: { $in: ['planned', 'scheduled'] },
        plannedFor: { $lt: now },
      }),
      this.occurrenceModel.countDocuments({
        ...q,
        status: { $in: ['planned', 'scheduled'] },
        plannedFor: { $gte: now, $lte: new Date(now.getTime() + 30 * 86400000) },
      }),
      this.occurrenceModel.countDocuments({ ...q, 'findings.type': 'major_nc', status: 'closed' }),
    ]);
    const statusMap = {};
    for (const r of byStatus) statusMap[r._id] = r.count;
    return { total, byStatus: statusMap, overdue, dueIn30, openMajorNc };
  }
}

function createAuditSchedulerService(deps) {
  return new AuditSchedulerService(deps);
}

let _defaultInstance = null;
function getDefault() {
  if (!_defaultInstance) {
    const scopeModel = require('../../models/quality/AuditScope.model');
    const occurrenceModel = require('../../models/quality/AuditOccurrence.model');
    let dispatcher = null;
    try {
      const bus = require('./qualityEventBus.service');
      if (typeof bus.getDefault === 'function') dispatcher = bus.getDefault();
    } catch (_) {
      /* optional */
    }
    _defaultInstance = new AuditSchedulerService({ scopeModel, occurrenceModel, dispatcher });
  }
  return _defaultInstance;
}

function _replaceDefault(instance) {
  _defaultInstance = instance;
}

module.exports = {
  AuditSchedulerService,
  createAuditSchedulerService,
  getDefault,
  _replaceDefault,
};
