/**
 * EducationRehab – shared constants, config maps & demo data.
 */
import {
  MenuBook as KnowledgeIcon,
  Article as CMSIcon,
  ChildCare as MontessoriIcon,
  Accessibility as ProgramsIcon,
  People as CommunityIcon,
} from '@mui/icons-material';
import { statusColors as paletteStatus } from '../../theme/palette';

// ── Chip color map ──────────────────────────
export const statusColors = {
  published: 'success',
  active: 'success',
  draft: 'default',
  completed: 'info',
  archived: 'default',
  'in-progress': 'warning',
  planned: 'info',
  suspended: 'error',
};

// ── Tab definitions ─────────────────────────
export const tabs = [
  { label: 'قاعدة المعرفة', icon: <KnowledgeIcon />, key: 'knowledge' },
  { label: 'إدارة المحتوى', icon: <CMSIcon />, key: 'cms' },
  { label: 'مونتيسوري', icon: <MontessoriIcon />, key: 'montessori' },
  { label: 'البرامج المتخصصة', icon: <ProgramsIcon />, key: 'programs' },
  { label: 'التوعية المجتمعية', icon: <CommunityIcon />, key: 'community' },
];

// ── Stats builder ───────────────────────────
export const buildStats = data => [
  {
    label: 'مقالات المعرفة',
    value: (Array.isArray(data.knowledge) ? data.knowledge : []).length,
    color: paletteStatus.success,
  },
  {
    label: 'صفحات المحتوى',
    value: (Array.isArray(data.cms) ? data.cms : []).length,
    color: paletteStatus.info,
  },
  {
    label: 'البرامج النشطة',
    value: (Array.isArray(data.programs) ? data.programs : []).filter(p => p.status === 'active')
      .length,
    color: paletteStatus.warning,
  },
  {
    label: 'المستفيدون',
    value: (Array.isArray(data.programs) ? data.programs : []).reduce(
      (sum, p) => sum + (p.beneficiaries || 0),
      0
    ),
    color: paletteStatus.purple,
  },
];

// ── Column definitions per tab ──────────────
export const colMap = {
  knowledge: {
    cols: ['title', 'category', 'author', 'type', 'status', 'views', 'lastUpdated'],
    headers: ['العنوان', 'الفئة', 'الكاتب', 'النوع', 'الحالة', 'المشاهدات', 'آخر تحديث'],
  },
  cms: {
    cols: ['title', 'slug', 'type', 'status', 'author', 'lastModified'],
    headers: ['العنوان', 'الرابط', 'النوع', 'الحالة', 'الكاتب', 'آخر تعديل'],
  },
  montessori: {
    cols: ['name', 'ageGroup', 'capacity', 'enrolled', 'instructor', 'status', 'schedule'],
    headers: ['البرنامج', 'الفئة العمرية', 'السعة', 'المسجلون', 'المعلم', 'الحالة', 'الجدول'],
  },
  programs: {
    cols: [
      'name',
      'type',
      'targetDisability',
      'beneficiaries',
      'duration',
      'sessionsPerWeek',
      'supervisor',
      'status',
      'startDate',
    ],
    headers: [
      'البرنامج',
      'النوع',
      'الإعاقة المستهدفة',
      'المستفيدون',
      'المدة',
      'جلسات/أسبوع',
      'المشرف',
      'الحالة',
      'تاريخ البدء',
    ],
  },
  community: {
    cols: ['title', 'type', 'targetAudience', 'date', 'location', 'status', 'participants'],
    headers: ['الفعالية', 'النوع', 'الجمهور المستهدف', 'التاريخ', 'الموقع', 'الحالة', 'المشاركون'],
  },
};

// ── Form field definitions per tab ──────────
export const fieldSets = {
  knowledge: [
    { key: 'title', label: 'العنوان' },
    { key: 'category', label: 'الفئة' },
    { key: 'author', label: 'الكاتب' },
    { key: 'type', label: 'النوع' },
  ],
  cms: [
    { key: 'title', label: 'العنوان' },
    { key: 'slug', label: 'الرابط' },
    { key: 'type', label: 'النوع' },
    { key: 'author', label: 'الكاتب' },
  ],
  montessori: [
    { key: 'name', label: 'اسم البرنامج' },
    { key: 'ageGroup', label: 'الفئة العمرية' },
    { key: 'capacity', label: 'السعة', type: 'number' },
    { key: 'instructor', label: 'المعلم' },
    { key: 'schedule', label: 'الجدول' },
  ],
  programs: [
    { key: 'name', label: 'اسم البرنامج' },
    { key: 'type', label: 'النوع' },
    { key: 'targetDisability', label: 'الإعاقة المستهدفة' },
    { key: 'beneficiaries', label: 'المستفيدون', type: 'number' },
    { key: 'duration', label: 'المدة' },
    { key: 'sessionsPerWeek', label: 'الجلسات/أسبوع', type: 'number' },
    { key: 'supervisor', label: 'المشرف' },
    { key: 'startDate', label: 'تاريخ البدء', type: 'date' },
    { key: 'goals', label: 'الأهداف الرئيسية' },
  ],
  community: [
    { key: 'title', label: 'الفعالية' },
    { key: 'type', label: 'النوع' },
    { key: 'targetAudience', label: 'الجمهور المستهدف' },
    { key: 'date', label: 'التاريخ', type: 'date' },
    { key: 'location', label: 'الموقع' },
  ],
};

// ── Demo / fallback data ────────────────────
export const demoData = {
  knowledge: [
    {
      _id: '1',
      title: 'دليل إجراءات التأهيل',
      category: 'تأهيل',
      author: 'د. أحمد',
      type: 'دليل',
      status: 'published',
      views: 234,
      lastUpdated: '2026-03-01',
    },
    {
      _id: '2',
      title: 'بروتوكول العلاج الطبيعي',
      category: 'علاج',
      author: 'د. سارة',
      type: 'بروتوكول',
      status: 'published',
      views: 189,
      lastUpdated: '2026-02-20',
    },
    {
      _id: '3',
      title: 'معايير السلامة في المختبرات',
      category: 'سلامة',
      author: 'م. خالد',
      type: 'معيار',
      status: 'draft',
      views: 45,
      lastUpdated: '2026-03-05',
    },
  ],
  cms: [
    {
      _id: '1',
      title: 'الصفحة الرئيسية',
      slug: 'home',
      type: 'صفحة',
      status: 'published',
      author: 'المدير',
      lastModified: '2026-03-08',
      language: 'العربية',
    },
    {
      _id: '2',
      title: 'عن المركز',
      slug: 'about',
      type: 'صفحة',
      status: 'published',
      author: 'التسويق',
      lastModified: '2026-03-05',
      language: 'العربية',
    },
    {
      _id: '3',
      title: 'أخبار المركز - مارس 2026',
      slug: 'news-march-2026',
      type: 'مقال',
      status: 'draft',
      author: 'التسويق',
      lastModified: '2026-03-07',
      language: 'العربية',
    },
  ],
  montessori: [
    {
      _id: '1',
      name: 'برنامج مونتيسوري - المرحلة الأولى',
      ageGroup: '3-6 سنوات',
      capacity: 15,
      enrolled: 12,
      instructor: 'أ. نورة',
      status: 'active',
      schedule: 'أحد-خميس 8:00-12:00',
    },
    {
      _id: '2',
      name: 'برنامج مونتيسوري - المرحلة الثانية',
      ageGroup: '6-9 سنوات',
      capacity: 12,
      enrolled: 10,
      instructor: 'أ. فاطمة',
      status: 'active',
      schedule: 'أحد-خميس 8:00-13:00',
    },
    {
      _id: '3',
      name: 'برنامج التعلم المبكر',
      ageGroup: '2-3 سنوات',
      capacity: 8,
      enrolled: 6,
      instructor: 'أ. سمية',
      status: 'active',
      schedule: 'أحد-أربعاء 9:00-11:00',
    },
  ],
  programs: [
    {
      _id: '1',
      name: 'برنامج التأهيل الحركي المتكامل',
      type: 'علاج طبيعي',
      targetDisability: 'إعاقة حركية',
      beneficiaries: 25,
      duration: '12 أسبوع',
      sessionsPerWeek: 3,
      status: 'active',
      supervisor: 'د. محمد',
      startDate: '2026-01-15',
      goals: 'تحسين المدى الحركي، تقوية العضلات، زيادة الاستقلالية في التنقل',
      outcomes: { completionRate: 78, avgImprovement: 22 },
    },
    {
      _id: '2',
      name: 'برنامج النطق والتخاطب التطويري',
      type: 'علاج نطق',
      targetDisability: 'اضطرابات النطق والكلام',
      beneficiaries: 18,
      duration: '16 أسبوع',
      sessionsPerWeek: 2,
      status: 'active',
      supervisor: 'د. ليلى',
      startDate: '2026-02-01',
      goals: 'تطوير مهارات النطق، تحسين الطلاقة اللفظية، تعزيز التواصل الوظيفي',
      outcomes: { completionRate: 85, avgImprovement: 30 },
    },
    {
      _id: '3',
      name: 'برنامج التأهيل المهني والتشغيلي',
      type: 'تأهيل مهني',
      targetDisability: 'إعاقة ذهنية',
      beneficiaries: 20,
      duration: '24 أسبوع',
      sessionsPerWeek: 5,
      status: 'in-progress',
      supervisor: 'أ. سعود',
      startDate: '2025-12-01',
      goals: 'اكتساب مهارات مهنية عملية، التدريب على بيئة العمل، تحسين الاستقلالية',
      outcomes: { completionRate: 60, avgImprovement: 18 },
    },
    {
      _id: '4',
      name: 'برنامج الدعم النفسي والإرشادي',
      type: 'نفسي',
      targetDisability: 'جميع الإعاقات',
      beneficiaries: 30,
      duration: '8 أسابيع',
      sessionsPerWeek: 1,
      status: 'planned',
      supervisor: 'د. هند',
      startDate: '2026-04-01',
      goals: 'تعزيز الصحة النفسية، بناء مهارات التكيف، دعم الأسرة',
      outcomes: { completionRate: 0, avgImprovement: 0 },
    },
    {
      _id: '5',
      name: 'برنامج التكامل الحسي',
      type: 'علاج وظيفي',
      targetDisability: 'اضطراب طيف التوحد',
      beneficiaries: 15,
      duration: '20 أسبوع',
      sessionsPerWeek: 3,
      status: 'active',
      supervisor: 'أ. هند العتيبي',
      startDate: '2026-01-20',
      goals: 'تنظيم المعالجة الحسية، تقليل الدفاعية اللمسية، تحسين التنظيم الذاتي',
      outcomes: { completionRate: 72, avgImprovement: 25 },
    },
    {
      _id: '6',
      name: 'برنامج التدخل المبكر',
      type: 'تدخل مبكر',
      targetDisability: 'تأخر نمائي',
      beneficiaries: 12,
      duration: '32 أسبوع',
      sessionsPerWeek: 4,
      status: 'active',
      supervisor: 'د. سارة أحمد',
      startDate: '2025-11-01',
      goals: 'تسريع النمو في المجالات المتأخرة، تدريب الأسرة، تعزيز التواصل المبكر',
      outcomes: { completionRate: 88, avgImprovement: 35 },
    },
    {
      _id: '7',
      name: 'برنامج تحليل السلوك التطبيقي (ABA)',
      type: 'سلوكي',
      targetDisability: 'اضطراب طيف التوحد',
      beneficiaries: 10,
      duration: '40 أسبوع',
      sessionsPerWeek: 5,
      status: 'active',
      supervisor: 'أ. منيرة العلي',
      startDate: '2025-09-15',
      goals: 'تعديل السلوكيات غير المرغوبة، تعليم المهارات الاجتماعية، زيادة التواصل',
      outcomes: { completionRate: 65, avgImprovement: 28 },
    },
    {
      _id: '8',
      name: 'برنامج العلاج بالموسيقى والفنون',
      type: 'علاج إبداعي',
      targetDisability: 'إعاقة متعددة',
      beneficiaries: 22,
      duration: '16 أسبوع',
      sessionsPerWeek: 2,
      status: 'active',
      supervisor: 'أ. رانيا محمود',
      startDate: '2026-02-10',
      goals: 'تعزيز التعبير الذاتي، تحسين المهارات الحركية الدقيقة، تقليل القلق',
      outcomes: { completionRate: 82, avgImprovement: 20 },
    },
    {
      _id: '9',
      name: 'برنامج التأهيل بالتقنيات المساعدة',
      type: 'تقنيات مساعدة',
      targetDisability: 'إعاقة حركية',
      beneficiaries: 14,
      duration: '10 أسابيع',
      sessionsPerWeek: 2,
      status: 'in-progress',
      supervisor: 'م. عبدالرحمن',
      startDate: '2026-02-20',
      goals: 'التدريب على الأجهزة المساعدة، تكييف البيئة، وسائل الاتصال البديلة',
      outcomes: { completionRate: 45, avgImprovement: 15 },
    },
    {
      _id: '10',
      name: 'برنامج المهارات الاجتماعية المتقدم',
      type: 'تأهيل اجتماعي',
      targetDisability: 'جميع الإعاقات',
      beneficiaries: 16,
      duration: '12 أسبوع',
      sessionsPerWeek: 2,
      status: 'planned',
      supervisor: 'أ. نورة خالد',
      startDate: '2026-04-15',
      goals: 'تطوير مهارات التفاعل، بناء الصداقات، الدمج المجتمعي',
      outcomes: { completionRate: 0, avgImprovement: 0 },
    },
  ],
  community: [
    {
      _id: '1',
      title: 'حملة التوعية بحقوق ذوي الإعاقة',
      type: 'توعية',
      targetAudience: 'المجتمع',
      date: '2026-03-21',
      location: 'قاعة المؤتمرات',
      status: 'planned',
      participants: 0,
    },
    {
      _id: '2',
      title: 'ورشة عمل - دمج ذوي الإعاقة',
      type: 'ورشة عمل',
      targetAudience: 'أولياء الأمور',
      date: '2026-02-28',
      location: 'المركز الرئيسي',
      status: 'completed',
      participants: 45,
    },
    {
      _id: '3',
      title: 'يوم مفتوح للمجتمع',
      type: 'فعالية',
      targetAudience: 'الجميع',
      date: '2026-04-15',
      location: 'المركز الرئيسي',
      status: 'planned',
      participants: 0,
    },
  ],
};
