/**
 * Canonical KPI Definitions Registry.
 *
 * Each KPI is a plain JS object with:
 *   - id (kebab-case, unique, stable across releases)
 *   - nameAr / nameEn (human labels)
 *   - category (one of CATEGORIES)
 *   - unit (% | count | sar | days | hours | score)
 *   - direction (higher_is_better | lower_is_better)
 *   - owner (role level responsible for the KPI)
 *   - description (what it measures, one sentence)
 *   - formula (plain-language formula reference)
 *   - cadence (real_time | daily | weekly | monthly | quarterly)
 *
 * Source of truth for Executive BI dashboard + compute engine.
 * See docs/blueprint/09-roadmap.md § P1.7.
 */

'use strict';

const CATEGORIES = {
  CLINICAL: 'clinical',
  FINANCIAL: 'financial',
  OPERATIONAL: 'operational',
  QUALITY: 'quality',
  HR: 'hr',
  COMPLIANCE: 'compliance',
};

const definitions = [
  // ════════════════════════════════
  // Clinical (10)
  // ════════════════════════════════
  {
    id: 'active-beneficiaries',
    nameAr: 'عدد المستفيدين النشطين',
    nameEn: 'Active Beneficiaries',
    category: CATEGORIES.CLINICAL,
    unit: 'count',
    direction: 'higher_is_better',
    owner: 'L3',
    cadence: 'daily',
    formula: 'count(Beneficiary where admissionStatus=active)',
  },
  {
    id: 'new-admissions-month',
    nameAr: 'قبولات جديدة (شهرياً)',
    nameEn: 'New Admissions (Monthly)',
    category: CATEGORIES.CLINICAL,
    unit: 'count',
    direction: 'higher_is_better',
    owner: 'L3',
    cadence: 'monthly',
    formula: 'count(Beneficiary where admissionDate in month)',
  },
  {
    id: 'goal-achievement-rate',
    nameAr: 'معدل تحقيق الأهداف',
    nameEn: 'Goal Achievement Rate',
    category: CATEGORIES.CLINICAL,
    unit: '%',
    direction: 'higher_is_better',
    owner: 'L4',
    cadence: 'monthly',
    formula: 'goals[status=achieved] / goals[targeted in period]',
  },
  {
    id: 'irp-on-time-approval',
    nameAr: 'اعتماد IRP في الوقت',
    nameEn: 'IRP Approved On Time',
    category: CATEGORIES.CLINICAL,
    unit: '%',
    direction: 'higher_is_better',
    owner: 'L4',
    cadence: 'monthly',
    formula: 'IRPs approved ≤14d after assessment / total IRPs',
  },
  {
    id: 'sessions-completed',
    nameAr: 'الجلسات المكتملة',
    nameEn: 'Sessions Completed',
    category: CATEGORIES.CLINICAL,
    unit: 'count',
    direction: 'higher_is_better',
    owner: 'L4',
    cadence: 'daily',
    formula: 'count(Session where status=completed)',
  },
  {
    id: 'no-show-rate',
    nameAr: 'معدل الغياب بدون إشعار',
    nameEn: 'No-Show Rate',
    category: CATEGORIES.CLINICAL,
    unit: '%',
    direction: 'lower_is_better',
    owner: 'L3',
    cadence: 'weekly',
    formula: 'no_show_sessions / scheduled_sessions',
  },
  {
    id: 'progress-measurements-week',
    nameAr: 'قياسات التقدم أسبوعياً',
    nameEn: 'Progress Measurements per Week',
    category: CATEGORIES.CLINICAL,
    unit: 'count',
    direction: 'higher_is_better',
    owner: 'L4',
    cadence: 'weekly',
    formula: 'count(Measurement)/goals',
  },
  {
    id: 'discharge-goal-met-rate',
    nameAr: 'معدل الإنهاء بتحقيق الأهداف',
    nameEn: 'Goal-Met Discharge Rate',
    category: CATEGORIES.CLINICAL,
    unit: '%',
    direction: 'higher_is_better',
    owner: 'L4',
    cadence: 'quarterly',
    formula: 'discharges with majority goals met / total discharges',
  },
  {
    id: 'avg-time-to-irp',
    nameAr: 'متوسط زمن إنشاء IRP',
    nameEn: 'Avg Days Intake→IRP Activated',
    category: CATEGORIES.CLINICAL,
    unit: 'days',
    direction: 'lower_is_better',
    owner: 'L4',
    cadence: 'monthly',
    formula: 'avg(IRP.activatedAt - Beneficiary.admissionDate)',
  },
  {
    id: 'caseload-per-therapist',
    nameAr: 'متوسط الحالات لكل معالج',
    nameEn: 'Avg Caseload per Therapist',
    category: CATEGORIES.CLINICAL,
    unit: 'count',
    direction: 'neutral',
    owner: 'L4',
    cadence: 'weekly',
    formula: 'active_beneficiaries / active_therapists',
  },

  // ════════════════════════════════
  // Financial (10)
  // ════════════════════════════════
  {
    id: 'revenue-month',
    nameAr: 'الإيرادات الشهرية',
    nameEn: 'Revenue (Monthly)',
    category: CATEGORIES.FINANCIAL,
    unit: 'sar',
    direction: 'higher_is_better',
    owner: 'L2',
    cadence: 'monthly',
    formula: 'sum(Invoice.total where paid in month)',
  },
  {
    id: 'outstanding-ar',
    nameAr: 'الذمم المدينة القائمة',
    nameEn: 'Outstanding AR',
    category: CATEGORIES.FINANCIAL,
    unit: 'sar',
    direction: 'lower_is_better',
    owner: 'L3',
    cadence: 'daily',
    formula: 'sum(Invoice.outstandingAmount)',
  },
  {
    id: 'ar-aging-60d',
    nameAr: 'ذمم مدينة >60 يوم',
    nameEn: 'AR Aging >60 days',
    category: CATEGORIES.FINANCIAL,
    unit: 'sar',
    direction: 'lower_is_better',
    owner: 'L3',
    cadence: 'weekly',
    formula: 'sum(Invoice.outstandingAmount where issuedAt > 60d ago)',
  },
  {
    id: 'zatca-acceptance-rate',
    nameAr: 'معدل قبول فواتير ZATCA',
    nameEn: 'ZATCA Acceptance Rate',
    category: CATEGORIES.FINANCIAL,
    unit: '%',
    direction: 'higher_is_better',
    owner: 'L3',
    cadence: 'daily',
    formula: 'zatca_accepted / zatca_submitted',
  },
  {
    id: 'collection-rate',
    nameAr: 'معدل التحصيل',
    nameEn: 'Collection Rate',
    category: CATEGORIES.FINANCIAL,
    unit: '%',
    direction: 'higher_is_better',
    owner: 'L3',
    cadence: 'monthly',
    formula: 'payments_received / invoices_issued (same period)',
  },
  {
    id: 'insurance-claim-approval-rate',
    nameAr: 'معدل قبول مطالبات التأمين',
    nameEn: 'Insurance Claim Approval Rate',
    category: CATEGORIES.FINANCIAL,
    unit: '%',
    direction: 'higher_is_better',
    owner: 'L3',
    cadence: 'monthly',
    formula: 'claims_approved / claims_submitted',
  },
  {
    id: 'expense-vs-budget',
    nameAr: 'المصاريف مقابل الميزانية',
    nameEn: 'Expenses vs Budget',
    category: CATEGORIES.FINANCIAL,
    unit: '%',
    direction: 'lower_is_better',
    owner: 'L3',
    cadence: 'monthly',
    formula: 'actual_expense / budgeted',
  },
  {
    id: 'revenue-per-beneficiary',
    nameAr: 'إيراد للمستفيد',
    nameEn: 'Revenue per Active Beneficiary',
    category: CATEGORIES.FINANCIAL,
    unit: 'sar',
    direction: 'higher_is_better',
    owner: 'L2',
    cadence: 'monthly',
    formula: 'revenue / active_beneficiaries',
  },
  {
    id: 'operating-margin',
    nameAr: 'هامش التشغيل',
    nameEn: 'Operating Margin',
    category: CATEGORIES.FINANCIAL,
    unit: '%',
    direction: 'higher_is_better',
    owner: 'L2',
    cadence: 'monthly',
    formula: '(revenue - expenses) / revenue',
  },
  {
    id: 'cash-days-on-hand',
    nameAr: 'أيام السيولة',
    nameEn: 'Days Cash on Hand',
    category: CATEGORIES.FINANCIAL,
    unit: 'days',
    direction: 'higher_is_better',
    owner: 'L2',
    cadence: 'weekly',
    formula: 'cash_balance / avg_daily_opex',
  },

  // ════════════════════════════════
  // Operational (10)
  // ════════════════════════════════
  {
    id: 'room-utilization',
    nameAr: 'استخدام الغرف',
    nameEn: 'Room Utilization',
    category: CATEGORIES.OPERATIONAL,
    unit: '%',
    direction: 'higher_is_better',
    owner: 'L3',
    cadence: 'weekly',
    formula: 'hours_booked / hours_available',
  },
  {
    id: 'therapist-utilization',
    nameAr: 'استخدام المعالجين',
    nameEn: 'Therapist Utilization',
    category: CATEGORIES.OPERATIONAL,
    unit: '%',
    direction: 'higher_is_better',
    owner: 'L4',
    cadence: 'weekly',
    formula: 'billable_hours / scheduled_hours',
  },
  {
    id: 'appointment-confirm-rate',
    nameAr: 'معدل تأكيد المواعيد',
    nameEn: 'Appointment Confirmation Rate',
    category: CATEGORIES.OPERATIONAL,
    unit: '%',
    direction: 'higher_is_better',
    owner: 'L5',
    cadence: 'daily',
    formula: 'confirmed / booked',
  },
  {
    id: 'transport-on-time',
    nameAr: 'التزام النقل بالوقت',
    nameEn: 'Transport On-Time %',
    category: CATEGORIES.OPERATIONAL,
    unit: '%',
    direction: 'higher_is_better',
    owner: 'L5',
    cadence: 'weekly',
    formula: 'on_time_trips / total_trips',
  },
  {
    id: 'avg-session-duration',
    nameAr: 'متوسط مدة الجلسة',
    nameEn: 'Avg Session Duration',
    category: CATEGORIES.OPERATIONAL,
    unit: 'minutes',
    direction: 'neutral',
    owner: 'L4',
    cadence: 'weekly',
    formula: 'avg(endedAt - startedAt)',
  },
  {
    id: 'scheduling-conflicts',
    nameAr: 'تعارضات الجدولة',
    nameEn: 'Scheduling Conflicts',
    category: CATEGORIES.OPERATIONAL,
    unit: 'count',
    direction: 'lower_is_better',
    owner: 'L3',
    cadence: 'weekly',
    formula: 'count(conflicts detected)',
  },
  {
    id: 'document-upload-compliance',
    nameAr: 'استكمال الوثائق',
    nameEn: 'Document Upload Compliance',
    category: CATEGORIES.OPERATIONAL,
    unit: '%',
    direction: 'higher_is_better',
    owner: 'L3',
    cadence: 'monthly',
    formula: 'complete_profiles / total_profiles',
  },
  {
    id: 'branch-capacity',
    nameAr: 'الطاقة الاستيعابية للفرع',
    nameEn: 'Branch Capacity Utilization',
    category: CATEGORIES.OPERATIONAL,
    unit: '%',
    direction: 'higher_is_better',
    owner: 'L3',
    cadence: 'weekly',
    formula: 'active_beneficiaries / capacity',
  },
  {
    id: 'vehicle-availability',
    nameAr: 'جاهزية المركبات',
    nameEn: 'Vehicle Availability',
    category: CATEGORIES.OPERATIONAL,
    unit: '%',
    direction: 'higher_is_better',
    owner: 'L5',
    cadence: 'weekly',
    formula: 'vehicles_ready / total_fleet',
  },
  {
    id: 'inventory-stockouts',
    nameAr: 'انقطاعات المخزون',
    nameEn: 'Inventory Stockouts',
    category: CATEGORIES.OPERATIONAL,
    unit: 'count',
    direction: 'lower_is_better',
    owner: 'L3',
    cadence: 'weekly',
    formula: 'count(items with qty=0)',
  },

  // ════════════════════════════════
  // Quality (8)
  // ════════════════════════════════
  {
    id: 'incidents-open',
    nameAr: 'الحوادث المفتوحة',
    nameEn: 'Open Incidents',
    category: CATEGORIES.QUALITY,
    unit: 'count',
    direction: 'lower_is_better',
    owner: 'L2',
    cadence: 'daily',
    formula: 'count(Incident where status in [open, under_investigation])',
  },
  {
    id: 'incident-close-sla',
    nameAr: 'إقفال الحوادث في SLA',
    nameEn: 'Incident Closure SLA',
    category: CATEGORIES.QUALITY,
    unit: '%',
    direction: 'higher_is_better',
    owner: 'L2',
    cadence: 'monthly',
    formula: 'incidents closed within SLA / total closed',
  },
  {
    id: 'capa-overdue',
    nameAr: 'CAPAs متأخرة',
    nameEn: 'CAPAs Overdue',
    category: CATEGORIES.QUALITY,
    unit: 'count',
    direction: 'lower_is_better',
    owner: 'L2',
    cadence: 'weekly',
    formula: 'count(CAPA where dueDate < now and status != closed)',
  },
  {
    id: 'complaints-open',
    nameAr: 'شكاوى مفتوحة',
    nameEn: 'Open Complaints',
    category: CATEGORIES.QUALITY,
    unit: 'count',
    direction: 'lower_is_better',
    owner: 'L3',
    cadence: 'daily',
    formula: 'count(Complaint where status != resolved)',
  },
  {
    id: 'complaint-response-time',
    nameAr: 'زمن الرد على الشكاوى',
    nameEn: 'Avg Complaint Response Time',
    category: CATEGORIES.QUALITY,
    unit: 'hours',
    direction: 'lower_is_better',
    owner: 'L3',
    cadence: 'weekly',
    formula: 'avg(firstResponseAt - createdAt)',
  },
  {
    id: 'nps',
    nameAr: 'مؤشر NPS',
    nameEn: 'NPS',
    category: CATEGORIES.QUALITY,
    unit: 'score',
    direction: 'higher_is_better',
    owner: 'L2',
    cadence: 'quarterly',
    formula: '%promoters - %detractors',
  },
  {
    id: 'csat',
    nameAr: 'رضا العملاء CSAT',
    nameEn: 'CSAT',
    category: CATEGORIES.QUALITY,
    unit: '%',
    direction: 'higher_is_better',
    owner: 'L3',
    cadence: 'monthly',
    formula: 'top-2-box ratings / total ratings',
  },
  {
    id: 'cbahi-readiness',
    nameAr: 'جاهزية CBAHI',
    nameEn: 'CBAHI Readiness',
    category: CATEGORIES.QUALITY,
    unit: '%',
    direction: 'higher_is_better',
    owner: 'L2',
    cadence: 'quarterly',
    formula: 'standards_met / total_standards',
  },

  // ════════════════════════════════
  // HR (7)
  // ════════════════════════════════
  {
    id: 'headcount',
    nameAr: 'عدد الموظفين',
    nameEn: 'Headcount',
    category: CATEGORIES.HR,
    unit: 'count',
    direction: 'neutral',
    owner: 'L2',
    cadence: 'daily',
    formula: 'count(Employee where status=active)',
  },
  {
    id: 'turnover-rate',
    nameAr: 'معدل الدوران',
    nameEn: 'Turnover Rate',
    category: CATEGORIES.HR,
    unit: '%',
    direction: 'lower_is_better',
    owner: 'L2',
    cadence: 'monthly',
    formula: 'terminations / avg_headcount',
  },
  {
    id: 'saudization-ratio',
    nameAr: 'نسبة السعودة',
    nameEn: 'Saudization Ratio',
    category: CATEGORIES.HR,
    unit: '%',
    direction: 'higher_is_better',
    owner: 'L2',
    cadence: 'monthly',
    formula: 'saudi_employees / total_employees',
  },
  {
    id: 'absence-rate',
    nameAr: 'معدل الغياب',
    nameEn: 'Absence Rate',
    category: CATEGORIES.HR,
    unit: '%',
    direction: 'lower_is_better',
    owner: 'L3',
    cadence: 'weekly',
    formula: 'absent_days / total_workable_days',
  },
  {
    id: 'training-hours-per-fte',
    nameAr: 'ساعات التدريب لكل موظف',
    nameEn: 'Training Hours per FTE',
    category: CATEGORIES.HR,
    unit: 'hours',
    direction: 'higher_is_better',
    owner: 'L2',
    cadence: 'quarterly',
    formula: 'total_training_hours / headcount',
  },
  {
    id: 'credential-expiring-30d',
    nameAr: 'رخص تنتهي خلال 30 يوم',
    nameEn: 'Credentials Expiring ≤30d',
    category: CATEGORIES.HR,
    unit: 'count',
    direction: 'lower_is_better',
    owner: 'L3',
    cadence: 'weekly',
    formula: 'count(Credential where expiry < now+30d and status=verified)',
  },
  {
    id: 'payroll-accuracy',
    nameAr: 'دقة الرواتب',
    nameEn: 'Payroll Accuracy',
    category: CATEGORIES.HR,
    unit: '%',
    direction: 'higher_is_better',
    owner: 'L2',
    cadence: 'monthly',
    formula: 'correct_slips / total_slips',
  },

  // ════════════════════════════════
  // Compliance (5)
  // ════════════════════════════════
  {
    id: 'pdpl-consent-coverage',
    nameAr: 'تغطية موافقات PDPL',
    nameEn: 'PDPL Consent Coverage',
    category: CATEGORIES.COMPLIANCE,
    unit: '%',
    direction: 'higher_is_better',
    owner: 'L2',
    cadence: 'weekly',
    formula: 'beneficiaries_with_active_consent / total_active_beneficiaries',
  },
  {
    id: 'audit-coverage-writes',
    nameAr: 'تغطية سجل التدقيق للكتابات',
    nameEn: 'Audit Coverage (Writes)',
    category: CATEGORIES.COMPLIANCE,
    unit: '%',
    direction: 'higher_is_better',
    owner: 'L1',
    cadence: 'monthly',
    formula: 'write_endpoints_audited / total_write_endpoints',
  },
  {
    id: 'policy-acknowledgment-rate',
    nameAr: 'نسبة اعتماد السياسات',
    nameEn: 'Policy Acknowledgment Rate',
    category: CATEGORIES.COMPLIANCE,
    unit: '%',
    direction: 'higher_is_better',
    owner: 'L2',
    cadence: 'quarterly',
    formula: 'acks_signed_within_30d / staff_notified',
  },
  {
    id: 'data-subject-requests-sla',
    nameAr: 'SLA طلبات صاحب البيانات',
    nameEn: 'DSR SLA Compliance',
    category: CATEGORIES.COMPLIANCE,
    unit: '%',
    direction: 'higher_is_better',
    owner: 'L2',
    cadence: 'monthly',
    formula: 'requests_answered_within_30d / total_requests',
  },
  {
    id: 'breach-count',
    nameAr: 'حوادث اختراق البيانات',
    nameEn: 'Data Breach Incidents',
    category: CATEGORIES.COMPLIANCE,
    unit: 'count',
    direction: 'lower_is_better',
    owner: 'L1',
    cadence: 'monthly',
    formula: 'count(Incident where category=data_breach)',
  },
];

// Runtime sanity (dev-time check)
(function validate() {
  const ids = new Set();
  for (const d of definitions) {
    if (!d.id || typeof d.id !== 'string') throw new Error('kpi.id missing');
    if (ids.has(d.id)) throw new Error(`kpi.id duplicated: ${d.id}`);
    ids.add(d.id);
    if (!Object.values(CATEGORIES).includes(d.category)) {
      throw new Error(`kpi ${d.id} has invalid category ${d.category}`);
    }
  }
})();

module.exports = {
  CATEGORIES,
  definitions,
  byId(id) {
    return definitions.find(d => d.id === id);
  },
  byCategory(cat) {
    return definitions.filter(d => d.category === cat);
  },
  count() {
    return definitions.length;
  },
};
