/**
 * Auto-generated tests for seeds/admin-users.seed.js
 * Validates syntax, structure, and patterns (module — 135L)
 * @generated by P#106 universal generator
 */
'use strict';

const fs = require('fs');
const path = require('path');
const vm = require('vm');

const SRC = path.resolve(__dirname, '../../seeds/admin-users.seed.js');

describe('seeds/admin-users.seed.js', () => {
  let source;
  beforeAll(() => {
    source = fs.readFileSync(SRC, 'utf8');
  });

  test('file exists', () => {
    expect(fs.existsSync(SRC)).toBe(true);
  });

  test('is syntactically valid JavaScript', () => {
    expect(() => new vm.Script(source, { filename: 'admin-users.seed.js' })).not.toThrow();
  });

  test('has npm dependencies (3)', () => {
    const npms = (source.match(/require\s*\(\s*['"](?![./])[^'"]+['"]\s*\)/g) || []);
    expect(npms.length).toBe(3);
  });

  test('has module.exports', () => {
    expect(source).toMatch(/module\.exports/);
  });

  test('exports seed', () => {
    expect(source).toMatch(/seed/);
  });

  test('exports down', () => {
    expect(source).toMatch(/down/);
  });
});
