/**
 * Auto-generated tests for validations/community-program.validation.js
 * Validates syntax, structure, and patterns (validator — 156L)
 * @generated by P#106 universal generator
 */
'use strict';

const fs = require('fs');
const path = require('path');
const vm = require('vm');

const SRC = path.resolve(__dirname, '../../validations/community-program.validation.js');

describe('validations/community-program.validation.js', () => {
  let source;
  beforeAll(() => {
    source = fs.readFileSync(SRC, 'utf8');
  });

  test('file exists', () => {
    expect(fs.existsSync(SRC)).toBe(true);
  });

  test('is syntactically valid JavaScript', () => {
    expect(() => new vm.Script(source, { filename: 'community-program.validation.js' })).not.toThrow();
  });

  test('defines validation rules', () => {
    expect(source).toMatch(/(?:body|param|query)\s*\(/);
  });

  test('has npm dependencies (1)', () => {
    const npms = (source.match(/require\s*\(\s*['"](?![./])[^'"]+['"]\s*\)/g) || []);
    expect(npms.length).toBe(1);
  });

  test('has module.exports', () => {
    expect(source).toMatch(/module\.exports/);
  });

  test('exports createProgram', () => {
    expect(source).toMatch(/createProgram/);
  });

  test('exports updateProgram', () => {
    expect(source).toMatch(/updateProgram/);
  });

  test('exports createProgramEnrollment', () => {
    expect(source).toMatch(/createProgramEnrollment/);
  });

  test('exports updateProgramEnrollment', () => {
    expect(source).toMatch(/updateProgramEnrollment/);
  });

  test('exports createProgramActivity', () => {
    expect(source).toMatch(/createProgramActivity/);
  });
});
