/**
 * Auto-generated tests for monitoring/distributedTracing.js
 * Validates syntax, structure, and patterns (middleware — 345L)
 * @generated by P#106 universal generator
 */
'use strict';

const fs = require('fs');
const path = require('path');
const vm = require('vm');

const SRC = path.resolve(__dirname, '../../monitoring/distributedTracing.js');

describe('monitoring/distributedTracing.js', () => {
  let source;
  beforeAll(() => {
    source = fs.readFileSync(SRC, 'utf8');
  });

  test('file exists', () => {
    expect(fs.existsSync(SRC)).toBe(true);
  });

  test('is syntactically valid JavaScript', () => {
    expect(() => new vm.Script(source, { filename: 'distributedTracing.js' })).not.toThrow();
  });

  test('exports a middleware function', () => {
    expect(source).toMatch(/(?:req,\s*res,\s*next|module\.exports)/);
  });

  test('has npm dependencies (2)', () => {
    const npms = (source.match(/require\s*\(\s*['"](?![./])[^'"]+['"]\s*\)/g) || []);
    expect(npms.length).toBe(2);
  });

  test('has local dependencies (1)', () => {
    const locals = (source.match(/require\s*\(\s*['"]\.[^'"]+['"]\s*\)/g) || []);
    expect(locals.length).toBe(1);
  });

  test('has module.exports', () => {
    expect(source).toMatch(/module\.exports/);
  });

  test('exports DistributedTracer', () => {
    expect(source).toMatch(/DistributedTracer/);
  });

  test('exports TraceContext', () => {
    expect(source).toMatch(/TraceContext/);
  });

  test('exports tracingMiddleware', () => {
    expect(source).toMatch(/tracingMiddleware/);
  });

  test('exports ConsoleExporter', () => {
    expect(source).toMatch(/ConsoleExporter/);
  });

  test('exports FileExporter', () => {
    expect(source).toMatch(/FileExporter/);
  });
});
