/**
 * Auto-generated tests for validations/environmental-monitor.validation.js
 * Validates syntax, structure, and patterns (validator — 158L)
 * @generated by P#106 universal generator
 */
'use strict';

const fs = require('fs');
const path = require('path');
const vm = require('vm');

const SRC = path.resolve(__dirname, '../../validations/environmental-monitor.validation.js');

describe('validations/environmental-monitor.validation.js', () => {
  let source;
  beforeAll(() => {
    source = fs.readFileSync(SRC, 'utf8');
  });

  test('file exists', () => {
    expect(fs.existsSync(SRC)).toBe(true);
  });

  test('is syntactically valid JavaScript', () => {
    expect(() => new vm.Script(source, { filename: 'environmental-monitor.validation.js' })).not.toThrow();
  });

  test('defines validation rules', () => {
    expect(source).toMatch(/(?:body|param|query)\s*\(/);
  });

  test('has npm dependencies (1)', () => {
    const npms = (source.match(/require\s*\(\s*['"](?![./])[^'"]+['"]\s*\)/g) || []);
    expect(npms.length).toBe(1);
  });

  test('has module.exports', () => {
    expect(source).toMatch(/module\.exports/);
  });

  test('exports createSensor', () => {
    expect(source).toMatch(/createSensor/);
  });

  test('exports updateSensor', () => {
    expect(source).toMatch(/updateSensor/);
  });

  test('exports createEnvironmentReading', () => {
    expect(source).toMatch(/createEnvironmentReading/);
  });

  test('exports updateEnvironmentReading', () => {
    expect(source).toMatch(/updateEnvironmentReading/);
  });

  test('exports createEnvironmentAlert', () => {
    expect(source).toMatch(/createEnvironmentAlert/);
  });
});
