/**
 * Auto-generated tests for database/event-bus.js
 * Validates syntax, structure, and patterns (model — 364L)
 * @generated by P#106 universal generator
 */
'use strict';

const fs = require('fs');
const path = require('path');
const vm = require('vm');

const SRC = path.resolve(__dirname, '../../database/event-bus.js');

describe('database/event-bus.js', () => {
  let source;
  beforeAll(() => {
    source = fs.readFileSync(SRC, 'utf8');
  });

  test('file exists', () => {
    expect(fs.existsSync(SRC)).toBe(true);
  });

  test('is syntactically valid JavaScript', () => {
    expect(() => new vm.Script(source, { filename: 'event-bus.js' })).not.toThrow();
  });

  test('defines a Mongoose model', () => {
    expect(source).toMatch(/mongoose\.model\s*\(/);
  });

  test('has npm dependencies (2)', () => {
    const npms = (source.match(/require\s*\(\s*['"](?![./])[^'"]+['"]\s*\)/g) || []);
    expect(npms.length).toBe(2);
  });

  test('has local dependencies (1)', () => {
    const locals = (source.match(/require\s*\(\s*['"]\.[^'"]+['"]\s*\)/g) || []);
    expect(locals.length).toBe(1);
  });

  test('has module.exports', () => {
    expect(source).toMatch(/module\.exports/);
  });

  test('exports DatabaseEventBus', () => {
    expect(source).toMatch(/DatabaseEventBus/);
  });

  test('exports databaseEventBus', () => {
    expect(source).toMatch(/databaseEventBus/);
  });
});
