/**
 * Auto-generated tests for validations/facility-manager.validation.js
 * Validates syntax, structure, and patterns (validator — 174L)
 * @generated by P#106 universal generator
 */
'use strict';

const fs = require('fs');
const path = require('path');
const vm = require('vm');

const SRC = path.resolve(__dirname, '../../validations/facility-manager.validation.js');

describe('validations/facility-manager.validation.js', () => {
  let source;
  beforeAll(() => {
    source = fs.readFileSync(SRC, 'utf8');
  });

  test('file exists', () => {
    expect(fs.existsSync(SRC)).toBe(true);
  });

  test('is syntactically valid JavaScript', () => {
    expect(() => new vm.Script(source, { filename: 'facility-manager.validation.js' })).not.toThrow();
  });

  test('defines validation rules', () => {
    expect(source).toMatch(/(?:body|param|query)\s*\(/);
  });

  test('has npm dependencies (1)', () => {
    const npms = (source.match(/require\s*\(\s*['"](?![./])[^'"]+['"]\s*\)/g) || []);
    expect(npms.length).toBe(1);
  });

  test('has module.exports', () => {
    expect(source).toMatch(/module\.exports/);
  });

  test('exports createBuilding', () => {
    expect(source).toMatch(/createBuilding/);
  });

  test('exports updateBuilding', () => {
    expect(source).toMatch(/updateBuilding/);
  });

  test('exports createFloor', () => {
    expect(source).toMatch(/createFloor/);
  });

  test('exports updateFloor', () => {
    expect(source).toMatch(/updateFloor/);
  });

  test('exports createRoom', () => {
    expect(source).toMatch(/createRoom/);
  });
});
