/**
 * Auto-generated tests for rehabilitation-services/goals-bank-service.js
 * Validates syntax, structure, and patterns (model — 1630L)
 * @generated by P#106 universal generator
 */
'use strict';

const fs = require('fs');
const path = require('path');
const vm = require('vm');

const SRC = path.resolve(__dirname, '../../rehabilitation-services/goals-bank-service.js');

describe('rehabilitation-services/goals-bank-service.js', () => {
  let source;
  beforeAll(() => {
    source = fs.readFileSync(SRC, 'utf8');
  });

  test('file exists', () => {
    expect(fs.existsSync(SRC)).toBe(true);
  });

  test('is syntactically valid JavaScript', () => {
    expect(() => new vm.Script(source, { filename: 'goals-bank-service.js' })).not.toThrow();
  });

  test('defines a Mongoose model', () => {
    expect(source).toMatch(/mongoose\.model\s*\(/);
  });

  test('uses timestamps', () => {
    expect(source).toMatch(/timestamps\s*:\s*true/);
  });

  test('has required fields', () => {
    expect(source).toMatch(/required\s*:\s*true/);
  });

  test('has npm dependencies (1)', () => {
    const npms = (source.match(/require\s*\(\s*['"](?![./])[^'"]+['"]\s*\)/g) || []);
    expect(npms.length).toBe(1);
  });

  test('has local dependencies (1)', () => {
    const locals = (source.match(/require\s*\(\s*['"]\.[^'"]+['"]\s*\)/g) || []);
    expect(locals.length).toBe(1);
  });

  test('has module.exports', () => {
    expect(source).toMatch(/module\.exports/);
  });

  test('exports GoalsBankService', () => {
    expect(source).toMatch(/GoalsBankService/);
  });

  test('exports Goal', () => {
    expect(source).toMatch(/Goal/);
  });

  test('exports GOALS_BANK', () => {
    expect(source).toMatch(/GOALS_BANK/);
  });
});
