/**
 * Auto-generated tests for services/hr/analyticsAIService.js
 * Validates syntax, structure, and patterns (service — 491L)
 * @generated by P#106 universal generator
 */
'use strict';

const fs = require('fs');
const path = require('path');
const vm = require('vm');

const SRC = path.resolve(__dirname, '../../services/hr/analyticsAIService.js');

describe('services/hr/analyticsAIService.js', () => {
  let source;
  beforeAll(() => {
    source = fs.readFileSync(SRC, 'utf8');
  });

  test('file exists', () => {
    expect(fs.existsSync(SRC)).toBe(true);
  });

  test('is syntactically valid JavaScript', () => {
    expect(() => new vm.Script(source, { filename: 'analyticsAIService.js' })).not.toThrow();
  });

  test('defines class HRAnalyticsAIService', () => {
    expect(source).toMatch(/class\s+HRAnalyticsAIService/);
  });

  test('has async methods (9)', () => {
    const matches = source.match(/async\s+\w+\s*\(/g) || [];
    expect(matches.length).toBeGreaterThanOrEqual(1);
  });

  test('uses error handling', () => {
    expect(source).toMatch(/try\s*\{/);
  });

  test('has local dependencies (4)', () => {
    const locals = (source.match(/require\s*\(\s*['"]\.[^'"]+['"]\s*\)/g) || []);
    expect(locals.length).toBe(4);
  });

  test('has module.exports', () => {
    expect(source).toMatch(/module\.exports/);
  });
});
