/**
 * Auto-generated tests for validations/knowledge-base.validation.js
 * Validates syntax, structure, and patterns (validator — 184L)
 * @generated by P#106 universal generator
 */
'use strict';

const fs = require('fs');
const path = require('path');
const vm = require('vm');

const SRC = path.resolve(__dirname, '../../validations/knowledge-base.validation.js');

describe('validations/knowledge-base.validation.js', () => {
  let source;
  beforeAll(() => {
    source = fs.readFileSync(SRC, 'utf8');
  });

  test('file exists', () => {
    expect(fs.existsSync(SRC)).toBe(true);
  });

  test('is syntactically valid JavaScript', () => {
    expect(() => new vm.Script(source, { filename: 'knowledge-base.validation.js' })).not.toThrow();
  });

  test('defines validation rules', () => {
    expect(source).toMatch(/(?:body|param|query)\s*\(/);
  });

  test('has npm dependencies (1)', () => {
    const npms = (source.match(/require\s*\(\s*['"](?![./])[^'"]+['"]\s*\)/g) || []);
    expect(npms.length).toBe(1);
  });

  test('has module.exports', () => {
    expect(source).toMatch(/module\.exports/);
  });

  test('exports createArticleCategory', () => {
    expect(source).toMatch(/createArticleCategory/);
  });

  test('exports updateArticleCategory', () => {
    expect(source).toMatch(/updateArticleCategory/);
  });

  test('exports createArticle', () => {
    expect(source).toMatch(/createArticle/);
  });

  test('exports updateArticle', () => {
    expect(source).toMatch(/updateArticle/);
  });

  test('exports createProtocol', () => {
    expect(source).toMatch(/createProtocol/);
  });
});
