/**
 * Auto-generated tests for seeds/measurement-system.seed.js
 * Validates syntax, structure, and patterns (module — 875L)
 * @generated by P#106 universal generator
 */
'use strict';

const fs = require('fs');
const path = require('path');
const vm = require('vm');

const SRC = path.resolve(__dirname, '../../seeds/measurement-system.seed.js');

describe('seeds/measurement-system.seed.js', () => {
  let source;
  beforeAll(() => {
    source = fs.readFileSync(SRC, 'utf8');
  });

  test('file exists', () => {
    expect(fs.existsSync(SRC)).toBe(true);
  });

  test('is syntactically valid JavaScript', () => {
    expect(() => new vm.Script(source, { filename: 'measurement-system.seed.js' })).not.toThrow();
  });

  test('has npm dependencies (2)', () => {
    const npms = (source.match(/require\s*\(\s*['"](?![./])[^'"]+['"]\s*\)/g) || []);
    expect(npms.length).toBe(2);
  });

  test('has local dependencies (5)', () => {
    const locals = (source.match(/require\s*\(\s*['"]\.[^'"]+['"]\s*\)/g) || []);
    expect(locals.length).toBe(5);
  });

  test('has module.exports', () => {
    expect(source).toMatch(/module\.exports/);
  });

  test('exports measurementTypes', () => {
    expect(source).toMatch(/measurementTypes/);
  });

  test('exports rehabilitationPrograms', () => {
    expect(source).toMatch(/rehabilitationPrograms/);
  });

  test('exports seedMeasurementSystem', () => {
    expect(source).toMatch(/seedMeasurementSystem/);
  });

  test('exports seedAdvancedMeasurementsAndPrograms', () => {
    expect(source).toMatch(/seedAdvancedMeasurementsAndPrograms/);
  });
});
