/**
 * Auto-generated tests for database/multi-tenant-isolator.js
 * Validates syntax, structure, and patterns (middleware — 386L)
 * @generated by P#106 universal generator
 */
'use strict';

const fs = require('fs');
const path = require('path');
const vm = require('vm');

const SRC = path.resolve(__dirname, '../../database/multi-tenant-isolator.js');

describe('database/multi-tenant-isolator.js', () => {
  let source;
  beforeAll(() => {
    source = fs.readFileSync(SRC, 'utf8');
  });

  test('file exists', () => {
    expect(fs.existsSync(SRC)).toBe(true);
  });

  test('is syntactically valid JavaScript', () => {
    expect(() => new vm.Script(source, { filename: 'multi-tenant-isolator.js' })).not.toThrow();
  });

  test('exports a middleware function', () => {
    expect(source).toMatch(/(?:req,\s*res,\s*next|module\.exports)/);
  });

  test('has npm dependencies (2)', () => {
    const npms = (source.match(/require\s*\(\s*['"](?![./])[^'"]+['"]\s*\)/g) || []);
    expect(npms.length).toBe(2);
  });

  test('has local dependencies (1)', () => {
    const locals = (source.match(/require\s*\(\s*['"]\.[^'"]+['"]\s*\)/g) || []);
    expect(locals.length).toBe(1);
  });

  test('has module.exports', () => {
    expect(source).toMatch(/module\.exports/);
  });

  test('exports MultiTenantIsolator', () => {
    expect(source).toMatch(/MultiTenantIsolator/);
  });

  test('exports tenantIsolator', () => {
    expect(source).toMatch(/tenantIsolator/);
  });

  test('exports tenantStore', () => {
    expect(source).toMatch(/tenantStore/);
  });
});
