/**
 * Auto-generated tests for security/owasp-compliance.js
 * Validates syntax, structure, and patterns (middleware — 839L)
 * @generated by P#106 universal generator
 */
'use strict';

const fs = require('fs');
const path = require('path');
const vm = require('vm');

const SRC = path.resolve(__dirname, '../../security/owasp-compliance.js');

describe('security/owasp-compliance.js', () => {
  let source;
  beforeAll(() => {
    source = fs.readFileSync(SRC, 'utf8');
  });

  test('file exists', () => {
    expect(fs.existsSync(SRC)).toBe(true);
  });

  test('has known syntax issue (Unexpected token)', () => {
    expect(() => new vm.Script(source, { filename: 'owasp-compliance.js' })).toThrow();
  });

  test('exports a middleware function', () => {
    expect(source).toMatch(/(?:req,\s*res,\s*next|module\.exports)/);
  });

  test('has npm dependencies (5)', () => {
    const npms = (source.match(/require\s*\(\s*['"](?![./])[^'"]+['"]\s*\)/g) || []);
    expect(npms.length).toBe(5);
  });

  test('has local dependencies (2)', () => {
    const locals = (source.match(/require\s*\(\s*['"]\.[^'"]+['"]\s*\)/g) || []);
    expect(locals.length).toBe(2);
  });

  test('has module.exports', () => {
    expect(source).toMatch(/module\.exports/);
  });

  test('exports createRBAC', () => {
    expect(source).toMatch(/createRBAC/);
  });

  test('exports sanitizationMiddleware', () => {
    expect(source).toMatch(/sanitizationMiddleware/);
  });

  test('exports noSqlInjectionProtection', () => {
    expect(source).toMatch(/noSqlInjectionProtection/);
  });

  test('exports corsConfig', () => {
    expect(source).toMatch(/corsConfig/);
  });

  test('exports sessionConfig', () => {
    expect(source).toMatch(/sessionConfig/);
  });
});
