/**
 * Auto-generated tests for seeds/programs.seed.js
 * Validates syntax, structure, and patterns (module — 364L)
 * @generated by P#106 universal generator
 */
'use strict';

const fs = require('fs');
const path = require('path');
const vm = require('vm');

const SRC = path.resolve(__dirname, '../../seeds/programs.seed.js');

describe('seeds/programs.seed.js', () => {
  let source;
  beforeAll(() => {
    source = fs.readFileSync(SRC, 'utf8');
  });

  test('file exists', () => {
    expect(fs.existsSync(SRC)).toBe(true);
  });

  test('is syntactically valid JavaScript', () => {
    expect(() => new vm.Script(source, { filename: 'programs.seed.js' })).not.toThrow();
  });

  test('has module.exports', () => {
    expect(source).toMatch(/module\.exports/);
  });

  test('exports seed', () => {
    expect(source).toMatch(/seed/);
  });

  test('exports down', () => {
    expect(source).toMatch(/down/);
  });
});
