/**
 * Auto-generated tests for database/query-governor.js
 * Validates syntax, structure, and patterns (middleware — 490L)
 * @generated by P#106 universal generator
 */
'use strict';

const fs = require('fs');
const path = require('path');
const vm = require('vm');

const SRC = path.resolve(__dirname, '../../database/query-governor.js');

describe('database/query-governor.js', () => {
  let source;
  beforeAll(() => {
    source = fs.readFileSync(SRC, 'utf8');
  });

  test('file exists', () => {
    expect(fs.existsSync(SRC)).toBe(true);
  });

  test('is syntactically valid JavaScript', () => {
    expect(() => new vm.Script(source, { filename: 'query-governor.js' })).not.toThrow();
  });

  test('exports a middleware function', () => {
    expect(source).toMatch(/(?:req,\s*res,\s*next|module\.exports)/);
  });

  test('has npm dependencies (1)', () => {
    const npms = (source.match(/require\s*\(\s*['"](?![./])[^'"]+['"]\s*\)/g) || []);
    expect(npms.length).toBe(1);
  });

  test('has local dependencies (2)', () => {
    const locals = (source.match(/require\s*\(\s*['"]\.[^'"]+['"]\s*\)/g) || []);
    expect(locals.length).toBe(2);
  });

  test('has module.exports', () => {
    expect(source).toMatch(/module\.exports/);
  });

  test('exports QueryGovernor', () => {
    expect(source).toMatch(/QueryGovernor/);
  });

  test('exports queryGovernor', () => {
    expect(source).toMatch(/queryGovernor/);
  });
});
