/**
 * Auto-generated tests for config/rbac.config.js
 * @generated by _gen_config_tests.js
 */
'use strict';

/* ── Module under test ── */
const mod = require('../../config/rbac.config');

describe('config/rbac.config', () => {
  test('should export a valid module', () => {
    expect(mod).toBeDefined();
    expect(typeof mod).toBe('object');
  });

  test('should export ROLES', () => {
    expect(mod.ROLES).toBeDefined();
  });

  test('should export ALL_ROLES', () => {
    expect(mod.ALL_ROLES).toBeDefined();
  });

  test('should export ACTIONS', () => {
    expect(mod.ACTIONS).toBeDefined();
  });

  test('should export RESOURCES', () => {
    expect(mod.RESOURCES).toBeDefined();
  });

  test('should export ROLE_HIERARCHY', () => {
    expect(mod.ROLE_HIERARCHY).toBeDefined();
  });

  test('should export ROLE_PERMISSIONS', () => {
    expect(mod.ROLE_PERMISSIONS).toBeDefined();
  });

  test('should export resolvePermissions', () => {
    expect(mod.resolvePermissions).toBeDefined();
    expect(typeof mod.resolvePermissions).toBe('function');
  });

  test('should export flattenPermissions', () => {
    expect(mod.flattenPermissions).toBeDefined();
    expect(typeof mod.flattenPermissions).toBe('function');
  });

  test('should export hasPermission', () => {
    expect(mod.hasPermission).toBeDefined();
    expect(typeof mod.hasPermission).toBe('function');
  });

  test('should export getRoleLevel', () => {
    expect(mod.getRoleLevel).toBeDefined();
    expect(typeof mod.getRoleLevel).toBe('function');
  });

  test('should export isAtLeast', () => {
    expect(mod.isAtLeast).toBeDefined();
    expect(typeof mod.isAtLeast).toBe('function');
  });

  test('should export getRoleLabel', () => {
    expect(mod.getRoleLabel).toBeDefined();
    expect(typeof mod.getRoleLabel).toBe('function');
  });

  test('should export clearCache', () => {
    expect(mod.clearCache).toBeDefined();
    expect(typeof mod.clearCache).toBe('function');
  });

});
