/**
 * Auto-generated tests for rbac.js
 * @generated by _gen_remaining_tests.js
 */
'use strict';

/* ── No mocks needed — rbac.js is pure logic with zero dependencies ── */

/* ── Module under test ── */
const mod = require('../../rbac');

describe('rbac', () => {
  test('should export a valid module', () => {
    expect(mod).toBeDefined();
    expect(typeof mod).toBe('object');
  });

  test('should export RBAC_ROLES', () => {
    expect(mod.RBAC_ROLES).toBeDefined();
  });

  test('should export PERMISSION_CATEGORIES', () => {
    expect(mod.PERMISSION_CATEGORIES).toBeDefined();
  });

  test('should export RESOURCE_PERMISSIONS', () => {
    expect(mod.RESOURCE_PERMISSIONS).toBeDefined();
  });

  test('should export RBAC_HELPERS', () => {
    expect(mod.RBAC_HELPERS).toBeDefined();
  });

  test('should export RBAC_API', () => {
    expect(mod.RBAC_API).toBeDefined();
  });

  test('should export createRBACMiddleware', () => {
    expect(mod.createRBACMiddleware).toBeDefined();
    expect(typeof mod.createRBACMiddleware).toBe('function');
  });

  test('RBAC_ROLES should have defined roles', () => {
    expect(mod.RBAC_ROLES).toBeDefined();
    expect(typeof mod.RBAC_ROLES).toBe('object');
  });

  test('createRBACMiddleware should return a function', () => {
    if (typeof mod.createRBACMiddleware === 'function') {
      const mw = mod.createRBACMiddleware({ requiredRole: 'admin' });
      expect(typeof mw).toBe('function');
    }
  });

  test('RBAC_HELPERS should be defined', () => {
    if (mod.RBAC_HELPERS) {
      expect(mod.RBAC_HELPERS).toBeDefined();
    }
  });

});
