/**
 * Auto-generated tests for config/redis.config.js
 * @generated by _gen_config_tests.js
 */
'use strict';

/* ── Mocks ── */
jest.mock('../../utils/logger', () => ({
  info: jest.fn(),
  error: jest.fn(),
  warn: jest.fn(),
  debug: jest.fn(),
  verbose: jest.fn(),
  silly: jest.fn(),
  child: jest.fn(() => ({ info: jest.fn(), error: jest.fn(), warn: jest.fn(), debug: jest.fn() })),
  stream: { write: jest.fn() },
}));

jest.mock('ioredis', () => {
  const RedisMock = jest.fn(() => ({
    get: jest.fn(() => Promise.resolve(null)),
    set: jest.fn(() => Promise.resolve('OK')),
    del: jest.fn(() => Promise.resolve(1)),
    setex: jest.fn(() => Promise.resolve('OK')),
    expire: jest.fn(() => Promise.resolve(1)),
    keys: jest.fn(() => Promise.resolve([])),
    info: jest.fn(() => Promise.resolve('# Server\nredis_version:7.0.0')),
    ping: jest.fn(() => Promise.resolve('PONG')),
    on: jest.fn().mockReturnThis(),
    connect: jest.fn(() => Promise.resolve()),
    disconnect: jest.fn(),
    quit: jest.fn(() => Promise.resolve()),
    status: 'ready',
    pipeline: jest.fn(() => ({ exec: jest.fn(() => Promise.resolve([])) })),
  }));
  RedisMock.Cluster = jest.fn(() => ({}));
  return RedisMock;
}, { virtual: true });

/* ── Module under test ── */
const mod = require('../../config/redis.config');

describe('config/redis.config', () => {
  test('should export a valid module', () => {
    expect(mod).toBeDefined();
    expect(typeof mod).toBe('object');
  });

  test('should export cache', () => {
    expect(mod.cache).toBeDefined();
  });

  test('should export connectRedis', () => {
    expect(mod.connectRedis).toBeDefined();
    expect(typeof mod.connectRedis).toBe('function');
  });

  test('should export disconnectRedis', () => {
    expect(mod.disconnectRedis).toBeDefined();
    expect(typeof mod.disconnectRedis).toBe('function');
  });

  test('should export checkRedisHealth', () => {
    expect(mod.checkRedisHealth).toBeDefined();
    expect(typeof mod.checkRedisHealth).toBe('function');
  });

  test('should export getRedisClient', () => {
    expect(mod.getRedisClient).toBeDefined();
    expect(typeof mod.getRedisClient).toBe('function');
  });

});
