/**
 * Auto-generated tests for config/redis.js (Redis cache singleton)
 * @generated by _gen_config_tests.js (manual — name clash with redis.config.js)
 */
'use strict';

/* ── Mocks ── */
jest.mock('../../utils/logger', () => ({
  info: jest.fn(),
  error: jest.fn(),
  warn: jest.fn(),
  debug: jest.fn(),
  verbose: jest.fn(),
  silly: jest.fn(),
  child: jest.fn(() => ({ info: jest.fn(), error: jest.fn(), warn: jest.fn(), debug: jest.fn() })),
  stream: { write: jest.fn() },
}));

jest.mock('ioredis', () => {
  const RedisMock = jest.fn(() => ({
    get: jest.fn(() => Promise.resolve(null)),
    set: jest.fn(() => Promise.resolve('OK')),
    del: jest.fn(() => Promise.resolve(1)),
    setex: jest.fn(() => Promise.resolve('OK')),
    expire: jest.fn(() => Promise.resolve(1)),
    keys: jest.fn(() => Promise.resolve([])),
    info: jest.fn(() => Promise.resolve('# Server\nredis_version:7.0.0')),
    ping: jest.fn(() => Promise.resolve('PONG')),
    on: jest.fn().mockReturnThis(),
    connect: jest.fn(() => Promise.resolve()),
    disconnect: jest.fn(),
    quit: jest.fn(() => Promise.resolve()),
    status: 'ready',
    pipeline: jest.fn(() => ({ exec: jest.fn(() => Promise.resolve([])) })),
    exists: jest.fn(() => Promise.resolve(0)),
    scan: jest.fn(() => Promise.resolve(['0', []])),
    flushall: jest.fn(() => Promise.resolve('OK')),
    dbsize: jest.fn(() => Promise.resolve(0)),
  }));
  RedisMock.Cluster = jest.fn(() => ({}));
  return RedisMock;
}, { virtual: true });

/* ── Module under test ── */
const mod = require('../../config/redis');

describe('config/redis', () => {
  test('should export a valid module', () => {
    expect(mod).toBeDefined();
    expect(typeof mod).toBe('object');
  });

  test('should export initializeRedis', () => {
    expect(mod.initializeRedis).toBeDefined();
    expect(typeof mod.initializeRedis).toBe('function');
  });

  test('should export get', () => {
    expect(mod.get).toBeDefined();
    expect(typeof mod.get).toBe('function');
  });

  test('should export set', () => {
    expect(mod.set).toBeDefined();
    expect(typeof mod.set).toBe('function');
  });

  test('should export del', () => {
    expect(mod.del).toBeDefined();
    expect(typeof mod.del).toBe('function');
  });

  test('should export delPattern', () => {
    expect(mod.delPattern).toBeDefined();
    expect(typeof mod.delPattern).toBe('function');
  });

  test('should export exists', () => {
    expect(mod.exists).toBeDefined();
    expect(typeof mod.exists).toBe('function');
  });

  test('should export expire', () => {
    expect(mod.expire).toBeDefined();
    expect(typeof mod.expire).toBe('function');
  });

  test('should export flushAll', () => {
    expect(mod.flushAll).toBeDefined();
    expect(typeof mod.flushAll).toBe('function');
  });

  test('should export close', () => {
    expect(mod.close).toBeDefined();
    expect(typeof mod.close).toBe('function');
  });

  test('should export getStats', () => {
    expect(mod.getStats).toBeDefined();
    expect(typeof mod.getStats).toBe('function');
  });

  test('should export getClient', () => {
    expect(mod.getClient).toBeDefined();
    expect(typeof mod.getClient).toBe('function');
  });

  test('should export isConnected', () => {
    expect(mod.isConnected).toBeDefined();
    expect(typeof mod.isConnected).toBe('function');
  });

  test('should export isEnabled', () => {
    expect(mod.isEnabled).toBeDefined();
    expect(typeof mod.isEnabled).toBe('function');
  });
});
