/**
 * Auto-generated tests for rehabilitation-services/rehabilitation-routes.js
 * Validates syntax, structure, and patterns (route — 4856L)
 * @generated by P#106 universal generator
 */
'use strict';

const fs = require('fs');
const path = require('path');
const vm = require('vm');

const SRC = path.resolve(__dirname, '../../rehabilitation-services/rehabilitation-routes.js');

describe('rehabilitation-services/rehabilitation-routes.js', () => {
  let source;
  beforeAll(() => {
    source = fs.readFileSync(SRC, 'utf8');
  });

  test('file exists', () => {
    expect(fs.existsSync(SRC)).toBe(true);
  });

  test('is syntactically valid JavaScript', () => {
    expect(() => new vm.Script(source, { filename: 'rehabilitation-routes.js' })).not.toThrow();
  });

  test('uses express Router', () => {
    expect(source).toMatch(/Router\s*\(/);
  });

  test('defines GET routes (90)', () => {
    const matches = source.match(/router\.get\s*\(/gi) || [];
    expect(matches.length).toBeGreaterThanOrEqual(1);
  });

  test('defines POST routes (236)', () => {
    const matches = source.match(/router\.post\s*\(/gi) || [];
    expect(matches.length).toBeGreaterThanOrEqual(1);
  });

  test('defines PUT routes (4)', () => {
    const matches = source.match(/router\.put\s*\(/gi) || [];
    expect(matches.length).toBeGreaterThanOrEqual(1);
  });

  test('exports the router', () => {
    expect(source).toMatch(/module\.exports/);
  });

  test('has npm dependencies (1)', () => {
    const npms = (source.match(/require\s*\(\s*['"](?![./])[^'"]+['"]\s*\)/g) || []);
    expect(npms.length).toBe(1);
  });

  test('has local dependencies (63)', () => {
    const locals = (source.match(/require\s*\(\s*['"]\.[^'"]+['"]\s*\)/g) || []);
    expect(locals.length).toBe(63);
  });

  test('has module.exports', () => {
    expect(source).toMatch(/module\.exports/);
  });
});
