/**
 * Auto-generated tests for vehicles/rehabilitation-transport-service.js
 * Validates syntax, structure, and patterns (service — 713L)
 * @generated by P#106 universal generator
 */
'use strict';

const fs = require('fs');
const path = require('path');
const vm = require('vm');

const SRC = path.resolve(__dirname, '../../vehicles/rehabilitation-transport-service.js');

describe('vehicles/rehabilitation-transport-service.js', () => {
  let source;
  beforeAll(() => {
    source = fs.readFileSync(SRC, 'utf8');
  });

  test('file exists', () => {
    expect(fs.existsSync(SRC)).toBe(true);
  });

  test('is syntactically valid JavaScript', () => {
    expect(() => new vm.Script(source, { filename: 'rehabilitation-transport-service.js' })).not.toThrow();
  });

  test('defines class AIRouteOptimizer', () => {
    expect(source).toMatch(/class\s+AIRouteOptimizer/);
  });

  test('defines class RehabilitationTransportService', () => {
    expect(source).toMatch(/class\s+RehabilitationTransportService/);
  });

  test('has async methods (12)', () => {
    const matches = source.match(/async\s+\w+\s*\(/g) || [];
    expect(matches.length).toBeGreaterThanOrEqual(1);
  });

  test('has npm dependencies (2)', () => {
    const npms = (source.match(/require\s*\(\s*['"](?![./])[^'"]+['"]\s*\)/g) || []);
    expect(npms.length).toBe(2);
  });

  test('has local dependencies (1)', () => {
    const locals = (source.match(/require\s*\(\s*['"]\.[^'"]+['"]\s*\)/g) || []);
    expect(locals.length).toBe(1);
  });

  test('has module.exports', () => {
    expect(source).toMatch(/module\.exports/);
  });

  test('exports RehabilitationTransportService', () => {
    expect(source).toMatch(/RehabilitationTransportService/);
  });

  test('exports rehabilitationTransportService', () => {
    expect(source).toMatch(/rehabilitationTransportService/);
  });

  test('exports nationalAddressConfig', () => {
    expect(source).toMatch(/nationalAddressConfig/);
  });

  test('exports AIRouteOptimizer', () => {
    expect(source).toMatch(/AIRouteOptimizer/);
  });
});
