/**
 * Auto-generated tests for errors/responseSystem.js
 * @generated by _gen_remaining_tests.js
 */
'use strict';

/* ── Module under test ── */
const mod = require('../../errors/responseSystem');

describe('errors/responseSystem', () => {
  test('should export a valid module', () => {
    expect(mod).toBeDefined();
    expect(typeof mod).toBe('object');
  });

  test('should export ErrorTypes', () => {
    expect(mod.ErrorTypes).toBeDefined();
  });

  test('should export SuccessResponse as a constructor', () => {
    expect(mod.SuccessResponse).toBeDefined();
    expect(typeof mod.SuccessResponse).toBe('function');
  });

  test('should export PaginatedResponse as a constructor', () => {
    expect(mod.PaginatedResponse).toBeDefined();
    expect(typeof mod.PaginatedResponse).toBe('function');
  });

  test('should export ErrorResponse as a constructor', () => {
    expect(mod.ErrorResponse).toBeDefined();
    expect(typeof mod.ErrorResponse).toBe('function');
  });

  test('should export successResponse', () => {
    expect(mod.successResponse).toBeDefined();
    expect(typeof mod.successResponse).toBe('function');
  });

  test('should export errorResponse', () => {
    expect(mod.errorResponse).toBeDefined();
    expect(typeof mod.errorResponse).toBe('function');
  });

  test('should export paginatedResponse', () => {
    expect(mod.paginatedResponse).toBeDefined();
    expect(typeof mod.paginatedResponse).toBe('function');
  });

  test('should export sendSuccess', () => {
    expect(mod.sendSuccess).toBeDefined();
    expect(typeof mod.sendSuccess).toBe('function');
  });

  test('should export sendError', () => {
    expect(mod.sendError).toBeDefined();
    expect(typeof mod.sendError).toBe('function');
  });

  test('should export sendCreated', () => {
    expect(mod.sendCreated).toBeDefined();
    expect(typeof mod.sendCreated).toBe('function');
  });

  test('should export sendPaginated', () => {
    expect(mod.sendPaginated).toBeDefined();
    expect(typeof mod.sendPaginated).toBe('function');
  });

  test('should export enhanceResponse', () => {
    expect(mod.enhanceResponse).toBeDefined();
    expect(typeof mod.enhanceResponse).toBe('function');
  });

});
