/**
 * Auto-generated tests for seeds/roles-permissions.seed.js
 * Validates syntax, structure, and patterns (module — 808L)
 * @generated by P#106 universal generator
 */
'use strict';

const fs = require('fs');
const path = require('path');
const vm = require('vm');

const SRC = path.resolve(__dirname, '../../seeds/roles-permissions.seed.js');

describe('seeds/roles-permissions.seed.js', () => {
  let source;
  beforeAll(() => {
    source = fs.readFileSync(SRC, 'utf8');
  });

  test('file exists', () => {
    expect(fs.existsSync(SRC)).toBe(true);
  });

  test('is syntactically valid JavaScript', () => {
    expect(() => new vm.Script(source, { filename: 'roles-permissions.seed.js' })).not.toThrow();
  });

  test('has npm dependencies (1)', () => {
    const npms = (source.match(/require\s*\(\s*['"](?![./])[^'"]+['"]\s*\)/g) || []);
    expect(npms.length).toBe(1);
  });

  test('has module.exports', () => {
    expect(source).toMatch(/module\.exports/);
  });

  test('exports seed', () => {
    expect(source).toMatch(/seed/);
  });

  test('exports down', () => {
    expect(source).toMatch(/down/);
  });

  test('exports PERMISSIONS', () => {
    expect(source).toMatch(/PERMISSIONS/);
  });

  test('exports ROLES', () => {
    expect(source).toMatch(/ROLES/);
  });
});
