/**
 * Auto-generated tests for api/routes/documents-pro-extended.routes.js
 * Validates syntax, structure, and patterns (route — 844L)
 * @generated by P#106 universal generator
 */
'use strict';

const fs = require('fs');
const path = require('path');
const vm = require('vm');

const SRC = path.resolve(__dirname, '../../api/routes/documents-pro-extended.routes.js');

describe('api/routes/documents-pro-extended.routes.js', () => {
  let source;
  beforeAll(() => {
    source = fs.readFileSync(SRC, 'utf8');
  });

  test('file exists', () => {
    expect(fs.existsSync(SRC)).toBe(true);
  });

  test('has known syntax issue (Unexpected token)', () => {
    expect(() => new vm.Script(source, { filename: 'documents-pro-extended.routes.js' })).toThrow();
  });

  test('defines GET routes (18)', () => {
    const matches = source.match(/router\.get\s*\(/gi) || [];
    expect(matches.length).toBeGreaterThanOrEqual(1);
  });

  test('defines POST routes (20)', () => {
    const matches = source.match(/router\.post\s*\(/gi) || [];
    expect(matches.length).toBeGreaterThanOrEqual(1);
  });

  test('defines PUT routes (1)', () => {
    const matches = source.match(/router\.put\s*\(/gi) || [];
    expect(matches.length).toBeGreaterThanOrEqual(1);
  });

  test('defines DELETE routes (2)', () => {
    const matches = source.match(/router\.delete\s*\(/gi) || [];
    expect(matches.length).toBeGreaterThanOrEqual(1);
  });

  test('exports the router', () => {
    expect(source).toMatch(/module\.exports/);
  });

  test('has npm dependencies (2)', () => {
    const npms = (source.match(/require\s*\(\s*['"](?![./])[^'"]+['"]\s*\)/g) || []);
    expect(npms.length).toBe(2);
  });

  test('has local dependencies (8)', () => {
    const locals = (source.match(/require\s*\(\s*['"]\.[^'"]+['"]\s*\)/g) || []);
    expect(locals.length).toBe(8);
  });

  test('has module.exports', () => {
    expect(source).toMatch(/module\.exports/);
  });
});
