/**
 * Auto-generated tests for config/security.advanced.js
 * @generated by _gen_config_tests.js
 */
'use strict';

/* ── Mocks ── */
jest.mock('../../utils/logger', () => ({
  info: jest.fn(),
  error: jest.fn(),
  warn: jest.fn(),
  debug: jest.fn(),
  verbose: jest.fn(),
  silly: jest.fn(),
  child: jest.fn(() => ({ info: jest.fn(), error: jest.fn(), warn: jest.fn(), debug: jest.fn() })),
  stream: { write: jest.fn() },
}));

jest.mock('express-rate-limit', () => jest.fn(() => jest.fn((req, res, next) => next && next())));

jest.mock('express-mongo-sanitize', () => jest.fn(() => jest.fn((req, res, next) => next && next())), { virtual: true });

/* ── Module under test ── */
const mod = require('../../config/security.advanced');

describe('config/security.advanced', () => {
  test('should export a valid module', () => {
    expect(mod).toBeDefined();
    expect(typeof mod).toBe('object');
  });

  test('should export authRateLimiter', () => {
    expect(mod.authRateLimiter).toBeDefined();
  });

  test('should export apiRateLimiter', () => {
    expect(mod.apiRateLimiter).toBeDefined();
  });

  test('should export mongoSanitizeMiddleware', () => {
    expect(mod.mongoSanitizeMiddleware).toBeDefined();
  });

  test('should export createRateLimiter', () => {
    expect(mod.createRateLimiter).toBeDefined();
    expect(typeof mod.createRateLimiter).toBe('function');
  });

  test('should export ipWhitelist', () => {
    expect(mod.ipWhitelist).toBeDefined();
    expect(typeof mod.ipWhitelist).toBe('function');
  });

  test('should export securityHeaders', () => {
    expect(mod.securityHeaders).toBeDefined();
    expect(typeof mod.securityHeaders).toBe('function');
  });

  test('should export requestLogger', () => {
    expect(mod.requestLogger).toBeDefined();
    expect(typeof mod.requestLogger).toBe('function');
  });

});
