/**
 * Auto-generated tests for config/security.config.js
 * @generated by _gen_config_tests.js
 */
'use strict';

/* ── Mocks ── */
jest.mock('../../utils/logger', () => ({
  info: jest.fn(),
  error: jest.fn(),
  warn: jest.fn(),
  debug: jest.fn(),
  verbose: jest.fn(),
  silly: jest.fn(),
  child: jest.fn(() => ({ info: jest.fn(), error: jest.fn(), warn: jest.fn(), debug: jest.fn() })),
  stream: { write: jest.fn() },
}));

jest.mock('../../config/secrets', () => new Proxy({}, {
  get: (_, p) => {
    if (p === '__esModule') return false;
    if (p === 'default') return {};
    return jest.fn(() => Promise.resolve({}));
  },
}));

jest.mock('crypto', () => ({
  ...jest.requireActual('crypto'),
  randomBytes: jest.fn(() => Buffer.from('abcdef1234567890', 'hex')),
  createHash: jest.fn(() => ({ update: jest.fn().mockReturnThis(), digest: jest.fn(() => 'mockhash') })),
  createHmac: jest.fn(() => ({ update: jest.fn().mockReturnThis(), digest: jest.fn(() => 'mockhmac') })),
}));

jest.mock('../../config/redis.config', () => new Proxy({}, {
  get: (_, p) => {
    if (p === '__esModule') return false;
    if (p === 'default') return {};
    return jest.fn(() => Promise.resolve({}));
  },
}));

/* ── Module under test (loaded after mocks) ── */
let mod;
beforeAll(() => {
  mod = require('../../config/security.config');
});

describe('config/security.config', () => {
  test('should export a valid module', () => {
    expect(mod).toBeDefined();
    expect(typeof mod).toBe('object');
  });

  test('should export securityConfig', () => {
    expect(mod.securityConfig).toBeDefined();
  });

  test('should export SecurityService as a class', () => {
    expect(mod.SecurityService).toBeDefined();
    expect(typeof mod.SecurityService).toBe('function');
  });

  test('should export RateLimiter as a class', () => {
    expect(mod.RateLimiter).toBeDefined();
    expect(typeof mod.RateLimiter).toBe('function');
  });

});
