/**
 * Auto-generated tests for validations/staff-manager.validation.js
 * Validates syntax, structure, and patterns (validator — 170L)
 * @generated by P#106 universal generator
 */
'use strict';

const fs = require('fs');
const path = require('path');
const vm = require('vm');

const SRC = path.resolve(__dirname, '../../validations/staff-manager.validation.js');

describe('validations/staff-manager.validation.js', () => {
  let source;
  beforeAll(() => {
    source = fs.readFileSync(SRC, 'utf8');
  });

  test('file exists', () => {
    expect(fs.existsSync(SRC)).toBe(true);
  });

  test('is syntactically valid JavaScript', () => {
    expect(() => new vm.Script(source, { filename: 'staff-manager.validation.js' })).not.toThrow();
  });

  test('defines validation rules', () => {
    expect(source).toMatch(/(?:body|param|query)\s*\(/);
  });

  test('has npm dependencies (1)', () => {
    const npms = (source.match(/require\s*\(\s*['"](?![./])[^'"]+['"]\s*\)/g) || []);
    expect(npms.length).toBe(1);
  });

  test('has module.exports', () => {
    expect(source).toMatch(/module\.exports/);
  });

  test('exports createStaffProfile', () => {
    expect(source).toMatch(/createStaffProfile/);
  });

  test('exports updateStaffProfile', () => {
    expect(source).toMatch(/updateStaffProfile/);
  });

  test('exports createDepartment', () => {
    expect(source).toMatch(/createDepartment/);
  });

  test('exports updateDepartment', () => {
    expect(source).toMatch(/updateDepartment/);
  });

  test('exports createPosition', () => {
    expect(source).toMatch(/createPosition/);
  });
});
