/**
 * Auto-generated tests for students/student-service.js
 * Validates syntax, structure, and patterns (model — 3546L)
 * @generated by P#106 universal generator
 */
'use strict';

const fs = require('fs');
const path = require('path');
const vm = require('vm');

const SRC = path.resolve(__dirname, '../../students/student-service.js');

describe('students/student-service.js', () => {
  let source;
  beforeAll(() => {
    source = fs.readFileSync(SRC, 'utf8');
  });

  test('file exists', () => {
    expect(fs.existsSync(SRC)).toBe(true);
  });

  test('is syntactically valid JavaScript', () => {
    expect(() => new vm.Script(source, { filename: 'student-service.js' })).not.toThrow();
  });

  test('defines a Mongoose model', () => {
    expect(source).toMatch(/mongoose\.model\s*\(/);
  });

  test('has required fields', () => {
    expect(source).toMatch(/required\s*:\s*true/);
  });

  test('defines indexes', () => {
    expect(source).toMatch(/index/);
  });

  test('has npm dependencies (2)', () => {
    const npms = (source.match(/require\s*\(\s*['"](?![./])[^'"]+['"]\s*\)/g) || []);
    expect(npms.length).toBe(2);
  });

  test('has local dependencies (1)', () => {
    const locals = (source.match(/require\s*\(\s*['"]\.[^'"]+['"]\s*\)/g) || []);
    expect(locals.length).toBe(1);
  });

  test('has module.exports', () => {
    expect(source).toMatch(/module\.exports/);
  });

  test('exports StudentService', () => {
    expect(source).toMatch(/StudentService/);
  });

  test('exports studentService', () => {
    expect(source).toMatch(/studentService/);
  });

  test('exports studentConfig', () => {
    expect(source).toMatch(/studentConfig/);
  });
});
