/**
 * Auto-generated tests for config/swagger.js (swaggerJsdoc spec)
 * @generated by _gen_config_tests.js (manual — name clash with swagger.config.js)
 */
'use strict';

/* ── Mocks ── */
jest.mock('swagger-jsdoc', () => jest.fn(() => ({
  openapi: '3.0.0',
  info: { title: 'Test', version: '1.0.0' },
  paths: {},
})), { virtual: true });

/* ── Module under test ── */
const mod = require('../../config/swagger');

describe('config/swagger', () => {
  test('should export a valid spec object', () => {
    expect(mod).toBeDefined();
    expect(typeof mod).toBe('object');
  });

  test('should have openapi version', () => {
    expect(mod.openapi).toBeDefined();
  });

  test('should have info block', () => {
    expect(mod.info).toBeDefined();
  });

  test('should have paths property', () => {
    expect(mod).toHaveProperty('paths');
  });
});
