/**
 * Auto-generated tests for seed/system-settings-seed.js
 * Validates syntax, structure, and patterns (module — 177L)
 * @generated by P#106 universal generator
 */
'use strict';

const fs = require('fs');
const path = require('path');
const vm = require('vm');

const SRC = path.resolve(__dirname, '../../seed/system-settings-seed.js');

describe('seed/system-settings-seed.js', () => {
  let source;
  beforeAll(() => {
    source = fs.readFileSync(SRC, 'utf8');
  });

  test('file exists', () => {
    expect(fs.existsSync(SRC)).toBe(true);
  });

  test('is syntactically valid JavaScript', () => {
    expect(() => new vm.Script(source, { filename: 'system-settings-seed.js' })).not.toThrow();
  });

  test('has npm dependencies (2)', () => {
    const npms = (source.match(/require\s*\(\s*['"](?![./])[^'"]+['"]\s*\)/g) || []);
    expect(npms.length).toBe(2);
  });
});
