/**
 * ثوابت جدول المستفيدين
 * Beneficiaries Table Constants
 */

// Sample / fallback data
export const sampleData = [
  {
    id: 1,
    name: 'أحمد محمد علي',
    nameEn: 'Ahmed Mohammed Ali',
    nationalId: '1234567890',
    birthDate: '2012-03-15',
    age: 14,
    gender: 'male',
    phone: '0501234567',
    email: 'ahmed@example.com',
    address: 'الرياض، حي النرجس',
    status: 'active',
    category: 'physical',
    joinDate: '2024-01-15',
    lastVisit: '2026-01-10',
    nextAppointment: '2026-01-20',
    totalSessions: 45,
    completedSessions: 42,
    progress: 75,
    therapist: 'د. سارة أحمد',
    guardian: 'محمد علي',
    guardianPhone: '0551234567',
    notes: 'تحسن ملحوظ في الحركة',
    favorite: false,
    archived: false,
  },
  {
    id: 2,
    name: 'فاطمة أحمد حسن',
    nameEn: 'Fatima Ahmed Hassan',
    nationalId: '0987654321',
    birthDate: '2016-07-22',
    age: 10,
    gender: 'female',
    phone: '0557654321',
    email: 'fatima@example.com',
    address: 'جدة، حي الروضة',
    status: 'active',
    category: 'mental',
    joinDate: '2024-03-20',
    lastVisit: '2026-01-12',
    nextAppointment: '2026-01-18',
    totalSessions: 38,
    completedSessions: 35,
    progress: 82,
    therapist: 'أ. نورة خالد',
    guardian: 'أحمد حسن',
    guardianPhone: '0557654322',
    notes: 'تفاعل جيد مع الأنشطة',
    favorite: true,
    archived: false,
  },
  {
    id: 3,
    name: 'خالد سعيد محمود',
    nameEn: 'Khaled Saeed Mahmoud',
    nationalId: '5678901234',
    birthDate: '2009-11-08',
    age: 17,
    gender: 'male',
    phone: '0509876543',
    email: null,
    address: 'الدمام، حي الفيصلية',
    status: 'pending',
    category: 'sensory',
    joinDate: '2026-01-05',
    lastVisit: null,
    nextAppointment: '2026-01-16',
    totalSessions: 5,
    completedSessions: 2,
    progress: 20,
    therapist: 'د. محمد صالح',
    guardian: 'سعيد محمود',
    guardianPhone: '0509876544',
    notes: 'بحاجة لتقييم شامل',
    favorite: false,
    archived: false,
  },
  {
    id: 4,
    name: 'نورة عبدالله',
    nameEn: 'Noura Abdullah',
    nationalId: '3456789012',
    birthDate: '2014-05-14',
    age: 12,
    gender: 'female',
    phone: '0503456789',
    email: 'noura@example.com',
    address: 'مكة، حي العزيزية',
    status: 'inactive',
    category: 'multiple',
    joinDate: '2023-09-10',
    lastVisit: '2025-11-20',
    nextAppointment: null,
    totalSessions: 67,
    completedSessions: 65,
    progress: 88,
    therapist: 'د. سارة أحمد',
    guardian: 'عبدالله محمد',
    guardianPhone: '0503456780',
    notes: 'تم إيقاف العلاج مؤقتاً',
    favorite: false,
    archived: false,
  },
];

// Table column definitions
export const columns = [
  { id: 'name', label: 'الاسم', sortable: true },
  { id: 'nationalId', label: 'رقم الهوية', sortable: true },
  { id: 'age', label: 'العمر', sortable: true },
  { id: 'category', label: 'نوع الإعاقة', sortable: true },
  { id: 'status', label: 'الحالة', sortable: true },
  { id: 'totalSessions', label: 'الجلسات', sortable: true },
  { id: 'progress', label: 'التقدم', sortable: true },
  { id: 'lastVisit', label: 'آخر زيارة', sortable: true },
  { id: 'actions', label: 'الإجراءات', sortable: false },
];

// Default filters
export const DEFAULT_FILTERS = {
  status: 'all',
  category: 'all',
  gender: 'all',
  ageRange: 'all',
  dateRange: 'all',
};
