export const DEMO_ATTENDANCE = [
  {
    _id: 'a1',
    employeeId: 'EMP-2501',
    employeeName: 'أحمد محمد العتيبي',
    department: 'تقنية المعلومات',
    checkIn: '07:55',
    checkOut: '16:10',
    status: 'present',
    overtime: 0,
  },
  {
    _id: 'a2',
    employeeId: 'EMP-2502',
    employeeName: 'سارة أحمد الغامدي',
    department: 'الموارد البشرية',
    checkIn: '08:15',
    checkOut: '16:45',
    status: 'present',
    overtime: 0.5,
  },
  {
    _id: 'a3',
    employeeId: 'EMP-2503',
    employeeName: 'خالد العلي الشهري',
    department: 'المالية',
    checkIn: '09:10',
    checkOut: null,
    status: 'late',
    overtime: 0,
  },
  {
    _id: 'a4',
    employeeId: 'EMP-2504',
    employeeName: 'نورة السالم المطيري',
    department: 'التعليم',
    checkIn: null,
    checkOut: null,
    status: 'absent',
    overtime: 0,
  },
  {
    _id: 'a5',
    employeeId: 'EMP-2505',
    employeeName: 'فهد الحربي الدوسري',
    department: 'العلاج الطبيعي',
    checkIn: '07:45',
    checkOut: '15:50',
    status: 'present',
    overtime: 0,
  },
  {
    _id: 'a6',
    employeeId: 'EMP-2506',
    employeeName: 'منى القحطاني',
    department: 'الإدارة',
    checkIn: '07:50',
    checkOut: '17:20',
    status: 'present',
    overtime: 1.5,
  },
  {
    _id: 'a7',
    employeeId: 'EMP-2507',
    employeeName: 'عبدالله الشمري',
    department: 'العلاج الوظيفي',
    checkIn: null,
    checkOut: null,
    status: 'on_leave',
    overtime: 0,
  },
  {
    _id: 'a8',
    employeeId: 'EMP-2508',
    employeeName: 'ريم الدوسري',
    department: 'علاج النطق',
    checkIn: '08:05',
    checkOut: '16:05',
    status: 'present',
    overtime: 0,
  },
  {
    _id: 'a9',
    employeeId: 'EMP-2509',
    employeeName: 'محمد الزهراني',
    department: 'التمريض',
    checkIn: '07:30',
    checkOut: '16:30',
    status: 'present',
    overtime: 1.0,
  },
  {
    _id: 'a10',
    employeeId: 'EMP-2510',
    employeeName: 'هند العنزي',
    department: 'الخدمات المساندة',
    checkIn: '08:00',
    checkOut: '12:00',
    status: 'half_day',
    overtime: 0,
  },
];
