export const DEMO_LEAVES = [
  {
    _id: 'l1',
    employeeId: 'EMP-2501',
    employeeName: 'أحمد محمد العتيبي',
    leaveType: 'annual',
    startDate: '2026-03-10',
    endDate: '2026-03-15',
    days: 6,
    status: 'approved',
    reason: 'إجازة عائلية',
    managerNote: 'بالتوفيق',
  },
  {
    _id: 'l2',
    employeeId: 'EMP-2502',
    employeeName: 'سارة أحمد الغامدي',
    leaveType: 'sick',
    startDate: '2026-03-05',
    endDate: '2026-03-06',
    days: 2,
    status: 'approved',
    reason: 'مراجعة طبية وفحوصات مخبرية',
    managerNote: 'سلامتك',
  },
  {
    _id: 'l3',
    employeeId: 'EMP-2503',
    employeeName: 'خالد العلي الشهري',
    leaveType: 'annual',
    startDate: '2026-03-20',
    endDate: '2026-03-25',
    days: 6,
    status: 'pending',
    reason: 'سفر عائلي للخارج',
  },
  {
    _id: 'l4',
    employeeId: 'EMP-2507',
    employeeName: 'عبدالله الشمري',
    leaveType: 'emergency',
    startDate: '2026-03-08',
    endDate: '2026-03-10',
    days: 3,
    status: 'approved',
    reason: 'ظرف عائلي طارئ',
    managerNote: 'تم الاعتماد',
  },
  {
    _id: 'l5',
    employeeId: 'EMP-2508',
    employeeName: 'ريم الدوسري',
    leaveType: 'annual',
    startDate: '2026-04-01',
    endDate: '2026-04-05',
    days: 5,
    status: 'pending',
    reason: 'إجازة شخصية',
  },
  {
    _id: 'l6',
    employeeId: 'EMP-2504',
    employeeName: 'نورة السالم المطيري',
    leaveType: 'sick',
    startDate: '2026-02-20',
    endDate: '2026-02-24',
    days: 5,
    status: 'rejected',
    reason: 'إنفلونزا موسمية',
    managerNote: 'يرجى تقديم تقرير طبي معتمد',
  },
  {
    _id: 'l7',
    employeeId: 'EMP-2506',
    employeeName: 'منى القحطاني',
    leaveType: 'hajj',
    startDate: '2026-06-01',
    endDate: '2026-06-15',
    days: 15,
    status: 'pending',
    reason: 'أداء فريضة الحج',
  },
  {
    _id: 'l8',
    employeeId: 'EMP-2509',
    employeeName: 'محمد الزهراني',
    leaveType: 'unpaid',
    startDate: '2026-04-10',
    endDate: '2026-04-14',
    days: 5,
    status: 'rejected',
    reason: 'سفر شخصي',
    managerNote: 'لا يمكن الموافقة بسبب ضغط العمل خلال هذه الفترة',
  },
];
