export const DEMO_REVIEWS = [
  {
    _id: 'r1',
    employeeId: 'EMP-2501',
    employeeName: 'أحمد محمد العتيبي',
    department: 'تقنية المعلومات',
    reviewPeriod: '2026-Q1',
    type: 'ربع سنوي',
    overallRating: 4.2,
    reviewer: 'منى القحطاني',
    status: 'completed',
  },
  {
    _id: 'r2',
    employeeId: 'EMP-2502',
    employeeName: 'سارة أحمد الغامدي',
    department: 'الموارد البشرية',
    reviewPeriod: '2026-Q1',
    type: 'ربع سنوي',
    overallRating: 4.5,
    reviewer: 'منى القحطاني',
    status: 'completed',
  },
  {
    _id: 'r3',
    employeeId: 'EMP-2503',
    employeeName: 'خالد العلي الشهري',
    department: 'المالية',
    reviewPeriod: '2026-Q1',
    type: 'ربع سنوي',
    overallRating: 3.8,
    reviewer: 'منى القحطاني',
    status: 'in_progress',
  },
  {
    _id: 'r4',
    employeeId: 'EMP-2505',
    employeeName: 'فهد الحربي',
    department: 'العلاج الطبيعي',
    reviewPeriod: '2026-Q1',
    type: 'ربع سنوي',
    overallRating: 4.0,
    reviewer: 'سارة أحمد الغامدي',
    status: 'draft',
  },
  {
    _id: 'r5',
    employeeId: 'EMP-2504',
    employeeName: 'نورة السالم المطيري',
    department: 'التعليم',
    reviewPeriod: '2026-Q1',
    type: 'ربع سنوي',
    overallRating: 4.3,
    reviewer: 'سارة أحمد الغامدي',
    status: 'completed',
  },
  {
    _id: 'r6',
    employeeId: 'EMP-2508',
    employeeName: 'ريم الدوسري',
    department: 'علاج النطق',
    reviewPeriod: '2026-Q1',
    type: 'ربع سنوي',
    overallRating: 4.1,
    reviewer: 'منى القحطاني',
    status: 'completed',
  },
];
