/**
 * 📄 خدمة المستندات الذكية — Smart Documents Service
 * AlAwael ERP — Templates, AI generation, workflows, analytics
 * @created 2026-03-13
 */
import apiClient from './api.client';
import logger from '../utils/logger';

const safe = (fn, fallback = null) =>
  fn().catch(err => {
    logger.warn('smartDocumentsService ▸', err.message);
    return fallback;
  });

/* ═══ Static Constants ═══ */
const TEMPLATE_CATEGORIES = [
  { id: 'EMPLOYEE', label: 'شؤون الموظفين', icon: '👥', color: '#1E88E5' },
  { id: 'STUDENT', label: 'شؤون الطلاب', icon: '🎓', color: '#9C27B0' },
  { id: 'FINANCE', label: 'مالية ومحاسبة', icon: '💰', color: '#43A047' },
  { id: 'LEGAL', label: 'قانونية وعقود', icon: '⚖️', color: '#E53935' },
  { id: 'MEDICAL', label: 'طبية وصحية', icon: '🏥', color: '#00BCD4' },
  { id: 'TRANSPORT', label: 'نقل ولوجستيات', icon: '🚛', color: '#FF9800' },
  { id: 'IT', label: 'تقنية المعلومات', icon: '💻', color: '#3F51B5' },
  { id: 'PROCUREMENT', label: 'مشتريات وتوريد', icon: '🛒', color: '#795548' },
  { id: 'QUALITY', label: 'جودة وامتثال', icon: '✅', color: '#009688' },
  { id: 'MARKETING', label: 'تسويق وعلاقات', icon: '📢', color: '#FF5722' },
  { id: 'HOUSING', label: 'إسكان ومرافق', icon: '🏠', color: '#607D8B' },
  { id: 'ADMIN', label: 'إدارية عامة', icon: '📋', color: '#757575' },
];

const DOCUMENT_STATUSES = [
  { id: 'draft', label: 'مسودة', color: '#9E9E9E' },
  { id: 'pending', label: 'قيد المراجعة', color: '#FF9800' },
  { id: 'approved', label: 'معتمد', color: '#43A047' },
  { id: 'rejected', label: 'مرفوض', color: '#E53935' },
  { id: 'published', label: 'منشور', color: '#1E88E5' },
  { id: 'archived', label: 'مؤرشف', color: '#607D8B' },
];

const AI_FEATURES = [
  {
    id: 'auto-fill',
    label: 'تعبئة تلقائية',
    icon: '🤖',
    desc: 'تعبئة البيانات من النظام تلقائياً',
  },
  {
    id: 'ocr',
    label: 'التعرف الضوئي',
    icon: '👁️',
    desc: 'استخراج النص من الصور والملفات الممسوحة',
  },
  { id: 'summarize', label: 'تلخيص ذكي', icon: '📝', desc: 'تلخيص المستندات الطويلة تلقائياً' },
  {
    id: 'translate',
    label: 'ترجمة فورية',
    icon: '🌍',
    desc: 'ترجمة المستندات بين العربية والإنجليزية',
  },
  { id: 'classify', label: 'تصنيف تلقائي', icon: '🏷️', desc: 'تصنيف المستندات حسب المحتوى' },
  { id: 'validate', label: 'تدقيق لغوي', icon: '✍️', desc: 'مراجعة وتصحيح الأخطاء اللغوية' },
];

const WORKFLOW_STAGES = [
  { id: 'creation', label: 'الإنشاء', color: '#9E9E9E' },
  { id: 'review', label: 'المراجعة', color: '#FF9800' },
  { id: 'approval', label: 'الاعتماد', color: '#1E88E5' },
  { id: 'signing', label: 'التوقيع', color: '#9C27B0' },
  { id: 'distribution', label: 'التوزيع', color: '#43A047' },
];

const OUTPUT_FORMATS = [
  { id: 'pdf', label: 'PDF', icon: '📄', color: '#E53935' },
  { id: 'docx', label: 'Word', icon: '📝', color: '#1E88E5' },
  { id: 'html', label: 'HTML', icon: '🌐', color: '#FF9800' },
  { id: 'xlsx', label: 'Excel', icon: '📊', color: '#43A047' },
];

/* ═══ Mock Templates (35 templates across all categories) ═══ */
const MOCK_TEMPLATES = [
  // EMPLOYEE
  {
    id: 'T001',
    name: 'خطاب تعريف موظف',
    nameEn: 'Employee Introduction Letter',
    type: 'EMPLOYEE',
    language: 'AR',
    difficulty: 'easy',
    usageCount: 342,
    rating: 4.8,
    fields: [
      'EMPLOYEE_NAME',
      'EMPLOYEE_ID',
      'POSITION',
      'DEPARTMENT',
      'JOIN_DATE',
      'SALARY',
      'DATE',
    ],
    body: '<h2>خطاب تعريف</h2><p>نفيد بأن السيد/ة {{EMPLOYEE_NAME}} يعمل لدينا بوظيفة {{POSITION}} في قسم {{DEPARTMENT}} منذ {{JOIN_DATE}}.</p>',
    estimatedTime: '2 دقيقة',
    tags: ['تعريف', 'موظف', 'خطاب'],
  },
  {
    id: 'T002',
    name: 'شهادة خبرة',
    nameEn: 'Experience Certificate',
    type: 'EMPLOYEE',
    language: 'AR',
    difficulty: 'easy',
    usageCount: 289,
    rating: 4.9,
    fields: ['EMPLOYEE_NAME', 'POSITION', 'DEPARTMENT', 'START_DATE', 'END_DATE', 'DATE'],
    body: '<h2>شهادة خبرة</h2><p>نشهد بأن {{EMPLOYEE_NAME}} قد عمل لدينا بوظيفة {{POSITION}} في قسم {{DEPARTMENT}} من {{START_DATE}} حتى {{END_DATE}}.</p>',
    estimatedTime: '2 دقيقة',
    tags: ['خبرة', 'شهادة'],
  },
  {
    id: 'T003',
    name: 'نموذج طلب إجازة',
    nameEn: 'Leave Request Form',
    type: 'EMPLOYEE',
    language: 'AR',
    difficulty: 'easy',
    usageCount: 512,
    rating: 4.7,
    fields: [
      'EMPLOYEE_NAME',
      'DEPARTMENT',
      'LEAVE_TYPE',
      'START_DATE',
      'END_DATE',
      'REASON',
      'DATE',
    ],
    body: '<h2>طلب إجازة</h2><p>يرجى الموافقة على طلب الإجازة المقدم من {{EMPLOYEE_NAME}} - {{DEPARTMENT}}</p>',
    estimatedTime: '1 دقيقة',
    tags: ['إجازة', 'طلب'],
  },
  // STUDENT
  {
    id: 'T004',
    name: 'شهادة قيد طالب',
    nameEn: 'Student Enrollment Certificate',
    type: 'STUDENT',
    language: 'AR',
    difficulty: 'easy',
    usageCount: 445,
    rating: 4.8,
    fields: ['STUDENT_NAME', 'STUDENT_ID', 'GRADE', 'SECTION', 'ACADEMIC_YEAR', 'DATE'],
    body: '<h2>شهادة قيد</h2><p>نفيد بأن الطالب/ة {{STUDENT_NAME}} مقيد/ة لدينا في الصف {{GRADE}} - الشعبة {{SECTION}} للعام الدراسي {{ACADEMIC_YEAR}}.</p>',
    estimatedTime: '1 دقيقة',
    tags: ['طالب', 'قيد', 'شهادة'],
  },
  {
    id: 'T005',
    name: 'كشف درجات',
    nameEn: 'Grade Report',
    type: 'STUDENT',
    language: 'AR',
    difficulty: 'medium',
    usageCount: 378,
    rating: 4.6,
    fields: ['STUDENT_NAME', 'STUDENT_ID', 'GRADE', 'SEMESTER', 'SUBJECTS', 'GPA', 'DATE'],
    body: '<h2>كشف درجات</h2><p>الطالب/ة: {{STUDENT_NAME}} - الصف: {{GRADE}} - الفصل: {{SEMESTER}}</p>',
    estimatedTime: '3 دقائق',
    tags: ['درجات', 'كشف'],
  },
  {
    id: 'T006',
    name: 'إفادة حسن سلوك',
    nameEn: 'Good Conduct Certificate',
    type: 'STUDENT',
    language: 'AR',
    difficulty: 'easy',
    usageCount: 201,
    rating: 4.5,
    fields: ['STUDENT_NAME', 'STUDENT_ID', 'GRADE', 'DATE'],
    body: '<h2>إفادة حسن سلوك</h2><p>نشهد بأن الطالب/ة {{STUDENT_NAME}} يتحلى بحسن السلوك والأخلاق الحميدة.</p>',
    estimatedTime: '1 دقيقة',
    tags: ['سلوك', 'إفادة'],
  },
  // FINANCE
  {
    id: 'T007',
    name: 'سند قبض',
    nameEn: 'Receipt Voucher',
    type: 'FINANCE',
    language: 'AR',
    difficulty: 'easy',
    usageCount: 678,
    rating: 4.9,
    fields: [
      'RECEIPT_NO',
      'PAYER_NAME',
      'AMOUNT',
      'AMOUNT_WORDS',
      'PURPOSE',
      'PAYMENT_METHOD',
      'DATE',
    ],
    body: '<h2>سند قبض</h2><p>استلمنا من السيد/ة {{PAYER_NAME}} مبلغ {{AMOUNT}} ريال فقط {{AMOUNT_WORDS}}.</p>',
    estimatedTime: '2 دقيقة',
    tags: ['قبض', 'سند', 'مالي'],
  },
  {
    id: 'T008',
    name: 'سند صرف',
    nameEn: 'Payment Voucher',
    type: 'FINANCE',
    language: 'AR',
    difficulty: 'easy',
    usageCount: 590,
    rating: 4.8,
    fields: ['VOUCHER_NO', 'PAYEE_NAME', 'AMOUNT', 'AMOUNT_WORDS', 'PURPOSE', 'DATE'],
    body: '<h2>سند صرف</h2><p>يُصرف للسيد/ة {{PAYEE_NAME}} مبلغ {{AMOUNT}} ريال عن {{PURPOSE}}.</p>',
    estimatedTime: '2 دقيقة',
    tags: ['صرف', 'سند'],
  },
  {
    id: 'T009',
    name: 'فاتورة ضريبية',
    nameEn: 'Tax Invoice',
    type: 'FINANCE',
    language: 'BILINGUAL',
    difficulty: 'medium',
    usageCount: 423,
    rating: 4.7,
    fields: [
      'INVOICE_NO',
      'CLIENT_NAME',
      'CLIENT_VAT',
      'ITEMS',
      'SUBTOTAL',
      'VAT_AMOUNT',
      'TOTAL',
      'DATE',
    ],
    body: '<h2>فاتورة ضريبية / Tax Invoice</h2>',
    estimatedTime: '5 دقائق',
    tags: ['فاتورة', 'ضريبة'],
  },
  // LEGAL
  {
    id: 'T010',
    name: 'عقد عمل',
    nameEn: 'Employment Contract',
    type: 'LEGAL',
    language: 'AR',
    difficulty: 'hard',
    usageCount: 156,
    rating: 4.9,
    fields: [
      'EMPLOYEE_NAME',
      'NATIONAL_ID',
      'POSITION',
      'SALARY',
      'START_DATE',
      'DURATION',
      'BENEFITS',
      'DATE',
    ],
    body: '<h2>عقد عمل</h2><p>بين المؤسسة (الطرف الأول) والسيد/ة {{EMPLOYEE_NAME}} (الطرف الثاني)...</p>',
    estimatedTime: '10 دقائق',
    tags: ['عقد', 'عمل'],
  },
  {
    id: 'T011',
    name: 'عقد إيجار',
    nameEn: 'Lease Agreement',
    type: 'LEGAL',
    language: 'AR',
    difficulty: 'hard',
    usageCount: 89,
    rating: 4.6,
    fields: ['TENANT_NAME', 'PROPERTY_DESC', 'RENT_AMOUNT', 'DURATION', 'START_DATE', 'DATE'],
    body: '<h2>عقد إيجار</h2><p>تم الاتفاق بين الطرف الأول والسيد/ة {{TENANT_NAME}} على...</p>',
    estimatedTime: '15 دقيقة',
    tags: ['عقد', 'إيجار'],
  },
  {
    id: 'T012',
    name: 'تفويض رسمي',
    nameEn: 'Power of Attorney',
    type: 'LEGAL',
    language: 'AR',
    difficulty: 'medium',
    usageCount: 234,
    rating: 4.7,
    fields: ['AUTHORIZER_NAME', 'AUTHORIZED_NAME', 'PURPOSE', 'VALIDITY', 'DATE'],
    body: '<h2>تفويض رسمي</h2><p>أنا الموقع أدناه {{AUTHORIZER_NAME}} أفوض السيد/ة {{AUTHORIZED_NAME}} بـ{{PURPOSE}}.</p>',
    estimatedTime: '3 دقائق',
    tags: ['تفويض'],
  },
  // MEDICAL
  {
    id: 'T013',
    name: 'تقرير طبي',
    nameEn: 'Medical Report',
    type: 'MEDICAL',
    language: 'AR',
    difficulty: 'medium',
    usageCount: 167,
    rating: 4.5,
    fields: ['PATIENT_NAME', 'PATIENT_ID', 'DIAGNOSIS', 'TREATMENT', 'DOCTOR_NAME', 'DATE'],
    body: '<h2>تقرير طبي</h2><p>المريض: {{PATIENT_NAME}}<br>التشخيص: {{DIAGNOSIS}}</p>',
    estimatedTime: '5 دقائق',
    tags: ['طبي', 'تقرير'],
  },
  {
    id: 'T014',
    name: 'وصفة طبية',
    nameEn: 'Medical Prescription',
    type: 'MEDICAL',
    language: 'BILINGUAL',
    difficulty: 'easy',
    usageCount: 892,
    rating: 4.8,
    fields: ['PATIENT_NAME', 'AGE', 'MEDICATIONS', 'DOCTOR_NAME', 'DATE'],
    body: '<h2>وصفة طبية</h2>',
    estimatedTime: '2 دقيقة',
    tags: ['وصفة', 'دواء'],
  },
  {
    id: 'T015',
    name: 'إجازة مرضية',
    nameEn: 'Sick Leave Certificate',
    type: 'MEDICAL',
    language: 'AR',
    difficulty: 'easy',
    usageCount: 345,
    rating: 4.6,
    fields: ['PATIENT_NAME', 'DIAGNOSIS', 'LEAVE_DAYS', 'START_DATE', 'DOCTOR_NAME', 'DATE'],
    body: '<h2>إجازة مرضية</h2><p>نوصي بمنح {{PATIENT_NAME}} إجازة مرضية لمدة {{LEAVE_DAYS}} أيام.</p>',
    estimatedTime: '2 دقيقة',
    tags: ['مرضية', 'إجازة'],
  },
  // TRANSPORT
  {
    id: 'T016',
    name: 'أمر نقل',
    nameEn: 'Transport Order',
    type: 'TRANSPORT',
    language: 'AR',
    difficulty: 'easy',
    usageCount: 278,
    rating: 4.4,
    fields: ['DRIVER_NAME', 'VEHICLE_NO', 'DESTINATION', 'PURPOSE', 'DEPARTURE_DATE', 'DATE'],
    body: '<h2>أمر نقل</h2><p>يُكلف السائق {{DRIVER_NAME}} بقيادة المركبة رقم {{VEHICLE_NO}} إلى {{DESTINATION}}.</p>',
    estimatedTime: '2 دقيقة',
    tags: ['نقل', 'أمر'],
  },
  {
    id: 'T017',
    name: 'محضر تسليم مركبة',
    nameEn: 'Vehicle Handover Report',
    type: 'TRANSPORT',
    language: 'AR',
    difficulty: 'medium',
    usageCount: 134,
    rating: 4.3,
    fields: [
      'VEHICLE_NO',
      'VEHICLE_TYPE',
      'FROM_DRIVER',
      'TO_DRIVER',
      'CONDITION',
      'MILEAGE',
      'DATE',
    ],
    body: '<h2>محضر تسليم مركبة</h2>',
    estimatedTime: '5 دقائق',
    tags: ['مركبة', 'تسليم'],
  },
  // IT
  {
    id: 'T018',
    name: 'طلب دعم فني',
    nameEn: 'IT Support Request',
    type: 'IT',
    language: 'AR',
    difficulty: 'easy',
    usageCount: 456,
    rating: 4.5,
    fields: ['REQUESTER_NAME', 'DEPARTMENT', 'ISSUE_TYPE', 'DESCRIPTION', 'PRIORITY', 'DATE'],
    body: '<h2>طلب دعم فني</h2><p>مقدم من: {{REQUESTER_NAME}} - القسم: {{DEPARTMENT}}<br>نوع المشكلة: {{ISSUE_TYPE}}</p>',
    estimatedTime: '3 دقائق',
    tags: ['دعم', 'فني', 'تقنية'],
  },
  {
    id: 'T019',
    name: 'تقرير أمن معلومات',
    nameEn: 'Information Security Report',
    type: 'IT',
    language: 'AR',
    difficulty: 'hard',
    usageCount: 67,
    rating: 4.2,
    fields: ['REPORTER_NAME', 'INCIDENT_TYPE', 'SEVERITY', 'DESCRIPTION', 'ACTION_TAKEN', 'DATE'],
    body: '<h2>تقرير حادثة أمن معلومات</h2>',
    estimatedTime: '10 دقائق',
    tags: ['أمن', 'معلومات'],
  },
  // PROCUREMENT
  {
    id: 'T020',
    name: 'أمر شراء',
    nameEn: 'Purchase Order',
    type: 'PROCUREMENT',
    language: 'AR',
    difficulty: 'medium',
    usageCount: 389,
    rating: 4.7,
    fields: ['PO_NUMBER', 'SUPPLIER_NAME', 'ITEMS', 'TOTAL_AMOUNT', 'DELIVERY_DATE', 'DATE'],
    body: '<h2>أمر شراء</h2><p>رقم الأمر: {{PO_NUMBER}}<br>المورد: {{SUPPLIER_NAME}}</p>',
    estimatedTime: '5 دقائق',
    tags: ['شراء', 'أمر', 'مشتريات'],
  },
  {
    id: 'T021',
    name: 'طلب عرض أسعار',
    nameEn: 'Request for Quotation',
    type: 'PROCUREMENT',
    language: 'BILINGUAL',
    difficulty: 'medium',
    usageCount: 245,
    rating: 4.6,
    fields: ['RFQ_NUMBER', 'SUPPLIER_NAME', 'ITEMS', 'DEADLINE', 'DATE'],
    body: '<h2>طلب عرض أسعار</h2>',
    estimatedTime: '5 دقائق',
    tags: ['عرض', 'أسعار'],
  },
  // QUALITY
  {
    id: 'T022',
    name: 'تقرير تدقيق داخلي',
    nameEn: 'Internal Audit Report',
    type: 'QUALITY',
    language: 'AR',
    difficulty: 'hard',
    usageCount: 78,
    rating: 4.4,
    fields: ['AUDITOR_NAME', 'DEPARTMENT', 'SCOPE', 'FINDINGS', 'RECOMMENDATIONS', 'DATE'],
    body: '<h2>تقرير تدقيق داخلي</h2>',
    estimatedTime: '15 دقيقة',
    tags: ['تدقيق', 'جودة'],
  },
  {
    id: 'T023',
    name: 'نموذج عدم مطابقة',
    nameEn: 'Non-Conformance Report',
    type: 'QUALITY',
    language: 'AR',
    difficulty: 'medium',
    usageCount: 112,
    rating: 4.3,
    fields: ['NCR_NUMBER', 'AREA', 'DESCRIPTION', 'ROOT_CAUSE', 'CORRECTIVE_ACTION', 'DATE'],
    body: '<h2>تقرير عدم مطابقة</h2>',
    estimatedTime: '8 دقائق',
    tags: ['عدم مطابقة', 'جودة'],
  },
  // MARKETING
  {
    id: 'T024',
    name: 'خطة تسويقية',
    nameEn: 'Marketing Plan',
    type: 'MARKETING',
    language: 'AR',
    difficulty: 'hard',
    usageCount: 56,
    rating: 4.5,
    fields: ['CAMPAIGN_NAME', 'TARGET_AUDIENCE', 'BUDGET', 'CHANNELS', 'TIMELINE', 'DATE'],
    body: '<h2>خطة تسويقية</h2>',
    estimatedTime: '20 دقيقة',
    tags: ['تسويق', 'خطة'],
  },
  {
    id: 'T025',
    name: 'تقرير فعالية',
    nameEn: 'Event Report',
    type: 'MARKETING',
    language: 'AR',
    difficulty: 'medium',
    usageCount: 134,
    rating: 4.4,
    fields: ['EVENT_NAME', 'EVENT_DATE', 'LOCATION', 'ATTENDEES', 'SUMMARY', 'DATE'],
    body: '<h2>تقرير فعالية</h2>',
    estimatedTime: '10 دقائق',
    tags: ['فعالية', 'تقرير'],
  },
  // HOUSING
  {
    id: 'T026',
    name: 'طلب صيانة سكن',
    nameEn: 'Housing Maintenance Request',
    type: 'HOUSING',
    language: 'AR',
    difficulty: 'easy',
    usageCount: 312,
    rating: 4.3,
    fields: ['RESIDENT_NAME', 'UNIT_NUMBER', 'ISSUE_TYPE', 'DESCRIPTION', 'PRIORITY', 'DATE'],
    body: '<h2>طلب صيانة</h2><p>المقيم: {{RESIDENT_NAME}} - الوحدة: {{UNIT_NUMBER}}</p>',
    estimatedTime: '3 دقائق',
    tags: ['صيانة', 'سكن'],
  },
  {
    id: 'T027',
    name: 'محضر معاينة وحدة',
    nameEn: 'Unit Inspection Report',
    type: 'HOUSING',
    language: 'AR',
    difficulty: 'medium',
    usageCount: 89,
    rating: 4.2,
    fields: ['UNIT_NUMBER', 'INSPECTOR_NAME', 'CONDITION', 'ITEMS_CHECKED', 'REMARKS', 'DATE'],
    body: '<h2>محضر معاينة وحدة سكنية</h2>',
    estimatedTime: '10 دقائق',
    tags: ['معاينة', 'سكن'],
  },
  // ADMIN
  {
    id: 'T028',
    name: 'محضر اجتماع',
    nameEn: 'Meeting Minutes',
    type: 'ADMIN',
    language: 'AR',
    difficulty: 'medium',
    usageCount: 567,
    rating: 4.8,
    fields: [
      'MEETING_TITLE',
      'MEETING_DATE',
      'ATTENDEES',
      'AGENDA',
      'DECISIONS',
      'ACTION_ITEMS',
      'DATE',
    ],
    body: '<h2>محضر اجتماع</h2><p>عنوان الاجتماع: {{MEETING_TITLE}}<br>التاريخ: {{MEETING_DATE}}</p>',
    estimatedTime: '10 دقائق',
    tags: ['اجتماع', 'محضر'],
  },
  {
    id: 'T029',
    name: 'تعميم إداري',
    nameEn: 'Administrative Circular',
    type: 'ADMIN',
    language: 'AR',
    difficulty: 'easy',
    usageCount: 445,
    rating: 4.7,
    fields: ['CIRCULAR_NO', 'SUBJECT', 'BODY_TEXT', 'EFFECTIVE_DATE', 'DATE'],
    body: '<h2>تعميم إداري</h2><p>رقم التعميم: {{CIRCULAR_NO}}<br>الموضوع: {{SUBJECT}}</p>',
    estimatedTime: '5 دقائق',
    tags: ['تعميم', 'إداري'],
  },
  {
    id: 'T030',
    name: 'خطاب رسمي',
    nameEn: 'Official Letter',
    type: 'ADMIN',
    language: 'AR',
    difficulty: 'easy',
    usageCount: 890,
    rating: 4.9,
    fields: ['RECIPIENT_NAME', 'RECIPIENT_TITLE', 'SUBJECT', 'BODY_TEXT', 'DATE'],
    body: '<h2>خطاب رسمي</h2><p>السيد/ة {{RECIPIENT_NAME}} - {{RECIPIENT_TITLE}}<br>الموضوع: {{SUBJECT}}</p>',
    estimatedTime: '3 دقائق',
    tags: ['خطاب', 'رسمي'],
  },
  {
    id: 'T031',
    name: 'قرار إداري',
    nameEn: 'Administrative Decision',
    type: 'ADMIN',
    language: 'AR',
    difficulty: 'medium',
    usageCount: 234,
    rating: 4.6,
    fields: ['DECISION_NO', 'SUBJECT', 'BODY_TEXT', 'EFFECTIVE_DATE', 'DATE'],
    body: '<h2>قرار إداري</h2><p>رقم القرار: {{DECISION_NO}}</p>',
    estimatedTime: '8 دقائق',
    tags: ['قرار', 'إداري'],
  },
  {
    id: 'T032',
    name: 'خطاب شكر وتقدير',
    nameEn: 'Appreciation Letter',
    type: 'ADMIN',
    language: 'AR',
    difficulty: 'easy',
    usageCount: 312,
    rating: 4.8,
    fields: ['EMPLOYEE_NAME', 'DEPARTMENT', 'ACHIEVEMENT', 'DATE'],
    body: '<h2>خطاب شكر وتقدير</h2><p>تقديراً للجهود المتميزة التي بذلها/بذلتها {{EMPLOYEE_NAME}} من قسم {{DEPARTMENT}}.</p>',
    estimatedTime: '2 دقيقة',
    tags: ['شكر', 'تقدير'],
  },
  {
    id: 'T033',
    name: 'نموذج تقييم أداء',
    nameEn: 'Performance Evaluation Form',
    type: 'EMPLOYEE',
    language: 'AR',
    difficulty: 'hard',
    usageCount: 189,
    rating: 4.5,
    fields: [
      'EMPLOYEE_NAME',
      'DEPARTMENT',
      'POSITION',
      'EVALUATOR',
      'PERIOD',
      'RATING',
      'COMMENTS',
      'DATE',
    ],
    body: '<h2>نموذج تقييم أداء</h2>',
    estimatedTime: '15 دقيقة',
    tags: ['تقييم', 'أداء'],
  },
  {
    id: 'T034',
    name: 'طلب نقل موظف',
    nameEn: 'Employee Transfer Request',
    type: 'EMPLOYEE',
    language: 'AR',
    difficulty: 'easy',
    usageCount: 145,
    rating: 4.4,
    fields: ['EMPLOYEE_NAME', 'CURRENT_DEPT', 'NEW_DEPT', 'REASON', 'EFFECTIVE_DATE', 'DATE'],
    body: '<h2>طلب نقل</h2>',
    estimatedTime: '3 دقائق',
    tags: ['نقل', 'موظف'],
  },
  {
    id: 'T035',
    name: 'استقالة',
    nameEn: 'Resignation Letter',
    type: 'EMPLOYEE',
    language: 'AR',
    difficulty: 'easy',
    usageCount: 67,
    rating: 4.3,
    fields: ['EMPLOYEE_NAME', 'POSITION', 'DEPARTMENT', 'LAST_DAY', 'REASON', 'DATE'],
    body: '<h2>خطاب استقالة</h2>',
    estimatedTime: '3 دقائق',
    tags: ['استقالة'],
  },
];

/* ═══ Mock Generated Documents ═══ */
const MOCK_GENERATED_DOCS = [
  {
    _id: 'GD001',
    refNumber: 'DOC-2026-0001',
    templateId: 'T001',
    templateName: 'خطاب تعريف موظف',
    category: 'EMPLOYEE',
    title: 'خطاب تعريف — أحمد محمد',
    createdBy: 'سارة العلي',
    createdAt: '2026-03-12T09:30:00Z',
    status: 'published',
    format: 'pdf',
    fileSize: 245000,
    version: 2,
    approvedBy: 'محمد القحطاني',
    approvedAt: '2026-03-12T10:00:00Z',
    downloads: 5,
    tags: ['تعريف', 'موظف'],
  },
  {
    _id: 'GD002',
    refNumber: 'DOC-2026-0002',
    templateId: 'T007',
    templateName: 'سند قبض',
    category: 'FINANCE',
    title: 'سند قبض #1245 — شركة الأمل',
    createdBy: 'خالد الشمري',
    createdAt: '2026-03-12T11:15:00Z',
    status: 'approved',
    format: 'pdf',
    fileSize: 180000,
    version: 1,
    approvedBy: 'فاطمة الحربي',
    approvedAt: '2026-03-12T14:00:00Z',
    downloads: 3,
    tags: ['قبض', 'مالي'],
  },
  {
    _id: 'GD003',
    refNumber: 'DOC-2026-0003',
    templateId: 'T004',
    templateName: 'شهادة قيد طالب',
    category: 'STUDENT',
    title: 'شهادة قيد — عبدالله سعد',
    createdBy: 'نورة الدوسري',
    createdAt: '2026-03-11T08:45:00Z',
    status: 'published',
    format: 'pdf',
    fileSize: 198000,
    version: 1,
    approvedBy: 'أحمد الزهراني',
    approvedAt: '2026-03-11T09:30:00Z',
    downloads: 2,
    tags: ['قيد', 'طالب'],
  },
  {
    _id: 'GD004',
    refNumber: 'DOC-2026-0004',
    templateId: 'T010',
    templateName: 'عقد عمل',
    category: 'LEGAL',
    title: 'عقد عمل — محمد العتيبي',
    createdBy: 'سارة العلي',
    createdAt: '2026-03-11T14:20:00Z',
    status: 'pending',
    format: 'docx',
    fileSize: 420000,
    version: 3,
    approvedBy: null,
    downloads: 0,
    tags: ['عقد', 'عمل'],
  },
  {
    _id: 'GD005',
    refNumber: 'DOC-2026-0005',
    templateId: 'T028',
    templateName: 'محضر اجتماع',
    category: 'ADMIN',
    title: 'محضر اجتماع مجلس الإدارة — مارس 2026',
    createdBy: 'فهد المطيري',
    createdAt: '2026-03-10T16:00:00Z',
    status: 'published',
    format: 'pdf',
    fileSize: 356000,
    version: 1,
    approvedBy: 'محمد القحطاني',
    approvedAt: '2026-03-10T17:30:00Z',
    downloads: 12,
    tags: ['اجتماع', 'محضر'],
  },
  {
    _id: 'GD006',
    refNumber: 'DOC-2026-0006',
    templateId: 'T013',
    templateName: 'تقرير طبي',
    category: 'MEDICAL',
    title: 'تقرير طبي — فيصل الحربي',
    createdBy: 'د. عائشة السالم',
    createdAt: '2026-03-10T10:30:00Z',
    status: 'approved',
    format: 'pdf',
    fileSize: 290000,
    version: 1,
    approvedBy: 'د. سلمان الرشيدي',
    approvedAt: '2026-03-10T11:00:00Z',
    downloads: 1,
    tags: ['طبي', 'تقرير'],
  },
  {
    _id: 'GD007',
    refNumber: 'DOC-2026-0007',
    templateId: 'T020',
    templateName: 'أمر شراء',
    category: 'PROCUREMENT',
    title: 'أمر شراء — أثاث مكتبي',
    createdBy: 'علي الغامدي',
    createdAt: '2026-03-09T13:00:00Z',
    status: 'approved',
    format: 'pdf',
    fileSize: 267000,
    version: 2,
    approvedBy: 'خالد الشمري',
    approvedAt: '2026-03-09T15:00:00Z',
    downloads: 4,
    tags: ['شراء', 'مشتريات'],
  },
  {
    _id: 'GD008',
    refNumber: 'DOC-2026-0008',
    templateId: 'T029',
    templateName: 'تعميم إداري',
    category: 'ADMIN',
    title: 'تعميم — إجازة عيد الفطر 2026',
    createdBy: 'محمد القحطاني',
    createdAt: '2026-03-08T09:00:00Z',
    status: 'published',
    format: 'pdf',
    fileSize: 145000,
    version: 1,
    approvedBy: 'المدير العام',
    approvedAt: '2026-03-08T09:30:00Z',
    downloads: 89,
    tags: ['تعميم', 'إجازة'],
  },
  {
    _id: 'GD009',
    refNumber: 'DOC-2026-0009',
    templateId: 'T002',
    templateName: 'شهادة خبرة',
    category: 'EMPLOYEE',
    title: 'شهادة خبرة — سلمان الرشيدي',
    createdBy: 'سارة العلي',
    createdAt: '2026-03-07T11:45:00Z',
    status: 'draft',
    format: 'docx',
    fileSize: 210000,
    version: 1,
    approvedBy: null,
    downloads: 0,
    tags: ['خبرة', 'شهادة'],
  },
  {
    _id: 'GD010',
    refNumber: 'DOC-2026-0010',
    templateId: 'T003',
    templateName: 'نموذج طلب إجازة',
    category: 'EMPLOYEE',
    title: 'طلب إجازة — نورة الدوسري',
    createdBy: 'نورة الدوسري',
    createdAt: '2026-03-07T08:30:00Z',
    status: 'approved',
    format: 'pdf',
    fileSize: 132000,
    version: 1,
    approvedBy: 'فهد المطيري',
    approvedAt: '2026-03-07T10:00:00Z',
    downloads: 1,
    tags: ['إجازة', 'طلب'],
  },
  {
    _id: 'GD011',
    refNumber: 'DOC-2026-0011',
    templateId: 'T018',
    templateName: 'طلب دعم فني',
    category: 'IT',
    title: 'طلب دعم — مشكلة طابعة الطابق الثالث',
    createdBy: 'ماجد السبيعي',
    createdAt: '2026-03-06T14:00:00Z',
    status: 'published',
    format: 'pdf',
    fileSize: 156000,
    version: 1,
    approvedBy: 'أحمد التقني',
    approvedAt: '2026-03-06T15:00:00Z',
    downloads: 2,
    tags: ['دعم', 'فني'],
  },
  {
    _id: 'GD012',
    refNumber: 'DOC-2026-0012',
    templateId: 'T022',
    templateName: 'تقرير تدقيق داخلي',
    category: 'QUALITY',
    title: 'تقرير تدقيق — قسم المالية Q1 2026',
    createdBy: 'ريم الخالدي',
    createdAt: '2026-03-05T10:00:00Z',
    status: 'pending',
    format: 'docx',
    fileSize: 890000,
    version: 4,
    approvedBy: null,
    downloads: 0,
    tags: ['تدقيق', 'جودة'],
  },
  {
    _id: 'GD013',
    refNumber: 'DOC-2026-0013',
    templateId: 'T016',
    templateName: 'أمر نقل',
    category: 'TRANSPORT',
    title: 'أمر نقل — رحلة جدة',
    createdBy: 'فهد المطيري',
    createdAt: '2026-03-04T09:15:00Z',
    status: 'approved',
    format: 'pdf',
    fileSize: 145000,
    version: 1,
    approvedBy: 'علي الغامدي',
    approvedAt: '2026-03-04T10:00:00Z',
    downloads: 1,
    tags: ['نقل', 'أمر'],
  },
  {
    _id: 'GD014',
    refNumber: 'DOC-2026-0014',
    templateId: 'T030',
    templateName: 'خطاب رسمي',
    category: 'ADMIN',
    title: 'خطاب رسمي — وزارة التعليم',
    createdBy: 'محمد القحطاني',
    createdAt: '2026-03-03T11:30:00Z',
    status: 'published',
    format: 'pdf',
    fileSize: 198000,
    version: 2,
    approvedBy: 'المدير العام',
    approvedAt: '2026-03-03T14:00:00Z',
    downloads: 7,
    tags: ['خطاب', 'رسمي'],
  },
  {
    _id: 'GD015',
    refNumber: 'DOC-2026-0015',
    templateId: 'T009',
    templateName: 'فاتورة ضريبية',
    category: 'FINANCE',
    title: 'فاتورة ضريبية — شركة الأفق',
    createdBy: 'خالد الشمري',
    createdAt: '2026-03-02T15:00:00Z',
    status: 'rejected',
    format: 'pdf',
    fileSize: 234000,
    version: 1,
    approvedBy: null,
    downloads: 0,
    tags: ['فاتورة', 'ضريبة'],
    rejectionReason: 'خطأ في الرقم الضريبي',
  },
  {
    _id: 'GD016',
    refNumber: 'DOC-2026-0016',
    templateId: 'T026',
    templateName: 'طلب صيانة سكن',
    category: 'HOUSING',
    title: 'طلب صيانة — الوحدة A-204',
    createdBy: 'ماجد السبيعي',
    createdAt: '2026-03-01T08:00:00Z',
    status: 'approved',
    format: 'pdf',
    fileSize: 167000,
    version: 1,
    approvedBy: 'إبراهيم العمري',
    approvedAt: '2026-03-01T12:00:00Z',
    downloads: 2,
    tags: ['صيانة', 'سكن'],
  },
  {
    _id: 'GD017',
    refNumber: 'DOC-2026-0017',
    templateId: 'T032',
    templateName: 'خطاب شكر وتقدير',
    category: 'ADMIN',
    title: 'شكر وتقدير — فريق المشاريع',
    createdBy: 'محمد القحطاني',
    createdAt: '2026-02-28T10:00:00Z',
    status: 'published',
    format: 'pdf',
    fileSize: 178000,
    version: 1,
    approvedBy: 'المدير العام',
    approvedAt: '2026-02-28T11:00:00Z',
    downloads: 15,
    tags: ['شكر', 'تقدير'],
  },
  {
    _id: 'GD018',
    refNumber: 'DOC-2026-0018',
    templateId: 'T005',
    templateName: 'كشف درجات',
    category: 'STUDENT',
    title: 'كشف درجات — الصف السادس أ',
    createdBy: 'نورة الدوسري',
    createdAt: '2026-02-27T13:00:00Z',
    status: 'published',
    format: 'xlsx',
    fileSize: 567000,
    version: 1,
    approvedBy: 'أحمد الزهراني',
    approvedAt: '2026-02-27T15:00:00Z',
    downloads: 25,
    tags: ['درجات', 'كشف'],
  },
];

/* ═══ Mock Workflows ═══ */
const MOCK_WORKFLOWS = [
  {
    _id: 'WF001',
    documentRef: 'DOC-2026-0004',
    documentTitle: 'عقد عمل — محمد العتيبي',
    currentStage: 'review',
    initiator: 'سارة العلي',
    startedAt: '2026-03-11T14:20:00Z',
    stages: [
      {
        stage: 'creation',
        status: 'completed',
        assignee: 'سارة العلي',
        completedAt: '2026-03-11T14:20:00Z',
        notes: 'تم إنشاء العقد',
      },
      {
        stage: 'review',
        status: 'in-progress',
        assignee: 'فهد المطيري',
        startedAt: '2026-03-11T15:00:00Z',
        notes: 'قيد المراجعة القانونية',
      },
      { stage: 'approval', status: 'pending', assignee: 'محمد القحطاني' },
      { stage: 'signing', status: 'pending', assignee: 'المدير العام' },
      { stage: 'distribution', status: 'pending', assignee: 'سارة العلي' },
    ],
  },
  {
    _id: 'WF002',
    documentRef: 'DOC-2026-0012',
    documentTitle: 'تقرير تدقيق — قسم المالية Q1 2026',
    currentStage: 'approval',
    initiator: 'ريم الخالدي',
    startedAt: '2026-03-05T10:00:00Z',
    stages: [
      {
        stage: 'creation',
        status: 'completed',
        assignee: 'ريم الخالدي',
        completedAt: '2026-03-05T10:00:00Z',
        notes: 'تقرير أولي',
      },
      {
        stage: 'review',
        status: 'completed',
        assignee: 'خالد الشمري',
        completedAt: '2026-03-06T09:00:00Z',
        notes: 'تمت المراجعة وطلب تعديلات',
      },
      {
        stage: 'approval',
        status: 'in-progress',
        assignee: 'محمد القحطاني',
        startedAt: '2026-03-07T08:00:00Z',
      },
      { stage: 'signing', status: 'pending', assignee: 'المدير العام' },
      { stage: 'distribution', status: 'pending', assignee: 'ريم الخالدي' },
    ],
  },
  {
    _id: 'WF003',
    documentRef: 'DOC-2026-0001',
    documentTitle: 'خطاب تعريف — أحمد محمد',
    currentStage: 'distribution',
    initiator: 'سارة العلي',
    startedAt: '2026-03-12T09:30:00Z',
    stages: [
      {
        stage: 'creation',
        status: 'completed',
        assignee: 'سارة العلي',
        completedAt: '2026-03-12T09:30:00Z',
      },
      {
        stage: 'review',
        status: 'completed',
        assignee: 'فهد المطيري',
        completedAt: '2026-03-12T09:45:00Z',
      },
      {
        stage: 'approval',
        status: 'completed',
        assignee: 'محمد القحطاني',
        completedAt: '2026-03-12T10:00:00Z',
      },
      {
        stage: 'signing',
        status: 'completed',
        assignee: 'المدير العام',
        completedAt: '2026-03-12T10:30:00Z',
      },
      {
        stage: 'distribution',
        status: 'completed',
        assignee: 'سارة العلي',
        completedAt: '2026-03-12T11:00:00Z',
      },
    ],
  },
];

/* ═══ Mock Analytics ═══ */
const MOCK_ANALYTICS = {
  totalGenerated: 218,
  totalTemplates: MOCK_TEMPLATES.length,
  avgGenerationTime: 3.5,
  aiAccuracy: 96.8,
  monthlyUsage: [
    { month: 'أكتوبر', generated: 28, approved: 24 },
    { month: 'نوفمبر', generated: 35, approved: 31 },
    { month: 'ديسمبر', generated: 22, approved: 19 },
    { month: 'يناير', generated: 42, approved: 38 },
    { month: 'فبراير', generated: 48, approved: 44 },
    { month: 'مارس', generated: 43, approved: 39 },
  ],
  categoryUsage: TEMPLATE_CATEGORIES.map(cat => ({
    name: cat.label,
    value: MOCK_TEMPLATES.filter(t => t.type === cat.id).reduce((s, t) => s + t.usageCount, 0),
    color: cat.color,
  })).filter(c => c.value > 0),
  topTemplates: [...MOCK_TEMPLATES]
    .sort((a, b) => b.usageCount - a.usageCount)
    .slice(0, 8)
    .map(t => ({
      name: t.name,
      usageCount: t.usageCount,
      rating: t.rating,
      category: t.type,
    })),
  statusBreakdown: DOCUMENT_STATUSES.map(s => ({
    name: s.label,
    value: MOCK_GENERATED_DOCS.filter(d => d.status === s.id).length,
    color: s.color,
  })),
  formatDistribution: [
    { name: 'PDF', value: 14, color: '#E53935' },
    { name: 'Word', value: 3, color: '#1E88E5' },
    { name: 'Excel', value: 1, color: '#43A047' },
  ],
  recentActivity: [
    {
      user: 'سارة العلي',
      action: 'إنشاء مستند',
      document: 'خطاب تعريف — أحمد محمد',
      timestamp: '2026-03-12T09:30:00Z',
    },
    {
      user: 'خالد الشمري',
      action: 'اعتماد مستند',
      document: 'سند قبض #1245',
      timestamp: '2026-03-12T14:00:00Z',
    },
    {
      user: 'محمد القحطاني',
      action: 'نشر مستند',
      document: 'تعميم — إجازة عيد الفطر',
      timestamp: '2026-03-08T09:30:00Z',
    },
    {
      user: 'ريم الخالدي',
      action: 'تحديث مستند',
      document: 'تقرير تدقيق — المالية',
      timestamp: '2026-03-07T14:00:00Z',
    },
    {
      user: 'نورة الدوسري',
      action: 'إنشاء مستند',
      document: 'شهادة قيد — عبدالله سعد',
      timestamp: '2026-03-11T08:45:00Z',
    },
  ],
};

/* ═══ API Methods ═══ */
const smartDocumentsService = {
  /* ─── Templates ─── */
  getTemplates: () =>
    safe(
      () => apiClient.get('/documents-smart/templates').then(r => r.data?.data || r.data),
      MOCK_TEMPLATES
    ),
  getTemplateById: id =>
    safe(
      () => apiClient.get(`/documents-smart/templates/${id}`).then(r => r.data?.data || r.data),
      MOCK_TEMPLATES.find(t => t.id === id) || null
    ),
  searchTemplates: query => {
    const q = (query || '').toLowerCase();
    return Promise.resolve(
      MOCK_TEMPLATES.filter(
        t =>
          t.name.includes(q) ||
          t.nameEn?.toLowerCase().includes(q) ||
          (t.tags || []).some(tag => tag.includes(q)) ||
          t.type.toLowerCase().includes(q)
      )
    );
  },

  /* ─── Document Generation ─── */
  generate: data =>
    safe(
      () => apiClient.post('/documents-smart/generate', data).then(r => r.data?.data || r.data),
      {
        success: true,
        data: {
          _id: 'GD' + Date.now(),
          refNumber: `DOC-2026-${String(MOCK_GENERATED_DOCS.length + 1).padStart(4, '0')}`,
          content:
            '<div style="font-family: \'Traditional Arabic\', serif; direction: rtl; padding: 40px;"><h2 style="text-align: center; color: #1E88E5;">مؤسسة الأوائل التعليمية</h2><hr/><p>تم إنشاء المستند بنجاح باستخدام المحرك الذكي.</p><p style="margin-top: 30px; text-align: left; color: #666;">التاريخ: ' +
            new Date().toLocaleDateString('ar-SA') +
            '</p></div>',
          createdAt: new Date().toISOString(),
          status: 'draft',
        },
      }
    ),

  /* ─── Generated Documents ─── */
  getGeneratedDocuments: () =>
    safe(
      () => apiClient.get('/documents-smart/generated').then(r => r.data?.data || r.data),
      MOCK_GENERATED_DOCS
    ),
  getGeneratedDocument: id =>
    safe(
      () => apiClient.get(`/documents-smart/generated/${id}`).then(r => r.data?.data || r.data),
      MOCK_GENERATED_DOCS.find(d => d._id === id) || null
    ),
  updateDocumentStatus: (id, status) =>
    safe(() => apiClient.patch(`/documents-smart/generated/${id}/status`, { status }), {
      success: true,
    }),
  deleteGeneratedDocument: id =>
    safe(() => apiClient.delete(`/documents-smart/generated/${id}`), { success: true }),

  /* ─── Workflows ─── */
  getWorkflows: () =>
    safe(
      () => apiClient.get('/documents-smart/workflows').then(r => r.data?.data || r.data),
      MOCK_WORKFLOWS
    ),
  advanceWorkflow: (wfId, stageId, action) =>
    safe(() => apiClient.post(`/documents-smart/workflows/${wfId}/advance`, { stageId, action }), {
      success: true,
    }),

  /* ─── Analytics ─── */
  getAnalytics: () =>
    safe(
      () => apiClient.get('/documents-smart/analytics').then(r => r.data?.data || r.data),
      MOCK_ANALYTICS
    ),

  /* ─── Static Data ─── */
  getCategories: () => TEMPLATE_CATEGORIES,
  getDocumentStatuses: () => DOCUMENT_STATUSES,
  getAIFeatures: () => AI_FEATURES,
  getWorkflowStages: () => WORKFLOW_STAGES,
  getOutputFormats: () => OUTPUT_FORMATS,

  /* ─── Helper ─── */
  formatFileSize: bytes => {
    if (!bytes) return '0 B';
    const k = 1024;
    const sizes = ['B', 'KB', 'MB', 'GB'];
    const i = Math.floor(Math.log(bytes) / Math.log(k));
    return parseFloat((bytes / Math.pow(k, i)).toFixed(1)) + ' ' + sizes[i];
  },
  getDifficultyLabel: d => ({ easy: 'سهل', medium: 'متوسط', hard: 'متقدم' })[d] || d,
  getDifficultyColor: d =>
    ({ easy: '#43A047', medium: '#FF9800', hard: '#E53935' })[d] || '#757575',
};

export default smartDocumentsService;
