/* eslint-disable import/no-anonymous-default-export */
/**
 * Specialized Rehabilitation Service
 * خدمات مقاييس التقييم المتخصصة وبرامج التأهيل
 */
import api from './api.client';

/* ═══════════════════════════════════════════════════════════════════════════ *
 *  SPECIALIZED ASSESSMENT SCALES — المقاييس المتخصصة
 * ═══════════════════════════════════════════════════════════════════════════ */

export const specializedScalesService = {
  getAll: params => api.get('/api/specialized-scales', { params }),
  getCategories: () => api.get('/api/specialized-scales/categories'),
  getByDisability: type => api.get(`/api/specialized-scales/by-disability/${type}`),
  getById: id => api.get(`/api/specialized-scales/${id}`),
  create: data => api.post('/api/specialized-scales', data),
  update: (id, data) => api.put(`/api/specialized-scales/${id}`, data),
  delete: id => api.delete(`/api/specialized-scales/${id}`),

  // Results
  getResults: params => api.get('/api/specialized-scales/results', { params }),
  getResultStats: () => api.get('/api/specialized-scales/results/stats'),
  getBeneficiaryResults: id => api.get(`/api/specialized-scales/results/beneficiary/${id}`),
  getResultById: id => api.get(`/api/specialized-scales/results/${id}`),
  recordResult: data => api.post('/api/specialized-scales/results', data),
  updateResult: (id, data) => api.put(`/api/specialized-scales/results/${id}`, data),
  reviewResult: (id, action) => api.put(`/api/specialized-scales/results/${id}/review`, { action }),
};

/* ═══════════════════════════════════════════════════════════════════════════ *
 *  REHAB PROGRAM TEMPLATES — قوالب برامج التأهيل
 * ═══════════════════════════════════════════════════════════════════════════ */

export const rehabProgramTemplatesService = {
  getAll: params => api.get('/api/rehab-program-templates', { params }),
  getCategories: () => api.get('/api/rehab-program-templates/categories'),
  getByDisability: type => api.get(`/api/rehab-program-templates/by-disability/${type}`),
  getById: id => api.get(`/api/rehab-program-templates/${id}`),
  create: data => api.post('/api/rehab-program-templates', data),
  update: (id, data) => api.put(`/api/rehab-program-templates/${id}`, data),
  delete: id => api.delete(`/api/rehab-program-templates/${id}`),

  // Enrollments
  getEnrollments: params => api.get('/api/rehab-program-templates/enrollments', { params }),
  getEnrollmentStats: () => api.get('/api/rehab-program-templates/enrollments/stats'),
  getBeneficiaryEnrollments: id =>
    api.get(`/api/rehab-program-templates/enrollments/beneficiary/${id}`),
  getEnrollmentById: id => api.get(`/api/rehab-program-templates/enrollments/${id}`),
  enroll: data => api.post('/api/rehab-program-templates/enrollments', data),
  updateEnrollment: (id, data) => api.put(`/api/rehab-program-templates/enrollments/${id}`, data),
  changeEnrollmentStatus: (id, status) =>
    api.put(`/api/rehab-program-templates/enrollments/${id}/status`, { status }),
  logSession: (id, data) =>
    api.post(`/api/rehab-program-templates/enrollments/${id}/sessions`, data),
  addGoal: (id, data) => api.post(`/api/rehab-program-templates/enrollments/${id}/goals`, data),
  updateGoal: (enrollmentId, goalId, data) =>
    api.put(`/api/rehab-program-templates/enrollments/${enrollmentId}/goals/${goalId}`, data),
  discharge: (id, data) =>
    api.post(`/api/rehab-program-templates/enrollments/${id}/discharge`, data),
};

/* ═══════════════════════════════════════════════════════════════════════════ *
 *  BUILT-IN SCALES DATA — بيانات المقاييس المدمجة
 * ═══════════════════════════════════════════════════════════════════════════ */

/** 25 مقياساً متخصصاً مصنفة بحسب الإعاقة */
export const SPECIALIZED_SCALES_CATALOG = [
  // ─── التوحد (5 مقاييس) ──────────────────────────────────────
  {
    scaleCode: 'ADOS2',
    abbreviation: 'ADOS-2',
    category: 'autism',
    nameAr: 'مقياس الملاحظة التشخيصية للتوحد - الإصدار الثاني',
    nameEn: 'Autism Diagnostic Observation Schedule-2',
    description: 'أداة تشخيصية معيارية لتقييم التواصل الاجتماعي والتفاعل والسلوكيات النمطية',
    targetDisabilities: ['autism'],
    totalMaxScore: 30,
    ageRange: { minMonths: 12, maxMonths: 600, label: 'من 12 شهراً فأكثر' },
    administrationTime: 60,
    administrationType: 'observation',
    domains: [
      { key: 'socialAffect', nameAr: 'التأثير الاجتماعي', nameEn: 'Social Affect', maxScore: 20 },
      {
        key: 'restrictedRepetitive',
        nameAr: 'السلوكيات المقيدة والنمطية',
        nameEn: 'Restricted & Repetitive',
        maxScore: 10,
      },
    ],
    interpretation: [
      { min: 0, max: 6, levelKey: 'normal', labelAr: 'لا يوجد توحد', severity: 'normal' },
      { min: 7, max: 11, levelKey: 'at_risk', labelAr: 'طيف التوحد', severity: 'at_risk' },
      { min: 12, max: 30, levelKey: 'severe', labelAr: 'توحد', severity: 'severe' },
    ],
    requiredQualification: 'psychologist',
    developer: 'Lord, Rutter, DiLavore, Risi, Gotham & Bishop',
  },
  {
    scaleCode: 'MCHAT',
    abbreviation: 'M-CHAT-R',
    category: 'autism',
    nameAr: 'قائمة فحص التوحد المعدلة للأطفال الصغار',
    nameEn: 'Modified Checklist for Autism in Toddlers-Revised',
    description: 'أداة فحص مبكر للتوحد تعتمد على ملاحظات الوالدين',
    targetDisabilities: ['autism', 'developmental'],
    totalMaxScore: 20,
    ageRange: { minMonths: 16, maxMonths: 30, label: '16-30 شهراً' },
    administrationTime: 10,
    administrationType: 'parent_report',
    domains: [
      { key: 'socialRelatedness', nameAr: 'العلاقات الاجتماعية', maxScore: 10 },
      { key: 'communicationPlay', nameAr: 'التواصل واللعب', maxScore: 10 },
    ],
    interpretation: [
      { min: 0, max: 2, levelKey: 'low_risk', labelAr: 'خطر منخفض', severity: 'normal' },
      { min: 3, max: 7, levelKey: 'medium_risk', labelAr: 'خطر متوسط', severity: 'at_risk' },
      { min: 8, max: 20, levelKey: 'high_risk', labelAr: 'خطر مرتفع', severity: 'severe' },
    ],
    requiredQualification: 'any_trained',
    developer: 'Robins, Fein, Barton',
  },
  {
    scaleCode: 'GARS3',
    abbreviation: 'GARS-3',
    category: 'autism',
    nameAr: 'مقياس جيليام لتقدير التوحد - الإصدار الثالث',
    nameEn: 'Gilliam Autism Rating Scale-3',
    description: 'مقياس تقدير لتحديد مدى شدة أعراض التوحد',
    targetDisabilities: ['autism'],
    totalMaxScore: 174,
    ageRange: { minMonths: 36, maxMonths: 264, label: '3-22 سنة' },
    administrationTime: 15,
    administrationType: 'teacher_report',
    domains: [
      { key: 'restrictedRepetitive', nameAr: 'السلوكيات النمطية', maxScore: 42 },
      { key: 'socialInteraction', nameAr: 'التفاعل الاجتماعي', maxScore: 42 },
      { key: 'socialCommunication', nameAr: 'التواصل الاجتماعي', maxScore: 42 },
      { key: 'emotionalResponses', nameAr: 'الاستجابات العاطفية', maxScore: 24 },
      { key: 'cognitiveStyle', nameAr: 'الأسلوب المعرفي', maxScore: 24 },
    ],
    interpretation: [
      { min: 0, max: 54, levelKey: 'unlikely', labelAr: 'غير مرجح', severity: 'normal' },
      { min: 55, max: 100, levelKey: 'possible', labelAr: 'محتمل', severity: 'at_risk' },
      { min: 101, max: 130, levelKey: 'likely', labelAr: 'مرجح', severity: 'moderate' },
      { min: 131, max: 174, levelKey: 'very_likely', labelAr: 'مرجح جداً', severity: 'severe' },
    ],
    requiredQualification: 'specialist',
    developer: 'Gilliam',
  },
  {
    scaleCode: 'SRS2',
    abbreviation: 'SRS-2',
    category: 'autism',
    nameAr: 'مقياس الاستجابة الاجتماعية - الإصدار الثاني',
    nameEn: 'Social Responsiveness Scale-2',
    description: 'يقيم صعوبات التواصل الاجتماعي المرتبطة بالتوحد',
    targetDisabilities: ['autism', 'behavioral'],
    totalMaxScore: 195,
    ageRange: { minMonths: 30, maxMonths: 600, label: '2.5 سنة فأكثر' },
    administrationTime: 20,
    administrationType: 'parent_report',
    domains: [
      { key: 'socialAwareness', nameAr: 'الوعي الاجتماعي', maxScore: 39 },
      { key: 'socialCognition', nameAr: 'الإدراك الاجتماعي', maxScore: 39 },
      { key: 'socialCommunication', nameAr: 'التواصل الاجتماعي', maxScore: 39 },
      { key: 'socialMotivation', nameAr: 'الدافعية الاجتماعية', maxScore: 39 },
      { key: 'restrictedInterests', nameAr: 'الاهتمامات المحدودة', maxScore: 39 },
    ],
    interpretation: [
      { min: 0, max: 57, levelKey: 'normal', labelAr: 'طبيعي', severity: 'normal' },
      { min: 58, max: 72, levelKey: 'mild', labelAr: 'صعوبات خفيفة', severity: 'mild' },
      { min: 73, max: 97, levelKey: 'moderate', labelAr: 'صعوبات متوسطة', severity: 'moderate' },
      { min: 98, max: 195, levelKey: 'severe', labelAr: 'صعوبات شديدة', severity: 'severe' },
    ],
    requiredQualification: 'specialist',
    developer: 'Constantino & Gruber',
  },
  {
    scaleCode: 'ATEC',
    abbreviation: 'ATEC',
    category: 'autism',
    nameAr: 'استمارة تقييم علاج التوحد',
    nameEn: 'Autism Treatment Evaluation Checklist',
    description: 'أداة لتقييم فعالية التدخلات العلاجية للتوحد',
    targetDisabilities: ['autism'],
    totalMaxScore: 180,
    ageRange: { minMonths: 24, maxMonths: 600, label: 'سنتان فأكثر' },
    administrationTime: 15,
    administrationType: 'parent_report',
    domains: [
      { key: 'speechLanguage', nameAr: 'النطق / اللغة / التواصل', maxScore: 28 },
      { key: 'sociability', nameAr: 'الاجتماعية', maxScore: 40 },
      { key: 'sensoryAwareness', nameAr: 'الإدراك الحسي / المعرفي', maxScore: 36 },
      { key: 'healthBehavior', nameAr: 'الصحة / السلوك الجسدي', maxScore: 75 },
    ],
    interpretation: [
      { min: 0, max: 30, levelKey: 'mild', labelAr: 'أعراض خفيفة', severity: 'mild' },
      { min: 31, max: 50, levelKey: 'moderate', labelAr: 'أعراض متوسطة', severity: 'moderate' },
      { min: 51, max: 103, levelKey: 'severe', labelAr: 'أعراض شديدة', severity: 'severe' },
      {
        min: 104,
        max: 180,
        levelKey: 'profound',
        labelAr: 'أعراض شديدة جداً',
        severity: 'profound',
      },
    ],
    requiredQualification: 'any_trained',
    developer: 'Rimland & Edelson',
  },

  // ─── المقاييس الحركية (4 مقاييس) ──────────────────────────────
  {
    scaleCode: 'GMFCS',
    abbreviation: 'GMFCS',
    category: 'motor',
    nameAr: 'نظام تصنيف الوظائف الحركية الكبرى',
    nameEn: 'Gross Motor Function Classification System',
    description: 'يصنف القدرات الحركية الكبرى للأطفال ذوي الشلل الدماغي إلى 5 مستويات',
    targetDisabilities: ['cerebral_palsy', 'physical'],
    totalMaxScore: 5,
    ageRange: { minMonths: 0, maxMonths: 216, label: '0-18 سنة' },
    administrationTime: 15,
    administrationType: 'observation',
    domains: [{ key: 'grossMotorLevel', nameAr: 'مستوى الوظيفة الحركية', maxScore: 5 }],
    interpretation: [
      {
        min: 1,
        max: 1,
        levelKey: 'level1',
        labelAr: 'المستوى الأول - يمشي بدون قيود',
        severity: 'mild',
      },
      {
        min: 2,
        max: 2,
        levelKey: 'level2',
        labelAr: 'المستوى الثاني - يمشي مع قيود',
        severity: 'mild',
      },
      {
        min: 3,
        max: 3,
        levelKey: 'level3',
        labelAr: 'المستوى الثالث - يستخدم أداة مساعدة',
        severity: 'moderate',
      },
      {
        min: 4,
        max: 4,
        levelKey: 'level4',
        labelAr: 'المستوى الرابع - تنقل محدود بكرسي متحرك',
        severity: 'severe',
      },
      {
        min: 5,
        max: 5,
        levelKey: 'level5',
        labelAr: 'المستوى الخامس - يُنقل بالكامل',
        severity: 'profound',
      },
    ],
    requiredQualification: 'therapist',
    developer: 'Palisano, Rosenbaum, Walter, Russell, Wood & Galuppi',
  },
  {
    scaleCode: 'MACS',
    abbreviation: 'MACS',
    category: 'motor',
    nameAr: 'نظام تصنيف القدرة اليدوية',
    nameEn: 'Manual Ability Classification System',
    description: 'يصنف كيفية استخدام الأطفال لأيديهم في التعامل مع الأشياء في الأنشطة اليومية',
    targetDisabilities: ['cerebral_palsy', 'physical'],
    totalMaxScore: 5,
    ageRange: { minMonths: 48, maxMonths: 216, label: '4-18 سنة' },
    administrationTime: 15,
    administrationType: 'observation',
    domains: [{ key: 'manualAbility', nameAr: 'القدرة اليدوية', maxScore: 5 }],
    interpretation: [
      { min: 1, max: 1, levelKey: 'level1', labelAr: 'يتعامل مع الأشياء بسهولة', severity: 'mild' },
      {
        min: 2,
        max: 2,
        levelKey: 'level2',
        labelAr: 'يتعامل مع معظم الأشياء مع بعض الصعوبة',
        severity: 'mild',
      },
      {
        min: 3,
        max: 3,
        levelKey: 'level3',
        labelAr: 'يتعامل مع الأشياء بصعوبة ويحتاج مساعدة',
        severity: 'moderate',
      },
      {
        min: 4,
        max: 4,
        levelKey: 'level4',
        labelAr: 'يتعامل مع أشياء محدودة في بيئة معدلة',
        severity: 'severe',
      },
      { min: 5, max: 5, levelKey: 'level5', labelAr: 'لا يتعامل مع الأشياء', severity: 'profound' },
    ],
    requiredQualification: 'therapist',
    developer: 'Eliasson et al.',
  },
  {
    scaleCode: 'BERG',
    abbreviation: 'Berg',
    category: 'motor',
    nameAr: 'مقياس بيرج للتوازن',
    nameEn: 'Berg Balance Scale',
    description: 'يقيم التوازن الوظيفي الثابت والمتحرك من خلال 14 مهمة',
    targetDisabilities: ['physical', 'cerebral_palsy'],
    totalMaxScore: 56,
    ageRange: { minMonths: 60, maxMonths: 900, label: '5 سنوات فأكثر' },
    administrationTime: 20,
    administrationType: 'individual',
    domains: [
      { key: 'staticBalance', nameAr: 'التوازن الثابت', maxScore: 28 },
      { key: 'dynamicBalance', nameAr: 'التوازن الديناميكي', maxScore: 28 },
    ],
    interpretation: [
      {
        min: 0,
        max: 20,
        levelKey: 'high_fall_risk',
        labelAr: 'خطر سقوط مرتفع',
        severity: 'severe',
      },
      {
        min: 21,
        max: 40,
        levelKey: 'medium_fall_risk',
        labelAr: 'خطر سقوط متوسط',
        severity: 'moderate',
      },
      { min: 41, max: 56, levelKey: 'low_fall_risk', labelAr: 'خطر سقوط منخفض', severity: 'mild' },
    ],
    requiredQualification: 'therapist',
    developer: 'Katherine Berg',
  },
  {
    scaleCode: 'WEEFIM',
    abbreviation: 'WeeFIM',
    category: 'motor',
    nameAr: 'مقياس الاستقلالية الوظيفية للأطفال',
    nameEn: 'Functional Independence Measure for Children',
    description: 'يقيم مستوى الاستقلالية الوظيفية للأطفال في 18 مهمة',
    targetDisabilities: ['physical', 'cerebral_palsy', 'developmental', 'intellectual'],
    totalMaxScore: 126,
    ageRange: { minMonths: 6, maxMonths: 96, label: '6 أشهر - 8 سنوات' },
    administrationTime: 30,
    administrationType: 'observation',
    domains: [
      { key: 'selfCare', nameAr: 'الرعاية الذاتية', maxScore: 42 },
      { key: 'mobility', nameAr: 'التنقل', maxScore: 35 },
      { key: 'cognition', nameAr: 'الإدراك', maxScore: 49 },
    ],
    interpretation: [
      {
        min: 18,
        max: 36,
        levelKey: 'total_assistance',
        labelAr: 'مساعدة كاملة',
        severity: 'profound',
      },
      {
        min: 37,
        max: 54,
        levelKey: 'maximal_assistance',
        labelAr: 'مساعدة كبيرة',
        severity: 'severe',
      },
      {
        min: 55,
        max: 72,
        levelKey: 'moderate_assistance',
        labelAr: 'مساعدة متوسطة',
        severity: 'moderate',
      },
      {
        min: 73,
        max: 90,
        levelKey: 'minimal_assistance',
        labelAr: 'مساعدة بسيطة',
        severity: 'mild',
      },
      { min: 91, max: 126, levelKey: 'independent', labelAr: 'مستقل', severity: 'normal' },
    ],
    requiredQualification: 'therapist',
    developer: 'Uniform Data System for Medical Rehabilitation',
  },

  // ─── المقاييس الذهنية (4 مقاييس) ──────────────────────────────
  {
    scaleCode: 'SIS',
    abbreviation: 'SIS',
    category: 'intellectual',
    nameAr: 'مقياس شدة الدعم المطلوب',
    nameEn: 'Supports Intensity Scale',
    description: 'يقيس نوع وشدة الدعم اللازم للأشخاص ذوي الإعاقة الذهنية',
    targetDisabilities: ['intellectual', 'down_syndrome'],
    totalMaxScore: 150,
    ageRange: { minMonths: 192, maxMonths: 900, label: '16 سنة فأكثر' },
    administrationTime: 45,
    administrationType: 'interview',
    domains: [
      { key: 'homeActivities', nameAr: 'أنشطة المنزل', maxScore: 30 },
      { key: 'communityActivities', nameAr: 'أنشطة مجتمعية', maxScore: 30 },
      { key: 'lifelongLearning', nameAr: 'التعلم مدى الحياة', maxScore: 30 },
      { key: 'employment', nameAr: 'العمل', maxScore: 30 },
      { key: 'healthSafety', nameAr: 'الصحة والسلامة', maxScore: 30 },
    ],
    interpretation: [
      { min: 0, max: 37, levelKey: 'intermittent', labelAr: 'دعم متقطع', severity: 'mild' },
      { min: 38, max: 75, levelKey: 'limited', labelAr: 'دعم محدود', severity: 'moderate' },
      { min: 76, max: 112, levelKey: 'extensive', labelAr: 'دعم واسع', severity: 'severe' },
      { min: 113, max: 150, levelKey: 'pervasive', labelAr: 'دعم شامل', severity: 'profound' },
    ],
    requiredQualification: 'psychologist',
    developer: 'AAIDD',
  },
  {
    scaleCode: 'ABAS3',
    abbreviation: 'ABAS-3',
    category: 'intellectual',
    nameAr: 'نظام تقييم السلوك التكيفي - الإصدار الثالث',
    nameEn: 'Adaptive Behavior Assessment System-3',
    description: 'يقيم المهارات التكيفية اللازمة للحياة اليومية',
    targetDisabilities: ['intellectual', 'down_syndrome', 'autism', 'developmental'],
    totalMaxScore: 300,
    ageRange: { minMonths: 0, maxMonths: 1080, label: 'من الولادة إلى 89 سنة' },
    administrationTime: 20,
    administrationType: 'parent_report',
    domains: [
      { key: 'conceptual', nameAr: 'المفاهيمي', maxScore: 100 },
      { key: 'social', nameAr: 'الاجتماعي', maxScore: 100 },
      { key: 'practical', nameAr: 'العملي', maxScore: 100 },
    ],
    interpretation: [
      { min: 0, max: 70, levelKey: 'very_low', labelAr: 'منخفض جداً', severity: 'severe' },
      { min: 71, max: 85, levelKey: 'low', labelAr: 'منخفض', severity: 'moderate' },
      { min: 86, max: 114, levelKey: 'average', labelAr: 'متوسط', severity: 'normal' },
      {
        min: 115,
        max: 300,
        levelKey: 'above_average',
        labelAr: 'فوق المتوسط',
        severity: 'above_average',
      },
    ],
    requiredQualification: 'specialist',
    developer: 'Harrison & Oakland',
  },
  {
    scaleCode: 'VINELAND3',
    abbreviation: 'Vineland-3',
    category: 'intellectual',
    nameAr: 'مقياس فاينلاند للسلوك التكيفي - الإصدار الثالث',
    nameEn: 'Vineland Adaptive Behavior Scales-3',
    description: 'يقيم السلوك التكيفي في مجالات التواصل والمهارات اليومية والاجتماعية والحركية',
    targetDisabilities: ['intellectual', 'down_syndrome', 'autism', 'developmental'],
    totalMaxScore: 400,
    ageRange: { minMonths: 0, maxMonths: 1080, label: 'من الولادة إلى 90+ سنة' },
    administrationTime: 40,
    administrationType: 'interview',
    domains: [
      { key: 'communication', nameAr: 'التواصل', maxScore: 100 },
      { key: 'dailyLiving', nameAr: 'المهارات الحياتية', maxScore: 100 },
      { key: 'socialization', nameAr: 'التنشئة الاجتماعية', maxScore: 100 },
      { key: 'motorSkills', nameAr: 'المهارات الحركية', maxScore: 100 },
    ],
    interpretation: [
      { min: 0, max: 70, levelKey: 'low', labelAr: 'منخفض', severity: 'severe' },
      { min: 71, max: 85, levelKey: 'below_average', labelAr: 'دون المتوسط', severity: 'moderate' },
      { min: 86, max: 114, levelKey: 'average', labelAr: 'متوسط', severity: 'normal' },
      {
        min: 115,
        max: 400,
        levelKey: 'above_average',
        labelAr: 'فوق المتوسط',
        severity: 'above_average',
      },
    ],
    requiredQualification: 'psychologist',
    developer: 'Sparrow, Cicchetti & Saulnier',
  },
  {
    scaleCode: 'LEITER3',
    abbreviation: 'Leiter-3',
    category: 'intellectual',
    nameAr: 'مقياس لايتر الدولي للأداء - الإصدار الثالث',
    nameEn: 'Leiter International Performance Scale-3',
    description: 'مقياس غير لفظي لتقييم الذكاء والقدرات المعرفية',
    targetDisabilities: ['intellectual', 'hearing', 'speech', 'autism'],
    totalMaxScore: 160,
    ageRange: { minMonths: 36, maxMonths: 900, label: '3-75+ سنة' },
    administrationTime: 45,
    administrationType: 'individual',
    domains: [
      { key: 'cognitiveAbility', nameAr: 'القدرة المعرفية', maxScore: 80 },
      { key: 'attentionMemory', nameAr: 'الانتباه والذاكرة', maxScore: 80 },
    ],
    interpretation: [
      { min: 0, max: 69, levelKey: 'very_low', labelAr: 'منخفض جداً', severity: 'severe' },
      { min: 70, max: 84, levelKey: 'below_average', labelAr: 'دون المتوسط', severity: 'moderate' },
      { min: 85, max: 115, levelKey: 'average', labelAr: 'متوسط', severity: 'normal' },
      {
        min: 116,
        max: 160,
        levelKey: 'above_average',
        labelAr: 'فوق المتوسط',
        severity: 'above_average',
      },
    ],
    requiredQualification: 'psychologist',
    developer: 'Roid, Miller, Pomplun & Koch',
  },

  // ─── مقاييس النطق واللغة (4 مقاييس) ──────────────────────────
  {
    scaleCode: 'CELF5',
    abbreviation: 'CELF-5',
    category: 'speech',
    nameAr: 'التقييم السريري لأساسيات اللغة - الإصدار الخامس',
    nameEn: 'Clinical Evaluation of Language Fundamentals-5',
    description: 'أداة شاملة لتقييم اللغة الاستقبالية والتعبيرية',
    targetDisabilities: ['speech', 'learning', 'autism', 'hearing'],
    totalMaxScore: 200,
    ageRange: { minMonths: 60, maxMonths: 264, label: '5-21 سنة' },
    administrationTime: 45,
    administrationType: 'individual',
    domains: [
      { key: 'coreLanguage', nameAr: 'اللغة الأساسية', maxScore: 50 },
      { key: 'receptiveLanguage', nameAr: 'اللغة الاستقبالية', maxScore: 50 },
      { key: 'expressiveLanguage', nameAr: 'اللغة التعبيرية', maxScore: 50 },
      { key: 'languageStructure', nameAr: 'بنية اللغة', maxScore: 50 },
    ],
    interpretation: [
      { min: 0, max: 69, levelKey: 'severe', labelAr: 'اضطراب شديد', severity: 'severe' },
      { min: 70, max: 84, levelKey: 'moderate', labelAr: 'اضطراب متوسط', severity: 'moderate' },
      { min: 85, max: 114, levelKey: 'normal', labelAr: 'طبيعي', severity: 'normal' },
      {
        min: 115,
        max: 200,
        levelKey: 'superior',
        labelAr: 'فوق المتوسط',
        severity: 'above_average',
      },
    ],
    requiredQualification: 'therapist',
    developer: 'Wiig, Semel & Secord',
  },
  {
    scaleCode: 'PLS5',
    abbreviation: 'PLS-5',
    category: 'speech',
    nameAr: 'مقاييس اللغة لمرحلة ما قبل المدرسة - الإصدار الخامس',
    nameEn: 'Preschool Language Scales-5',
    description: 'يقيس اللغة الاستقبالية والتعبيرية للأطفال الصغار',
    targetDisabilities: ['speech', 'developmental', 'hearing'],
    totalMaxScore: 170,
    ageRange: { minMonths: 0, maxMonths: 95, label: 'من الولادة إلى 7 سنوات و11 شهراً' },
    administrationTime: 30,
    administrationType: 'individual',
    domains: [
      { key: 'auditoryComprehension', nameAr: 'الفهم السمعي', maxScore: 85 },
      { key: 'expressiveCommunication', nameAr: 'التواصل التعبيري', maxScore: 85 },
    ],
    interpretation: [
      { min: 0, max: 69, levelKey: 'severe_delay', labelAr: 'تأخر شديد', severity: 'severe' },
      { min: 70, max: 84, levelKey: 'moderate_delay', labelAr: 'تأخر متوسط', severity: 'moderate' },
      { min: 85, max: 115, levelKey: 'normal', labelAr: 'طبيعي', severity: 'normal' },
      { min: 116, max: 170, levelKey: 'advanced', labelAr: 'متقدم', severity: 'above_average' },
    ],
    requiredQualification: 'therapist',
    developer: 'Zimmerman, Steiner & Pond',
  },
  {
    scaleCode: 'REEL3',
    abbreviation: 'REEL-3',
    category: 'speech',
    nameAr: 'مقياس اللغة الاستقبالية التعبيرية الطارئة - الإصدار الثالث',
    nameEn: 'Receptive-Expressive Emergent Language-3',
    description: 'يقيم قدرات اللغة المبكرة من خلال ملاحظات الوالدين والاختبار المباشر',
    targetDisabilities: ['speech', 'developmental', 'hearing'],
    totalMaxScore: 134,
    ageRange: { minMonths: 0, maxMonths: 36, label: 'من الولادة إلى 3 سنوات' },
    administrationTime: 20,
    administrationType: 'mixed',
    domains: [
      { key: 'receptiveLanguage', nameAr: 'اللغة الاستقبالية', maxScore: 67 },
      { key: 'expressiveLanguage', nameAr: 'اللغة التعبيرية', maxScore: 67 },
    ],
    interpretation: [
      { min: 0, max: 69, levelKey: 'delay', labelAr: 'تأخر لغوي', severity: 'severe' },
      { min: 70, max: 84, levelKey: 'below_average', labelAr: 'دون المتوسط', severity: 'moderate' },
      { min: 85, max: 115, levelKey: 'normal', labelAr: 'طبيعي', severity: 'normal' },
      { min: 116, max: 134, levelKey: 'advanced', labelAr: 'متقدم', severity: 'above_average' },
    ],
    requiredQualification: 'therapist',
    developer: 'Bzoch, League & Brown',
  },
  {
    scaleCode: 'SSI4',
    abbreviation: 'SSI-4',
    category: 'speech',
    nameAr: 'أداة شدة التأتأة - الإصدار الرابع',
    nameEn: 'Stuttering Severity Instrument-4',
    description: 'يقيم شدة التأتأة من خلال تكرار وطول ومظاهرها الجسدية',
    targetDisabilities: ['speech'],
    totalMaxScore: 46,
    ageRange: { minMonths: 24, maxMonths: 900, label: 'سنتان فأكثر' },
    administrationTime: 25,
    administrationType: 'individual',
    domains: [
      { key: 'frequency', nameAr: 'التكرار', maxScore: 18 },
      { key: 'duration', nameAr: 'المدة', maxScore: 18 },
      { key: 'physicalConcomitants', nameAr: 'المظاهر الجسدية', maxScore: 10 },
    ],
    interpretation: [
      { min: 0, max: 10, levelKey: 'very_mild', labelAr: 'بسيطة جداً', severity: 'mild' },
      { min: 11, max: 20, levelKey: 'mild', labelAr: 'بسيطة', severity: 'mild' },
      { min: 21, max: 30, levelKey: 'moderate', labelAr: 'متوسطة', severity: 'moderate' },
      { min: 31, max: 38, levelKey: 'severe', labelAr: 'شديدة', severity: 'severe' },
      { min: 39, max: 46, levelKey: 'very_severe', labelAr: 'شديدة جداً', severity: 'profound' },
    ],
    requiredQualification: 'therapist',
    developer: 'Riley',
  },

  // ─── المقاييس السلوكية (4 مقاييس) ──────────────────────────────
  {
    scaleCode: 'CBCL',
    abbreviation: 'CBCL',
    category: 'behavioral',
    nameAr: 'قائمة فحص سلوك الطفل',
    nameEn: 'Child Behavior Checklist',
    description: 'تقيم المشكلات السلوكية والعاطفية وفق تقرير الوالدين',
    targetDisabilities: ['behavioral', 'adhd', 'autism', 'intellectual'],
    totalMaxScore: 240,
    ageRange: { minMonths: 18, maxMonths: 216, label: '1.5-18 سنة' },
    administrationTime: 20,
    administrationType: 'parent_report',
    domains: [
      { key: 'internalizing', nameAr: 'المشكلات الداخلية', maxScore: 80 },
      { key: 'externalizing', nameAr: 'المشكلات الخارجية', maxScore: 80 },
      { key: 'totalProblems', nameAr: 'المشكلات الكلية', maxScore: 80 },
    ],
    interpretation: [
      { min: 0, max: 59, levelKey: 'normal', labelAr: 'طبيعي', severity: 'normal' },
      { min: 60, max: 63, levelKey: 'borderline', labelAr: 'حدّي', severity: 'at_risk' },
      { min: 64, max: 240, levelKey: 'clinical', labelAr: 'إكلينيكي', severity: 'severe' },
    ],
    requiredQualification: 'psychologist',
    developer: 'Achenbach & Rescorla',
  },
  {
    scaleCode: 'CONNERS3',
    abbreviation: 'Conners-3',
    category: 'behavioral',
    nameAr: 'مقياس كونرز - الإصدار الثالث',
    nameEn: 'Conners Rating Scales-3',
    description: 'يقيم أعراض فرط الحركة وتشتت الانتباه والمشكلات السلوكية',
    targetDisabilities: ['adhd', 'behavioral', 'learning'],
    totalMaxScore: 300,
    ageRange: { minMonths: 72, maxMonths: 216, label: '6-18 سنة' },
    administrationTime: 20,
    administrationType: 'parent_report',
    domains: [
      { key: 'inattention', nameAr: 'عدم الانتباه', maxScore: 60 },
      { key: 'hyperactivity', nameAr: 'فرط النشاط / الاندفاعية', maxScore: 60 },
      { key: 'learningProblems', nameAr: 'مشكلات التعلم', maxScore: 60 },
      { key: 'executiveFunction', nameAr: 'الوظائف التنفيذية', maxScore: 60 },
      { key: 'peerRelations', nameAr: 'العلاقات مع الأقران', maxScore: 60 },
    ],
    interpretation: [
      { min: 0, max: 59, levelKey: 'average', labelAr: 'متوسط', severity: 'normal' },
      { min: 60, max: 64, levelKey: 'high_average', labelAr: 'فوق المتوسط', severity: 'at_risk' },
      { min: 65, max: 69, levelKey: 'elevated', labelAr: 'مرتفع', severity: 'moderate' },
      { min: 70, max: 300, levelKey: 'very_elevated', labelAr: 'مرتفع جداً', severity: 'severe' },
    ],
    requiredQualification: 'psychologist',
    developer: 'C. Keith Conners',
  },
  {
    scaleCode: 'BASC3',
    abbreviation: 'BASC-3',
    category: 'behavioral',
    nameAr: 'نظام تقييم السلوك للأطفال - الإصدار الثالث',
    nameEn: 'Behavior Assessment System for Children-3',
    description: 'تقييم شامل للمشكلات السلوكية والعاطفية والتكيفية',
    targetDisabilities: ['behavioral', 'adhd', 'autism', 'learning'],
    totalMaxScore: 400,
    ageRange: { minMonths: 24, maxMonths: 300, label: '2-25 سنة' },
    administrationTime: 30,
    administrationType: 'mixed',
    domains: [
      { key: 'externalizing', nameAr: 'مشكلات خارجية', maxScore: 100 },
      { key: 'internalizing', nameAr: 'مشكلات داخلية', maxScore: 100 },
      { key: 'adaptiveSkills', nameAr: 'مهارات تكيفية', maxScore: 100 },
      { key: 'behavioralSymptoms', nameAr: 'مؤشر الأعراض السلوكية', maxScore: 100 },
    ],
    interpretation: [
      { min: 0, max: 59, levelKey: 'normal', labelAr: 'طبيعي', severity: 'normal' },
      { min: 60, max: 69, levelKey: 'at_risk', labelAr: 'معرض للخطر', severity: 'at_risk' },
      { min: 70, max: 400, levelKey: 'clinical', labelAr: 'إكلينيكي بارز', severity: 'severe' },
    ],
    requiredQualification: 'psychologist',
    developer: 'Reynolds & Kamphaus',
  },
  {
    scaleCode: 'ABC',
    abbreviation: 'ABC',
    category: 'behavioral',
    nameAr: 'قائمة فحص السلوك الشاذ',
    nameEn: 'Aberrant Behavior Checklist',
    description: 'يقيم السلوكيات غير التكيفية لدى الأشخاص ذوي الإعاقة الذهنية',
    targetDisabilities: ['intellectual', 'autism', 'behavioral'],
    totalMaxScore: 174,
    ageRange: { minMonths: 36, maxMonths: 900, label: '3 سنوات فأكثر' },
    administrationTime: 15,
    administrationType: 'teacher_report',
    domains: [
      { key: 'irritability', nameAr: 'الهيجان / العدوان', maxScore: 45 },
      { key: 'socialWithdrawal', nameAr: 'الانسحاب الاجتماعي', maxScore: 48 },
      { key: 'stereotypic', nameAr: 'السلوكيات النمطية', maxScore: 21 },
      { key: 'hyperactivity', nameAr: 'فرط النشاط', maxScore: 48 },
      { key: 'inappropriateSpeech', nameAr: 'الكلام غير الملائم', maxScore: 12 },
    ],
    interpretation: [
      { min: 0, max: 43, levelKey: 'mild', labelAr: 'مشكلات خفيفة', severity: 'mild' },
      { min: 44, max: 86, levelKey: 'moderate', labelAr: 'مشكلات متوسطة', severity: 'moderate' },
      { min: 87, max: 174, levelKey: 'severe', labelAr: 'مشكلات شديدة', severity: 'severe' },
    ],
    requiredQualification: 'specialist',
    developer: 'Aman & Singh',
  },

  // ─── المقاييس النمائية (4 مقاييس) ──────────────────────────────
  {
    scaleCode: 'BAYLEY3',
    abbreviation: 'Bayley-III',
    category: 'developmental',
    nameAr: 'مقاييس بايلي لنمو الطفل - الإصدار الثالث',
    nameEn: 'Bayley Scales of Infant & Toddler Development-III',
    description: 'يقيم النمو المعرفي واللغوي والحركي للرضع وصغار الأطفال',
    targetDisabilities: ['developmental', 'intellectual', 'down_syndrome', 'cerebral_palsy'],
    totalMaxScore: 500,
    ageRange: { minMonths: 1, maxMonths: 42, label: '1-42 شهراً' },
    administrationTime: 60,
    administrationType: 'individual',
    domains: [
      { key: 'cognitive', nameAr: 'المعرفي', maxScore: 100 },
      { key: 'language', nameAr: 'اللغة', maxScore: 100 },
      { key: 'motor', nameAr: 'الحركي', maxScore: 100 },
      { key: 'socialEmotional', nameAr: 'الاجتماعي العاطفي', maxScore: 100 },
      { key: 'adaptiveBehavior', nameAr: 'السلوك التكيفي', maxScore: 100 },
    ],
    interpretation: [
      { min: 0, max: 69, levelKey: 'severe_delay', labelAr: 'تأخر شديد', severity: 'severe' },
      { min: 70, max: 84, levelKey: 'moderate_delay', labelAr: 'تأخر متوسط', severity: 'moderate' },
      { min: 85, max: 115, levelKey: 'within_normal', labelAr: 'ضمن الطبيعي', severity: 'normal' },
      { min: 116, max: 500, levelKey: 'advanced', labelAr: 'متقدم', severity: 'above_average' },
    ],
    requiredQualification: 'psychologist',
    developer: 'Nancy Bayley',
  },
  {
    scaleCode: 'ASQ3',
    abbreviation: 'ASQ-3',
    category: 'developmental',
    nameAr: 'استبيان الأعمار والمراحل - الإصدار الثالث',
    nameEn: 'Ages & Stages Questionnaire-3',
    description: 'أداة فحص نمائي يملأها الوالدان لتقييم تطور الطفل',
    targetDisabilities: ['developmental'],
    totalMaxScore: 300,
    ageRange: { minMonths: 2, maxMonths: 66, label: '2-66 شهراً' },
    administrationTime: 15,
    administrationType: 'parent_report',
    domains: [
      { key: 'communication', nameAr: 'التواصل', maxScore: 60 },
      { key: 'grossMotor', nameAr: 'الحركة الكبرى', maxScore: 60 },
      { key: 'fineMotor', nameAr: 'الحركة الدقيقة', maxScore: 60 },
      { key: 'problemSolving', nameAr: 'حل المشكلات', maxScore: 60 },
      { key: 'personalSocial', nameAr: 'الشخصي الاجتماعي', maxScore: 60 },
    ],
    interpretation: [
      {
        min: 0,
        max: 99,
        levelKey: 'below_cutoff',
        labelAr: 'دون الحد - يحتاج تقييم',
        severity: 'severe',
      },
      { min: 100, max: 199, levelKey: 'monitoring', labelAr: 'يحتاج متابعة', severity: 'at_risk' },
      {
        min: 200,
        max: 300,
        levelKey: 'on_schedule',
        labelAr: 'ضمن الجدول الطبيعي',
        severity: 'normal',
      },
    ],
    requiredQualification: 'any_trained',
    developer: 'Squires & Bricker',
  },
  {
    scaleCode: 'DENVER2',
    abbreviation: 'Denver-II',
    category: 'developmental',
    nameAr: 'اختبار دنفر التطوري - الإصدار الثاني',
    nameEn: 'Denver Developmental Screening Test-II',
    description: 'فحص تطوري شامل يقيم أربعة مجالات رئيسية',
    targetDisabilities: ['developmental'],
    totalMaxScore: 125,
    ageRange: { minMonths: 0, maxMonths: 72, label: 'من الولادة إلى 6 سنوات' },
    administrationTime: 20,
    administrationType: 'observation',
    domains: [
      { key: 'personalSocial', nameAr: 'الشخصي الاجتماعي', maxScore: 25 },
      { key: 'fineMotorAdaptive', nameAr: 'الحركة الدقيقة / التكيفية', maxScore: 29 },
      { key: 'language', nameAr: 'اللغة', maxScore: 39 },
      { key: 'grossMotor', nameAr: 'الحركة الكبرى', maxScore: 32 },
    ],
    interpretation: [
      { min: 0, max: 41, levelKey: 'abnormal', labelAr: 'غير طبيعي', severity: 'severe' },
      { min: 42, max: 82, levelKey: 'suspect', labelAr: 'مشتبه', severity: 'at_risk' },
      { min: 83, max: 125, levelKey: 'normal', labelAr: 'طبيعي', severity: 'normal' },
    ],
    requiredQualification: 'any_trained',
    developer: 'Frankenburg & Dodds',
  },
  {
    scaleCode: 'PDMS2',
    abbreviation: 'PDMS-2',
    category: 'developmental',
    nameAr: 'مقياس بيبودي للنمو الحركي - الإصدار الثاني',
    nameEn: 'Peabody Developmental Motor Scales-2',
    description: 'يقيم المهارات الحركية الكبرى والدقيقة لدى الأطفال الصغار',
    targetDisabilities: ['developmental', 'physical', 'cerebral_palsy', 'down_syndrome'],
    totalMaxScore: 300,
    ageRange: { minMonths: 0, maxMonths: 72, label: 'من الولادة إلى 5 سنوات و11 شهراً' },
    administrationTime: 45,
    administrationType: 'individual',
    domains: [
      { key: 'reflexes', nameAr: 'ردود الفعل', maxScore: 50 },
      { key: 'stationary', nameAr: 'الثبات', maxScore: 50 },
      { key: 'locomotion', nameAr: 'التنقل', maxScore: 50 },
      { key: 'objectManipulation', nameAr: 'التعامل مع الأشياء', maxScore: 50 },
      { key: 'grasping', nameAr: 'القبض', maxScore: 50 },
      { key: 'visualMotor', nameAr: 'البصري الحركي', maxScore: 50 },
    ],
    interpretation: [
      { min: 0, max: 69, levelKey: 'very_poor', labelAr: 'ضعيف جداً', severity: 'severe' },
      { min: 70, max: 79, levelKey: 'poor', labelAr: 'ضعيف', severity: 'moderate' },
      { min: 80, max: 89, levelKey: 'below_average', labelAr: 'دون المتوسط', severity: 'mild' },
      { min: 90, max: 110, levelKey: 'average', labelAr: 'متوسط', severity: 'normal' },
      {
        min: 111,
        max: 300,
        levelKey: 'above_average',
        labelAr: 'فوق المتوسط',
        severity: 'above_average',
      },
    ],
    requiredQualification: 'therapist',
    developer: 'Folio & Fewell',
  },

  /* ─── Sensory Scales — مقاييس حسية ─────────────────────────────────────── */

  {
    scaleCode: 'SP2',
    abbreviation: 'SP-2',
    category: 'sensory',
    nameAr: 'مقياس الملف الحسي 2',
    nameEn: 'Sensory Profile 2',
    description:
      'يقيّم أنماط المعالجة الحسية لدى الأطفال وتأثيرها على الأداء اليومي عبر أربعة أنماط حسية',
    targetDisabilities: ['autism', 'sensory_processing', 'adhd', 'developmental', 'learning'],
    totalMaxScore: 300,
    ageRange: { minMonths: 0, maxMonths: 180, label: 'من الولادة إلى 14 سنة و11 شهراً' },
    administrationTime: 20,
    administrationType: 'parent_report',
    domains: [
      { key: 'seeking', nameAr: 'البحث الحسي', maxScore: 75 },
      { key: 'avoiding', nameAr: 'التجنب الحسي', maxScore: 75 },
      { key: 'sensitivity', nameAr: 'الحساسية الحسية', maxScore: 75 },
      { key: 'registration', nameAr: 'التسجيل الحسي', maxScore: 75 },
    ],
    interpretation: [
      {
        min: 0,
        max: 89,
        levelKey: 'much_less',
        labelAr: 'أقل بكثير من الآخرين',
        severity: 'severe',
      },
      { min: 90, max: 134, levelKey: 'less', labelAr: 'أقل من الآخرين', severity: 'moderate' },
      {
        min: 135,
        max: 189,
        levelKey: 'just_like',
        labelAr: 'مثل غالبية الآخرين',
        severity: 'normal',
      },
      { min: 190, max: 244, levelKey: 'more', labelAr: 'أكثر من الآخرين', severity: 'mild' },
      {
        min: 245,
        max: 300,
        levelKey: 'much_more',
        labelAr: 'أكثر بكثير من الآخرين',
        severity: 'severe',
      },
    ],
    requiredQualification: 'therapist',
    developer: 'Winnie Dunn',
  },
  {
    scaleCode: 'SPM2',
    abbreviation: 'SPM-2',
    category: 'sensory',
    nameAr: 'مقياس المعالجة الحسية 2',
    nameEn: 'Sensory Processing Measure 2',
    description:
      'يقيّم المعالجة الحسية والتخطيط الحركي والمشاركة الاجتماعية في البيئات المنزلية والمدرسية والمجتمعية',
    targetDisabilities: ['autism', 'sensory_processing', 'adhd', 'developmental', 'learning'],
    totalMaxScore: 240,
    ageRange: { minMonths: 24, maxMonths: 155, label: 'من سنتين إلى 12 سنة و11 شهراً' },
    administrationTime: 25,
    administrationType: 'parent_report',
    domains: [
      { key: 'socialParticipation', nameAr: 'المشاركة الاجتماعية', maxScore: 40 },
      { key: 'vision', nameAr: 'البصر', maxScore: 30 },
      { key: 'hearing', nameAr: 'السمع', maxScore: 30 },
      { key: 'touch', nameAr: 'اللمس', maxScore: 35 },
      { key: 'bodyAwareness', nameAr: 'الوعي الجسمي', maxScore: 35 },
      { key: 'balance', nameAr: 'التوازن والحركة', maxScore: 35 },
      { key: 'planning', nameAr: 'التخطيط الحركي', maxScore: 35 },
    ],
    interpretation: [
      { min: 0, max: 59, levelKey: 'definite', labelAr: 'صعوبة واضحة', severity: 'severe' },
      { min: 60, max: 95, levelKey: 'some', labelAr: 'بعض الصعوبة', severity: 'moderate' },
      { min: 96, max: 159, levelKey: 'typical', labelAr: 'نمط نموذجي', severity: 'normal' },
      {
        min: 160,
        max: 240,
        levelKey: 'above',
        labelAr: 'فوق النمط النموذجي',
        severity: 'above_average',
      },
    ],
    requiredQualification: 'therapist',
    developer: 'Parham & Ecker',
  },
  {
    scaleCode: 'SIPT',
    abbreviation: 'SIPT',
    category: 'sensory',
    nameAr: 'اختبارات التكامل الحسي والتطبيق العملي',
    nameEn: 'Sensory Integration and Praxis Tests',
    description: 'مجموعة شاملة من 17 اختباراً تقيس التكامل الحسي والتخطيط الحركي لدى الأطفال',
    targetDisabilities: ['sensory_processing', 'autism', 'learning', 'developmental', 'adhd'],
    totalMaxScore: 340,
    ageRange: { minMonths: 48, maxMonths: 107, label: 'من 4 سنوات إلى 8 سنوات و11 شهراً' },
    administrationTime: 120,
    administrationType: 'individual',
    domains: [
      { key: 'vestibular', nameAr: 'المعالجة الدهليزية', maxScore: 40 },
      { key: 'proprioceptive', nameAr: 'المعالجة الحسية العميقة', maxScore: 40 },
      { key: 'tactile', nameAr: 'المعالجة اللمسية', maxScore: 60 },
      { key: 'visualPerception', nameAr: 'الإدراك البصري', maxScore: 60 },
      { key: 'praxis', nameAr: 'التطبيق العملي', maxScore: 60 },
      { key: 'bilateralIntegration', nameAr: 'التكامل الثنائي', maxScore: 40 },
      { key: 'sequencing', nameAr: 'التسلسل الحركي', maxScore: 40 },
    ],
    interpretation: [
      { min: 0, max: 84, levelKey: 'deficit', labelAr: 'عجز واضح', severity: 'severe' },
      {
        min: 85,
        max: 114,
        levelKey: 'below_average',
        labelAr: 'دون المتوسط',
        severity: 'moderate',
      },
      { min: 115, max: 204, levelKey: 'average', labelAr: 'متوسط', severity: 'normal' },
      {
        min: 205,
        max: 269,
        levelKey: 'above_average',
        labelAr: 'فوق المتوسط',
        severity: 'above_average',
      },
      { min: 270, max: 340, levelKey: 'superior', labelAr: 'متفوق', severity: 'above_average' },
    ],
    requiredQualification: 'specialist',
    developer: 'A. Jean Ayres',
  },
  {
    scaleCode: 'AASP',
    abbreviation: 'AASP',
    category: 'sensory',
    nameAr: 'الملف الحسي للمراهقين والبالغين',
    nameEn: 'Adolescent/Adult Sensory Profile',
    description:
      'يقيّم أنماط المعالجة الحسية للمراهقين والبالغين وتأثيرها على الحياة اليومية والعمل',
    targetDisabilities: ['sensory_processing', 'autism', 'adhd', 'behavioral', 'intellectual'],
    totalMaxScore: 300,
    ageRange: { minMonths: 132, maxMonths: 780, label: 'من 11 سنة فما فوق' },
    administrationTime: 15,
    administrationType: 'self_report',
    domains: [
      { key: 'lowRegistration', nameAr: 'انخفاض التسجيل', maxScore: 75 },
      { key: 'sensationSeeking', nameAr: 'البحث عن الإحساس', maxScore: 75 },
      { key: 'sensoryAvoidance', nameAr: 'تجنب الإحساس', maxScore: 75 },
      { key: 'sensorySensitivity', nameAr: 'الحساسية الحسية', maxScore: 75 },
    ],
    interpretation: [
      {
        min: 0,
        max: 89,
        levelKey: 'much_less',
        labelAr: 'أقل بكثير من الآخرين',
        severity: 'severe',
      },
      { min: 90, max: 134, levelKey: 'less', labelAr: 'أقل من الآخرين', severity: 'moderate' },
      {
        min: 135,
        max: 189,
        levelKey: 'similar',
        labelAr: 'مثل غالبية الآخرين',
        severity: 'normal',
      },
      { min: 190, max: 244, levelKey: 'more', labelAr: 'أكثر من الآخرين', severity: 'mild' },
      {
        min: 245,
        max: 300,
        levelKey: 'much_more',
        labelAr: 'أكثر بكثير من الآخرين',
        severity: 'severe',
      },
    ],
    requiredQualification: 'therapist',
    developer: 'Catana Brown & Winnie Dunn',
  },

  /* ─── Adaptive Scales — مقاييس سلوك تكيفي ──────────────────────────────── */

  {
    scaleCode: 'VABS3',
    abbreviation: 'VABS-3',
    category: 'adaptive',
    nameAr: 'مقياس فاينلاند للسلوك التكيفي - الإصدار الثالث',
    nameEn: 'Vineland Adaptive Behavior Scales 3',
    description:
      'يقيّم مهارات السلوك التكيفي الضرورية للحياة اليومية من الطفولة إلى البلوغ شاملاً التواصل والمعيشة اليومية والتنشئة الاجتماعية',
    targetDisabilities: [
      'intellectual',
      'autism',
      'developmental',
      'down_syndrome',
      'learning',
      'multiple',
    ],
    totalMaxScore: 400,
    ageRange: { minMonths: 0, maxMonths: 1080, label: 'من الولادة إلى 90 سنة' },
    administrationTime: 45,
    administrationType: 'interview',
    domains: [
      { key: 'communication', nameAr: 'التواصل', maxScore: 100 },
      { key: 'dailyLiving', nameAr: 'مهارات الحياة اليومية', maxScore: 100 },
      { key: 'socialization', nameAr: 'التنشئة الاجتماعية', maxScore: 100 },
      { key: 'motorSkills', nameAr: 'المهارات الحركية', maxScore: 100 },
    ],
    interpretation: [
      { min: 0, max: 69, levelKey: 'low', labelAr: 'منخفض', severity: 'severe' },
      {
        min: 70,
        max: 84,
        levelKey: 'moderately_low',
        labelAr: 'منخفض بدرجة متوسطة',
        severity: 'moderate',
      },
      { min: 85, max: 114, levelKey: 'adequate', labelAr: 'مناسب / كافٍ', severity: 'normal' },
      {
        min: 115,
        max: 129,
        levelKey: 'moderately_high',
        labelAr: 'مرتفع بدرجة متوسطة',
        severity: 'above_average',
      },
      { min: 130, max: 400, levelKey: 'high', labelAr: 'مرتفع', severity: 'above_average' },
    ],
    requiredQualification: 'psychologist',
    developer: 'Sparrow, Cicchetti & Saulnier',
  },
  {
    scaleCode: 'DABS',
    abbreviation: 'DABS',
    category: 'adaptive',
    nameAr: 'مقياس السلوك التكيفي التشخيصي',
    nameEn: 'Diagnostic Adaptive Behavior Scale',
    description:
      'يقيّم السلوك التكيفي لتحديد أهلية تشخيص الإعاقة الذهنية وفق معايير AAIDD عبر ثلاثة مجالات رئيسية',
    targetDisabilities: [
      'intellectual',
      'developmental',
      'autism',
      'learning',
      'down_syndrome',
      'multiple',
    ],
    totalMaxScore: 330,
    ageRange: { minMonths: 48, maxMonths: 252, label: 'من 4 إلى 21 سنة' },
    administrationTime: 40,
    administrationType: 'interview',
    domains: [
      { key: 'conceptual', nameAr: 'المفاهيمي', maxScore: 110 },
      { key: 'social', nameAr: 'الاجتماعي', maxScore: 110 },
      { key: 'practical', nameAr: 'العملي', maxScore: 110 },
    ],
    interpretation: [
      {
        min: 0,
        max: 69,
        levelKey: 'significant_limitation',
        labelAr: 'قصور واضح',
        severity: 'severe',
      },
      { min: 70, max: 84, levelKey: 'limitation', labelAr: 'قصور', severity: 'moderate' },
      { min: 85, max: 114, levelKey: 'adequate', labelAr: 'كافٍ', severity: 'normal' },
      { min: 115, max: 330, levelKey: 'strength', labelAr: 'نقطة قوة', severity: 'above_average' },
    ],
    requiredQualification: 'psychologist',
    developer: 'Tassé, Schalock, Balboni et al.',
  },
  {
    scaleCode: 'SIBR',
    abbreviation: 'SIB-R',
    category: 'adaptive',
    nameAr: 'مقاييس السلوك المستقل - النسخة المراجعة',
    nameEn: 'Scales of Independent Behavior - Revised',
    description: 'يقيّم مهارات السلوك التكيفي والسلوكيات المشكلة لتحديد مستوى الدعم المطلوب',
    targetDisabilities: ['intellectual', 'developmental', 'multiple', 'autism', 'down_syndrome'],
    totalMaxScore: 280,
    ageRange: { minMonths: 3, maxMonths: 960, label: 'من 3 أشهر إلى 80 سنة' },
    administrationTime: 50,
    administrationType: 'interview',
    domains: [
      { key: 'motorSkills', nameAr: 'المهارات الحركية', maxScore: 70 },
      { key: 'socialCommunication', nameAr: 'التواصل الاجتماعي', maxScore: 70 },
      { key: 'personalLiving', nameAr: 'مهارات المعيشة الشخصية', maxScore: 70 },
      { key: 'communityLiving', nameAr: 'مهارات المعيشة المجتمعية', maxScore: 70 },
    ],
    interpretation: [
      { min: 0, max: 69, levelKey: 'limited', labelAr: 'محدود', severity: 'severe' },
      { min: 70, max: 84, levelKey: 'low', labelAr: 'منخفض', severity: 'moderate' },
      { min: 85, max: 114, labelAr: 'متوسط', levelKey: 'average', severity: 'normal' },
      { min: 115, max: 129, levelKey: 'high', labelAr: 'مرتفع', severity: 'above_average' },
      {
        min: 130,
        max: 280,
        levelKey: 'very_high',
        labelAr: 'مرتفع جداً',
        severity: 'above_average',
      },
    ],
    requiredQualification: 'psychologist',
    developer: 'Bruininks, Woodcock, Weatherman & Hill',
  },
  {
    scaleCode: 'ICAP',
    abbreviation: 'ICAP',
    category: 'adaptive',
    nameAr: 'قائمة جرد تخطيط العميل والمؤسسة',
    nameEn: 'Inventory for Client and Agency Planning',
    description:
      'أداة تقييم شاملة لتحديد مستوى الخدمات والدعم اللازم للأفراد ذوي الإعاقة ضمن المؤسسات التأهيلية',
    targetDisabilities: ['intellectual', 'developmental', 'multiple', 'physical', 'behavioral'],
    totalMaxScore: 300,
    ageRange: { minMonths: 0, maxMonths: 960, label: 'من الولادة إلى 80 سنة' },
    administrationTime: 25,
    administrationType: 'interview',
    domains: [
      { key: 'motorSkills', nameAr: 'المهارات الحركية', maxScore: 60 },
      { key: 'socialCommunication', nameAr: 'المهارات الاجتماعية والتواصلية', maxScore: 60 },
      { key: 'personalLiving', nameAr: 'مهارات المعيشة الشخصية', maxScore: 60 },
      { key: 'communityLiving', nameAr: 'مهارات المعيشة المجتمعية', maxScore: 60 },
      { key: 'problemBehavior', nameAr: 'السلوك المشكل', maxScore: 60 },
    ],
    interpretation: [
      { min: 0, max: 59, levelKey: 'total_care', labelAr: 'رعاية كاملة', severity: 'profound' },
      { min: 60, max: 119, levelKey: 'extensive_support', labelAr: 'دعم مكثف', severity: 'severe' },
      {
        min: 120,
        max: 179,
        levelKey: 'limited_support',
        labelAr: 'دعم محدود',
        severity: 'moderate',
      },
      {
        min: 180,
        max: 239,
        levelKey: 'intermittent_support',
        labelAr: 'دعم متقطع',
        severity: 'mild',
      },
      { min: 240, max: 300, levelKey: 'independent', labelAr: 'مستقل', severity: 'normal' },
    ],
    requiredQualification: 'specialist',
    developer: 'Bruininks, Hill, Weatherman & Woodcock',
  },

  /* ─── Vocational Scales — مقاييس تأهيل مهني ────────────────────────────── */

  {
    scaleCode: 'VCWS',
    abbreviation: 'VCWS',
    category: 'vocational',
    nameAr: 'عينات عمل فالبار المكونة',
    nameEn: 'Valpar Component Work Samples',
    description:
      'نظام تقييم مهني شامل يستخدم عينات عمل حقيقية لقياس قدرات العمل والمهارات المهنية للأشخاص ذوي الإعاقة',
    targetDisabilities: ['physical', 'intellectual', 'learning', 'visual', 'hearing', 'multiple'],
    totalMaxScore: 280,
    ageRange: { minMonths: 168, maxMonths: 780, label: 'من 14 سنة فما فوق' },
    administrationTime: 90,
    administrationType: 'individual',
    domains: [
      { key: 'smallTools', nameAr: 'استخدام الأدوات الصغيرة', maxScore: 40 },
      { key: 'sizeDiscrimination', nameAr: 'تمييز الأحجام', maxScore: 40 },
      { key: 'numericalSorting', nameAr: 'الفرز العددي', maxScore: 40 },
      { key: 'upperExtremity', nameAr: 'نطاق حركة الأطراف العلوية', maxScore: 40 },
      { key: 'clericalComprehension', nameAr: 'الاستيعاب الكتابي', maxScore: 40 },
      { key: 'problemSolving', nameAr: 'حل المشكلات', maxScore: 40 },
      { key: 'physicalCapacity', nameAr: 'القدرة البدنية', maxScore: 40 },
    ],
    interpretation: [
      { min: 0, max: 69, levelKey: 'not_ready', labelAr: 'غير مستعد للعمل', severity: 'severe' },
      {
        min: 70,
        max: 119,
        levelKey: 'sheltered',
        labelAr: 'يحتاج بيئة عمل محمية',
        severity: 'moderate',
      },
      { min: 120, max: 179, levelKey: 'supported', labelAr: 'يحتاج دعم مهني', severity: 'mild' },
      {
        min: 180,
        max: 224,
        levelKey: 'competitive_support',
        labelAr: 'عمل تنافسي مع دعم',
        severity: 'normal',
      },
      {
        min: 225,
        max: 280,
        levelKey: 'competitive',
        labelAr: 'عمل تنافسي مستقل',
        severity: 'above_average',
      },
    ],
    requiredQualification: 'specialist',
    developer: 'Valpar International',
  },
  {
    scaleCode: 'BWAP2',
    abbreviation: 'BWAP-2',
    category: 'vocational',
    nameAr: 'مقياس بيكر للتكيف المهني - الإصدار الثاني',
    nameEn: 'Becker Work Adjustment Profile 2',
    description:
      'يقيّم مهارات التكيف المهني والسلوكيات المطلوبة للنجاح في بيئة العمل للأشخاص ذوي الإعاقة',
    targetDisabilities: ['intellectual', 'learning', 'behavioral', 'physical', 'developmental'],
    totalMaxScore: 260,
    ageRange: { minMonths: 168, maxMonths: 780, label: 'من 14 سنة فما فوق' },
    administrationTime: 30,
    administrationType: 'observation',
    domains: [
      { key: 'workHabits', nameAr: 'عادات العمل', maxScore: 52 },
      { key: 'interpersonal', nameAr: 'العلاقات الشخصية', maxScore: 52 },
      { key: 'cognitiveSkills', nameAr: 'المهارات المعرفية', maxScore: 52 },
      { key: 'workPerformance', nameAr: 'الأداء المهني', maxScore: 52 },
      { key: 'workConformance', nameAr: 'الامتثال لقوانين العمل', maxScore: 52 },
    ],
    interpretation: [
      { min: 0, max: 64, levelKey: 'poor', labelAr: 'ضعيف', severity: 'severe' },
      {
        min: 65,
        max: 129,
        levelKey: 'below_average',
        labelAr: 'دون المتوسط',
        severity: 'moderate',
      },
      { min: 130, max: 194, levelKey: 'average', labelAr: 'متوسط', severity: 'normal' },
      {
        min: 195,
        max: 260,
        levelKey: 'above_average',
        labelAr: 'فوق المتوسط',
        severity: 'above_average',
      },
    ],
    requiredQualification: 'specialist',
    developer: 'Ralph Becker',
  },
  {
    scaleCode: 'TPI2',
    abbreviation: 'TPI-2',
    category: 'vocational',
    nameAr: 'قائمة جرد تخطيط الانتقال - الإصدار الثاني',
    nameEn: 'Transition Planning Inventory 2',
    description:
      'أداة تقييم شاملة لتخطيط انتقال الشباب ذوي الإعاقة من المدرسة إلى الحياة المهنية والمجتمعية',
    targetDisabilities: [
      'intellectual',
      'learning',
      'autism',
      'physical',
      'behavioral',
      'developmental',
    ],
    totalMaxScore: 270,
    ageRange: { minMonths: 168, maxMonths: 264, label: 'من 14 إلى 22 سنة' },
    administrationTime: 35,
    administrationType: 'mixed',
    domains: [
      { key: 'employment', nameAr: 'التوظيف', maxScore: 45 },
      { key: 'education', nameAr: 'التعليم المستمر', maxScore: 45 },
      { key: 'dailyLiving', nameAr: 'مهارات الحياة اليومية', maxScore: 45 },
      { key: 'leisure', nameAr: 'الترفيه والتواصل', maxScore: 45 },
      { key: 'communityParticipation', nameAr: 'المشاركة المجتمعية', maxScore: 45 },
      { key: 'selfDetermination', nameAr: 'تقرير المصير', maxScore: 45 },
    ],
    interpretation: [
      { min: 0, max: 67, levelKey: 'not_ready', labelAr: 'غير جاهز للانتقال', severity: 'severe' },
      {
        min: 68,
        max: 134,
        levelKey: 'developing',
        labelAr: 'في مرحلة التطوير',
        severity: 'moderate',
      },
      {
        min: 135,
        max: 202,
        levelKey: 'approaching_ready',
        labelAr: 'يقترب من الجاهزية',
        severity: 'mild',
      },
      { min: 203, max: 270, levelKey: 'ready', labelAr: 'جاهز للانتقال', severity: 'normal' },
    ],
    requiredQualification: 'specialist',
    developer: 'Clark & Patton',
  },
  {
    scaleCode: 'WRIOT3',
    abbreviation: 'WRIOT-3',
    category: 'vocational',
    nameAr: 'اختبار الاهتمامات والمهن واسع المدى - الإصدار الثالث',
    nameEn: 'Wide Range Interest and Occupation Test 3',
    description:
      'يحدد ميول واهتمامات الأفراد ذوي الإعاقة المهنية من خلال صور مرئية لتوجيه التأهيل المهني',
    targetDisabilities: ['intellectual', 'learning', 'physical', 'hearing', 'visual'],
    totalMaxScore: 240,
    ageRange: { minMonths: 108, maxMonths: 960, label: 'من 9 سنوات فما فوق' },
    administrationTime: 40,
    administrationType: 'individual',
    domains: [
      { key: 'realistic', nameAr: 'واقعي (تقني / حرفي)', maxScore: 40 },
      { key: 'investigative', nameAr: 'استقصائي (بحثي)', maxScore: 40 },
      { key: 'artistic', nameAr: 'فني (إبداعي)', maxScore: 40 },
      { key: 'social', nameAr: 'اجتماعي', maxScore: 40 },
      { key: 'enterprising', nameAr: 'مبادر (ريادي)', maxScore: 40 },
      { key: 'conventional', nameAr: 'تقليدي (إداري)', maxScore: 40 },
    ],
    interpretation: [
      { min: 0, max: 59, levelKey: 'low_interest', labelAr: 'اهتمام منخفض', severity: 'mild' },
      {
        min: 60,
        max: 119,
        levelKey: 'moderate_interest',
        labelAr: 'اهتمام متوسط',
        severity: 'normal',
      },
      {
        min: 120,
        max: 179,
        levelKey: 'high_interest',
        labelAr: 'اهتمام مرتفع',
        severity: 'normal',
      },
      {
        min: 180,
        max: 240,
        levelKey: 'very_high_interest',
        labelAr: 'اهتمام مرتفع جداً',
        severity: 'above_average',
      },
    ],
    requiredQualification: 'specialist',
    developer: 'Glutting & Wilkinson',
  },

  /* ─── Psychological Scales — مقاييس نفسية ──────────────────────────────── */

  {
    scaleCode: 'RCMAS2',
    abbreviation: 'RCMAS-2',
    category: 'psychological',
    nameAr: 'مقياس القلق الظاهر المراجع للأطفال - الإصدار الثاني',
    nameEn: "Revised Children's Manifest Anxiety Scale 2",
    description:
      'يقيّم مستوى القلق الظاهر لدى الأطفال والمراهقين ذوي الإعاقة بما في ذلك القلق الفسيولوجي والعصبية والقلق الاجتماعي',
    targetDisabilities: ['behavioral', 'autism', 'learning', 'intellectual', 'adhd'],
    totalMaxScore: 180,
    ageRange: { minMonths: 72, maxMonths: 228, label: 'من 6 إلى 19 سنة' },
    administrationTime: 15,
    administrationType: 'self_report',
    domains: [
      { key: 'physiologicalAnxiety', nameAr: 'القلق الفسيولوجي', maxScore: 45 },
      { key: 'worry', nameAr: 'القلق والتوتر', maxScore: 45 },
      { key: 'socialAnxiety', nameAr: 'القلق الاجتماعي', maxScore: 45 },
      { key: 'defensiveness', nameAr: 'الدفاعية', maxScore: 45 },
    ],
    interpretation: [
      { min: 0, max: 44, levelKey: 'low', labelAr: 'مستوى قلق منخفض', severity: 'normal' },
      { min: 45, max: 89, levelKey: 'average', labelAr: 'مستوى قلق متوسط', severity: 'normal' },
      {
        min: 90,
        max: 134,
        levelKey: 'above_average',
        labelAr: 'مستوى قلق فوق المتوسط',
        severity: 'moderate',
      },
      {
        min: 135,
        max: 180,
        levelKey: 'clinically_significant',
        labelAr: 'قلق مرتفع سريرياً',
        severity: 'severe',
      },
    ],
    requiredQualification: 'psychologist',
    developer: 'Reynolds & Richmond',
  },
  {
    scaleCode: 'CDI2',
    abbreviation: 'CDI-2',
    category: 'psychological',
    nameAr: 'قائمة اكتئاب الأطفال - الإصدار الثاني',
    nameEn: "Children's Depression Inventory 2",
    description:
      'يقيّم أعراض الاكتئاب لدى الأطفال والمراهقين ذوي الإعاقة شاملاً المزاج السلبي وعدم الفعالية والتقييم السلبي للذات',
    targetDisabilities: ['behavioral', 'learning', 'autism', 'intellectual', 'adhd', 'physical'],
    totalMaxScore: 168,
    ageRange: { minMonths: 84, maxMonths: 204, label: 'من 7 إلى 17 سنة' },
    administrationTime: 15,
    administrationType: 'self_report',
    domains: [
      { key: 'negativeMood', nameAr: 'المزاج السلبي / الأعراض الجسدية', maxScore: 42 },
      { key: 'negativeEsteem', nameAr: 'التقييم السلبي للذات', maxScore: 42 },
      { key: 'ineffectiveness', nameAr: 'عدم الفعالية', maxScore: 42 },
      { key: 'interpersonalProblems', nameAr: 'المشكلات الشخصية', maxScore: 42 },
    ],
    interpretation: [
      { min: 0, max: 41, levelKey: 'minimal', labelAr: 'أعراض طبيعية', severity: 'normal' },
      { min: 42, max: 83, levelKey: 'average', labelAr: 'أعراض متوسطة', severity: 'mild' },
      { min: 84, max: 125, levelKey: 'elevated', labelAr: 'أعراض مرتفعة', severity: 'moderate' },
      {
        min: 126,
        max: 168,
        levelKey: 'very_elevated',
        labelAr: 'أعراض مرتفعة جداً',
        severity: 'severe',
      },
    ],
    requiredQualification: 'psychologist',
    developer: 'Maria Kovacs',
  },
  {
    scaleCode: 'SCARED',
    abbreviation: 'SCARED',
    category: 'psychological',
    nameAr: 'مقياس القلق المرتبط بالاضطرابات الانفعالية لدى الأطفال',
    nameEn: 'Screen for Child Anxiety Related Disorders',
    description:
      'أداة فحص للكشف عن اضطرابات القلق بأنواعها لدى الأطفال والمراهقين ذوي الإعاقة شاملة القلق العام والانفصال والرهاب',
    targetDisabilities: [
      'behavioral',
      'autism',
      'adhd',
      'intellectual',
      'developmental',
      'learning',
    ],
    totalMaxScore: 164,
    ageRange: { minMonths: 96, maxMonths: 216, label: 'من 8 إلى 18 سنة' },
    administrationTime: 15,
    administrationType: 'self_report',
    domains: [
      { key: 'panicSomatic', nameAr: 'اضطراب الهلع / الأعراض الجسدية', maxScore: 39 },
      { key: 'generalizedAnxiety', nameAr: 'القلق العام', maxScore: 27 },
      { key: 'separationAnxiety', nameAr: 'قلق الانفصال', maxScore: 24 },
      { key: 'socialAnxiety', nameAr: 'القلق الاجتماعي', maxScore: 21 },
      { key: 'schoolAvoidance', nameAr: 'تجنب المدرسة', maxScore: 12 },
    ],
    interpretation: [
      { min: 0, max: 24, levelKey: 'minimal', labelAr: 'قلق طبيعي', severity: 'normal' },
      { min: 25, max: 49, levelKey: 'mild', labelAr: 'قلق بسيط', severity: 'mild' },
      { min: 50, max: 109, levelKey: 'moderate', labelAr: 'قلق متوسط', severity: 'moderate' },
      { min: 110, max: 164, levelKey: 'severe', labelAr: 'قلق شديد سريرياً', severity: 'severe' },
    ],
    requiredQualification: 'psychologist',
    developer: 'Boris Birmaher',
  },
  {
    scaleCode: 'PSI4',
    abbreviation: 'PSI-4',
    category: 'psychological',
    nameAr: 'مقياس الضغط النفسي للوالدين - الإصدار الرابع',
    nameEn: 'Parenting Stress Index 4',
    description:
      'يقيّم مستوى الضغط النفسي الذي يعاني منه والدا الطفل ذي الإعاقة بما في ذلك ضغوط الطفل وضغوط الوالد',
    targetDisabilities: [
      'autism',
      'intellectual',
      'developmental',
      'behavioral',
      'adhd',
      'multiple',
      'cerebral_palsy',
    ],
    totalMaxScore: 180,
    ageRange: { minMonths: 1, maxMonths: 144, label: 'للأطفال من شهر إلى 12 سنة (يُجيب الوالد)' },
    administrationTime: 20,
    administrationType: 'parent_report',
    domains: [
      { key: 'childDomain', nameAr: 'مجال الطفل', maxScore: 60 },
      { key: 'parentDomain', nameAr: 'مجال الوالد', maxScore: 60 },
      { key: 'lifeStress', nameAr: 'ضغوط الحياة', maxScore: 60 },
    ],
    interpretation: [
      { min: 0, max: 44, levelKey: 'low_stress', labelAr: 'ضغط نفسي منخفض', severity: 'normal' },
      {
        min: 45,
        max: 89,
        levelKey: 'normal_stress',
        labelAr: 'ضغط نفسي طبيعي',
        severity: 'normal',
      },
      {
        min: 90,
        max: 134,
        levelKey: 'high_stress',
        labelAr: 'ضغط نفسي مرتفع',
        severity: 'moderate',
      },
      {
        min: 135,
        max: 180,
        levelKey: 'clinically_significant',
        labelAr: 'ضغط نفسي مرتفع سريرياً',
        severity: 'severe',
      },
    ],
    requiredQualification: 'psychologist',
    developer: 'Richard Abidin',
  },

  /* ─── Additional Autism Scales — مقاييس توحد إضافية ────────────────────── */

  {
    scaleCode: 'PEP3',
    abbreviation: 'PEP-3',
    category: 'autism',
    nameAr: 'الملف النفسي التربوي - الإصدار الثالث',
    nameEn: 'Psychoeducational Profile 3',
    description:
      'يقيّم المهارات التعليمية والسلوكية لدى الأطفال ذوي اضطراب طيف التوحد لتصميم برامج تعليمية فردية',
    targetDisabilities: ['autism', 'developmental', 'intellectual'],
    totalMaxScore: 328,
    ageRange: { minMonths: 24, maxMonths: 90, label: 'من سنتين إلى 7 سنوات ونصف' },
    administrationTime: 60,
    administrationType: 'individual',
    domains: [
      { key: 'cognitivVerbal', nameAr: 'المعرفي اللفظي', maxScore: 68 },
      { key: 'expressiveLanguage', nameAr: 'اللغة التعبيرية', maxScore: 50 },
      { key: 'receptiveLanguage', nameAr: 'اللغة الاستقبالية', maxScore: 46 },
      { key: 'fineMotor', nameAr: 'الحركة الدقيقة', maxScore: 40 },
      { key: 'grossMotor', nameAr: 'الحركة الكبرى', maxScore: 36 },
      { key: 'visualMotorImitation', nameAr: 'التقليد البصري الحركي', maxScore: 28 },
      { key: 'affectiveExpression', nameAr: 'التعبير الانفعالي', maxScore: 24 },
      { key: 'socialReciprocity', nameAr: 'التبادل الاجتماعي', maxScore: 18 },
      { key: 'motorBehaviors', nameAr: 'السلوكيات الحركية المميزة', maxScore: 18 },
    ],
    interpretation: [
      { min: 0, max: 81, levelKey: 'severe', labelAr: 'تأخر شديد', severity: 'severe' },
      { min: 82, max: 163, levelKey: 'moderate', labelAr: 'تأخر متوسط', severity: 'moderate' },
      { min: 164, max: 245, levelKey: 'mild', labelAr: 'تأخر بسيط', severity: 'mild' },
      {
        min: 246,
        max: 328,
        levelKey: 'adequate',
        labelAr: 'مناسب / ضمن المتوقع',
        severity: 'normal',
      },
    ],
    requiredQualification: 'psychologist',
    developer: 'Schopler, Lansing, Reichler & Marcus',
  },
  {
    scaleCode: 'ABLLS',
    abbreviation: 'ABLLS-R',
    category: 'autism',
    nameAr: 'تقييم مهارات اللغة والتعلم الأساسية - النسخة المراجعة',
    nameEn: 'Assessment of Basic Language and Learning Skills - Revised',
    description:
      'أداة تقييم وتتبع شاملة تقيس 544 مهارة عبر 25 مجالاً لتصميم برامج ABA الفردية لأطفال التوحد',
    targetDisabilities: ['autism', 'developmental', 'intellectual', 'speech'],
    totalMaxScore: 544,
    ageRange: { minMonths: 0, maxMonths: 144, label: 'من الولادة إلى 12 سنة' },
    administrationTime: 90,
    administrationType: 'observation',
    domains: [
      { key: 'cooperation', nameAr: 'التعاون والفعالية', maxScore: 60 },
      { key: 'visualPerformance', nameAr: 'الأداء البصري', maxScore: 60 },
      { key: 'receptiveLanguage', nameAr: 'اللغة الاستقبالية', maxScore: 60 },
      { key: 'imitation', nameAr: 'التقليد', maxScore: 50 },
      { key: 'manding', nameAr: 'الطلب (ماندنغ)', maxScore: 54 },
      { key: 'tacting', nameAr: 'التسمية (تاكتنغ)', maxScore: 60 },
      { key: 'intraverbal', nameAr: 'المحادثة / الاستجابة اللفظية', maxScore: 60 },
      { key: 'socialInteraction', nameAr: 'التفاعل الاجتماعي', maxScore: 50 },
      { key: 'selfCare', nameAr: 'الرعاية الذاتية', maxScore: 45 },
      { key: 'academicSkills', nameAr: 'المهارات الأكاديمية', maxScore: 45 },
    ],
    interpretation: [
      { min: 0, max: 135, levelKey: 'beginning', labelAr: 'مستوى بداية', severity: 'severe' },
      {
        min: 136,
        max: 271,
        levelKey: 'intermediate',
        labelAr: 'مستوى متوسط',
        severity: 'moderate',
      },
      { min: 272, max: 407, levelKey: 'advanced', labelAr: 'مستوى متقدم', severity: 'mild' },
      { min: 408, max: 544, levelKey: 'mastery', labelAr: 'مستوى إتقان', severity: 'normal' },
    ],
    requiredQualification: 'specialist',
    developer: 'James Partington',
  },

  /* ─── Additional Speech Scales — مقاييس نطق ولغة إضافية ───────────────── */

  {
    scaleCode: 'GFTA3',
    abbreviation: 'GFTA-3',
    category: 'speech',
    nameAr: 'اختبار غولدمان-فريستو للنطق - الإصدار الثالث',
    nameEn: 'Goldman-Fristoe Test of Articulation 3',
    description: 'يقيّم قدرة الطفل على نطق أصوات الكلام بشكل صحيح في مواضع مختلفة من الكلمة',
    targetDisabilities: ['speech', 'hearing', 'cerebral_palsy', 'developmental', 'down_syndrome'],
    totalMaxScore: 180,
    ageRange: { minMonths: 24, maxMonths: 252, label: 'من سنتين إلى 21 سنة' },
    administrationTime: 20,
    administrationType: 'individual',
    domains: [
      { key: 'soundsInWords', nameAr: 'الأصوات في الكلمات', maxScore: 80 },
      { key: 'soundsInSentences', nameAr: 'الأصوات في الجمل', maxScore: 60 },
      { key: 'stimulability', nameAr: 'قابلية الاستثارة', maxScore: 40 },
    ],
    interpretation: [
      {
        min: 0,
        max: 44,
        levelKey: 'severe_disorder',
        labelAr: 'اضطراب نطقي شديد',
        severity: 'severe',
      },
      {
        min: 45,
        max: 89,
        levelKey: 'moderate_disorder',
        labelAr: 'اضطراب نطقي متوسط',
        severity: 'moderate',
      },
      {
        min: 90,
        max: 134,
        levelKey: 'mild_disorder',
        labelAr: 'اضطراب نطقي بسيط',
        severity: 'mild',
      },
      { min: 135, max: 180, levelKey: 'normal', labelAr: 'نطق طبيعي', severity: 'normal' },
    ],
    requiredQualification: 'therapist',
    developer: 'Goldman & Fristoe',
  },
  {
    scaleCode: 'PPVT5',
    abbreviation: 'PPVT-5',
    category: 'speech',
    nameAr: 'اختبار بيبودي للمفردات المصورة - الإصدار الخامس',
    nameEn: 'Peabody Picture Vocabulary Test 5',
    description:
      'يقيّم المفردات الاستقبالية (الفهم) لدى الأفراد من خلال اختيار الصورة الصحيحة من بين عدة خيارات',
    targetDisabilities: [
      'speech',
      'hearing',
      'intellectual',
      'autism',
      'developmental',
      'learning',
    ],
    totalMaxScore: 228,
    ageRange: { minMonths: 30, maxMonths: 1080, label: 'من سنتين ونصف إلى 90 سنة' },
    administrationTime: 20,
    administrationType: 'individual',
    domains: [{ key: 'receptiveVocab', nameAr: 'المفردات الاستقبالية', maxScore: 228 }],
    interpretation: [
      { min: 0, max: 56, levelKey: 'extremely_low', labelAr: 'منخفض للغاية', severity: 'severe' },
      {
        min: 57,
        max: 113,
        levelKey: 'below_average',
        labelAr: 'دون المتوسط',
        severity: 'moderate',
      },
      { min: 114, max: 170, levelKey: 'average', labelAr: 'متوسط', severity: 'normal' },
      {
        min: 171,
        max: 228,
        levelKey: 'above_average',
        labelAr: 'فوق المتوسط',
        severity: 'above_average',
      },
    ],
    requiredQualification: 'therapist',
    developer: 'Dunn & Dunn',
  },
];

/* ═══════════════════════════════════════════════════════════════════════════ *
 *  BUILT-IN PROGRAM TEMPLATES — قوالب البرامج المدمجة
 * ═══════════════════════════════════════════════════════════════════════════ */

export const REHAB_PROGRAM_TEMPLATES_CATALOG = [
  {
    programCode: 'EI-001',
    abbreviation: 'EI',
    category: 'early_intervention',
    nameAr: 'برنامج التدخل المبكر الشامل',
    nameEn: 'Comprehensive Early Intervention Program',
    description: 'برنامج متعدد التخصصات للأطفال دون 3 سنوات لتحسين النمو في جميع المجالات',
    targetDisabilities: [
      'developmental',
      'autism',
      'down_syndrome',
      'cerebral_palsy',
      'hearing',
      'visual',
    ],
    targetAgeRange: { minMonths: 0, maxMonths: 36, label: 'من الولادة إلى 3 سنوات' },
    severityLevels: ['all'],
    totalDurationWeeks: 52,
    sessionsPerWeek: 3,
    sessionDuration: 60,
    phases: [
      {
        phaseNumber: 1,
        nameAr: 'التقييم والتخطيط',
        durationWeeks: 4,
        objectives: [{ textAr: 'تقييم شامل متعدد التخصصات' }, { textAr: 'وضع خطة تدخل فردية' }],
      },
      {
        phaseNumber: 2,
        nameAr: 'التدخل المكثف',
        durationWeeks: 24,
        objectives: [
          { textAr: 'تحسين المهارات الحركية والتواصلية' },
          { textAr: 'تعزيز التفاعل الاجتماعي' },
        ],
      },
      {
        phaseNumber: 3,
        nameAr: 'الدمج والتطبيق',
        durationWeeks: 16,
        objectives: [
          { textAr: 'تطبيق المهارات في البيئة الطبيعية' },
          { textAr: 'تدريب الأسرة على الاستراتيجيات' },
        ],
      },
      {
        phaseNumber: 4,
        nameAr: 'المتابعة والانتقال',
        durationWeeks: 8,
        objectives: [{ textAr: 'تقييم نهائي' }, { textAr: 'خطة انتقال لمرحلة ما قبل المدرسة' }],
      },
    ],
    requiredTeam: [
      { role: 'physical_therapist', roleNameAr: 'أخصائي علاج طبيعي' },
      { role: 'occupational_therapist', roleNameAr: 'أخصائي علاج وظيفي' },
      { role: 'speech_therapist', roleNameAr: 'أخصائي نطق', isPrimary: true },
      { role: 'special_educator', roleNameAr: 'معلم تربية خاصة' },
    ],
  },
  {
    programCode: 'ABA-001',
    abbreviation: 'ABA',
    category: 'aba_therapy',
    nameAr: 'برنامج تحليل السلوك التطبيقي المكثف',
    nameEn: 'Intensive Applied Behavior Analysis Program',
    description: 'برنامج ABA مكثف لتطوير المهارات وتقليل السلوكيات غير المرغوبة لدى أطفال التوحد',
    targetDisabilities: ['autism', 'behavioral', 'intellectual'],
    targetAgeRange: { minMonths: 24, maxMonths: 144, label: '2-12 سنة' },
    severityLevels: ['mild', 'moderate', 'severe'],
    totalDurationWeeks: 48,
    sessionsPerWeek: 5,
    sessionDuration: 120,
    phases: [
      {
        phaseNumber: 1,
        nameAr: 'خط الأساس والتقييم',
        durationWeeks: 4,
        objectives: [{ textAr: 'تقييم VB-MAPP أو ABLLS-R' }, { textAr: 'تحديد أهداف التدخل' }],
      },
      {
        phaseNumber: 2,
        nameAr: 'بناء المهارات الأساسية',
        durationWeeks: 16,
        objectives: [{ textAr: 'تعليم الطلبات (الماند)' }, { textAr: 'تعليم التقليد والاستجابة' }],
      },
      {
        phaseNumber: 3,
        nameAr: 'توسيع المهارات',
        durationWeeks: 20,
        objectives: [{ textAr: 'تعليم المهارات الأكاديمية' }, { textAr: 'تطوير اللعب الاجتماعي' }],
      },
      {
        phaseNumber: 4,
        nameAr: 'التعميم والصيانة',
        durationWeeks: 8,
        objectives: [
          { textAr: 'تعميم المهارات عبر البيئات' },
          { textAr: 'صيانة السلوكيات المكتسبة' },
        ],
      },
    ],
    requiredTeam: [
      { role: 'behavior_analyst', roleNameAr: 'محلل سلوك معتمد BCBA', isPrimary: true },
      { role: 'special_educator', roleNameAr: 'معلم تربية خاصة' },
      { role: 'speech_therapist', roleNameAr: 'أخصائي نطق' },
    ],
  },
  {
    programCode: 'SI-001',
    abbreviation: 'SI',
    category: 'sensory_integration',
    nameAr: 'برنامج التكامل الحسي',
    nameEn: 'Sensory Integration Therapy Program',
    description: 'برنامج علاجي لمعالجة صعوبات المعالجة الحسية وتحسين التنظيم الذاتي',
    targetDisabilities: ['autism', 'sensory_processing', 'adhd', 'developmental'],
    targetAgeRange: { minMonths: 24, maxMonths: 144, label: '2-12 سنة' },
    severityLevels: ['mild', 'moderate', 'severe'],
    totalDurationWeeks: 24,
    sessionsPerWeek: 3,
    sessionDuration: 45,
    phases: [
      {
        phaseNumber: 1,
        nameAr: 'التقييم الحسي',
        durationWeeks: 2,
        objectives: [{ textAr: 'تطبيق Sensory Profile' }, { textAr: 'وضع خطة حسية فردية' }],
      },
      {
        phaseNumber: 2,
        nameAr: 'التدخل الحسي المكثف',
        durationWeeks: 16,
        objectives: [{ textAr: 'تحسين تحمل المثيرات الحسية' }, { textAr: 'تطوير التنظيم الذاتي' }],
      },
      {
        phaseNumber: 3,
        nameAr: 'الانتقال والتعميم',
        durationWeeks: 6,
        objectives: [{ textAr: 'تطبيق النظام الحسي في المنزل والمدرسة' }],
      },
    ],
    requiredTeam: [
      { role: 'occupational_therapist', roleNameAr: 'أخصائي علاج وظيفي', isPrimary: true },
    ],
  },
  {
    programCode: 'SLP-001',
    abbreviation: 'SLP',
    category: 'speech_language',
    nameAr: 'برنامج التأهيل النطقي واللغوي المكثف',
    nameEn: 'Intensive Speech-Language Rehabilitation Program',
    description: 'برنامج مكثف لعلاج اضطرابات النطق واللغة والتواصل',
    targetDisabilities: ['speech', 'hearing', 'autism', 'developmental', 'learning'],
    targetAgeRange: { minMonths: 18, maxMonths: 216, label: '1.5-18 سنة' },
    severityLevels: ['mild', 'moderate', 'severe'],
    totalDurationWeeks: 36,
    sessionsPerWeek: 3,
    sessionDuration: 45,
    phases: [
      {
        phaseNumber: 1,
        nameAr: 'التقييم اللغوي الشامل',
        durationWeeks: 2,
        objectives: [{ textAr: 'تطبيق CELF-5 أو PLS-5' }, { textAr: 'تحليل عينة لغوية' }],
      },
      {
        phaseNumber: 2,
        nameAr: 'التدخل المباشر',
        durationWeeks: 24,
        objectives: [{ textAr: 'تحسين الأصوات الكلامية' }, { textAr: 'تطوير المفردات والتراكيب' }],
      },
      {
        phaseNumber: 3,
        nameAr: 'التواصل الوظيفي',
        durationWeeks: 10,
        objectives: [{ textAr: 'تعزيز التواصل في المواقف اليومية' }],
      },
    ],
    requiredTeam: [{ role: 'speech_therapist', roleNameAr: 'أخصائي نطق ولغة', isPrimary: true }],
  },
  {
    programCode: 'PT-001',
    abbreviation: 'PT',
    category: 'physical_therapy',
    nameAr: 'برنامج العلاج الطبيعي المكثف',
    nameEn: 'Intensive Physical Therapy Program',
    description: 'برنامج مكثف لتحسين الوظائف الحركية والاستقلالية لذوي الإعاقة الحركية',
    targetDisabilities: ['physical', 'cerebral_palsy', 'down_syndrome'],
    targetAgeRange: { minMonths: 6, maxMonths: 600, label: '6 أشهر فأكثر' },
    severityLevels: ['mild', 'moderate', 'severe', 'profound'],
    totalDurationWeeks: 24,
    sessionsPerWeek: 5,
    sessionDuration: 60,
    phases: [
      {
        phaseNumber: 1,
        nameAr: 'التقييم الحركي',
        durationWeeks: 2,
        objectives: [{ textAr: 'تطبيق GMFM-88' }, { textAr: 'تقييم التوازن والقوة' }],
      },
      {
        phaseNumber: 2,
        nameAr: 'التقوية والمرونة',
        durationWeeks: 10,
        objectives: [{ textAr: 'تحسين القوة العضلية' }, { textAr: 'زيادة المدى الحركي' }],
      },
      {
        phaseNumber: 3,
        nameAr: 'الوظائف الحركية',
        durationWeeks: 8,
        objectives: [
          { textAr: 'تحسين المشي والتوازن' },
          { textAr: 'تطوير المهارات الحركية الكبرى' },
        ],
      },
      {
        phaseNumber: 4,
        nameAr: 'الاستقلالية',
        durationWeeks: 4,
        objectives: [{ textAr: 'تعميم المهارات في الأنشطة اليومية' }],
      },
    ],
    requiredTeam: [
      { role: 'physical_therapist', roleNameAr: 'أخصائي علاج طبيعي', isPrimary: true },
      { role: 'occupational_therapist', roleNameAr: 'أخصائي علاج وظيفي' },
    ],
  },
  {
    programCode: 'VR-001',
    abbreviation: 'VR',
    category: 'vocational_rehab',
    nameAr: 'برنامج التأهيل المهني والتوظيف المدعوم',
    nameEn: 'Vocational Rehabilitation & Supported Employment',
    description: 'برنامج شامل لتأهيل ذوي الإعاقة مهنياً وتوفير فرص عمل مدعومة',
    targetDisabilities: ['intellectual', 'autism', 'physical', 'hearing', 'visual', 'learning'],
    targetAgeRange: { minMonths: 180, maxMonths: 600, label: '15 سنة فأكثر' },
    severityLevels: ['mild', 'moderate'],
    totalDurationWeeks: 48,
    sessionsPerWeek: 5,
    sessionDuration: 180,
    phases: [
      {
        phaseNumber: 1,
        nameAr: 'التقييم المهني',
        durationWeeks: 4,
        objectives: [
          { textAr: 'تقييم الميول والقدرات المهنية' },
          { textAr: 'تحديد مسار مهني مناسب' },
        ],
      },
      {
        phaseNumber: 2,
        nameAr: 'التدريب المهني',
        durationWeeks: 20,
        objectives: [
          { textAr: 'اكتساب مهارات مهنية أساسية' },
          { textAr: 'التدريب على بيئة العمل' },
        ],
      },
      {
        phaseNumber: 3,
        nameAr: 'التدريب الميداني',
        durationWeeks: 16,
        objectives: [
          { textAr: 'التدريب في بيئة عمل حقيقية' },
          { textAr: 'تطوير مهارات التواصل المهني' },
        ],
      },
      {
        phaseNumber: 4,
        nameAr: 'التوظيف المدعوم',
        durationWeeks: 8,
        objectives: [{ textAr: 'الالتحاق ببيئة عمل مع دعم' }, { textAr: 'متابعة الأداء والتكيف' }],
      },
    ],
    requiredTeam: [
      { role: 'vocational_counselor', roleNameAr: 'مستشار مهني', isPrimary: true },
      { role: 'social_worker', roleNameAr: 'أخصائي اجتماعي' },
      { role: 'psychologist', roleNameAr: 'أخصائي نفسي' },
    ],
  },
  {
    programCode: 'LS-001',
    abbreviation: 'LS',
    category: 'life_skills',
    nameAr: 'برنامج المهارات الحياتية والاستقلالية',
    nameEn: 'Life Skills & Independence Program',
    description: 'برنامج لتعليم مهارات الحياة اليومية والاستقلالية لذوي الإعاقة',
    targetDisabilities: ['intellectual', 'autism', 'down_syndrome', 'developmental'],
    targetAgeRange: { minMonths: 72, maxMonths: 300, label: '6-25 سنة' },
    severityLevels: ['mild', 'moderate'],
    totalDurationWeeks: 36,
    sessionsPerWeek: 3,
    sessionDuration: 90,
    phases: [
      {
        phaseNumber: 1,
        nameAr: 'التقييم الوظيفي',
        durationWeeks: 2,
        objectives: [{ textAr: 'تقييم مهارات الحياة اليومية' }],
      },
      {
        phaseNumber: 2,
        nameAr: 'الرعاية الذاتية',
        durationWeeks: 12,
        objectives: [{ textAr: 'تعليم النظافة الشخصية' }, { textAr: 'إعداد الطعام البسيط' }],
      },
      {
        phaseNumber: 3,
        nameAr: 'المهارات المنزلية',
        durationWeeks: 10,
        objectives: [{ textAr: 'ترتيب الغرفة والملابس' }, { textAr: 'استخدام الأجهزة المنزلية' }],
      },
      {
        phaseNumber: 4,
        nameAr: 'المهارات المجتمعية',
        durationWeeks: 12,
        objectives: [{ textAr: 'استخدام وسائل النقل' }, { textAr: 'التسوق وإدارة المال' }],
      },
    ],
    requiredTeam: [
      { role: 'occupational_therapist', roleNameAr: 'أخصائي علاج وظيفي', isPrimary: true },
      { role: 'special_educator', roleNameAr: 'معلم تربية خاصة' },
    ],
  },
  {
    programCode: 'SS-001',
    abbreviation: 'SS',
    category: 'social_skills',
    nameAr: 'برنامج المهارات الاجتماعية',
    nameEn: 'Social Skills Training Program',
    description: 'برنامج جماعي لتطوير المهارات الاجتماعية والتواصل البيشخصي',
    targetDisabilities: ['autism', 'intellectual', 'behavioral', 'adhd', 'learning'],
    targetAgeRange: { minMonths: 48, maxMonths: 216, label: '4-18 سنة' },
    severityLevels: ['mild', 'moderate'],
    totalDurationWeeks: 24,
    sessionsPerWeek: 2,
    sessionDuration: 60,
    groupSize: { min: 4, max: 8, type_: 'group' },
    phases: [
      {
        phaseNumber: 1,
        nameAr: 'التعارف والتقييم',
        durationWeeks: 2,
        objectives: [{ textAr: 'بناء الألفة بين المجموعة' }],
      },
      {
        phaseNumber: 2,
        nameAr: 'المهارات الأساسية',
        durationWeeks: 10,
        objectives: [{ textAr: 'التحية والتعريف بالنفس' }, { textAr: 'الاستماع والتبادل' }],
      },
      {
        phaseNumber: 3,
        nameAr: 'المهارات المتقدمة',
        durationWeeks: 8,
        objectives: [{ textAr: 'حل النزاعات' }, { textAr: 'العمل الجماعي' }],
      },
      {
        phaseNumber: 4,
        nameAr: 'التطبيق والتعميم',
        durationWeeks: 4,
        objectives: [{ textAr: 'ممارسة المهارات في بيئات مختلفة' }],
      },
    ],
    requiredTeam: [
      { role: 'psychologist', roleNameAr: 'أخصائي نفسي', isPrimary: true },
      { role: 'social_worker', roleNameAr: 'أخصائي اجتماعي' },
    ],
  },
  {
    programCode: 'FT-001',
    abbreviation: 'FT',
    category: 'family_training',
    nameAr: 'برنامج تدريب وتمكين الأسرة',
    nameEn: 'Family Empowerment & Training Program',
    description: 'برنامج شامل لتدريب أسر ذوي الإعاقة على استراتيجيات الدعم والتعامل',
    targetDisabilities: ['autism', 'intellectual', 'physical', 'developmental', 'down_syndrome'],
    targetAgeRange: { minMonths: 0, maxMonths: 216, label: 'جميع الأعمار' },
    severityLevels: ['all'],
    totalDurationWeeks: 16,
    sessionsPerWeek: 1,
    sessionDuration: 120,
    groupSize: { min: 8, max: 15, type_: 'group' },
    phases: [
      {
        phaseNumber: 1,
        nameAr: 'فهم الإعاقة',
        durationWeeks: 4,
        objectives: [{ textAr: 'التعريف بطبيعة الإعاقة' }, { textAr: 'الدعم النفسي للأسرة' }],
      },
      {
        phaseNumber: 2,
        nameAr: 'استراتيجيات التعامل',
        durationWeeks: 6,
        objectives: [{ textAr: 'تقنيات إدارة السلوك' }, { textAr: 'تعزيز التواصل' }],
      },
      {
        phaseNumber: 3,
        nameAr: 'التطبيق العملي',
        durationWeeks: 4,
        objectives: [{ textAr: 'تطبيق الاستراتيجيات في المنزل' }],
      },
      {
        phaseNumber: 4,
        nameAr: 'المتابعة',
        durationWeeks: 2,
        objectives: [{ textAr: 'مراجعة التقدم ودعم مستمر' }],
      },
    ],
    requiredTeam: [
      { role: 'family_counselor', roleNameAr: 'مستشار أسري', isPrimary: true },
      { role: 'psychologist', roleNameAr: 'أخصائي نفسي' },
      { role: 'special_educator', roleNameAr: 'معلم تربية خاصة' },
    ],
  },
  {
    programCode: 'CI-001',
    abbreviation: 'CI',
    category: 'community_integration',
    nameAr: 'برنامج الدمج المجتمعي',
    nameEn: 'Community Integration Program',
    description: 'برنامج لتسهيل دمج ذوي الإعاقة في المجتمع وتعزيز المشاركة المجتمعية',
    targetDisabilities: ['intellectual', 'autism', 'physical', 'hearing', 'visual'],
    targetAgeRange: { minMonths: 120, maxMonths: 600, label: '10 سنوات فأكثر' },
    severityLevels: ['mild', 'moderate'],
    totalDurationWeeks: 24,
    sessionsPerWeek: 2,
    sessionDuration: 120,
    phases: [
      {
        phaseNumber: 1,
        nameAr: 'التهيئة',
        durationWeeks: 4,
        objectives: [{ textAr: 'تقييم مهارات الاندماج' }],
      },
      {
        phaseNumber: 2,
        nameAr: 'المهارات المجتمعية',
        durationWeeks: 10,
        objectives: [{ textAr: 'استخدام المرافق العامة' }, { textAr: 'التعامل مع الآخرين' }],
      },
      {
        phaseNumber: 3,
        nameAr: 'التدريب الميداني',
        durationWeeks: 8,
        objectives: [{ textAr: 'زيارات مجتمعية منتظمة' }],
      },
      {
        phaseNumber: 4,
        nameAr: 'الاستقلالية',
        durationWeeks: 2,
        objectives: [{ textAr: 'ممارسة الأنشطة بشكل مستقل' }],
      },
    ],
    requiredTeam: [
      { role: 'social_worker', roleNameAr: 'أخصائي اجتماعي', isPrimary: true },
      { role: 'recreation_therapist', roleNameAr: 'أخصائي ترفيه علاجي' },
    ],
  },
  {
    programCode: 'CR-001',
    abbreviation: 'CR',
    category: 'cognitive_rehab',
    nameAr: 'برنامج التأهيل المعرفي',
    nameEn: 'Cognitive Rehabilitation Program',
    description: 'برنامج لتحسين الوظائف المعرفية كالانتباه والذاكرة والوظائف التنفيذية',
    targetDisabilities: ['intellectual', 'learning', 'adhd', 'developmental'],
    targetAgeRange: { minMonths: 60, maxMonths: 216, label: '5-18 سنة' },
    severityLevels: ['mild', 'moderate'],
    totalDurationWeeks: 24,
    sessionsPerWeek: 3,
    sessionDuration: 45,
    phases: [
      {
        phaseNumber: 1,
        nameAr: 'التقييم المعرفي',
        durationWeeks: 2,
        objectives: [{ textAr: 'تقييم الانتباه والذاكرة' }],
      },
      {
        phaseNumber: 2,
        nameAr: 'تدريب الانتباه',
        durationWeeks: 8,
        objectives: [{ textAr: 'تحسين الانتباه المتواصل' }, { textAr: 'تقليل التشتت' }],
      },
      {
        phaseNumber: 3,
        nameAr: 'تدريب الذاكرة',
        durationWeeks: 8,
        objectives: [{ textAr: 'تطوير استراتيجيات الذاكرة' }],
      },
      {
        phaseNumber: 4,
        nameAr: 'الوظائف التنفيذية',
        durationWeeks: 6,
        objectives: [{ textAr: 'تحسين التخطيط وحل المشكلات' }],
      },
    ],
    requiredTeam: [
      { role: 'psychologist', roleNameAr: 'أخصائي نفسي', isPrimary: true },
      { role: 'special_educator', roleNameAr: 'معلم تربية خاصة' },
    ],
  },
  {
    programCode: 'BS-001',
    abbreviation: 'BS',
    category: 'behavioral_support',
    nameAr: 'برنامج الدعم السلوكي الإيجابي',
    nameEn: 'Positive Behavioral Support Program',
    description: 'برنامج يعتمد على مبادئ الدعم السلوكي الإيجابي لتقليل السلوكيات الصعبة',
    targetDisabilities: ['behavioral', 'autism', 'intellectual', 'adhd'],
    targetAgeRange: { minMonths: 36, maxMonths: 216, label: '3-18 سنة' },
    severityLevels: ['mild', 'moderate', 'severe'],
    totalDurationWeeks: 24,
    sessionsPerWeek: 3,
    sessionDuration: 60,
    phases: [
      {
        phaseNumber: 1,
        nameAr: 'التقييم الوظيفي للسلوك',
        durationWeeks: 3,
        objectives: [{ textAr: 'إجراء تحليل وظيفي للسلوك (FBA)' }],
      },
      {
        phaseNumber: 2,
        nameAr: 'بناء خطة الدعم',
        durationWeeks: 3,
        objectives: [{ textAr: 'تصميم خطة دعم سلوكي' }],
      },
      {
        phaseNumber: 3,
        nameAr: 'التطبيق المكثف',
        durationWeeks: 12,
        objectives: [{ textAr: 'تعليم سلوكيات بديلة' }, { textAr: 'تعديل البيئة' }],
      },
      {
        phaseNumber: 4,
        nameAr: 'الصيانة والتعميم',
        durationWeeks: 6,
        objectives: [{ textAr: 'تعميم السلوكيات عبر البيئات' }],
      },
    ],
    requiredTeam: [
      { role: 'behavior_analyst', roleNameAr: 'محلل سلوك', isPrimary: true },
      { role: 'psychologist', roleNameAr: 'أخصائي نفسي' },
    ],
  },
];

/** Category labels for UI */
export const SCALE_CATEGORY_LABELS = {
  autism: { nameAr: 'مقاييس طيف التوحد', icon: 'Psychology', color: '#7C4DFF' },
  motor: { nameAr: 'مقاييس حركية', icon: 'DirectionsRun', color: '#00BCD4' },
  intellectual: { nameAr: 'مقاييس ذهنية', icon: 'Memory', color: '#FF9800' },
  speech: { nameAr: 'مقاييس نطق ولغة', icon: 'RecordVoiceOver', color: '#4CAF50' },
  behavioral: { nameAr: 'مقاييس سلوكية', icon: 'EmojiPeople', color: '#F44336' },
  developmental: { nameAr: 'مقاييس نمائية', icon: 'ChildCare', color: '#E91E63' },
  sensory: { nameAr: 'مقاييس حسية', icon: 'Visibility', color: '#9C27B0' },
  adaptive: { nameAr: 'مقاييس تكيفية', icon: 'AccessibilityNew', color: '#3F51B5' },
  vocational: { nameAr: 'مقاييس مهنية', icon: 'Work', color: '#795548' },
  psychological: { nameAr: 'مقاييس نفسية', icon: 'Spa', color: '#607D8B' },
};

export const PROGRAM_CATEGORY_LABELS = {
  early_intervention: { nameAr: 'التدخل المبكر', icon: 'ChildFriendly', color: '#E91E63' },
  aba_therapy: { nameAr: 'تحليل السلوك التطبيقي', icon: 'Psychology', color: '#7C4DFF' },
  sensory_integration: { nameAr: 'التكامل الحسي', icon: 'Visibility', color: '#9C27B0' },
  speech_language: { nameAr: 'التأهيل النطقي', icon: 'RecordVoiceOver', color: '#4CAF50' },
  physical_therapy: { nameAr: 'العلاج الطبيعي', icon: 'FitnessCenter', color: '#00BCD4' },
  occupational_therapy: { nameAr: 'العلاج الوظيفي', icon: 'Handyman', color: '#FF9800' },
  cognitive_rehab: { nameAr: 'التأهيل المعرفي', icon: 'Memory', color: '#3F51B5' },
  vocational_rehab: { nameAr: 'التأهيل المهني', icon: 'Work', color: '#795548' },
  life_skills: { nameAr: 'المهارات الحياتية', icon: 'Home', color: '#009688' },
  social_skills: { nameAr: 'المهارات الاجتماعية', icon: 'Groups', color: '#FF5722' },
  family_training: { nameAr: 'تدريب الأسرة', icon: 'FamilyRestroom', color: '#8BC34A' },
  community_integration: { nameAr: 'الدمج المجتمعي', icon: 'Public', color: '#2196F3' },
  assistive_technology: { nameAr: 'التقنيات المساعدة', icon: 'Devices', color: '#607D8B' },
  transition_planning: { nameAr: 'التخطيط الانتقالي', icon: 'SwapHoriz', color: '#CDDC39' },
  behavioral_support: { nameAr: 'الدعم السلوكي', icon: 'Support', color: '#F44336' },
};

export const DISABILITY_LABELS = {
  autism: 'اضطراب طيف التوحد',
  physical: 'إعاقة حركية',
  visual: 'إعاقة بصرية',
  hearing: 'إعاقة سمعية',
  intellectual: 'إعاقة ذهنية',
  learning: 'صعوبات تعلم',
  multiple: 'إعاقة متعددة',
  speech: 'إعاقة نطق ولغة',
  behavioral: 'اضطرابات سلوكية',
  developmental: 'تأخر نمائي',
  down_syndrome: 'متلازمة داون',
  cerebral_palsy: 'شلل دماغي',
  adhd: 'فرط الحركة وتشتت الانتباه',
  sensory_processing: 'اضطرابات المعالجة الحسية',
};

export default {
  specializedScalesService,
  rehabProgramTemplatesService,
  SPECIALIZED_SCALES_CATALOG,
  REHAB_PROGRAM_TEMPLATES_CATALOG,
  SCALE_CATEGORY_LABELS,
  PROGRAM_CATEGORY_LABELS,
  DISABILITY_LABELS,
};
