/**
 * ✅ إدارة المهام — Task Management Service
 * AlAwael ERP
 */
import apiClient from 'services/api.client';
import logger from 'utils/logger';

const safe = async (fn, fallback = null) => {
  try {
    return await fn();
  } catch (e) {
    logger.error('taskService:', e);
    return fallback;
  }
};

// ═══════════════════════════════════════════
// Mock Data
// ═══════════════════════════════════════════
export const MOCK_TASKS = [
  {
    _id: 'task-1',
    title: 'مراجعة التقرير الشهري للحضور',
    description: 'مراجعة وتدقيق تقرير الحضور والغياب لشهر مارس',
    status: 'قيد التنفيذ',
    priority: 'عالي',
    category: 'إداري',
    assignedTo: 'أحمد المحمد',
    assignedBy: 'مدير الموارد البشرية',
    team: 'الموارد البشرية',
    dueDate: '2026-03-20',
    startDate: '2026-03-15',
    completedDate: null,
    progress: 60,
    tags: ['تقارير', 'حضور'],
    attachments: 0,
  },
  {
    _id: 'task-2',
    title: 'تحديث بيانات الموظفين الجدد',
    description: 'إضافة بيانات 5 موظفين جدد تم تعيينهم هذا الشهر',
    status: 'مكتمل',
    priority: 'متوسط',
    category: 'إداري',
    assignedTo: 'سارة العلي',
    assignedBy: 'مدير الموارد البشرية',
    team: 'الموارد البشرية',
    dueDate: '2026-03-10',
    startDate: '2026-03-05',
    completedDate: '2026-03-09',
    progress: 100,
    tags: ['موظفين'],
    attachments: 3,
  },
  {
    _id: 'task-3',
    title: 'إعداد ميزانية الربع الثاني',
    description: 'تجهيز ميزانية الربع الثاني مع التقديرات والمخصصات',
    status: 'لم تبدأ',
    priority: 'عاجل',
    category: 'مالي',
    assignedTo: 'إبراهيم الحربي',
    assignedBy: 'المدير المالي',
    team: 'المالية',
    dueDate: '2026-03-25',
    startDate: null,
    completedDate: null,
    progress: 0,
    tags: ['ميزانية', 'مالية'],
    attachments: 0,
  },
  {
    _id: 'task-4',
    title: 'صيانة السيرفرات الدورية',
    description: 'صيانة شهرية للسيرفرات وتحديث أنظمة التشغيل',
    status: 'قيد التنفيذ',
    priority: 'عالي',
    category: 'تقني',
    assignedTo: 'محمد الأحمد',
    assignedBy: 'مدير تقنية المعلومات',
    team: 'تقنية المعلومات',
    dueDate: '2026-03-18',
    startDate: '2026-03-16',
    completedDate: null,
    progress: 40,
    tags: ['تقنية', 'خوادم'],
    attachments: 1,
  },
  {
    _id: 'task-5',
    title: 'تنظيم فعالية يوم المعلم',
    description: 'التنسيق والتحضير لفعالية الاحتفاء بيوم المعلم',
    status: 'لم تبدأ',
    priority: 'متوسط',
    category: 'فعاليات',
    assignedTo: 'نورة القحطاني',
    assignedBy: 'مدير العلاقات العامة',
    team: 'العلاقات العامة',
    dueDate: '2026-04-05',
    startDate: null,
    completedDate: null,
    progress: 0,
    tags: ['فعاليات', 'معلمين'],
    attachments: 0,
  },
  {
    _id: 'task-6',
    title: 'تقرير أداء الطلاب الفصلي',
    description: 'إعداد تقرير شامل عن أداء الطلاب للفصل الدراسي',
    status: 'قيد التنفيذ',
    priority: 'عالي',
    category: 'أكاديمي',
    assignedTo: 'هدى المالكي',
    assignedBy: 'مدير الشؤون الأكاديمية',
    team: 'الشؤون الأكاديمية',
    dueDate: '2026-03-22',
    startDate: '2026-03-12',
    completedDate: null,
    progress: 75,
    tags: ['تقارير', 'طلاب', 'أداء'],
    attachments: 2,
  },
  {
    _id: 'task-7',
    title: 'مراجعة عقود الموردين',
    description: 'مراجعة وتجديد عقود الموردين قبل انتهائها',
    status: 'لم تبدأ',
    priority: 'عالي',
    category: 'مشتريات',
    assignedTo: 'عبدالله القحطاني',
    assignedBy: 'مدير المشتريات',
    team: 'المشتريات',
    dueDate: '2026-03-30',
    startDate: null,
    completedDate: null,
    progress: 0,
    tags: ['عقود', 'موردين'],
    attachments: 0,
  },
  {
    _id: 'task-8',
    title: 'تحديث دليل السياسات والإجراءات',
    description: 'مراجعة وتحديث دليل السياسات ليشمل التعديلات الجديدة',
    status: 'مكتمل',
    priority: 'متوسط',
    category: 'إداري',
    assignedTo: 'خالد المنصور',
    assignedBy: 'المدير العام',
    team: 'الإدارة العليا',
    dueDate: '2026-03-08',
    startDate: '2026-02-25',
    completedDate: '2026-03-07',
    progress: 100,
    tags: ['سياسات', 'وثائق'],
    attachments: 5,
  },
  {
    _id: 'task-9',
    title: 'اختبار النظام المحاسبي الجديد',
    description: 'إجراء اختبارات شاملة للنظام المحاسبي قبل الإطلاق',
    status: 'قيد التنفيذ',
    priority: 'عاجل',
    category: 'تقني',
    assignedTo: 'يوسف الدوسري',
    assignedBy: 'مدير تقنية المعلومات',
    team: 'تقنية المعلومات',
    dueDate: '2026-03-19',
    startDate: '2026-03-14',
    completedDate: null,
    progress: 55,
    tags: ['تقنية', 'محاسبة', 'اختبار'],
    attachments: 2,
  },
  {
    _id: 'task-10',
    title: 'إعداد خطة التدريب السنوية',
    description: 'وضع خطة تدريب شاملة لجميع الموظفين للعام القادم',
    status: 'مكتمل',
    priority: 'متوسط',
    category: 'تدريب',
    assignedTo: 'سلمان العمري',
    assignedBy: 'مدير التطوير',
    team: 'التدريب والتطوير',
    dueDate: '2026-02-28',
    startDate: '2026-02-10',
    completedDate: '2026-02-27',
    progress: 100,
    tags: ['تدريب', 'تخطيط'],
    attachments: 4,
  },
  {
    _id: 'task-11',
    title: 'تنظيف وأرشفة الملفات القديمة',
    description: 'أرشفة الملفات الورقية للسنوات السابقة ورقمنتها',
    status: 'لم تبدأ',
    priority: 'منخفض',
    category: 'إداري',
    assignedTo: 'فاطمة الزهراني',
    assignedBy: 'مدير الإدارة',
    team: 'الشؤون الإدارية',
    dueDate: '2026-04-15',
    startDate: null,
    completedDate: null,
    progress: 0,
    tags: ['أرشفة', 'وثائق'],
    attachments: 0,
  },
  {
    _id: 'task-12',
    title: 'تقييم مخاطر الأمن والسلامة',
    description: 'إعداد تقرير شامل لمخاطر الأمن والسلامة في المباني',
    status: 'قيد التنفيذ',
    priority: 'عاجل',
    category: 'أمن وسلامة',
    assignedTo: 'ناصر الحربي',
    assignedBy: 'مدير الأمن',
    team: 'الأمن والسلامة',
    dueDate: '2026-03-17',
    startDate: '2026-03-10',
    completedDate: null,
    progress: 80,
    tags: ['أمن', 'سلامة', 'مخاطر'],
    attachments: 3,
  },
];

export const MOCK_TASK_DASHBOARD = {
  totalTasks: 12,
  completedTasks: 3,
  inProgressTasks: 5,
  notStartedTasks: 4,
  overdueTasks: 1,
  completionRate: 25,
  avgProgress: 43,
  statusDistribution: [
    { name: 'لم تبدأ', count: 4, color: '#9E9E9E' },
    { name: 'قيد التنفيذ', count: 5, color: '#1E88E5' },
    { name: 'مكتمل', count: 3, color: '#43A047' },
  ],
  priorityDistribution: [
    { name: 'عاجل', count: 3 },
    { name: 'عالي', count: 4 },
    { name: 'متوسط', count: 3 },
    { name: 'منخفض', count: 2 },
  ],
  categoryDistribution: [
    { name: 'إداري', count: 4 },
    { name: 'تقني', count: 3 },
    { name: 'مالي', count: 1 },
    { name: 'أكاديمي', count: 1 },
    { name: 'أخرى', count: 3 },
  ],
  teamPerformance: [
    { team: 'الموارد البشرية', total: 2, completed: 1, rate: 50 },
    { team: 'تقنية المعلومات', total: 2, completed: 0, rate: 0 },
    { team: 'المالية', total: 1, completed: 0, rate: 0 },
    { team: 'الشؤون الأكاديمية', total: 1, completed: 0, rate: 0 },
    { team: 'التدريب والتطوير', total: 1, completed: 1, rate: 100 },
    { team: 'الأمن والسلامة', total: 1, completed: 0, rate: 0 },
  ],
  weeklyTrend: [
    { week: 'الأسبوع 1', created: 3, completed: 1 },
    { week: 'الأسبوع 2', created: 4, completed: 2 },
    { week: 'الأسبوع 3', created: 3, completed: 1 },
    { week: 'الأسبوع 4', created: 2, completed: 2 },
  ],
};

// ═══════════════════════════════════════════
// Services
// ═══════════════════════════════════════════
export const tasksService = {
  getAll: () => safe(() => apiClient.get('/tasks').then(r => r.data), MOCK_TASKS),
  getById: id =>
    safe(
      () => apiClient.get(`/tasks/${id}`).then(r => r.data),
      MOCK_TASKS.find(t => t._id === id)
    ),
  create: data => safe(() => apiClient.post('/tasks', data).then(r => r.data)),
  update: (id, data) => safe(() => apiClient.put(`/tasks/${id}`, data).then(r => r.data)),
  remove: id => safe(() => apiClient.delete(`/tasks/${id}`).then(r => r.data)),
  updateStatus: (id, status) =>
    safe(() => apiClient.patch(`/tasks/${id}/status`, { status }).then(r => r.data)),
  updateProgress: (id, progress) =>
    safe(() => apiClient.patch(`/tasks/${id}/progress`, { progress }).then(r => r.data)),
};

export const taskReportsService = {
  getDashboardStats: () =>
    safe(() => apiClient.get('/tasks/dashboard/stats').then(r => r.data), MOCK_TASK_DASHBOARD),
};
