/**
 * 🏢 إدارة الموردين — Vendor Management Service
 * AlAwael ERP
 */
import apiClient from 'services/api.client';
import logger from 'utils/logger';

const safe = async (fn, fallback = null) => {
  try {
    return await fn();
  } catch (e) {
    logger.error('vendorService:', e);
    return fallback;
  }
};

// ═══════════════════════════════════════════
// Mock Data
// ═══════════════════════════════════════════
export const MOCK_VENDORS = [
  {
    _id: 'v-1',
    name: 'شركة الأمان للتوريدات',
    category: 'مستلزمات مكتبية',
    contactPerson: 'خالد المنصور',
    phone: '0501234567',
    email: 'info@aleman.sa',
    address: 'الرياض - حي العليا',
    rating: 4.5,
    status: 'نشط',
    totalOrders: 45,
    totalAmount: 325000,
    taxNumber: '300123456789',
    contractStart: '2025-01-15',
    contractEnd: '2026-01-15',
    paymentTerms: '30 يوم',
    notes: 'مورد موثوق',
  },
  {
    _id: 'v-2',
    name: 'مؤسسة التقنية المتقدمة',
    category: 'أجهزة تقنية',
    contactPerson: 'أحمد الغامدي',
    phone: '0551234567',
    email: 'tech@advanced.sa',
    address: 'جدة - شارع التحلية',
    rating: 4.2,
    status: 'نشط',
    totalOrders: 28,
    totalAmount: 780000,
    taxNumber: '300234567890',
    contractStart: '2025-03-01',
    contractEnd: '2026-03-01',
    paymentTerms: '45 يوم',
    notes: '',
  },
  {
    _id: 'v-3',
    name: 'شركة النظافة الشاملة',
    category: 'خدمات نظافة',
    contactPerson: 'سعد العتيبي',
    phone: '0561234567',
    email: 'clean@shamelah.sa',
    address: 'الرياض - الملز',
    rating: 3.8,
    status: 'نشط',
    totalOrders: 12,
    totalAmount: 96000,
    taxNumber: '300345678901',
    contractStart: '2025-02-01',
    contractEnd: '2025-08-01',
    paymentTerms: '15 يوم',
    notes: '',
  },
  {
    _id: 'v-4',
    name: 'مؤسسة الصيانة المحترفة',
    category: 'صيانة وتشغيل',
    contactPerson: 'فهد الشمري',
    phone: '0571234567',
    email: 'maint@pro.sa',
    address: 'الدمام - الفيصلية',
    rating: 4.0,
    status: 'نشط',
    totalOrders: 34,
    totalAmount: 210000,
    taxNumber: '300456789012',
    contractStart: '2024-12-01',
    contractEnd: '2025-12-01',
    paymentTerms: '30 يوم',
    notes: '',
  },
  {
    _id: 'v-5',
    name: 'شركة المأكولات الصحية',
    category: 'تغذية وإعاشة',
    contactPerson: 'محمد العمري',
    phone: '0581234567',
    email: 'food@healthy.sa',
    address: 'الرياض - النسيم',
    rating: 4.7,
    status: 'نشط',
    totalOrders: 65,
    totalAmount: 540000,
    taxNumber: '300567890123',
    contractStart: '2025-01-01',
    contractEnd: '2025-12-31',
    paymentTerms: '15 يوم',
    notes: 'التزام ممتاز بالجودة',
  },
  {
    _id: 'v-6',
    name: 'مؤسسة الأثاث التعليمي',
    category: 'أثاث ومفروشات',
    contactPerson: 'عبدالله القحطاني',
    phone: '0591234567',
    email: 'furniture@edu.sa',
    address: 'جدة - حي السلامة',
    rating: 3.5,
    status: 'نشط',
    totalOrders: 8,
    totalAmount: 420000,
    taxNumber: '300678901234',
    contractStart: '2025-06-01',
    contractEnd: '2026-06-01',
    paymentTerms: '60 يوم',
    notes: '',
  },
  {
    _id: 'v-7',
    name: 'شركة الطباعة الحديثة',
    category: 'طباعة ونشر',
    contactPerson: 'يوسف الدوسري',
    phone: '0541234567',
    email: 'print@modern.sa',
    address: 'الرياض - حي الربيع',
    rating: 4.1,
    status: 'نشط',
    totalOrders: 22,
    totalAmount: 85000,
    taxNumber: '300789012345',
    contractStart: '2025-04-01',
    contractEnd: '2026-04-01',
    paymentTerms: '30 يوم',
    notes: '',
  },
  {
    _id: 'v-8',
    name: 'مؤسسة النقل المدرسي',
    category: 'نقل ومواصلات',
    contactPerson: 'ناصر الحربي',
    phone: '0521234567',
    email: 'transport@school.sa',
    address: 'مكة - العزيزية',
    rating: 3.9,
    status: 'نشط',
    totalOrders: 15,
    totalAmount: 360000,
    taxNumber: '300890123456',
    contractStart: '2025-09-01',
    contractEnd: '2026-09-01',
    paymentTerms: '30 يوم',
    notes: '',
  },
  {
    _id: 'v-9',
    name: 'شركة الأجهزة الطبية',
    category: 'معدات طبية',
    contactPerson: 'سلطان المطيري',
    phone: '0531234567',
    email: 'med@devices.sa',
    address: 'الرياض - حي المرسلات',
    rating: 4.6,
    status: 'نشط',
    totalOrders: 17,
    totalAmount: 950000,
    taxNumber: '300901234567',
    contractStart: '2025-02-15',
    contractEnd: '2026-02-15',
    paymentTerms: '45 يوم',
    notes: 'معتمد من هيئة الغذاء والدواء',
  },
  {
    _id: 'v-10',
    name: 'مؤسسة الوسائل التعليمية',
    category: 'وسائل تعليمية',
    contactPerson: 'عمر الزهراني',
    phone: '0511234567',
    email: 'edu@tools.sa',
    address: 'الدمام - حي الجامعيين',
    rating: 4.3,
    status: 'نشط',
    totalOrders: 30,
    totalAmount: 175000,
    taxNumber: '301012345678',
    contractStart: '2025-05-01',
    contractEnd: '2026-05-01',
    paymentTerms: '30 يوم',
    notes: '',
  },
  {
    _id: 'v-11',
    name: 'شركة البرمجيات التربوية',
    category: 'أجهزة تقنية',
    contactPerson: 'إبراهيم العسيري',
    phone: '0509876543',
    email: 'soft@tarbawi.sa',
    address: 'الرياض - حي الياسمين',
    rating: 4.4,
    status: 'معلق',
    totalOrders: 5,
    totalAmount: 290000,
    taxNumber: '301123456789',
    contractStart: '2025-07-01',
    contractEnd: '2026-07-01',
    paymentTerms: '45 يوم',
    notes: 'تحت المراجعة',
  },
  {
    _id: 'v-12',
    name: 'مؤسسة المستلزمات الرياضية',
    category: 'مستلزمات رياضية',
    contactPerson: 'تركي الفيفي',
    phone: '0559876543',
    email: 'sport@supplies.sa',
    address: 'جدة - حي البوادي',
    rating: 3.6,
    status: 'غير نشط',
    totalOrders: 3,
    totalAmount: 42000,
    taxNumber: '301234567890',
    contractStart: '2024-06-01',
    contractEnd: '2025-06-01',
    paymentTerms: '30 يوم',
    notes: 'انتهى العقد',
  },
];

export const MOCK_EVALUATIONS = [
  {
    _id: 'ev-1',
    vendorId: 'v-1',
    vendorName: 'شركة الأمان للتوريدات',
    period: 'الربع الأول 2026',
    qualityScore: 4.5,
    deliveryScore: 4.0,
    priceScore: 4.2,
    communicationScore: 4.8,
    complianceScore: 4.3,
    overallScore: 4.36,
    evaluatedBy: 'إدارة المشتريات',
    date: '2026-03-15',
    comments: 'أداء ممتاز بشكل عام',
  },
  {
    _id: 'ev-2',
    vendorId: 'v-2',
    vendorName: 'مؤسسة التقنية المتقدمة',
    period: 'الربع الأول 2026',
    qualityScore: 4.3,
    deliveryScore: 3.8,
    priceScore: 3.5,
    communicationScore: 4.0,
    complianceScore: 4.5,
    overallScore: 4.02,
    evaluatedBy: 'إدارة تقنية المعلومات',
    date: '2026-03-10',
    comments: 'جودة جيدة لكن الأسعار مرتفعة',
  },
  {
    _id: 'ev-3',
    vendorId: 'v-5',
    vendorName: 'شركة المأكولات الصحية',
    period: 'الربع الأول 2026',
    qualityScore: 4.8,
    deliveryScore: 4.7,
    priceScore: 4.0,
    communicationScore: 4.5,
    complianceScore: 4.9,
    overallScore: 4.58,
    evaluatedBy: 'إدارة التغذية',
    date: '2026-03-20',
    comments: 'التزام ممتاز بمعايير الجودة والسلامة',
  },
  {
    _id: 'ev-4',
    vendorId: 'v-3',
    vendorName: 'شركة النظافة الشاملة',
    period: 'الربع الأول 2026',
    qualityScore: 3.5,
    deliveryScore: 4.0,
    priceScore: 4.5,
    communicationScore: 3.0,
    complianceScore: 3.8,
    overallScore: 3.76,
    evaluatedBy: 'إدارة الصيانة',
    date: '2026-03-05',
    comments: 'يحتاج تحسين في التواصل',
  },
  {
    _id: 'ev-5',
    vendorId: 'v-9',
    vendorName: 'شركة الأجهزة الطبية',
    period: 'الربع الأول 2026',
    qualityScore: 4.9,
    deliveryScore: 4.5,
    priceScore: 3.8,
    communicationScore: 4.6,
    complianceScore: 5.0,
    overallScore: 4.56,
    evaluatedBy: 'إدارة التأهيل',
    date: '2026-03-18',
    comments: 'التزام عالي بمعايير الصحة',
  },
];

export const MOCK_VENDOR_DASHBOARD = {
  totalVendors: 12,
  activeVendors: 10,
  pendingVendors: 1,
  inactiveVendors: 1,
  avgRating: 4.14,
  totalSpend: 4273000,
  categoryDistribution: [
    { name: 'أجهزة تقنية', count: 2, spend: 1070000 },
    { name: 'تغذية وإعاشة', count: 1, spend: 540000 },
    { name: 'معدات طبية', count: 1, spend: 950000 },
    { name: 'صيانة وتشغيل', count: 1, spend: 210000 },
    { name: 'أثاث ومفروشات', count: 1, spend: 420000 },
    { name: 'أخرى', count: 6, spend: 1083000 },
  ],
  monthlySpend: [
    { month: 'يناير', amount: 380000 },
    { month: 'فبراير', amount: 420000 },
    { month: 'مارس', amount: 510000 },
    { month: 'أبريل', amount: 390000 },
    { month: 'مايو', amount: 445000 },
    { month: 'يونيو', amount: 480000 },
  ],
  topVendors: [
    { name: 'شركة الأجهزة الطبية', rating: 4.6, spend: 950000 },
    { name: 'مؤسسة التقنية المتقدمة', rating: 4.2, spend: 780000 },
    { name: 'شركة المأكولات الصحية', rating: 4.7, spend: 540000 },
    { name: 'مؤسسة الأثاث التعليمي', rating: 3.5, spend: 420000 },
    { name: 'مؤسسة النقل المدرسي', rating: 3.9, spend: 360000 },
  ],
  contractsExpiringSoon: 3,
};

// ═══════════════════════════════════════════
// Vendor Service
// ═══════════════════════════════════════════
export const vendorsService = {
  getAll: () => safe(() => apiClient.get('/vendors').then(r => r.data), MOCK_VENDORS),
  getById: id =>
    safe(
      () => apiClient.get(`/vendors/${id}`).then(r => r.data),
      MOCK_VENDORS.find(v => v._id === id)
    ),
  create: data => safe(() => apiClient.post('/vendors', data).then(r => r.data)),
  update: (id, data) => safe(() => apiClient.put(`/vendors/${id}`, data).then(r => r.data)),
  remove: id => safe(() => apiClient.delete(`/vendors/${id}`).then(r => r.data)),
};

export const evaluationsService = {
  getAll: () =>
    safe(() => apiClient.get('/vendor-evaluations').then(r => r.data), MOCK_EVALUATIONS),
  create: data => safe(() => apiClient.post('/vendor-evaluations', data).then(r => r.data)),
  getByVendor: vendorId =>
    safe(
      () => apiClient.get(`/vendor-evaluations/vendor/${vendorId}`).then(r => r.data),
      MOCK_EVALUATIONS.filter(e => e.vendorId === vendorId)
    ),
};

export const vendorReportsService = {
  getDashboardStats: () =>
    safe(() => apiClient.get('/vendors/dashboard/stats').then(r => r.data), MOCK_VENDOR_DASHBOARD),
};
