

import SupportIcon from '@mui/icons-material/Support';
export const statusColors = {
  open: 'warning',
  'in-progress': 'info',
  closed: 'default',
  resolved: 'success',
  compliant: 'success',
  'non-compliant': 'error',
  pending: 'warning',
  active: 'success',
  completed: 'info',
  high: 'error',
  medium: 'warning',
  low: 'success',
};

export const tabs = [
  { label: 'معايير الجودة', icon: <QualityIcon />, key: 'quality' },
  { label: 'التدقيق الداخلي', icon: <AuditIcon />, key: 'audits' },
  { label: 'إدارة الحالات', icon: <CaseIcon />, key: 'cases' },
  { label: 'تذاكر الدعم', icon: <SupportIcon />, key: 'tickets' },
];

export const colMap = {
  quality: {
    cols: ['title', 'category', 'standard', 'complianceRate', 'status', 'nextReview'],
    headers: ['المعيار', 'الفئة', 'المرجع', 'نسبة الامتثال', 'الحالة', 'المراجعة القادمة'],
  },
  audits: {
    cols: ['title', 'type', 'auditor', 'department', 'status', 'startDate', 'findings'],
    headers: ['العنوان', 'النوع', 'المدقق', 'القسم', 'الحالة', 'تاريخ البداية', 'الملاحظات'],
  },
  cases: {
    cols: ['caseNumber', 'title', 'type', 'priority', 'status', 'assignedTo', 'createdDate'],
    headers: ['رقم الحالة', 'العنوان', 'النوع', 'الأولوية', 'الحالة', 'المسؤول', 'تاريخ الإنشاء'],
  },
  tickets: {
    cols: [
      'ticketNumber',
      'subject',
      'category',
      'priority',
      'status',
      'assignedTo',
      'createdDate',
    ],
    headers: ['رقم التذكرة', 'الموضوع', 'الفئة', 'الأولوية', 'الحالة', 'المسؤول', 'التاريخ'],
  },
};

export const fieldSets = {
  quality: [
    { key: 'title', label: 'المعيار' },
    { key: 'category', label: 'الفئة' },
    { key: 'standard', label: 'المرجع' },
    { key: 'complianceRate', label: 'نسبة الامتثال', type: 'number' },
    { key: 'nextReview', label: 'المراجعة القادمة', type: 'date' },
  ],
  audits: [
    { key: 'title', label: 'العنوان' },
    { key: 'type', label: 'النوع' },
    { key: 'auditor', label: 'المدقق' },
    { key: 'department', label: 'القسم' },
    { key: 'startDate', label: 'تاريخ البداية', type: 'date' },
    { key: 'endDate', label: 'تاريخ النهاية', type: 'date' },
  ],
  cases: [
    { key: 'title', label: 'العنوان' },
    { key: 'type', label: 'النوع' },
    { key: 'assignedTo', label: 'المسؤول' },
    { key: 'description', label: 'الوصف', multiline: true },
  ],
  tickets: [
    { key: 'subject', label: 'الموضوع' },
    { key: 'category', label: 'الفئة' },
    { key: 'requester', label: 'مقدم الطلب' },
    { key: 'assignedTo', label: 'المسؤول' },
  ],
};

export const demoData = {
  quality: [
    {
      _id: '1',
      title: 'معيار جودة الخدمات التأهيلية',
      category: 'خدمات',
      standard: 'ISO 9001',
      complianceRate: 95,
      status: 'compliant',
      lastReview: '2026-02-15',
      nextReview: '2026-08-15',
    },
    {
      _id: '2',
      title: 'معيار السلامة المهنية',
      category: 'سلامة',
      standard: 'OHSAS 18001',
      complianceRate: 88,
      status: 'compliant',
      lastReview: '2026-01-10',
      nextReview: '2026-07-10',
    },
    {
      _id: '3',
      title: 'معيار حماية البيانات',
      category: 'تقنية',
      standard: 'ISO 27001',
      complianceRate: 72,
      status: 'non-compliant',
      lastReview: '2026-02-01',
      nextReview: '2026-05-01',
    },
  ],
  audits: [
    {
      _id: '1',
      title: 'تدقيق مالي ربع سنوي',
      type: 'مالي',
      auditor: 'شركة المراجعة المحدودة',
      department: 'المالية',
      status: 'completed',
      startDate: '2026-02-01',
      endDate: '2026-02-15',
      findings: 3,
    },
    {
      _id: '2',
      title: 'تدقيق إجراءات السلامة',
      type: 'سلامة',
      auditor: 'فريق التدقيق الداخلي',
      department: 'العمليات',
      status: 'in-progress',
      startDate: '2026-03-01',
      endDate: '2026-03-20',
      findings: 0,
    },
    {
      _id: '3',
      title: 'مراجعة الامتثال للأنظمة',
      type: 'امتثال',
      auditor: 'المستشار القانوني',
      department: 'القانونية',
      status: 'pending',
      startDate: '2026-04-01',
      endDate: '2026-04-15',
      findings: 0,
    },
  ],
  cases: [
    {
      _id: '1',
      title: 'شكوى خدمة مقدم رعاية',
      caseNumber: 'CASE-2026-001',
      type: 'شكوى',
      priority: 'high',
      status: 'open',
      assignedTo: 'محمد أحمد',
      createdDate: '2026-03-05',
      description: 'شكوى بخصوص جودة الخدمة المقدمة',
    },
    {
      _id: '2',
      title: 'حادثة سلامة - مبنى 2',
      caseNumber: 'CASE-2026-002',
      type: 'حادثة',
      priority: 'medium',
      status: 'in-progress',
      assignedTo: 'خالد سعود',
      createdDate: '2026-03-03',
      description: 'بلاغ عن مشكلة في نظام الإنذار',
    },
    {
      _id: '3',
      title: 'طلب تحسين إجراء',
      caseNumber: 'CASE-2026-003',
      type: 'تحسين',
      priority: 'low',
      status: 'resolved',
      assignedTo: 'نورة علي',
      createdDate: '2026-02-20',
      description: 'اقتراح تحسين إجراءات الاستقبال',
    },
  ],
  tickets: [
    {
      _id: '1',
      subject: 'مشكلة في نظام الحضور',
      ticketNumber: 'TKT-001',
      category: 'تقنية',
      priority: 'high',
      status: 'open',
      requester: 'فهد محمد',
      createdDate: '2026-03-08',
      assignedTo: 'فريق IT',
    },
    {
      _id: '2',
      subject: 'طلب صيانة مكيف',
      ticketNumber: 'TKT-002',
      category: 'صيانة',
      priority: 'medium',
      status: 'in-progress',
      requester: 'سارة أحمد',
      createdDate: '2026-03-07',
      assignedTo: 'فريق الصيانة',
    },
    {
      _id: '3',
      subject: 'استفسار عن الإجازات',
      ticketNumber: 'TKT-003',
      category: 'موارد بشرية',
      priority: 'low',
      status: 'resolved',
      requester: 'عبدالله خالد',
      createdDate: '2026-03-06',
      assignedTo: 'قسم HR',
    },
  ],
};
