/**
 * KPI Seed Data — مؤشرات أداء رئيسية افتراضية
 *
 * يوفر مجموعة من مؤشرات KPI المعيارية للمنصة
 */

const standardKPIs = [
  {
    code: 'KPI-CLI-001',
    name: 'Goal Achievement Rate',
    nameAr: 'معدل تحقيق الأهداف العلاجية',
    category: 'clinical_outcomes',
    domain: 'goals',
    unit: '%',
    dataType: 'percentage',
    direction: 'higher_is_better',
    frequency: 'monthly',
    target: { value: 75, warningThreshold: 60, criticalThreshold: 50, stretch: 90 },
    description: 'Percentage of therapeutic goals achieved or exceeded within the episode',
  },
  {
    code: 'KPI-CLI-002',
    name: 'Assessment Completion Rate',
    nameAr: 'معدل إكمال التقييمات',
    category: 'clinical_outcomes',
    domain: 'assessments',
    unit: '%',
    dataType: 'percentage',
    direction: 'higher_is_better',
    frequency: 'monthly',
    target: { value: 90, warningThreshold: 80, criticalThreshold: 70 },
    description: 'Percentage of scheduled assessments completed on time',
  },
  {
    code: 'KPI-OPS-001',
    name: 'Session Utilization Rate',
    nameAr: 'معدل استخدام الجلسات',
    category: 'operational_efficiency',
    domain: 'sessions',
    unit: '%',
    dataType: 'percentage',
    direction: 'higher_is_better',
    frequency: 'weekly',
    target: { value: 85, warningThreshold: 70, criticalThreshold: 60, stretch: 95 },
    description: 'Ratio of completed sessions to scheduled sessions',
  },
  {
    code: 'KPI-OPS-002',
    name: 'Average Episode Duration (days)',
    nameAr: 'متوسط مدة الحلقة العلاجية (أيام)',
    category: 'operational_efficiency',
    domain: 'episodes',
    unit: 'days',
    dataType: 'duration',
    direction: 'lower_is_better',
    frequency: 'monthly',
    target: { value: 120, warningThreshold: 150, criticalThreshold: 180 },
    description: 'Average number of days from episode start to discharge',
  },
  {
    code: 'KPI-QUA-001',
    name: 'Documentation Compliance',
    nameAr: 'الامتثال في التوثيق',
    category: 'quality_safety',
    domain: 'quality',
    unit: '%',
    dataType: 'percentage',
    direction: 'higher_is_better',
    frequency: 'monthly',
    target: { value: 95, warningThreshold: 85, criticalThreshold: 75 },
    description: 'Percentage of sessions with complete documentation within 48 hours',
  },
  {
    code: 'KPI-QUA-002',
    name: 'Incident Rate per 100 Beneficiaries',
    nameAr: 'معدل الحوادث لكل 100 مستفيد',
    category: 'quality_safety',
    domain: 'behavior',
    unit: 'incidents',
    dataType: 'ratio',
    direction: 'lower_is_better',
    frequency: 'monthly',
    target: { value: 5, warningThreshold: 10, criticalThreshold: 15 },
    description: 'Number of severe behavior incidents per 100 active beneficiaries',
  },
  {
    code: 'KPI-SAT-001',
    name: 'Family Satisfaction Score',
    nameAr: 'درجة رضا العائلة',
    category: 'patient_satisfaction',
    domain: 'family',
    unit: '/5',
    dataType: 'number',
    direction: 'higher_is_better',
    frequency: 'quarterly',
    target: { value: 4.0, warningThreshold: 3.5, criticalThreshold: 3.0, stretch: 4.5 },
    description: 'Average family satisfaction rating on a 5-point scale',
  },
  {
    code: 'KPI-SAT-002',
    name: 'Tele-Rehab Satisfaction',
    nameAr: 'رضا جلسات التأهيل عن بُعد',
    category: 'patient_satisfaction',
    domain: 'tele-rehab',
    unit: '/5',
    dataType: 'number',
    direction: 'higher_is_better',
    frequency: 'monthly',
    target: { value: 4.0, warningThreshold: 3.5, criticalThreshold: 3.0 },
    description: 'Average beneficiary satisfaction rating for tele-rehabilitation sessions',
  },
  {
    code: 'KPI-WRK-001',
    name: 'Therapist Caseload Utilization',
    nameAr: 'استخدام حالات الأخصائي',
    category: 'workforce',
    domain: 'core',
    unit: '%',
    dataType: 'percentage',
    direction: 'higher_is_better',
    frequency: 'weekly',
    target: { value: 80, warningThreshold: 60, criticalThreshold: 50, stretch: 90 },
    description: 'Average caseload as percentage of maximum capacity per therapist',
  },
  {
    code: 'KPI-WRK-002',
    name: 'Trainee Completion Rate',
    nameAr: 'معدل إكمال التدريب',
    category: 'workforce',
    domain: 'field-training',
    unit: '%',
    dataType: 'percentage',
    direction: 'higher_is_better',
    frequency: 'quarterly',
    target: { value: 85, warningThreshold: 70, criticalThreshold: 60 },
    description: 'Percentage of trainees completing their program on time',
  },
  {
    code: 'KPI-RES-001',
    name: 'Active Research Studies',
    nameAr: 'الدراسات البحثية النشطة',
    category: 'research',
    domain: 'research',
    unit: 'studies',
    dataType: 'count',
    direction: 'higher_is_better',
    frequency: 'quarterly',
    target: { value: 5, warningThreshold: 2, criticalThreshold: 1 },
    description: 'Number of currently active clinical research studies',
  },
  {
    code: 'KPI-ACC-001',
    name: 'Wait Time to First Assessment (days)',
    nameAr: 'وقت الانتظار لأول تقييم (أيام)',
    category: 'access',
    domain: 'episodes',
    unit: 'days',
    dataType: 'duration',
    direction: 'lower_is_better',
    frequency: 'monthly',
    target: { value: 7, warningThreshold: 14, criticalThreshold: 21 },
    description: 'Average days from episode registration to first clinical assessment',
  },
  {
    code: 'KPI-TEC-001',
    name: 'Tele-Rehab Connection Quality',
    nameAr: 'جودة اتصال التأهيل عن بُعد',
    category: 'technology',
    domain: 'tele-rehab',
    unit: '%',
    dataType: 'percentage',
    direction: 'higher_is_better',
    frequency: 'weekly',
    target: { value: 90, warningThreshold: 75, criticalThreshold: 60 },
    description: 'Average connection quality score for tele-rehabilitation sessions',
  },
  {
    code: 'KPI-TEC-002',
    name: 'AR/VR Session Completion Rate',
    nameAr: 'معدل إكمال جلسات الواقع الافتراضي',
    category: 'technology',
    domain: 'ar-vr',
    unit: '%',
    dataType: 'percentage',
    direction: 'higher_is_better',
    frequency: 'monthly',
    target: { value: 85, warningThreshold: 70, criticalThreshold: 55 },
    description: 'Percentage of AR/VR sessions completed without abort',
  },
  {
    code: 'KPI-CMP-001',
    name: 'Corrective Action Closure Rate',
    nameAr: 'معدل إغلاق الإجراءات التصحيحية',
    category: 'compliance',
    domain: 'quality',
    unit: '%',
    dataType: 'percentage',
    direction: 'higher_is_better',
    frequency: 'monthly',
    target: { value: 90, warningThreshold: 75, criticalThreshold: 60 },
    description: 'Percentage of corrective actions closed within due date',
  },
];

module.exports = { standardKPIs };
