'use strict';

/**
 * assessment-goal-provenance-behavioral-wave1151.test.js — gap #3 behavioral.
 *
 * Proves the additive `TherapeuticGoal.measureApplicationId` provenance link
 * round-trips against an in-memory MongoDB, that the backward query ("which
 * goals did this assessment generate?") returns the right goals, and that the
 * change is ADDITIVE (a goal with no provenance still saves). Paired with the
 * static guard `assessment-goal-provenance-wave1151.test.js`.
 *
 * Per docs/blueprint/43-beneficiary-journey-operating-system.md §III gap #3.
 *
 * Run: cd backend && npx jest --config=jest.config.js \
 *        __tests__/assessment-goal-provenance-behavioral-wave1151.test.js --runInBand
 */

jest.unmock('mongoose');
jest.setTimeout(30000);

const mongoose = require('mongoose');
const fs = require('fs');
const path = require('path');
const { MongoMemoryServer } = require('mongodb-memory-server');

let mongod;
let TherapeuticGoal;

beforeAll(async () => {
  const URI_FILE = path.join(__dirname, '..', '.test-mongo-uri');
  let uri;
  if (fs.existsSync(URI_FILE)) {
    uri = fs.readFileSync(URI_FILE, 'utf-8').trim();
  } else {
    mongod = await MongoMemoryServer.create({
      instance: { dbName: 'w1151-assessment-goal-behavioral-test' },
    });
    uri = mongod.getUri();
  }
  await mongoose.connect(uri);
  TherapeuticGoal = require('../domains/goals/models/TherapeuticGoal').TherapeuticGoal;
  await TherapeuticGoal.init();
});

afterAll(async () => {
  await mongoose.disconnect().catch(() => null);
  if (mongod) await mongod.stop().catch(() => null);
});

beforeEach(async () => {
  await TherapeuticGoal.deleteMany({});
});

const oid = () => new mongoose.Types.ObjectId();

function baseGoal(overrides = {}) {
  return {
    beneficiaryId: oid(),
    episodeId: oid(),
    title: 'Independent transfers',
    type: 'short_term',
    target: { value: 80 },
    startDate: new Date('2026-02-01'),
    ...overrides,
  };
}

describe('gap #3 (W1151) — assessment→goal provenance behavioral', () => {
  test('a goal derived from an assessment records measureApplicationId and round-trips', async () => {
    const applicationId = oid();
    const g = await TherapeuticGoal.create(
      baseGoal({ measureApplicationId: applicationId, tags: ['assessment-derived'] })
    );
    const fresh = await TherapeuticGoal.findById(g._id).lean();
    expect(String(fresh.measureApplicationId)).toBe(String(applicationId));
  });

  test('backward query: find all goals generated by a given assessment administration', async () => {
    const appA = oid();
    const appB = oid();
    await TherapeuticGoal.create(baseGoal({ measureApplicationId: appA }));
    await TherapeuticGoal.create(baseGoal({ measureApplicationId: appA }));
    await TherapeuticGoal.create(baseGoal({ measureApplicationId: appB }));

    const goalsFromA = await TherapeuticGoal.find({ measureApplicationId: appA }).lean();
    expect(goalsFromA).toHaveLength(2);

    const goalsFromB = await TherapeuticGoal.find({ measureApplicationId: appB }).lean();
    expect(goalsFromB).toHaveLength(1);
  });

  test('additive — a goal with NO provenance still saves (no breaking change)', async () => {
    const g = await TherapeuticGoal.create(baseGoal());
    const fresh = await TherapeuticGoal.findById(g._id).lean();
    expect(fresh.measureApplicationId).toBeUndefined();
  });

  test('the measureApplicationId index is registered on the collection', async () => {
    const indexes = await TherapeuticGoal.collection.indexes();
    const hasIndex = indexes.some(ix => ix.key && ix.key.measureApplicationId === 1);
    expect(hasIndex).toBe(true);
  });
});
