'use strict';

/**
 * postrehab-case-core-linkage-wave987.test.js — W987.
 *
 * Wires post-rehabilitation follow-up cases onto the unified-core timeline: a
 * completed case (the beneficiary was successfully followed through — success)
 * and a lost-to-follow-up case (the beneficiary disengaged — a clinically
 * important warning). Producer: native PostRehabCase post-save hook (status flip
 * to COMPLETED / LOST_TO_FOLLOW_UP). RUNTIME end-to-end against a real in-memory
 * Mongo + the real integration bus + real subscribers → CareTimeline rows.
 *
 * NOTE: the model's beneficiary ref field is `beneficiary` (not `beneficiaryId`).
 */

jest.unmock('mongoose');
jest.setTimeout(90000);

const mongoose = require('mongoose');
const { MongoMemoryServer } = require('mongodb-memory-server');

let mongod;
let PostRehabCase, CareTimeline;

async function waitForTimeline(query, { timeout = 4000, interval = 25 } = {}) {
  const start = Date.now();
  // eslint-disable-next-line no-constant-condition
  while (true) {
    const row = await CareTimeline.findOne(query);
    if (row) return row;
    if (Date.now() - start > timeout) return null;
    await new Promise(r => setTimeout(r, interval));
  }
}

beforeAll(async () => {
  mongod = await MongoMemoryServer.create({ instance: { dbName: 'w987-postrehab' } });
  await mongoose.connect(mongod.getUri());
  PostRehabCase = require('../models/post-rehab/PostRehabCase.model');
  ({ CareTimeline } = require('../domains/timeline/models/CareTimeline'));
  require('../models/Beneficiary');
  const { integrationBus } = require('../integration/systemIntegrationBus');
  const { initializeDDDSubscribers } = require('../integration/dddCrossModuleSubscribers');
  initializeDDDSubscribers(integrationBus);
});

afterAll(async () => {
  await mongoose.disconnect().catch(() => null);
  if (mongod) await mongod.stop().catch(() => null);
});

afterEach(async () => {
  await Promise.all([PostRehabCase.deleteMany({}), CareTimeline.deleteMany({})]);
});

// Create a fresh ACTIVE case (required: beneficiary + dischargeDate; caseNumber
// auto-generated by the existing pre-save hook).
function newActiveCase(extra = {}) {
  return PostRehabCase.create({
    beneficiary: new mongoose.Types.ObjectId(),
    dischargeDate: new Date(),
    status: 'ACTIVE',
    ...extra,
  });
}

describe('W987 — post-rehab follow-up cases reach the unified-core timeline', () => {
  it('an active case produces no timeline row until it reaches a terminal status', async () => {
    const c = await newActiveCase();
    await new Promise(r => setTimeout(r, 150));
    expect(await CareTimeline.countDocuments({ beneficiaryId: c.beneficiary })).toBe(0);

    const loaded = await PostRehabCase.findById(c._id);
    loaded.status = 'COMPLETED';
    await loaded.save();

    const tl = await waitForTimeline({
      beneficiaryId: c.beneficiary,
      eventType: 'followup_completed',
    });
    expect(tl).toBeTruthy();
    expect(tl.category).toBe('clinical');
    expect(tl.severity).toBe('success');
  });

  it('lost-to-follow-up lands a WARNING followup_lost row', async () => {
    const c = await newActiveCase();
    const loaded = await PostRehabCase.findById(c._id);
    loaded.status = 'LOST_TO_FOLLOW_UP';
    await loaded.save();
    const tl = await waitForTimeline({
      beneficiaryId: c.beneficiary,
      eventType: 'followup_lost',
    });
    expect(tl).toBeTruthy();
    expect(tl.severity).toBe('warning');
  });

  it('a non-terminal status change (ON_HOLD) produces no row', async () => {
    const c = await newActiveCase();
    const loaded = await PostRehabCase.findById(c._id);
    loaded.status = 'ON_HOLD';
    await loaded.save();
    await new Promise(r => setTimeout(r, 200));
    expect(await CareTimeline.countDocuments({ beneficiaryId: c.beneficiary })).toBe(0);
  });
});
