/**
 * Mobile App Mock Data
 * بيانات تجريبية لتطبيق الجوال
 */

export const mockUser = {
  id: 'u1',
  name: 'أحمد المطيري',
  role: 'أخصائي علاج وظيفي',
  avatar: '',
  branch: 'فرع الرياض الرئيسي',
  unreadNotifications: 5,
};

export const mockStats = {
  todaySessions: 8,
  pendingTasks: 3,
  unreadNotifications: 5,
  completedSessionsThisWeek: 24,
};

export const mockTodaySessions = [
  {
    id: 's1',
    beneficiaryName: 'محمد العلي',
    beneficiaryId: 'B-1042',
    time: '09:00',
    duration: 45,
    type: 'علاج وظيفي',
    status: 'completed',
    room: 'غرفة 3A',
    goals: ['تنظيم الحركة', 'التنسيق البصري'],
    notes: '',
  },
  {
    id: 's2',
    beneficiaryName: 'سارة الخالد',
    beneficiaryId: 'B-1089',
    time: '10:00',
    duration: 60,
    type: 'علاج نطقي',
    status: 'in-progress',
    room: 'غرفة 2B',
    goals: ['نطق الحروف', 'بناء الجمل'],
    notes: '',
  },
  {
    id: 's3',
    beneficiaryName: 'عبدالله الشمري',
    beneficiaryId: 'B-1123',
    time: '11:30',
    duration: 45,
    type: 'علاج سلوكي ABA',
    status: 'upcoming',
    room: 'غرفة 4C',
    goals: ['المهارات الاجتماعية', 'تقليل السلوكيات التكرارية'],
    notes: '',
  },
  {
    id: 's4',
    beneficiaryName: 'نورة القحطاني',
    beneficiaryId: 'B-1156',
    time: '13:00',
    duration: 60,
    type: 'علاج فيزيائي',
    status: 'upcoming',
    room: 'صالة التأهيل',
    goals: ['تقوية العضلات', 'المشي المستقل'],
    notes: '',
  },
  {
    id: 's5',
    beneficiaryName: 'فهد العنزي',
    beneficiaryId: 'B-1198',
    time: '14:30',
    duration: 45,
    type: 'علاج وظيفي',
    status: 'upcoming',
    room: 'غرفة 3A',
    goals: ['المهارات الحياتية اليومية', 'الإدراك البصري'],
    notes: '',
  },
  {
    id: 's6',
    beneficiaryName: 'ليلى الحربي',
    beneficiaryId: 'B-1201',
    time: '15:30',
    duration: 60,
    type: 'جلسة جماعية',
    status: 'upcoming',
    room: 'قاعة الأنشطة',
    goals: ['التفاعل الاجتماعي', 'اللعب التعاوني'],
    notes: '',
  },
];

export const mockBeneficiaries = [
  {
    id: 'B-1042',
    name: 'محمد العلي',
    age: 7,
    diagnosis: 'اضطراب طيف التوحد',
    icfScore: 68,
    lastSession: '2025-10-03',
    nextSession: '2025-10-04',
    avatar: '',
    status: 'active',
    carePlan: 'خطة التأهيل الشاملة Q4-2025',
    primaryTherapist: 'أحمد المطيري',
  },
  {
    id: 'B-1089',
    name: 'سارة الخالد',
    age: 5,
    diagnosis: 'تأخر النمو',
    icfScore: 72,
    lastSession: '2025-10-04',
    nextSession: '2025-10-05',
    avatar: '',
    status: 'active',
    carePlan: 'خطة التدخل المبكر 2025',
    primaryTherapist: 'نورة السبيعي',
  },
  {
    id: 'B-1123',
    name: 'عبدالله الشمري',
    age: 9,
    diagnosis: 'متلازمة داون',
    icfScore: 55,
    lastSession: '2025-10-03',
    nextSession: '2025-10-04',
    avatar: '',
    status: 'active',
    carePlan: 'خطة التأهيل الوظيفي',
    primaryTherapist: 'أحمد المطيري',
  },
  {
    id: 'B-1156',
    name: 'نورة القحطاني',
    age: 6,
    diagnosis: 'شلل دماغي',
    icfScore: 45,
    lastSession: '2025-10-02',
    nextSession: '2025-10-04',
    avatar: '',
    status: 'active',
    carePlan: 'خطة التأهيل الفيزيائي',
    primaryTherapist: 'خالد الزهراني',
  },
  {
    id: 'B-1198',
    name: 'فهد العنزي',
    age: 8,
    diagnosis: 'اضطراب طيف التوحد',
    icfScore: 61,
    lastSession: '2025-10-03',
    nextSession: '2025-10-04',
    avatar: '',
    status: 'active',
    carePlan: 'خطة التأهيل السلوكي',
    primaryTherapist: 'أحمد المطيري',
  },
  {
    id: 'B-1201',
    name: 'ليلى الحربي',
    age: 4,
    diagnosis: 'تأخر النمو الحركي',
    icfScore: 78,
    lastSession: '2025-10-04',
    nextSession: '2025-10-07',
    avatar: '',
    status: 'active',
    carePlan: 'خطة التدخل المبكر الحركي',
    primaryTherapist: 'منى القرني',
  },
];

export const mockAlerts = [
  {
    id: 'a1',
    title: 'تأخر وصول المستفيد',
    message: 'المستفيد محمد العلي (B-1042) لم يصل بعد — الجلسة الساعة 09:00',
    type: 'warning',
    time: '09:05',
    read: false,
    action: 'contact-parent',
  },
  {
    id: 'a2',
    title: 'تقرير تقييم جديد',
    message: 'تم إكمال تقييم ICF للمستفيدة سارة الخالد',
    type: 'success',
    time: '08:30',
    read: false,
    action: 'view-report',
  },
  {
    id: 'a3',
    title: 'موعد تجديد خطة الرعاية',
    message: 'خطة رعاية المستفيد عبدالله الشمري تنتهي بعد 5 أيام',
    type: 'info',
    time: '08:00',
    read: true,
    action: 'view-care-plan',
  },
  {
    id: 'a4',
    title: 'طلب إجازة معلق',
    message: 'طلب إجازة من الأخصائية نورة السبيعي بانتظار الموافقة',
    type: 'info',
    time: '07:45',
    read: true,
    action: 'approve-leave',
  },
  {
    id: 'a5',
    title: 'تنبيه سلوكي',
    message: 'زيادة في السلوكيات التكرارية لدى المستفيد فهد العنزي خلال الجلسة الأخيرة',
    type: 'error',
    time: '07:30',
    read: false,
    action: 'view-behavior',
  },
];

export const mockPendingTasks = [
  {
    id: 't1',
    title: 'كتابة ملاحظات جلسة',
    sessionId: 's1',
    beneficiary: 'محمد العلي',
    due: '10:00',
    completed: false,
  },
  {
    id: 't2',
    title: 'تحديث خطة الرعاية',
    beneficiary: 'عبدالله الشمري',
    due: '16:00',
    completed: false,
  },
  {
    id: 't3',
    title: 'مراجعة تقرير ICF',
    beneficiary: 'سارة الخالد',
    due: '12:00',
    completed: false,
  },
];

export const mockWeeklyProgress = [
  { day: 'السبت', completed: 6, planned: 8 },
  { day: 'الأحد', completed: 7, planned: 8 },
  { day: 'الإثنين', completed: 5, planned: 7 },
  { day: 'الثلاثاء', completed: 8, planned: 8 },
  { day: 'الأربعاء', completed: 4, planned: 6 },
  { day: 'الخميس', completed: 3, planned: 5 },
];

export const mockICFHistory = [
  { date: '2025-01-15', score: 52 },
  { date: '2025-04-15', score: 58 },
  { date: '2025-07-15', score: 64 },
  { date: '2025-10-01', score: 68 },
];
