/**
 * Navigation configuration — icon imports + nav tree builder.
 * Pure data / config — no React state or rendering.
 *
 * ═══════════════════════════════════════════════════════════
 *  Organized into 9 logical sections with dividers:
 *  ① الرئيسية          — Dashboard & Monitoring
 *  ② الخدمات الأساسية  — Beneficiaries, Rehab, Education, Scheduling
 *  ③ الموارد البشرية   — HR, Recruitment, Training, Performance
 *  ④ المالية والمحاسبة — Finance (5 sub-groups)
 *  ⑤ العمليات والإمداد — Operations, Fleet, Logistics, Quality & Safety
 *  ⑥ التواصل والمعلومات — Comms, Docs, Media, Signatures, Forms
 *  ⑦ التحليلات والذكاء — Analytics, CRM, KPI, BI
 *  ⑧ إدارة الأعمال    — Administration, Workflow, Tasks, Business
 *  ⑨ البوابات          — Student, Therapist, Parent, Employee
 *  ⑩ الإدارة والنظام   — Gov Integration, Admin Portal, System, Security
 * ═══════════════════════════════════════════════════════════
 */
import {
  Dashboard as DashboardIcon,
  AutoAwesome as PremiumIcon,
  People as PeopleIcon,
  School as SchoolIcon,
  Settings as SettingsIcon,
  AccountBalance as FinanceIcon,
  LocalHospital as RehabIcon,
  CalendarMonth as ScheduleIcon,
  Message as MessageIcon,
  Description as DocumentIcon,
  Security as SecurityIcon,
  Analytics as AnalyticsIcon,
  AdminPanelSettings as AdminIcon,
  FolderSpecial as ProjectIcon,
  SupervisorAccount as TherapistIcon,
  FamilyRestroom as ParentIcon,
  MonitorHeart as MonitorIcon,
  Gavel as ContractsIcon,
  NotificationsActive as SmartNotifIcon,
  ConfirmationNumber as TicketIcon,
  EventNote as MeetingIcon,
  Badge as VisitorIcon,
  DriveFileRenameOutline as SignatureIcon,
  Verified as StampIcon,
  MenuBook as KnowledgeIcon,
  AccountBalanceWallet as BudgetIcon,
  Person as EmployeeIcon,
  Speed as KPIChartIcon,
  Handshake as CRMIcon,
  ModelTraining as TrainingIcon,
  WorkOutlined as RecruitmentIcon,
  Build as MaintenanceIcon,
  Store as VendorIcon,
  VolunteerActivism as DonationsIcon,
  Feedback as ComplaintsIcon,
  Assignment as TaskIcon,
  Accessibility as SpecializedRehabIcon,
  Business as AdministrationIcon,
  AccountTree as AccountTreeIcon,
  ListAlt as FormTemplateIcon,
  PhotoLibrary as MediaLibraryIcon,
  ContactMail as AdminCommIcon,
  Campaign as CampaignIcon,
  SwapHoriz as SwapHorizIcon,
  AttachMoney as WageProtectionIcon,
  Work as EmploymentIcon,
  VerifiedUser as CBAHIIcon,
  MedicalServices as PreAuthIcon,
  SentimentSatisfiedAlt as SurveyIcon,
  Policy as GovernmentIcon,
  School as NoorIcon,
  Security as GosiIcon,
  Business as QiwaIcon,
  ChildCare as EarlyInterventionIcon,
  FollowTheSigns as PostRehabIcon,
  SupervisedUserCircle as GuardianIcon,
  // ─── Phase: 14 Additional Systems ───
  MedicalInformation as MedicalFilesIcon,
  Psychology as MHPSSIcon,
  Home as IndependentLivingIcon,
  Science as ResearchIcon,
  ShoppingCart as ECommerceIcon,
  Article as CMSIcon,
  HourglassBottom as WaitlistIcon,
  VpnKey as SSOIcon,
  // ─── Phase 10: Missing Sidebar Systems ───
  Warehouse as WarehouseIcon,
  HealthAndSafety as HSEIcon,
  RecordVoiceOver as PRIcon,
  BarChart as BIDashboardIcon,
  SupportAgent as HelpDeskIcon,
  // ─── Phase: Advanced Systems (Blockchain, ICF, MDT, AR-Rehab) ───
  Token as BlockchainIcon,
  Assessment as ICFIcon,
  GroupWork as MDTIcon,
  ViewInAr as ARRehabIcon,
  // ─── Phase: Telehealth (الطب عن بُعد) ───
  VideoCall as TelehealthIcon,
  // ─── Print Center (مركز الطباعة) ───
  LocalPrintshop as PrintCenterIcon,
  Share as SocialShareIcon,
  Psychology as CDSSIcon,
  PhoneAndroid as PhoneAndroidIcon,
  Videocam as CctvIcon,
} from '@mui/icons-material';

const getNavigationItems = () => [
  // ═══════════════════════════════════════════════════════
  //  ① الرئيسية — Core Navigation
  // ═══════════════════════════════════════════════════════
  {
    id: 'dashboard',
    label: 'لوحة التحكم',
    icon: <DashboardIcon />,
    path: '/dashboard',
    roles: ['*'],
  },
  {
    id: 'executive-dashboard',
    label: 'لوحة القيادة التنفيذية',
    icon: <DashboardIcon />,
    path: '/executive-dashboard',
    roles: ['admin', 'super_admin', 'manager', 'executive'],
    badge: 'جديد',
    badgeColor: 'success',
  },
  {
    id: 'monitoring',
    label: 'المراقبة',
    icon: <MonitorIcon />,
    path: '/monitoring',
    roles: ['admin', 'super_admin', 'manager'],
  },

  {
    id: 'premium-hub',
    label: 'اللوحات التخصصية',
    icon: <PremiumIcon />,
    path: '/premium',
    roles: ['admin', 'super_admin', 'manager'],
    badge: 'PRO',
    badgeColor: 'success',
  },
  {
    id: 'hq-executive',
    label: 'لوحات القيادة',
    icon: <PremiumIcon />,
    roles: ['admin', 'super_admin', 'hq_admin', 'hq_super_admin', 'executive'],
    children: [
      {
        id: 'hq-dashboard',
        label: 'لوحة المقر الرئيسي',
        path: '/hq-dashboard',
        roles: ['admin', 'super_admin', 'hq_admin', 'hq_super_admin'],
      },
      {
        id: 'executive-snapshot',
        label: 'اللقطة التنفيذية',
        path: '/executive-snapshot',
        roles: ['admin', 'super_admin', 'executive', 'hq_admin'],
      },
      {
        id: 'branches-dashboard',
        label: 'لوحة تحكم الفروع',
        path: '/branches/dashboard',
        roles: ['admin', 'super_admin', 'branch_manager', 'hq_admin'],
      },
      {
        id: 'branches-analytics',
        label: 'تحليلات الفروع',
        path: '/branches/analytics',
        roles: ['admin', 'super_admin', 'branch_manager', 'hq_admin'],
      },
    ],
  },

  // ═══════════════════════════════════════════════════════
  //  ② الخدمات الأساسية — Core Services
  // ═══════════════════════════════════════════════════════
  { id: 'divider-core-services', type: 'divider', label: 'الخدمات الأساسية' },
  {
    id: 'beneficiaries',
    label: 'المستفيدون',
    icon: <PeopleIcon />,
    roles: ['admin', 'super_admin', 'manager', 'social_worker'],
    badge: null,
    children: [
      { id: 'ben-dashboard', label: 'لوحة تحكم المستفيدين', path: '/beneficiaries-dashboard' },
      { id: 'ben-list', label: 'قائمة المستفيدين', path: '/beneficiaries' },
      { id: 'ben-register', label: 'تسجيل طالب جديد', path: '/student-registration' },
      { id: 'ben-table', label: 'جدول المستفيدين', path: '/beneficiaries/table' },
      { id: 'ben-students-dash', label: 'لوحة تحكم الطلاب', path: '/students-dashboard' },
      { id: 'ben-manage', label: 'إدارة الطلاب', path: '/student-management' },
      { id: 'ben-reports-center', label: 'مركز تقارير الطلاب', path: '/student-reports-center' },
      { id: 'ben-periodic-report', label: 'التقرير الدوري', path: '/student-reports/periodic' },
      { id: 'ben-comparison-report', label: 'تقرير المقارنة', path: '/student-reports/comparison' },
      { id: 'ben-print-templates', label: 'قوالب الطباعة', path: '/beneficiaries/templates' },
      {
        id: 'ben-consent-admin',
        label: 'إدارة الموافقات الإكلينيكية',
        path: '/beneficiary-consents',
        badge: 'P1',
        badgeColor: 'error',
      },
      {
        id: 'ben-transfer-admin',
        label: 'إدارة التحويلات بين الفروع',
        path: '/beneficiary-transfers',
        badge: 'جديد',
        badgeColor: 'primary',
      },
    ],
  },
  {
    id: 'rehabilitation',
    label: 'إعادة التأهيل',
    icon: <RehabIcon />,
    roles: ['admin', 'super_admin', 'therapist', 'doctor'],
    children: [
      { id: 'rehab-main', label: 'العلاج والتأهيل', path: '/rehab' },
      {
        id: 'episodes-manage',
        label: 'حلقات الرعاية',
        path: '/episodes',
        badge: 'جديد',
        badgeColor: 'primary',
      },
      {
        id: 'episode-center',
        label: 'مركز الحلقة الموحدة',
        path: '/episode-center',
        badge: 'جديد',
        badgeColor: 'success',
      },
      {
        id: 'session-center',
        label: 'مركز الجلسات العلاجية',
        path: '/session-center',
        badge: 'جديد',
        badgeColor: 'info',
      },
      {
        id: 'care-plans-manage',
        label: 'خطط الرعاية المتكاملة',
        path: '/care-plans',
        badge: 'جديد',
        badgeColor: 'primary',
      },
      {
        id: 'therapeutic-goals',
        label: 'الأهداف العلاجية',
        path: '/goals',
        badge: 'جديد',
        badgeColor: 'success',
      },
      { id: 'group-therapy-manage', label: 'العلاج الجماعي', path: '/group-therapy' },
      { id: 'behavior-manage', label: 'إدارة السلوك', path: '/behavior-management' },
      {
        id: 'family-engagement',
        label: 'التواصل الأسري',
        path: '/family-engagement',
        badge: 'جديد',
        badgeColor: 'secondary',
      },
      {
        id: 'tele-rehab',
        label: 'التأهيل عن بُعد',
        path: '/tele-rehab',
        badge: 'جديد',
        badgeColor: 'info',
      },
      {
        id: 'field-training',
        label: 'التدريب الميداني',
        path: '/field-training',
        badge: 'جديد',
        badgeColor: 'info',
      },
      {
        id: 'ai-recommendations',
        label: 'التوصيات الذكية',
        path: '/ai-recommendations',
        badge: 'AI',
        badgeColor: 'error',
      },
      {
        id: 'ai-predictive',
        label: 'التحليلات التنبؤية',
        path: '/ai-predictive',
        badge: 'AI',
        badgeColor: 'error',
      },
      {
        id: 'clinical-research',
        label: 'الأبحاث السريرية',
        path: '/clinical-research',
        badge: 'جديد',
        badgeColor: 'secondary',
      },
      { id: 'ar-vr', label: 'تأهيل AR/VR', path: '/ar-vr', badge: 'جديد', badgeColor: 'info' },
      {
        id: 'programs',
        label: 'البرامج التأهيلية',
        path: '/programs',
        badge: 'جديد',
        badgeColor: 'success',
      },
      {
        id: 'compliance-hub',
        label: 'مركز الامتثال',
        path: '/compliance-hub',
        badge: 'جديد',
        badgeColor: 'secondary',
      },
      {
        id: 'patient-engagement',
        label: 'تفاعل المستفيدين',
        path: '/patient-engagement',
        badge: 'جديد',
        badgeColor: 'info',
      },
      {
        id: 'interoperability',
        label: 'التشغيل البيني والتكامل',
        path: '/interoperability',
        badge: 'جديد',
        badgeColor: 'primary',
      },
      {
        id: 'business-continuity',
        label: 'استمرارية الأعمال',
        path: '/business-continuity',
        badge: 'جديد',
        badgeColor: 'error',
      },
      {
        id: 'hr-development',
        label: 'تطوير الكوادر البشرية',
        path: '/hr-development',
        badge: 'جديد',
        badgeColor: 'secondary',
      },
      {
        id: 'equipment-lifecycle',
        label: 'دورة حياة المعدات',
        path: '/equipment-lifecycle',
        badge: 'جديد',
        badgeColor: 'success',
      },
      {
        id: 'facility-management',
        label: 'إدارة المرافق والأصول',
        path: '/facility-management',
        badge: 'جديد',
        badgeColor: 'info',
      },
      {
        id: 'research-hub',
        label: 'مركز الأبحاث والنشر',
        path: '/research-hub',
        badge: 'جديد',
        badgeColor: 'primary',
      },
      {
        id: 'community-engagement',
        label: 'الانخراط المجتمعي',
        path: '/community-engagement',
        badge: 'جديد',
        badgeColor: 'warning',
      },
      { id: 'rehab-care', label: 'خطط الرعاية (كلاسيك)', path: '/integrated-care' },
      { id: 'rehab-assessment', label: 'مقاييس التقييم', path: '/assessment-scales' },
      { id: 'rehab-tests', label: 'اختبارات التقييم', path: '/assessment-tests' },
      { id: 'rehab-dashboard', label: 'لوحة تحكم التأهيل', path: '/disability-rehab-dashboard' },
      { id: 'rehab-programs-mgmt', label: 'البرامج التأهيلية', path: '/rehab-programs' },
      { id: 'therapy-sessions-admin', label: 'الجلسات العلاجية', path: '/therapy-sessions-admin' },
      { id: 'assistive-devices', label: 'الأجهزة المساعدة', path: '/assistive-devices' },
      { id: 'rehab-reports', label: 'تقارير التأهيل', path: '/disability-rehab-reports' },
      {
        id: 'gamification',
        label: 'نظام التحفيز',
        path: '/gamification',
        badge: 'جديد',
        badgeColor: 'warning',
      },
    ],
  },
  {
    id: 'specialized-rehab',
    label: 'التأهيل المتخصص',
    icon: <SpecializedRehabIcon />,
    roles: ['admin', 'super_admin', 'therapist', 'doctor'],
    children: [
      { id: 'spec-scales-lib', label: 'مكتبة المقاييس المتخصصة', path: '/specialized-scales' },
      { id: 'spec-scale-admin', label: 'تطبيق المقاييس', path: '/scale-administration' },
      { id: 'spec-programs-lib', label: 'مكتبة برامج التأهيل', path: '/rehab-programs-library' },
      { id: 'spec-enrollment', label: 'تسجيل البرامج', path: '/program-enrollment' },
      { id: 'spec-progress', label: 'متابعة التقدم', path: '/rehab-progress' },
      { id: 'spec-behavior', label: 'إدارة السلوك', path: '/behavior-management' },
    ],
  },
  {
    id: 'smart-assessment-engine',
    label: 'محرك التقييم الذكي',
    icon: <ICFIcon />,
    roles: ['admin', 'super_admin', 'therapist', 'doctor'],
    badge: 'AI',
    badgeColor: '#7b1fa2',
    children: [
      { id: 'smart-assessment-main', label: 'لوحة التقييم الذكي', path: '/smart-assessment' },
      {
        id: 'clinical-assessments-page',
        label: 'التقييمات السريرية',
        path: '/clinical-assessments',
        badge: 'جديد',
        badgeColor: 'success',
      },
      {
        id: 'rehab-measures',
        label: 'مقاييس التأهيل الشاملة',
        path: '/rehab-measures',
        badge: 'AI',
        badgeColor: '#1565c0',
      },
      {
        id: 'rehab-templates',
        label: 'القوالب التأهيلية الذكية',
        path: '/rehab-templates',
        badge: 'جديد',
        badgeColor: 'success',
      },
      {
        id: 'rehab-progress-tracker',
        label: 'متتبع التقدم التأهيلي',
        path: '/rehab-progress-tracker',
      },
    ],
  },
  {
    id: 'icf-assessments',
    label: 'تقييمات ICF',
    icon: <ICFIcon />,
    path: '/icf-assessments',
    roles: ['admin', 'super_admin', 'therapist', 'specialist'],
  },
  {
    id: 'clinical-dashboard',
    label: 'الملف السريري المتكامل',
    icon: <MonitorIcon />,
    path: '/clinical-dashboard',
    roles: ['admin', 'super_admin', 'therapist', 'doctor', 'clinical_director'],
    badge: 'جديد',
    badgeColor: 'success',
  },
  {
    id: 'integrated-reports',
    label: 'التقارير المتكاملة',
    icon: <PrintCenterIcon />,
    path: '/reports/integrated',
    roles: ['admin', 'super_admin', 'therapist', 'doctor', 'clinical_director'],
    badge: 'جديد',
    badgeColor: 'primary',
  },
  {
    id: 'mdt-coordination',
    label: 'التنسيق متعدد التخصصات',
    icon: <MDTIcon />,
    path: '/mdt-coordination',
    roles: ['admin', 'super_admin', 'therapist', 'specialist', 'doctor'],
  },
  {
    id: 'rehab-disciplines',
    label: 'سجل التخصصات التأهيلية',
    icon: <MDTIcon />,
    path: '/rehab/disciplines',
    roles: ['admin', 'super_admin', 'therapist', 'clinical_coordinator', 'manager'],
  },
  {
    id: 'rehab-goal-suggestions',
    label: 'اقتراحات الأهداف الذكية',
    icon: <MDTIcon />,
    path: '/rehab/goal-suggestions',
    roles: ['admin', 'super_admin', 'therapist', 'clinical_coordinator', 'manager'],
  },
  {
    id: 'ar-rehab',
    label: 'تأهيل الواقع المعزز',
    icon: <ARRehabIcon />,
    path: '/ar-rehab',
    roles: ['admin', 'super_admin', 'therapist', 'specialist'],
  },
  {
    id: 'telehealth',
    label: 'جلسات الفيديو',
    icon: <TelehealthIcon />,
    path: '/telehealth',
    badge: 'جديد',
    badgeColor: 'success',
    roles: [
      'admin',
      'super_admin',
      'therapist',
      'specialist',
      'clinical_supervisor',
      'manager',
      'parent',
      'guardian',
    ],
  },
  {
    id: 'scheduling',
    label: 'الجلسات والمواعيد',
    icon: <ScheduleIcon />,
    roles: ['admin', 'super_admin', 'therapist', 'receptionist'],
    children: [
      { id: 'sessions-dashboard', label: 'لوحة تحكم الجلسات', path: '/sessions-dashboard' },
      { id: 'sessions-manage', label: 'إدارة الجلسات', path: '/sessions' },
      {
        id: 'sessions-amendment-audit',
        label: 'سجل تعديلات السجلات',
        path: '/sessions/amendment-audit',
        roles: ['admin', 'super_admin', 'clinical_supervisor', 'manager'],
      },
    ],
  },
  {
    id: 'medical-files',
    label: 'الملفات الطبية',
    icon: <MedicalFilesIcon />,
    path: '/medical-files',
    roles: ['admin', 'super_admin', 'doctor', 'therapist'],
  },
  {
    id: 'emr',
    label: 'السجل الطبي الإلكتروني',
    icon: <MonitorIcon />,
    path: '/emr',
    roles: ['admin', 'super_admin', 'doctor', 'therapist', 'nurse'],
    badge: 'جديد',
    badgeColor: 'success',
  },
  {
    id: 'mhpss',
    label: 'الدعم النفسي والاجتماعي',
    icon: <MHPSSIcon />,
    path: '/mhpss',
    roles: ['admin', 'super_admin', 'therapist', 'social_worker'],
  },
  {
    id: 'independent-living',
    label: 'الحياة المستقلة',
    icon: <IndependentLivingIcon />,
    path: '/independent-living',
    roles: ['admin', 'super_admin', 'therapist', 'social_worker'],
  },
  {
    id: 'waitlist',
    label: 'قائمة الانتظار',
    icon: <WaitlistIcon />,
    path: '/waitlist',
    roles: ['admin', 'super_admin', 'manager', 'receptionist'],
  },
  {
    id: 'education',
    label: 'التعليم والتأهيل',
    icon: <SchoolIcon />,
    roles: ['admin', 'super_admin', 'teacher', 'therapist', 'student'],
    children: [
      { id: 'education-lms', label: 'التعليم الإلكتروني (LMS)', path: '/lms' },
      { id: 'education-rehab', label: 'برنامج التعليم التأهيلي', path: '/education' },
    ],
  },
  {
    id: 'montessori',
    label: 'برنامج مونتيسوري',
    icon: <EarlyInterventionIcon />,
    roles: ['admin', 'super_admin', 'teacher', 'therapist'],
    children: [
      { id: 'montessori-dashboard', label: 'لوحة تحكم مونتيسوري', path: '/montessori' },
      { id: 'montessori-students', label: 'الطلاب', path: '/montessori/students' },
      { id: 'montessori-programs', label: 'البرامج', path: '/montessori/programs' },
      { id: 'montessori-sessions', label: 'الجلسات والتقييمات', path: '/montessori/sessions' },
      { id: 'montessori-team', label: 'الفريق وأولياء الأمور', path: '/montessori/team' },
    ],
  },

  // ═══════════════════════════════════════════════════════
  //  ③ الموارد البشرية — Human Resources & Workforce
  // ═══════════════════════════════════════════════════════
  { id: 'divider-hr', type: 'divider', label: 'الموارد البشرية' },
  {
    id: 'hr',
    label: 'الموارد البشرية',
    icon: <PeopleIcon />,
    roles: ['admin', 'super_admin', 'hr_manager'],
    children: [
      {
        id: 'hr-command-center',
        label: '🧠 مركز القيادة الذكي',
        path: '/hr/command-center',
        roles: ['admin', 'super_admin', 'hr_manager', 'manager'],
      },
      { id: 'hr-main', label: 'لوحة الموارد البشرية', path: '/hr' },
      { id: 'hr-employees', label: 'إدارة الموظفين', path: '/hr/employees' },
      { id: 'hr-attendance', label: 'الحضور والانصراف', path: '/hr/attendance' },
      { id: 'hr-attendance-pro', label: '⚡ نظام الحضور الذكي', path: '/attendance/pro' },
      { id: 'hr-leaves', label: 'إدارة الإجازات', path: '/hr/leaves' },
      { id: 'hr-payroll', label: 'الرواتب', path: '/hr/payroll' },
      { id: 'hr-incentives', label: 'الحوافز', path: '/hr/incentives' },
      { id: 'hr-compensation', label: 'هيكل التعويضات', path: '/hr/compensation' },
      { id: 'hr-analytics', label: 'تحليلات الرواتب', path: '/hr/analytics' },
      { id: 'hr-salary-slip', label: 'كشف الراتب', path: '/hr/salary-slip' },
      { id: 'hr-payroll-processing', label: 'معالجة الرواتب', path: '/hr/payroll-processing' },
      { id: 'hr-payroll-reports', label: 'تقارير الرواتب', path: '/hr/payroll-reports' },
      { id: 'hr-payroll-settings', label: 'إعدادات الرواتب', path: '/hr/payroll-settings' },
      { id: 'hr-end-of-service', label: 'مكافأة نهاية الخدمة', path: '/hr/end-of-service' },
      { id: 'hr-org', label: 'الهيكل التنظيمي', path: '/organization' },
      { id: 'hr-insurance', label: 'تأمين الموظفين الصحي', path: '/hr/insurance' },
      {
        id: 'credential-expiry',
        label: 'صلاحية الاعتمادات (SCFHS/إقامة)',
        path: '/hr/credential-expiry',
        roles: ['admin', 'super_admin', 'hr_manager'],
      },
    ],
  },
  {
    id: 'recruitment',
    label: 'التوظيف والاستقطاب',
    icon: <RecruitmentIcon />,
    path: '/recruitment',
    roles: ['admin', 'super_admin', 'hr_manager', 'manager'],
  },
  {
    id: 'training',
    label: 'التدريب والتطوير',
    icon: <TrainingIcon />,
    roles: ['admin', 'super_admin', 'hr_manager', 'manager'],
    children: [
      { id: 'training-dashboard', label: 'لوحة تحكم التدريب', path: '/training' },
      { id: 'training-programs', label: 'البرامج التدريبية', path: '/training/programs' },
      { id: 'training-reports', label: 'تقارير التدريب', path: '/training/reports' },
    ],
  },
  {
    id: 'performance',
    label: 'الأداء والتخطيط',
    icon: <AnalyticsIcon />,
    path: '/performance',
    roles: ['admin', 'super_admin', 'hr_manager', 'manager'],
  },

  // ═══════════════════════════════════════════════════════
  //  ④ المالية والمحاسبة — Finance & Accounting
  // ═══════════════════════════════════════════════════════
  { id: 'divider-finance', type: 'divider', label: 'المالية والمحاسبة' },
  {
    id: 'finance-core',
    label: 'المحاسبة الأساسية',
    icon: <FinanceIcon />,
    roles: ['admin', 'super_admin', 'finance_manager', 'accountant'],
    children: [
      { id: 'accounting-dashboard', label: 'لوحة المحاسبة', path: '/accounting' },
      { id: 'chart-of-accounts', label: 'دليل الحسابات', path: '/accounting/chart-of-accounts' },
      { id: 'journal-entries', label: 'القيود اليومية', path: '/accounting/journal-entries' },
      { id: 'general-ledger', label: 'الأستاذ العام', path: '/accounting/general-ledger' },
      { id: 'trial-balance', label: 'ميزان المراجعة', path: '/accounting/trial-balance' },
      { id: 'profit-loss', label: 'الأرباح والخسائر', path: '/accounting/profit-loss' },
      { id: 'balance-sheet', label: 'الميزانية العمومية', path: '/accounting/balance-sheet' },
    ],
  },
  {
    id: 'finance-billing',
    label: 'الفوترة والمدفوعات',
    icon: <BudgetIcon />,
    roles: ['admin', 'super_admin', 'finance_manager', 'accountant'],
    children: [
      { id: 'invoices', label: 'الفواتير', path: '/accounting/invoices' },
      { id: 'e-invoicing', label: 'الفوترة الإلكترونية (ZATCA)', path: '/e-invoicing' },
      { id: 'payment-vouchers', label: 'سندات الصرف والقبض', path: '/accounting/payment-vouchers' },
      {
        id: 'bank-reconciliation',
        label: 'التسوية البنكية',
        path: '/accounting/bank-reconciliation',
      },
      { id: 'bank-accounts', label: 'الحسابات البنكية', path: '/accounting/bank-accounts' },
      { id: 'petty-cash', label: 'العهد والصندوق', path: '/accounting/petty-cash' },
      { id: 'multi-currency', label: 'العملات وأسعار الصرف', path: '/accounting/multi-currency' },
    ],
  },
  {
    id: 'finance-budget',
    label: 'الموازنات والتكاليف',
    icon: <DonationsIcon />,
    roles: ['admin', 'super_admin', 'finance_manager', 'accountant', 'manager'],
    children: [
      { id: 'budgets', label: 'الموازنات', path: '/accounting/budgets' },
      {
        id: 'budget-variance',
        label: 'الموازنة مقابل الفعلي',
        path: '/accounting/budget-variance',
      },
      { id: 'cost-centers', label: 'مراكز التكلفة', path: '/accounting/cost-centers' },
      { id: 'fixed-assets', label: 'الأصول الثابتة', path: '/accounting/fixed-assets' },
      { id: 'cash-flow', label: 'التدفقات النقدية', path: '/accounting/cash-flow' },
      { id: 'donations', label: 'التبرعات', path: '/donations' },
    ],
  },
  {
    id: 'finance-tax',
    label: 'الضرائب والزكاة',
    icon: <FinanceIcon />,
    roles: ['admin', 'super_admin', 'finance_manager', 'accountant'],
    children: [
      { id: 'vat-zakat', label: 'ضريبة القيمة المضافة والزكاة', path: '/accounting/vat-zakat' },
      { id: 'withholding-tax', label: 'ضريبة الاستقطاع', path: '/accounting/withholding-tax' },
      { id: 'tax-filing', label: 'الإقرارات الضريبية', path: '/finance/tax-filing' },
      { id: 'tax-calendar', label: 'التقويم الضريبي', path: '/accounting/tax-calendar' },
    ],
  },
  {
    id: 'finance-reports',
    label: 'التقارير المالية',
    icon: <AnalyticsIcon />,
    roles: ['admin', 'super_admin', 'finance_manager', 'accountant', 'manager'],
    children: [
      { id: 'financial-reports', label: 'التقارير المالية', path: '/accounting/reports' },
      { id: 'financial-ratios', label: 'النسب المالية', path: '/accounting/financial-ratios' },
      { id: 'aged-reports', label: 'تقارير أعمار الديون', path: '/accounting/aged-reports' },
      { id: 'cash-flow-report', label: 'التدفقات النقدية', path: '/accounting/cash-flow' },
      { id: 'executive-summary', label: 'الملخص التنفيذي', path: '/accounting/executive-summary' },
      { id: 'financial-planning', label: 'التخطيط المالي', path: '/finance/financial-planning' },
      { id: 'audit-manager', label: 'إدارة التدقيق', path: '/finance/audit-manager' },
    ],
  },

  // ═══════════════════════════════════════════════════════
  //  ⑤ العمليات والإمداد — Operations & Logistics
  // ═══════════════════════════════════════════════════════
  { id: 'divider-operations', type: 'divider', label: 'العمليات والإمداد' },
  {
    id: 'operations',
    label: 'العمليات والأصول',
    icon: <SettingsIcon />,
    roles: ['admin', 'super_admin', 'manager', 'operations_manager'],
    children: [
      { id: 'ops-dashboard', label: 'لوحة تحكم العمليات', path: '/operations-dashboard' },
      { id: 'ops-manage', label: 'إدارة العمليات', path: '/operations' },
      { id: 'ops-inventory', label: 'إدارة المخزون', path: '/inventory' },
      { id: 'ops-purchasing', label: 'المشتريات', path: '/purchasing' },
      { id: 'ops-equipment', label: 'المعدات والأصول', path: '/equipment' },
      { id: 'ops-incidents', label: 'إدارة الحوادث', path: '/incidents' },
      { id: 'ops-licenses', label: 'الرخص والتصاريح', path: '/licenses' },
      { id: 'ops-rehab-licenses', label: 'تراخيص مراكز التأهيل', path: '/rehab-licenses' },
      { id: 'ops-branch-warehouses', label: 'مخازن الفروع', path: '/branch-warehouses' },
      { id: 'ops-stock-transfers', label: 'تحويلات المخزون', path: '/stock-transfers' },
      { id: 'ops-branch-purchasing', label: 'مشتريات الفروع', path: '/branch-purchasing' },
      { id: 'ops-branch-reports', label: 'تقارير الفروع', path: '/branch-reports' },
    ],
  },
  {
    id: 'cctv-monitoring',
    label: 'مركز المراقبة',
    icon: <CctvIcon />,
    path: '/cctv-monitoring',
    roles: ['admin', 'super_admin', 'manager', 'security_officer'],
    badge: 'CCTV',
    badgeColor: 'error',
  },
  {
    id: 'fleet',
    label: 'الأسطول والنقل',
    icon: <MonitorIcon />,
    roles: ['admin', 'super_admin', 'manager', 'fleet_manager'],
    children: [
      { id: 'fleet-dashboard', label: 'لوحة تحكم الأسطول', path: '/fleet-dashboard' },
      { id: 'fleet-manage', label: 'إدارة الأسطول', path: '/fleet' },
      { id: 'vehicle-manage', label: 'إدارة المركبات', path: '/vehicle-management' },
      { id: 'insurance-manage', label: 'إدارة التأمين', path: '/insurance-management' },
      { id: 'transport-manage', label: 'إدارة النقل', path: '/transport-management' },
    ],
  },
  {
    id: 'maintenance',
    label: 'الصيانة والمرافق',
    icon: <MaintenanceIcon />,
    path: '/maintenance',
    roles: ['admin', 'super_admin', 'manager', 'maintenance'],
  },
  {
    id: 'vendors',
    label: 'إدارة الموردين',
    icon: <VendorIcon />,
    path: '/vendors',
    roles: ['admin', 'super_admin', 'manager', 'accountant', 'purchasing'],
  },
  {
    id: 'contracts',
    label: 'إدارة العقود',
    icon: <ContractsIcon />,
    roles: ['admin', 'super_admin', 'manager'],
    children: [
      { id: 'contracts-dashboard', label: 'لوحة تحكم العقود', path: '/contracts-dashboard' },
      { id: 'contracts-manage', label: 'إدارة العقود', path: '/contracts' },
    ],
  },
  {
    id: 'projects',
    label: 'إدارة المشاريع',
    icon: <ProjectIcon />,
    path: '/projects',
    roles: ['admin', 'super_admin', 'manager'],
  },
  {
    id: 'ops-extended',
    label: 'اللوجستيات والخدمات',
    icon: <WarehouseIcon />,
    roles: ['admin', 'super_admin', 'manager', 'operations_manager'],
    children: [
      { id: 'warehouse', label: 'إدارة المستودعات', path: '/warehouse' },
      { id: 'supply-chain', label: 'سلسلة الإمداد', path: '/supply-chain' },
      { id: 'gps-tracking', label: 'تتبع GPS', path: '/gps-tracking' },
      { id: 'iot-management', label: 'إنترنت الأشياء (IoT)', path: '/iot' },
      { id: 'kitchen', label: 'إدارة المطبخ', path: '/kitchen' },
      { id: 'laundry', label: 'إدارة المغسلة', path: '/laundry' },
    ],
  },
  {
    id: 'ops-compliance',
    label: 'الجودة والسلامة',
    icon: <HSEIcon />,
    roles: ['admin', 'super_admin', 'manager', 'quality_manager', 'hse_officer'],
    children: [
      { id: 'quality-dashboard', label: 'لوحة تحكم الجودة', path: '/quality-dashboard' },
      { id: 'quality-manage', label: 'إدارة الجودة', path: '/quality' },
      { id: 'quality-audit', label: 'التدقيق الداخلي', path: '/internal-audit' },
      { id: 'risk-assessment', label: 'تقييم المخاطر', path: '/risk-assessment' },
      { id: 'risk-management', label: 'إدارة المخاطر المؤسسية', path: '/risk-management' },
      { id: 'risk-register', label: 'سجل المخاطر', path: '/risk-management/register' },
      { id: 'capa-admin', label: 'الإجراءات التصحيحية (CAPA)', path: '/quality/capa' },
      {
        id: 'policy-library',
        label: 'مكتبة السياسات والإجراءات',
        path: '/quality/policy-library',
        roles: ['admin', 'super_admin', 'manager', 'quality_manager'],
      },
      { id: 'hse', label: 'الصحة والسلامة (HSE)', path: '/hse' },
      { id: 'crisis-management', label: 'إدارة الأزمات', path: '/crisis' },
      {
        id: 'compliance-center',
        label: 'مركز الامتثال والاعتماد',
        path: '/compliance',
        badge: 'جديد',
        badgeColor: 'primary',
      },
    ],
  },

  // ═══════════════════════════════════════════════════════
  //  ⑥ التواصل والمراسلات — Communications & Messaging
  // ═══════════════════════════════════════════════════════
  { id: 'divider-comms', type: 'divider', label: 'التواصل والمعلومات' },
  {
    id: 'communications',
    label: 'التواصل',
    icon: <MessageIcon />,
    roles: ['*'],
    children: [
      {
        id: 'chat-v2',
        label: 'الرسائل (جديد)',
        path: '/chat',
        badge: 'جديد',
        badgeColor: 'success',
      },
      { id: 'comm-messages', label: 'الرسائل', path: '/messages' },
      { id: 'comm-system', label: 'نظام التواصل', path: '/communications-system' },
      {
        id: 'comm-whatsapp',
        label: 'واتساب / الذكاء الاصطناعي',
        path: '/whatsapp',
        badge: 'جديد',
        badgeColor: 'success',
      },
      {
        id: 'comm-whatsapp-chatbot',
        label: 'روبوت واتساب',
        path: '/whatsapp-chatbot',
        roles: ['admin', 'super_admin', 'manager'],
      },
    ],
  },
  {
    id: 'admin-communications',
    label: 'الاتصالات الإدارية',
    icon: <AdminCommIcon />,
    roles: ['admin', 'super_admin', 'manager', 'secretary'],
    children: [
      { id: 'admcomm-dashboard', label: 'لوحة التحكم', path: '/admin-communications' },
      { id: 'admcomm-inbox', label: 'البريد الوارد', path: '/admin-communications/inbox' },
      { id: 'admcomm-outbox', label: 'البريد الصادر', path: '/admin-communications/outbox' },
      { id: 'admcomm-internal', label: 'المراسلات الداخلية', path: '/admin-communications/all' },
      { id: 'admcomm-compose', label: 'مراسلة جديدة', path: '/admin-communications/compose' },
      { id: 'admcomm-templates', label: 'القوالب', path: '/admin-communications/templates' },
      {
        id: 'admcomm-entities',
        label: 'الجهات الخارجية',
        path: '/admin-communications/external-entities',
      },
    ],
  },
  {
    id: 'electronic-directives',
    label: 'التوجيهات الإلكترونية',
    icon: <CampaignIcon />,
    roles: ['admin', 'super_admin', 'manager', 'department_head'],
    children: [
      { id: 'dir-dashboard', label: 'لوحة التحكم', path: '/electronic-directives' },
      { id: 'dir-list', label: 'قائمة التوجيهات', path: '/electronic-directives/list' },
      { id: 'dir-compose', label: 'توجيه جديد', path: '/electronic-directives/compose' },
    ],
  },
  {
    id: 'smart-notifications',
    label: 'مركز الإشعارات',
    icon: <SmartNotifIcon />,
    path: '/smart-notifications',
    roles: ['*'],
  },
  {
    id: 'meetings',
    label: 'الاجتماعات',
    icon: <MeetingIcon />,
    path: '/meetings',
    roles: ['*'],
  },
  {
    id: 'public-relations',
    label: 'العلاقات العامة',
    icon: <PRIcon />,
    path: '/public-relations',
    roles: ['admin', 'super_admin', 'manager', 'pr_officer'],
  },
  {
    id: 'social-media',
    label: 'إدارة السوشل ميديا',
    icon: <SocialShareIcon />,
    path: '/social-media',
    roles: ['admin', 'super_admin', 'manager', 'pr_officer'],
    badge: 'جديد',
    badgeColor: 'primary',
    children: [
      { id: 'sm-dashboard', label: 'لوحة التحكم', path: '/social-media' },
      { id: 'sm-posts', label: 'المنشورات', path: '/social-media' },
      { id: 'sm-analytics', label: 'التحليلات', path: '/social-media' },
      { id: 'sm-audience', label: 'الجمهور', path: '/social-media' },
      { id: 'sm-campaigns', label: 'الحملات', path: '/social-media' },
    ],
  },
  {
    id: 'cdss',
    label: 'دعم القرار السريري',
    icon: <CDSSIcon />,
    path: '/cdss',
    roles: ['admin', 'super_admin', 'clinical_director', 'therapist'],
    badge: 'ذكاء',
    badgeColor: 'error',
    children: [
      { id: 'cdss-overview', label: 'لوحة المراقبة', path: '/cdss' },
      { id: 'cdss-alerts', label: 'التنبيهات السريرية', path: '/cdss' },
      { id: 'cdss-rules', label: 'قواعد القرار', path: '/cdss' },
      { id: 'cdss-suggestions', label: 'اقتراحات الذكاء', path: '/cdss' },
      { id: 'cdss-drugs', label: 'مكتبة الأدوية', path: '/cdss' },
      { id: 'cdss-log', label: 'سجل القرارات', path: '/cdss' },
    ],
  },

  // ─── المستندات والأرشفة (ضمن قسم التواصل والمعلومات) ───
  {
    id: 'documents',
    label: 'المستندات',
    icon: <DocumentIcon />,
    roles: ['*'],
    children: [
      {
        id: 'docs-center',
        label: 'مركز الوثائق الموحد',
        path: '/document-management',
        badge: 'جديد',
      },
      { id: 'docs-main', label: 'المستندات', path: '/documents' },
      { id: 'docs-smart', label: 'المستندات الذكية', path: '/smart-documents' },
      { id: 'docs-archive', label: 'الأرشفة الإلكترونية', path: '/archiving' },
    ],
  },
  {
    id: 'media-library',
    label: 'مكتبة الوسائط',
    icon: <MediaLibraryIcon />,
    roles: ['*'],
    children: [{ id: 'media-dashboard', label: 'لوحة الوسائط', path: '/media-library' }],
  },
  {
    id: 'e-signature',
    label: 'التوقيع الإلكتروني',
    icon: <SignatureIcon />,
    path: '/e-signature',
    roles: ['admin', 'super_admin', 'manager'],
    children: [
      { id: 'e-signature-dashboard', label: 'لوحة التوقيع', path: '/e-signature' },
      { id: 'e-signature-create', label: 'طلب توقيع جديد', path: '/e-signature/create' },
      { id: 'e-signature-templates', label: 'القوالب', path: '/e-signature/templates' },
      { id: 'e-signature-verify', label: 'التحقق', path: '/e-signature/verify' },
      {
        id: 'e-signature-nafath',
        label: 'توقيعات نفاذ الوطنية',
        path: '/e-signature/nafath-signing',
        badge: 'P1',
        badgeColor: 'error',
      },
    ],
  },
  {
    id: 'e-stamp',
    label: 'الختم الإلكتروني',
    icon: <StampIcon />,
    path: '/e-stamp',
    roles: ['admin', 'super_admin', 'manager'],
    children: [
      { id: 'e-stamp-dashboard', label: 'لوحة الأختام', path: '/e-stamp' },
      { id: 'e-stamp-create', label: 'إنشاء ختم جديد', path: '/e-stamp/create' },
      { id: 'e-stamp-verify', label: 'التحقق من ختم', path: '/e-stamp/verify' },
    ],
  },
  {
    id: 'form-templates',
    label: 'النماذج الجاهزة',
    icon: <FormTemplateIcon />,
    path: '/form-templates',
    roles: ['*'],
  },
  {
    id: 'cms',
    label: 'إدارة المحتوى',
    icon: <CMSIcon />,
    path: '/cms',
    roles: ['admin', 'super_admin', 'manager', 'content_manager'],
  },
  {
    id: 'articles-section',
    label: 'المقالات والمحتوى',
    icon: <CMSIcon />,
    roles: ['admin', 'super_admin', 'manager', 'content_manager'],
    children: [{ id: 'articles-list', label: 'قائمة المقالات', path: '/articles' }],
  },
  {
    id: 'print-center',
    label: 'مركز الطباعة',
    icon: <PrintCenterIcon />,
    roles: ['*'],
    children: [
      { id: 'print-hub', label: 'جميع القوالب', path: '/print-center' },
      { id: 'print-hr', label: 'قوالب الموارد البشرية', path: '/print-center/hr' },
      { id: 'print-finance', label: 'قوالب المالية', path: '/print-center/finance' },
      { id: 'print-therapy', label: 'قوالب العلاج والتأهيل', path: '/print-center/therapy' },
      { id: 'print-admin', label: 'قوالب الإدارة', path: '/print-center/admin' },
      { id: 'print-operations', label: 'قوالب العمليات', path: '/print-center/operations' },
    ],
  },

  // ═══════════════════════════════════════════════════════
  //  ⑧ التحليلات والذكاء — Analytics & Intelligence
  // ═══════════════════════════════════════════════════════
  { id: 'divider-analytics', type: 'divider', label: 'التحليلات والذكاء' },
  {
    id: 'analytics',
    label: 'التحليلات والتقارير',
    icon: <AnalyticsIcon />,
    roles: ['admin', 'super_admin', 'manager'],
    children: [
      { id: 'analytics-main', label: 'لوحة التحليلات', path: '/analytics' },
      { id: 'analytics-reports', label: 'التقارير', path: '/reports' },
      { id: 'analytics-ai', label: 'التحليلات الذكية', path: '/ai-analytics' },
      { id: 'analytics-advanced', label: 'تقارير متقدمة', path: '/analytics/advanced' },
      {
        id: 'kpi-framework',
        label: 'إطار مؤشرات الأداء (KPI)',
        path: '/kpi-framework',
        roles: ['admin', 'super_admin', 'manager', 'quality_manager'],
      },
      { id: 'analytics-export', label: 'تصدير واستيراد', path: '/export-import' },
    ],
  },
  {
    id: 'import-export-pro',
    label: 'مركز الاستيراد والتصدير',
    icon: <SwapHorizIcon />,
    path: '/import-export',
    roles: ['admin', 'super_admin', 'manager'],
    badge: 'PRO',
  },
  {
    id: 'crm',
    label: 'إدارة علاقات العملاء',
    icon: <CRMIcon />,
    roles: ['admin', 'super_admin', 'manager', 'sales'],
    children: [
      { id: 'crm-dashboard', label: 'لوحة تحكم CRM', path: '/crm' },
      { id: 'crm-contacts', label: 'جهات الاتصال', path: '/crm/contacts' },
      { id: 'crm-leads', label: 'العملاء المحتملين', path: '/crm/leads' },
      { id: 'crm-reports', label: 'تقارير CRM', path: '/crm/reports' },
    ],
  },
  {
    id: 'kpi-dashboard',
    label: 'مؤشرات الأداء',
    icon: <KPIChartIcon />,
    path: '/kpi-dashboard',
    roles: ['admin', 'super_admin', 'manager'],
  },
  {
    id: 'research',
    label: 'البحث والدراسات',
    icon: <ResearchIcon />,
    path: '/research',
    roles: ['admin', 'super_admin', 'manager', 'researcher'],
  },
  {
    id: 'bi-dashboard',
    label: 'لوحة BI التحليلية',
    icon: <BIDashboardIcon />,
    path: '/bi-dashboard',
    roles: ['admin', 'super_admin', 'manager'],
  },
  {
    id: 'bi-analytics',
    label: 'التحليلات المتقدمة',
    icon: <AnalyticsIcon />,
    path: '/bi-analytics',
    roles: ['admin', 'super_admin', 'manager', 'analyst', 'finance_manager', 'hr_manager'],
    badge: 'جديد',
    badgeColor: 'primary',
  },

  // ═══════════════════════════════════════════════════════
  //  ⑨ إدارة الأعمال — Business Management
  // ═══════════════════════════════════════════════════════
  { id: 'divider-business', type: 'divider', label: 'إدارة الأعمال' },
  {
    id: 'administration',
    label: 'نظام الإدارة',
    icon: <AdministrationIcon />,
    roles: ['admin', 'super_admin', 'manager'],
    children: [
      { id: 'admin-dashboard', label: 'لوحة الإدارة', path: '/administration' },
      { id: 'admin-decisions', label: 'القرارات والمذكرات', path: '/administration/decisions' },
      { id: 'admin-correspondence', label: 'المراسلات', path: '/administration/correspondence' },
      { id: 'admin-delegations', label: 'التفويضات', path: '/administration/delegations' },
    ],
  },
  {
    id: 'workflow',
    label: 'سير العمل',
    icon: <AccountTreeIcon />,
    roles: ['admin', 'super_admin', 'manager', 'hr', 'employee'],
    children: [
      { id: 'wf-dashboard', label: 'لوحة التحكم', path: '/workflow' },
      { id: 'wf-builder', label: 'مُنشئ سير العمل', path: '/workflow/builder' },
      { id: 'wf-approvals', label: 'صندوق الموافقات', path: '/approvals' },
      { id: 'wf-my-tasks', label: 'مهامي', path: '/workflow/my-tasks' },
      { id: 'wf-instances', label: 'النسخ المنفذة', path: '/workflow/instances' },
      { id: 'wf-templates', label: 'القوالب', path: '/workflow/templates' },
      { id: 'wf-analytics', label: 'التحليلات', path: '/workflow/analytics' },
    ],
  },
  {
    id: 'tasks',
    label: 'إدارة المهام',
    icon: <TaskIcon />,
    path: '/tasks',
    roles: ['*'],
  },
  {
    id: 'advanced-tickets',
    label: 'نظام التذاكر',
    icon: <TicketIcon />,
    path: '/advanced-tickets',
    roles: ['*'],
  },
  {
    id: 'complaints',
    label: 'الشكاوى والمقترحات',
    icon: <ComplaintsIcon />,
    path: '/complaints',
    roles: ['admin', 'super_admin', 'manager', 'hr_manager'],
  },
  {
    id: 'complaints-sla-admin',
    label: 'إعدادات SLA للشكاوى',
    icon: <ComplaintsIcon />,
    path: '/complaints/sla-admin',
    roles: ['admin', 'super_admin', 'manager'],
  },
  {
    id: 'visitors',
    label: 'سجل الزوار',
    icon: <VisitorIcon />,
    path: '/visitors',
    roles: ['admin', 'super_admin', 'manager', 'receptionist'],
  },
  {
    id: 'knowledge-center',
    label: 'مركز المعرفة',
    icon: <KnowledgeIcon />,
    path: '/knowledge-center',
    roles: ['*'],
  },
  {
    id: 'ecommerce',
    label: 'المتجر الإلكتروني',
    icon: <ECommerceIcon />,
    path: '/ecommerce',
    roles: ['admin', 'super_admin', 'manager', 'sales'],
  },

  // ═══════════════════════════════════════════════════════
  //  ⑩ البوابات — Portals
  // ═══════════════════════════════════════════════════════
  { id: 'divider-portals', type: 'divider', label: 'البوابات' },
  {
    id: 'mobile-app',
    label: 'تطبيق الموبايل',
    icon: <PhoneAndroidIcon />,
    path: '/mobile',
    roles: ['*'],
    badge: 'PWA',
    badgeColor: 'success',
  },
  {
    id: 'student-portal',
    label: 'بوابة الطالب',
    icon: <SchoolIcon />,
    path: '/student-portal',
    roles: ['student', 'admin', 'super_admin'],
  },
  {
    id: 'therapist-portal',
    label: 'بوابة المعالج',
    icon: <TherapistIcon />,
    path: '/therapist-portal',
    roles: ['therapist', 'specialist', 'clinical_supervisor', 'admin', 'super_admin'],
    children: [
      { id: 'therapist-dashboard', label: 'لوحة التحكم', path: '/therapist-portal' },
      {
        id: 'therapist-workbench',
        label: 'منصّة العمل (جديدة)',
        path: '/workbench',
        badge: 'جديد',
        badgeColor: 'success',
      },
      { id: 'therapist-patients', label: 'المرضى', path: '/therapist-portal/patients' },
      { id: 'therapist-schedule', label: 'الجدول', path: '/therapist-portal/schedule' },
      { id: 'therapist-sessions', label: 'الجلسات', path: '/therapist-portal/sessions' },
      { id: 'therapist-cases', label: 'الحالات', path: '/therapist-portal/cases' },
      { id: 'therapist-documents', label: 'المستندات', path: '/therapist-portal/documents' },
      { id: 'therapist-reports', label: 'التقارير', path: '/therapist-portal/reports' },
      { id: 'therapist-messages', label: 'الرسائل', path: '/therapist-portal/messages' },
      {
        id: 'therapist-treatment-plans',
        label: 'الخطط العلاجية',
        path: '/therapist-portal/treatment-plans',
      },
      { id: 'therapist-assessments', label: 'التقييمات', path: '/therapist-portal/assessments' },
      {
        id: 'therapist-prescriptions',
        label: 'الوصفات العلاجية',
        path: '/therapist-portal/prescriptions',
      },
      {
        id: 'therapist-professional-dev',
        label: 'التطوير المهني',
        path: '/therapist-portal/professional-dev',
      },
      { id: 'therapist-analytics', label: 'التحليلات', path: '/therapist-portal/analytics' },
      {
        id: 'therapist-consultations',
        label: 'الاستشارات',
        path: '/therapist-portal/consultations',
      },
      { id: 'therapist-tasks', label: 'سجل المهام', path: '/therapist-portal/tasks' },
      {
        id: 'therapist-progress-tracking',
        label: 'تتبع التقدم',
        path: '/therapist-portal/progress-tracking',
      },
      {
        id: 'therapist-clinical-library',
        label: 'المكتبة العلمية',
        path: '/therapist-portal/clinical-library',
      },
      {
        id: 'therapist-doc-templates',
        label: 'نماذج التوثيق',
        path: '/therapist-portal/doc-templates',
      },
      {
        id: 'therapist-parent-comm',
        label: 'التواصل مع الأهل',
        path: '/therapist-portal/parent-comm',
      },
      {
        id: 'therapist-smart-goals',
        label: 'الأهداف الذكية',
        path: '/therapist-portal/smart-goals',
      },
      { id: 'therapist-referrals', label: 'سجل الإحالات', path: '/therapist-portal/referrals' },
      {
        id: 'therapist-group-therapy',
        label: 'العلاج الجماعي',
        path: '/therapist-portal/group-therapy',
      },
      { id: 'therapist-equipment', label: 'إدارة المعدات', path: '/therapist-portal/equipment' },
      { id: 'therapist-kpis', label: 'مؤشرات الأداء', path: '/therapist-portal/kpis' },
      {
        id: 'therapist-safety-protocols',
        label: 'بروتوكولات السلامة',
        path: '/therapist-portal/safety-protocols',
      },
      {
        id: 'therapist-clinical-research',
        label: 'البحث السريري',
        path: '/therapist-portal/clinical-research',
      },
      { id: 'therapist-telehealth', label: 'العلاج عن بُعد', path: '/therapist-portal/telehealth' },
      {
        id: 'therapist-field-training',
        label: 'سجل التدريب الميداني',
        path: '/therapist-portal/field-training',
      },
      { id: 'therapist-consents', label: 'إدارة الموافقات', path: '/therapist-portal/consents' },
      {
        id: 'therapist-quality-reports',
        label: 'تقارير الجودة',
        path: '/therapist-portal/quality-reports',
      },
      {
        id: 'therapist-waiting-list',
        label: 'قائمة الانتظار',
        path: '/therapist-portal/waiting-list',
      },
      {
        id: 'therapist-achievements',
        label: 'لوحة الإنجازات',
        path: '/therapist-portal/achievements',
      },
    ],
  },
  {
    id: 'parent-portal',
    label: 'بوابة ولي الأمر',
    icon: <ParentIcon />,
    path: '/parent-portal',
    roles: ['parent', 'admin', 'super_admin'],
    children: [
      { id: 'parent-dashboard', label: 'لوحة التحكم', path: '/parent-portal' },
      {
        id: 'parent-my-children',
        label: 'أطفالي (بوابة جديدة)',
        path: '/my-children',
        badge: 'جديد',
        badgeColor: 'success',
      },
      {
        id: 'parent-children-progress',
        label: 'تقدم الأبناء',
        path: '/parent-portal/children-progress',
      },
      {
        id: 'parent-attendance',
        label: 'تقارير الحضور',
        path: '/parent-portal/attendance-reports',
      },
      {
        id: 'parent-therapist',
        label: 'التواصل مع المعالجين',
        path: '/parent-portal/therapist-communications',
      },
      { id: 'parent-payments', label: 'المدفوعات', path: '/parent-portal/payments-history' },
      {
        id: 'parent-documents',
        label: 'المستندات والتقارير',
        path: '/parent-portal/documents-reports',
      },
      {
        id: 'parent-appointments',
        label: 'المواعيد',
        path: '/parent-portal/appointments-scheduling',
      },
      { id: 'parent-messages', label: 'الرسائل', path: '/parent-portal/messages' },
      {
        id: 'parent-beneficiary-detail',
        label: 'تفاصيل المستفيد',
        path: '/parent-portal/:beneficiaryId',
        badge: 'جديد',
        badgeColor: 'primary',
      },
      {
        id: 'parent-portal-management',
        label: 'إدارة البوابة',
        path: '/parent-portal/management',
        roles: ['admin', 'super_admin', 'manager'],
      },
    ],
  },
  {
    id: 'employee-portal',
    label: 'بوابة الموظف',
    icon: <EmployeeIcon />,
    path: '/employee-portal',
    roles: ['*'],
  },

  // ═══════════════════════════════════════════════════════
  //  ⑩ الإدارة والنظام — System Administration & Gov Integration
  // ═══════════════════════════════════════════════════════
  { id: 'divider-admin', type: 'divider', label: 'الإدارة والنظام' },
  {
    id: 'gov-integration',
    label: 'التكامل الحكومي',
    icon: <GovernmentIcon />,
    roles: ['admin', 'super_admin', 'hr_manager', 'finance_manager', 'quality_manager'],
    children: [
      {
        id: 'gov-mudad',
        label: 'مُدد — حماية الأجور',
        path: '/mudad',
        icon: <WageProtectionIcon />,
      },
      { id: 'gov-taqat', label: 'طاقات — التوظيف', path: '/taqat', icon: <EmploymentIcon /> },
      {
        id: 'gov-authority',
        label: 'هيئة رعاية ذوي الإعاقة',
        path: '/disability-authority',
        icon: <GovernmentIcon />,
      },
      { id: 'gov-cbahi', label: 'معايير سباهي (CBAHI)', path: '/cbahi', icon: <CBAHIIcon /> },
      {
        id: 'gov-preauth',
        label: 'التصاريح العلاجية',
        path: '/treatment-authorization',
        icon: <PreAuthIcon />,
      },
      {
        id: 'gov-satisfaction',
        label: 'استبيانات رضا الأسر',
        path: '/family-satisfaction',
        icon: <SurveyIcon />,
      },
      { id: 'gov-noor', label: 'نظام نور — وزارة التعليم', path: '/noor', icon: <NoorIcon /> },
      { id: 'gov-gosi', label: 'التأمينات الاجتماعية (GOSI)', path: '/gosi', icon: <GosiIcon /> },
      { id: 'gov-qiwa', label: 'منصة قوى — الموارد البشرية', path: '/qiwa', icon: <QiwaIcon /> },
      {
        id: 'gov-early-intervention',
        label: 'التدخل المبكر (0–3)',
        path: '/early-intervention',
        icon: <EarlyInterventionIcon />,
      },
      {
        id: 'gov-post-rehab',
        label: 'متابعة ما بعد التأهيل',
        path: '/post-rehab-followup',
        icon: <PostRehabIcon />,
      },
      {
        id: 'gov-guardian',
        label: 'بوابة ولي الأمر',
        path: '/guardian-portal',
        icon: <GuardianIcon />,
      },
    ],
  },
  {
    id: 'institutional-admin',
    label: 'الإدارة المؤسسية',
    icon: <AdministrationIcon />,
    roles: ['admin', 'super_admin', 'manager'],
    children: [
      { id: 'strategic-planning', label: 'التخطيط الاستراتيجي', path: '/strategic-planning' },
      { id: 'org-structure', label: 'الهيكل التنظيمي', path: '/org-structure' },
      { id: 'succession-planning', label: 'التعاقب الوظيفي', path: '/succession-planning' },
      { id: 'facility-management', label: 'إدارة المرافق', path: '/facility-management' },
      { id: 'legal-affairs', label: 'الشؤون القانونية', path: '/legal-affairs' },
      { id: 'events-management', label: 'إدارة الفعاليات', path: '/events' },
      { id: 'employee-affairs', label: 'شؤون الموظفين', path: '/employee-affairs' },
      { id: 'community-integration', label: 'التكامل المجتمعي', path: '/community' },
      { id: 'volunteer-management', label: 'إدارة المتطوعين', path: '/volunteers' },
    ],
  },
  {
    id: 'admin-operations',
    label: 'إدارة العمليات',
    icon: <AdminIcon />,
    roles: [
      'admin',
      'super_admin',
      'manager',
      'clinical_supervisor',
      'receptionist',
      'coordinator',
    ],
    children: [
      { id: 'admin-branches', label: 'الفروع والمراكز', path: '/admin/branches' },
      {
        id: 'admin-branch-license-expiry',
        label: 'تراخيص الفروع وانتهاء الصلاحية',
        path: '/admin-portal/branch-license-expiry',
        badge: 'P1',
        badgeColor: 'warning',
      },
      { id: 'admin-beneficiaries', label: 'المستفيدون', path: '/admin/beneficiaries' },
      { id: 'admin-therapy-sessions', label: 'الجلسات العلاجية', path: '/admin/therapy-sessions' },
      { id: 'admin-assessments', label: 'التقييمات السريرية', path: '/admin/assessments' },
      { id: 'admin-care-plans', label: 'خطط الرعاية (IEP)', path: '/admin/care-plans' },
      { id: 'admin-bi-analytics', label: 'تحليلات BI', path: '/admin/analytics', badge: 'BI' },
      {
        id: 'admin-invoices',
        label: 'الفواتير (ZATCA)',
        path: '/admin/invoices',
        badge: 'ZATCA',
        badgeColor: 'success',
      },
      {
        id: 'admin-clinical-docs',
        label: 'المستندات الإكلينيكية',
        path: '/admin/clinical-docs',
        badge: 'DOCS',
        badgeColor: 'info',
      },
      {
        id: 'admin-hr-compliance',
        label: 'الامتثال (GOSI + SCFHS)',
        path: '/admin/hr/compliance',
        badge: 'COMPLY',
        badgeColor: 'warning',
      },
      {
        id: 'admin-hr-cpe',
        label: 'ساعات CPE',
        path: '/admin/hr/cpe',
        badge: 'CPE',
        badgeColor: 'info',
      },
      {
        id: 'admin-attendance',
        label: 'حضور الجلسات',
        path: '/admin/attendance',
        badge: 'ATT',
        badgeColor: 'success',
      },
      {
        id: 'admin-outcomes',
        label: 'النتائج السريرية',
        path: '/admin/outcomes',
        badge: 'OUT',
        badgeColor: 'primary',
      },
      {
        id: 'admin-nps',
        label: 'رضى العائلات',
        path: '/admin/nps',
        badge: 'NPS',
        badgeColor: 'secondary',
      },
      {
        id: 'admin-goal-progress',
        label: 'تقدُّم الأهداف',
        path: '/admin/goal-progress',
        badge: 'GOAL',
        badgeColor: 'primary',
      },
      {
        id: 'admin-utilization',
        label: 'إنتاجية المعالجين',
        path: '/admin/utilization',
        badge: 'UTIL',
        badgeColor: 'info',
      },
      {
        id: 'admin-waitlist',
        label: 'قائمة الانتظار',
        path: '/admin/waitlist',
        badge: 'WAIT',
        badgeColor: 'warning',
      },
      {
        id: 'admin-referrals',
        label: 'الإحالات — تحليل الشبكة',
        path: '/admin/referrals',
        badge: 'REF',
        badgeColor: 'info',
      },
      {
        id: 'referral-portal',
        label: 'بوابة الإحالات الخارجية',
        path: '/referrals',
        badge: 'REF',
        badgeColor: 'primary',
      },
      {
        id: 'admin-revenue',
        label: 'الإيرادات والذمم',
        path: '/admin/revenue',
        badge: 'AR',
        badgeColor: 'success',
      },
      {
        id: 'admin-claims-analytics',
        label: 'تحليلات مطالبات NPHIES',
        path: '/admin/claims-analytics',
        badge: 'CLM',
        badgeColor: 'info',
      },
      {
        id: 'admin-revenue-forecast',
        label: 'تنبؤ الإيرادات',
        path: '/admin/revenue-forecast',
        badge: 'FCST',
        badgeColor: 'primary',
      },
      {
        id: 'admin-retention',
        label: 'الاحتفاظ والتسرّب',
        path: '/admin/retention',
        badge: 'RET',
        badgeColor: 'warning',
      },
      {
        id: 'admin-complaints-analytics',
        label: 'تحليلات الشكاوى',
        path: '/admin/complaints-analytics',
        badge: 'CMP',
        badgeColor: 'error',
      },
      {
        id: 'admin-document-expiry',
        label: 'رادار انتهاء الوثائق',
        path: '/admin/document-expiry',
        badge: 'EXP',
        badgeColor: 'error',
      },
      {
        id: 'admin-incidents-analytics',
        label: 'تحليلات الحوادث والسلامة',
        path: '/admin/incidents-analytics',
        badge: 'INC',
        badgeColor: 'error',
      },
      {
        id: 'admin-saudization',
        label: 'نطاقات — التوطين المباشر',
        path: '/admin/saudization',
        badge: 'SAU',
        badgeColor: 'success',
      },
      {
        id: 'admin-onboarding',
        label: 'إعداد الموظفين الجدد',
        path: '/admin/onboarding',
        badge: 'OBN',
        badgeColor: 'info',
      },
      {
        id: 'admin-integrations-ops',
        label: 'لوحة عمليات التكاملات',
        path: '/admin/integrations-ops',
        badge: 'OPS',
        badgeColor: 'primary',
      },
      {
        id: 'admin-gov-integrations',
        label: 'التكاملات الحكومية',
        path: '/admin/gov-integrations',
        badge: 'GOV',
        badgeColor: 'error',
      },
      {
        id: 'admin-rate-limits',
        label: 'حدود الاستخدام',
        path: '/admin/rate-limits',
        badge: 'LIMIT',
        badgeColor: 'info',
      },
      {
        id: 'admin-adapter-audit',
        label: 'سجل تدقيق التكاملات (PDPL)',
        path: '/admin/adapter-audit',
        badge: 'PDPL',
        badgeColor: 'secondary',
      },
      {
        id: 'admin-nphies-claims',
        label: 'المطالبات التأمينية (NPHIES)',
        path: '/admin/nphies-claims',
        badge: 'NPHIES',
        badgeColor: 'success',
      },
      {
        id: 'admin-insurance-tariffs',
        label: 'تعريفات أسعار التأمين',
        path: '/insurance-tariffs',
        badge: 'NPHIES',
        badgeColor: 'success',
      },
      {
        id: 'admin-zatca-credentials',
        label: 'بيانات اعتماد ZATCA',
        path: '/zatca-credentials',
        badge: 'ZATCA',
        badgeColor: 'warning',
      },
      {
        id: 'admin-zatca-chain-integrity',
        label: 'سلامة سلسلة فواتير ZATCA',
        path: '/admin-portal/zatca-chain-integrity',
        badge: 'P1',
        badgeColor: 'error',
      },
      {
        id: 'admin-management-review',
        label: 'مراجعات الإدارة (ISO 9.3)',
        path: '/quality/management-review',
        badge: 'CBAHI',
        badgeColor: 'info',
      },
      {
        id: 'admin-evidence-vault',
        label: 'خزنة الأدلة',
        path: '/quality/evidence',
        badge: 'CBAHI',
        badgeColor: 'info',
      },
      {
        id: 'admin-compliance-calendar',
        label: 'تقويم الامتثال',
        path: '/quality/compliance-calendar',
        badge: 'CBAHI',
        badgeColor: 'info',
      },
      {
        id: 'admin-pdpl-dashboard',
        label: 'لوحة امتثال PDPL',
        path: '/quality/pdpl',
        badge: 'PDPL',
        badgeColor: 'error',
      },
      {
        id: 'admin-pdpl-subject-requests',
        label: 'طلبات أصحاب البيانات (PDPL)',
        path: '/quality/pdpl/subject-requests',
        badge: 'PDPL',
        badgeColor: 'error',
      },
      {
        id: 'admin-pdpl-consents',
        label: 'إدارة الموافقات (PDPL)',
        path: '/quality/pdpl/consents',
        badge: 'PDPL',
        badgeColor: 'error',
      },
      {
        id: 'admin-pdpl-breaches',
        label: 'خرق البيانات (مادة 20)',
        path: '/quality/pdpl/breaches',
        badge: 'PDPL',
        badgeColor: 'error',
      },
      {
        id: 'admin-pdpl-processing-records',
        label: 'سجل المعالجة (مادة 32)',
        path: '/quality/pdpl/processing-records',
        badge: 'PDPL',
        badgeColor: 'error',
      },
      {
        id: 'admin-pdpl-access-audit',
        label: 'سجل الوصول (مادة 13)',
        path: '/quality/pdpl/access-audit',
        badge: 'PDPL',
        badgeColor: 'error',
      },
      { id: 'admin-notifications', label: 'التنبيهات الموحَّدة', path: '/admin/notifications' },
      {
        id: 'admin-alerts',
        label: 'مركز التنبيهات',
        path: '/admin/alerts',
        roles: ['admin', 'super_admin', 'manager'],
      },
      {
        id: 'admin-red-flags',
        label: 'العلامات الحمراء',
        path: '/admin/red-flags',
        roles: ['admin', 'super_admin', 'manager', 'quality_coordinator', 'compliance_officer'],
      },
      {
        id: 'admin-capa',
        label: 'الإجراءات التصحيحية (CAPA)',
        path: '/admin/capa',
        roles: ['admin', 'super_admin', 'quality_coordinator', 'compliance_officer', 'manager'],
      },
      {
        id: 'admin-pdpl-consents',
        label: 'موافقات PDPL',
        path: '/admin/pdpl-consents',
        roles: ['admin', 'super_admin', 'compliance_officer', 'dpo'],
      },
      {
        id: 'admin-session-amendments',
        label: 'تدقيق تعديلات الجلسات',
        path: '/admin/session-amendments',
        roles: ['admin', 'super_admin', 'clinical_supervisor', 'manager'],
      },
      {
        id: 'admin-branch-license-expiry',
        label: 'تراخيص الفروع',
        path: '/admin/branch-license-expiry',
        roles: ['admin', 'super_admin', 'manager'],
      },
      { id: 'admin-bookings', label: 'حجوزات الموقع', path: '/admin/bookings' },
      { id: 'admin-applications', label: 'طلبات التوظيف', path: '/admin/applications' },
    ],
  },
  {
    id: 'admin-portal',
    label: 'لوحة الإدارة',
    icon: <AdminIcon />,
    roles: ['admin', 'super_admin'],
    children: [
      { id: 'admin-main', label: 'اللوحة الرئيسية', path: '/admin-portal' },
      { id: 'admin-settings', label: 'إعدادات النظام', path: '/admin-portal/settings' },
      { id: 'admin-branding', label: 'الهوية والتصميم', path: '/admin-portal/branding' },
      { id: 'admin-audit', label: 'سجل المراجعة', path: '/admin-portal/audit-logs' },
      { id: 'admin-reports', label: 'التقارير', path: '/admin-portal/reports' },
    ],
  },
  // نظام إدارة المستخدمين المتقدم — مع وصول HR و المديرين
  {
    id: 'user-management-standalone',
    label: 'إدارة المستخدمين',
    icon: <PeopleIcon />,
    path: '/user-management',
    roles: ['admin', 'super_admin', 'hr', 'hr_manager', 'manager'],
  },
  {
    id: 'system-admin',
    label: 'إدارة النظام',
    icon: <AdminIcon />,
    path: '/system-admin',
    roles: ['admin', 'super_admin'],
  },
  {
    id: 'security',
    label: 'الأمان',
    icon: <SecurityIcon />,
    path: '/security',
    roles: ['admin', 'super_admin'],
    children: [
      { id: 'security-settings', label: 'إعدادات الأمان', path: '/security' },
      {
        id: 'access-control-dashboard',
        label: 'لوحة الصلاحيات والوصول',
        path: '/access-control',
        roles: ['admin', 'super_admin', 'it_admin'],
        badge: 'جديد',
        badgeColor: 'primary',
      },
      {
        id: 'admin-break-glass',
        label: 'الوصول الطارئ (Break-Glass)',
        path: '/admin/break-glass',
        roles: ['admin', 'super_admin'],
        badge: 'SEC',
        badgeColor: 'error',
      },
      {
        id: 'admin-mfa-compliance',
        label: 'امتثال المصادقة الثنائية',
        path: '/admin-portal/mfa-compliance',
        badge: 'P1',
        badgeColor: 'warning',
      },
    ],
  },
  {
    id: 'sso-admin',
    label: 'الدخول الموحد (SSO)',
    icon: <SSOIcon />,
    path: '/sso-admin',
    roles: ['admin', 'super_admin'],
  },
  // ─── أنظمة متقدمة ───
  {
    id: 'blockchain-certificates',
    label: 'شهادات البلوكتشين',
    icon: <BlockchainIcon />,
    roles: ['admin', 'super_admin'],
    children: [
      { id: 'bc-dashboard', label: 'لوحة الشهادات', path: '/blockchain-certificates' },
      { id: 'bc-templates', label: 'القوالب', path: '/blockchain-certificates/templates' },
      { id: 'bc-batch', label: 'إصدار بالجملة', path: '/blockchain-certificates/batch-issue' },
      { id: 'bc-logs', label: 'سجل التحقق', path: '/blockchain-certificates/logs' },
    ],
  },
  {
    id: 'helpdesk',
    label: 'الدعم الفني',
    icon: <HelpDeskIcon />,
    path: '/helpdesk',
    roles: ['*'],
  },
  {
    id: 'settings',
    label: 'الإعدادات',
    icon: <SettingsIcon />,
    path: '/profile',
    roles: ['*'],
  },
];

export default getNavigationItems;
