/**
 * Chart of Accounts Seed
 * دليل الحسابات - مركز التأهيل
 * Saudi GAAP / IFRS compliant for non-profit rehabilitation centers
 */

'use strict';

/**
 * Account types:
 *  asset, liability, equity, revenue, expense
 * Normal balance:
 *  debit (assets, expenses), credit (liabilities, equity, revenue)
 */
const accounts = [
  // ══════════════════════════════════════════════════
  // 1 - الأصول (Assets)
  // ══════════════════════════════════════════════════
  {
    code: '1000',
    name: { ar: 'الأصول', en: 'Assets' },
    type: 'asset',
    normalBalance: 'debit',
    isParent: true,
    level: 1,
    parentCode: null,
  },

  // الأصول المتداولة
  {
    code: '1100',
    name: { ar: 'الأصول المتداولة', en: 'Current Assets' },
    type: 'asset',
    normalBalance: 'debit',
    isParent: true,
    level: 2,
    parentCode: '1000',
  },
  {
    code: '1110',
    name: { ar: 'النقد والأرصدة', en: 'Cash & Cash Equivalents' },
    type: 'asset',
    normalBalance: 'debit',
    isParent: true,
    level: 3,
    parentCode: '1100',
  },
  {
    code: '1111',
    name: { ar: 'الصندوق الرئيسي', en: 'Main Cash' },
    type: 'asset',
    normalBalance: 'debit',
    isParent: false,
    level: 4,
    parentCode: '1110',
  },
  {
    code: '1112',
    name: { ar: 'صندوق العهدة', en: 'Petty Cash' },
    type: 'asset',
    normalBalance: 'debit',
    isParent: false,
    level: 4,
    parentCode: '1110',
  },
  {
    code: '1113',
    name: { ar: 'البنك الأهلي السعودي', en: 'Saudi National Bank' },
    type: 'asset',
    normalBalance: 'debit',
    isParent: false,
    level: 4,
    parentCode: '1110',
  },
  {
    code: '1114',
    name: { ar: 'بنك الراجحي', en: 'Al Rajhi Bank' },
    type: 'asset',
    normalBalance: 'debit',
    isParent: false,
    level: 4,
    parentCode: '1110',
  },
  {
    code: '1115',
    name: { ar: 'بنك آخر', en: 'Other Bank' },
    type: 'asset',
    normalBalance: 'debit',
    isParent: false,
    level: 4,
    parentCode: '1110',
  },

  {
    code: '1120',
    name: { ar: 'الذمم المدينة', en: 'Accounts Receivable' },
    type: 'asset',
    normalBalance: 'debit',
    isParent: true,
    level: 3,
    parentCode: '1100',
  },
  {
    code: '1121',
    name: { ar: 'مديونية العملاء الأفراد', en: 'Individual Clients Receivable' },
    type: 'asset',
    normalBalance: 'debit',
    isParent: false,
    level: 4,
    parentCode: '1120',
  },
  {
    code: '1122',
    name: { ar: 'مديونية الجهات الحكومية', en: 'Government Entities Receivable' },
    type: 'asset',
    normalBalance: 'debit',
    isParent: false,
    level: 4,
    parentCode: '1120',
  },
  {
    code: '1123',
    name: { ar: 'مديونية شركات التأمين', en: 'Insurance Companies Receivable' },
    type: 'asset',
    normalBalance: 'debit',
    isParent: false,
    level: 4,
    parentCode: '1120',
  },
  {
    code: '1124',
    name: { ar: 'مخصص الديون المشكوك فيها', en: 'Allowance for Doubtful Accounts' },
    type: 'asset',
    normalBalance: 'credit',
    isParent: false,
    level: 4,
    parentCode: '1120',
  },

  {
    code: '1130',
    name: { ar: 'المخزون والمستلزمات', en: 'Inventory & Supplies' },
    type: 'asset',
    normalBalance: 'debit',
    isParent: true,
    level: 3,
    parentCode: '1100',
  },
  {
    code: '1131',
    name: { ar: 'مستلزمات طبية', en: 'Medical Supplies' },
    type: 'asset',
    normalBalance: 'debit',
    isParent: false,
    level: 4,
    parentCode: '1130',
  },
  {
    code: '1132',
    name: { ar: 'مستلزمات مكتبية', en: 'Office Supplies' },
    type: 'asset',
    normalBalance: 'debit',
    isParent: false,
    level: 4,
    parentCode: '1130',
  },
  {
    code: '1133',
    name: { ar: 'أدوية ومستحضرات', en: 'Medications & Preparations' },
    type: 'asset',
    normalBalance: 'debit',
    isParent: false,
    level: 4,
    parentCode: '1130',
  },

  {
    code: '1140',
    name: { ar: 'مدفوعات مقدمة', en: 'Prepaid Expenses' },
    type: 'asset',
    normalBalance: 'debit',
    isParent: true,
    level: 3,
    parentCode: '1100',
  },
  {
    code: '1141',
    name: { ar: 'إيجار مدفوع مقدماً', en: 'Prepaid Rent' },
    type: 'asset',
    normalBalance: 'debit',
    isParent: false,
    level: 4,
    parentCode: '1140',
  },
  {
    code: '1142',
    name: { ar: 'تأمين مدفوع مقدماً', en: 'Prepaid Insurance' },
    type: 'asset',
    normalBalance: 'debit',
    isParent: false,
    level: 4,
    parentCode: '1140',
  },
  {
    code: '1143',
    name: { ar: 'سلفيات الموظفين', en: 'Employee Advances' },
    type: 'asset',
    normalBalance: 'debit',
    isParent: false,
    level: 4,
    parentCode: '1140',
  },

  // الأصول الثابتة
  {
    code: '1200',
    name: { ar: 'الأصول غير المتداولة', en: 'Non-Current Assets' },
    type: 'asset',
    normalBalance: 'debit',
    isParent: true,
    level: 2,
    parentCode: '1000',
  },
  {
    code: '1210',
    name: { ar: 'الأصول الثابتة', en: 'Property, Plant & Equipment' },
    type: 'asset',
    normalBalance: 'debit',
    isParent: true,
    level: 3,
    parentCode: '1200',
  },
  {
    code: '1211',
    name: { ar: 'الأراضي والمباني', en: 'Land & Buildings' },
    type: 'asset',
    normalBalance: 'debit',
    isParent: false,
    level: 4,
    parentCode: '1210',
  },
  {
    code: '1212',
    name: { ar: 'الأجهزة والمعدات الطبية', en: 'Medical Devices & Equipment' },
    type: 'asset',
    normalBalance: 'debit',
    isParent: false,
    level: 4,
    parentCode: '1210',
  },
  {
    code: '1213',
    name: { ar: 'الأثاث والتجهيزات', en: 'Furniture & Fittings' },
    type: 'asset',
    normalBalance: 'debit',
    isParent: false,
    level: 4,
    parentCode: '1210',
  },
  {
    code: '1214',
    name: { ar: 'أجهزة الحاسوب والتقنية', en: 'Computers & Technology' },
    type: 'asset',
    normalBalance: 'debit',
    isParent: false,
    level: 4,
    parentCode: '1210',
  },
  {
    code: '1215',
    name: { ar: 'السيارات والمركبات', en: 'Vehicles' },
    type: 'asset',
    normalBalance: 'debit',
    isParent: false,
    level: 4,
    parentCode: '1210',
  },
  {
    code: '1219',
    name: { ar: 'مجمع إهلاك الأصول الثابتة', en: 'Accumulated Depreciation' },
    type: 'asset',
    normalBalance: 'credit',
    isParent: false,
    level: 4,
    parentCode: '1210',
  },

  // ══════════════════════════════════════════════════
  // 2 - الخصوم (Liabilities)
  // ══════════════════════════════════════════════════
  {
    code: '2000',
    name: { ar: 'الخصوم', en: 'Liabilities' },
    type: 'liability',
    normalBalance: 'credit',
    isParent: true,
    level: 1,
    parentCode: null,
  },

  {
    code: '2100',
    name: { ar: 'الخصوم المتداولة', en: 'Current Liabilities' },
    type: 'liability',
    normalBalance: 'credit',
    isParent: true,
    level: 2,
    parentCode: '2000',
  },
  {
    code: '2110',
    name: { ar: 'الذمم الدائنة', en: 'Accounts Payable' },
    type: 'liability',
    normalBalance: 'credit',
    isParent: false,
    level: 3,
    parentCode: '2100',
  },
  {
    code: '2120',
    name: { ar: 'مستحقات ضريبة القيمة المضافة', en: 'VAT Payable' },
    type: 'liability',
    normalBalance: 'credit',
    isParent: false,
    level: 3,
    parentCode: '2100',
  },
  {
    code: '2121',
    name: { ar: 'ضريبة القيمة المضافة المحصلة', en: 'Output VAT' },
    type: 'liability',
    normalBalance: 'credit',
    isParent: false,
    level: 4,
    parentCode: '2120',
  },
  {
    code: '2122',
    name: { ar: 'ضريبة القيمة المضافة القابلة للاسترداد', en: 'Input VAT' },
    type: 'liability',
    normalBalance: 'debit',
    isParent: false,
    level: 4,
    parentCode: '2120',
  },
  {
    code: '2130',
    name: { ar: 'مستحقات الموظفين', en: 'Accrued Salaries & Wages' },
    type: 'liability',
    normalBalance: 'credit',
    isParent: false,
    level: 3,
    parentCode: '2100',
  },
  {
    code: '2131',
    name: { ar: 'رواتب مستحقة', en: 'Salaries Payable' },
    type: 'liability',
    normalBalance: 'credit',
    isParent: false,
    level: 4,
    parentCode: '2130',
  },
  {
    code: '2132',
    name: { ar: 'مستحقات التأمينات الاجتماعية (GOSI)', en: 'GOSI Contributions Payable' },
    type: 'liability',
    normalBalance: 'credit',
    isParent: false,
    level: 4,
    parentCode: '2130',
  },
  {
    code: '2133',
    name: { ar: 'مستحقات مكافأة نهاية الخدمة', en: 'End of Service Benefits Payable' },
    type: 'liability',
    normalBalance: 'credit',
    isParent: false,
    level: 4,
    parentCode: '2130',
  },
  {
    code: '2140',
    name: { ar: 'إيرادات مؤجلة', en: 'Deferred Revenue' },
    type: 'liability',
    normalBalance: 'credit',
    isParent: false,
    level: 3,
    parentCode: '2100',
  },
  {
    code: '2150',
    name: { ar: 'قروض قصيرة الأجل', en: 'Short-term Loans' },
    type: 'liability',
    normalBalance: 'credit',
    isParent: false,
    level: 3,
    parentCode: '2100',
  },

  {
    code: '2200',
    name: { ar: 'الخصوم طويلة الأجل', en: 'Long-term Liabilities' },
    type: 'liability',
    normalBalance: 'credit',
    isParent: true,
    level: 2,
    parentCode: '2000',
  },
  {
    code: '2210',
    name: { ar: 'قروض طويلة الأجل', en: 'Long-term Loans' },
    type: 'liability',
    normalBalance: 'credit',
    isParent: false,
    level: 3,
    parentCode: '2200',
  },
  {
    code: '2220',
    name: { ar: 'مخصص مكافأة نهاية الخدمة', en: 'End of Service Benefits Reserve' },
    type: 'liability',
    normalBalance: 'credit',
    isParent: false,
    level: 3,
    parentCode: '2200',
  },

  // ══════════════════════════════════════════════════
  // 3 - حقوق الملكية (Equity)
  // ══════════════════════════════════════════════════
  {
    code: '3000',
    name: { ar: 'حقوق الملكية', en: 'Equity' },
    type: 'equity',
    normalBalance: 'credit',
    isParent: true,
    level: 1,
    parentCode: null,
  },
  {
    code: '3100',
    name: { ar: 'رأس المال', en: 'Capital' },
    type: 'equity',
    normalBalance: 'credit',
    isParent: false,
    level: 2,
    parentCode: '3000',
  },
  {
    code: '3200',
    name: { ar: 'الاحتياطيات', en: 'Reserves' },
    type: 'equity',
    normalBalance: 'credit',
    isParent: false,
    level: 2,
    parentCode: '3000',
  },
  {
    code: '3300',
    name: { ar: 'الأرباح المبقاة', en: 'Retained Earnings' },
    type: 'equity',
    normalBalance: 'credit',
    isParent: false,
    level: 2,
    parentCode: '3000',
  },
  {
    code: '3400',
    name: { ar: 'صافي الربح/الخسارة للسنة', en: 'Net Profit/Loss for the Year' },
    type: 'equity',
    normalBalance: 'credit',
    isParent: false,
    level: 2,
    parentCode: '3000',
  },

  // ══════════════════════════════════════════════════
  // 4 - الإيرادات (Revenue)
  // ══════════════════════════════════════════════════
  {
    code: '4000',
    name: { ar: 'الإيرادات', en: 'Revenue' },
    type: 'revenue',
    normalBalance: 'credit',
    isParent: true,
    level: 1,
    parentCode: null,
  },

  {
    code: '4100',
    name: { ar: 'إيرادات الخدمات التأهيلية', en: 'Rehabilitation Services Revenue' },
    type: 'revenue',
    normalBalance: 'credit',
    isParent: true,
    level: 2,
    parentCode: '4000',
  },
  {
    code: '4110',
    name: { ar: 'إيرادات الجلسات الفردية', en: 'Individual Sessions Revenue' },
    type: 'revenue',
    normalBalance: 'credit',
    isParent: false,
    level: 3,
    parentCode: '4100',
  },
  {
    code: '4111',
    name: { ar: 'جلسات العلاج الطبيعي', en: 'Physical Therapy Sessions' },
    type: 'revenue',
    normalBalance: 'credit',
    isParent: false,
    level: 4,
    parentCode: '4110',
  },
  {
    code: '4112',
    name: { ar: 'جلسات العلاج الوظيفي', en: 'Occupational Therapy Sessions' },
    type: 'revenue',
    normalBalance: 'credit',
    isParent: false,
    level: 4,
    parentCode: '4110',
  },
  {
    code: '4113',
    name: { ar: 'جلسات علاج النطق', en: 'Speech Therapy Sessions' },
    type: 'revenue',
    normalBalance: 'credit',
    isParent: false,
    level: 4,
    parentCode: '4110',
  },
  {
    code: '4114',
    name: { ar: 'جلسات الدعم النفسي', en: 'Psychological Support Sessions' },
    type: 'revenue',
    normalBalance: 'credit',
    isParent: false,
    level: 4,
    parentCode: '4110',
  },
  {
    code: '4115',
    name: { ar: 'جلسات التكامل الحسي', en: 'Sensory Integration Sessions' },
    type: 'revenue',
    normalBalance: 'credit',
    isParent: false,
    level: 4,
    parentCode: '4110',
  },
  {
    code: '4120',
    name: { ar: 'إيرادات البرامج التعليمية', en: 'Educational Programs Revenue' },
    type: 'revenue',
    normalBalance: 'credit',
    isParent: false,
    level: 3,
    parentCode: '4100',
  },
  {
    code: '4130',
    name: { ar: 'إيرادات التقييم والتشخيص', en: 'Assessment & Diagnosis Revenue' },
    type: 'revenue',
    normalBalance: 'credit',
    isParent: false,
    level: 3,
    parentCode: '4100',
  },
  {
    code: '4140',
    name: { ar: 'إيرادات الاستشارات', en: 'Consultation Revenue' },
    type: 'revenue',
    normalBalance: 'credit',
    isParent: false,
    level: 3,
    parentCode: '4100',
  },

  {
    code: '4200',
    name: { ar: 'إيرادات التأمين والجهات الحكومية', en: 'Insurance & Government Revenue' },
    type: 'revenue',
    normalBalance: 'credit',
    isParent: true,
    level: 2,
    parentCode: '4000',
  },
  {
    code: '4210',
    name: { ar: 'إيرادات التأمين الصحي', en: 'Health Insurance Revenue' },
    type: 'revenue',
    normalBalance: 'credit',
    isParent: false,
    level: 3,
    parentCode: '4200',
  },
  {
    code: '4220',
    name: { ar: 'إيرادات وزارة الموارد البشرية', en: 'HRSD Ministry Revenue' },
    type: 'revenue',
    normalBalance: 'credit',
    isParent: false,
    level: 3,
    parentCode: '4200',
  },
  {
    code: '4230',
    name: { ar: 'إيرادات برامج دعم الإعاقة', en: 'Disability Support Programs Revenue' },
    type: 'revenue',
    normalBalance: 'credit',
    isParent: false,
    level: 3,
    parentCode: '4200',
  },

  {
    code: '4300',
    name: { ar: 'إيرادات أخرى', en: 'Other Revenue' },
    type: 'revenue',
    normalBalance: 'credit',
    isParent: true,
    level: 2,
    parentCode: '4000',
  },
  {
    code: '4310',
    name: { ar: 'دخل الإيجار', en: 'Rental Income' },
    type: 'revenue',
    normalBalance: 'credit',
    isParent: false,
    level: 3,
    parentCode: '4300',
  },
  {
    code: '4320',
    name: { ar: 'دخل التدريب والتعليم', en: 'Training & Education Income' },
    type: 'revenue',
    normalBalance: 'credit',
    isParent: false,
    level: 3,
    parentCode: '4300',
  },
  {
    code: '4330',
    name: { ar: 'تبرعات ومنح', en: 'Donations & Grants' },
    type: 'revenue',
    normalBalance: 'credit',
    isParent: false,
    level: 3,
    parentCode: '4300',
  },
  {
    code: '4340',
    name: { ar: 'إيرادات متنوعة', en: 'Miscellaneous Revenue' },
    type: 'revenue',
    normalBalance: 'credit',
    isParent: false,
    level: 3,
    parentCode: '4300',
  },

  // ══════════════════════════════════════════════════
  // 5 - المصروفات (Expenses)
  // ══════════════════════════════════════════════════
  {
    code: '5000',
    name: { ar: 'المصروفات', en: 'Expenses' },
    type: 'expense',
    normalBalance: 'debit',
    isParent: true,
    level: 1,
    parentCode: null,
  },

  {
    code: '5100',
    name: { ar: 'مصروفات الرواتب والأجور', en: 'Salaries & Wages Expenses' },
    type: 'expense',
    normalBalance: 'debit',
    isParent: true,
    level: 2,
    parentCode: '5000',
  },
  {
    code: '5110',
    name: { ar: 'رواتب المعالجين والمختصين', en: 'Therapists & Specialists Salaries' },
    type: 'expense',
    normalBalance: 'debit',
    isParent: false,
    level: 3,
    parentCode: '5100',
  },
  {
    code: '5120',
    name: { ar: 'رواتب الإداريين', en: 'Administrative Staff Salaries' },
    type: 'expense',
    normalBalance: 'debit',
    isParent: false,
    level: 3,
    parentCode: '5100',
  },
  {
    code: '5130',
    name: { ar: 'رواتب السائقين والخدمات', en: 'Drivers & Support Staff Salaries' },
    type: 'expense',
    normalBalance: 'debit',
    isParent: false,
    level: 3,
    parentCode: '5100',
  },
  {
    code: '5140',
    name: { ar: 'بدل نقل وسكن', en: 'Transport & Housing Allowances' },
    type: 'expense',
    normalBalance: 'debit',
    isParent: false,
    level: 3,
    parentCode: '5100',
  },
  {
    code: '5150',
    name: { ar: 'حصص التأمينات الاجتماعية (GOSI)', en: 'GOSI Contributions' },
    type: 'expense',
    normalBalance: 'debit',
    isParent: false,
    level: 3,
    parentCode: '5100',
  },
  {
    code: '5160',
    name: { ar: 'مكافأة نهاية الخدمة', en: 'End of Service Benefits' },
    type: 'expense',
    normalBalance: 'debit',
    isParent: false,
    level: 3,
    parentCode: '5100',
  },

  {
    code: '5200',
    name: { ar: 'المصروفات التشغيلية', en: 'Operational Expenses' },
    type: 'expense',
    normalBalance: 'debit',
    isParent: true,
    level: 2,
    parentCode: '5000',
  },
  {
    code: '5210',
    name: { ar: 'إيجار المبنى', en: 'Building Rent' },
    type: 'expense',
    normalBalance: 'debit',
    isParent: false,
    level: 3,
    parentCode: '5200',
  },
  {
    code: '5220',
    name: {
      ar: 'فواتير الخدمات (كهرباء، ماء، إنترنت)',
      en: 'Utilities (Electricity, Water, Internet)',
    },
    type: 'expense',
    normalBalance: 'debit',
    isParent: false,
    level: 3,
    parentCode: '5200',
  },
  {
    code: '5230',
    name: { ar: 'مصروفات النقل والمواصلات', en: 'Transportation Expenses' },
    type: 'expense',
    normalBalance: 'debit',
    isParent: false,
    level: 3,
    parentCode: '5200',
  },
  {
    code: '5231',
    name: { ar: 'وقود المركبات', en: 'Vehicle Fuel' },
    type: 'expense',
    normalBalance: 'debit',
    isParent: false,
    level: 4,
    parentCode: '5230',
  },
  {
    code: '5232',
    name: { ar: 'صيانة المركبات', en: 'Vehicle Maintenance' },
    type: 'expense',
    normalBalance: 'debit',
    isParent: false,
    level: 4,
    parentCode: '5230',
  },
  {
    code: '5233',
    name: { ar: 'تأمين المركبات', en: 'Vehicle Insurance' },
    type: 'expense',
    normalBalance: 'debit',
    isParent: false,
    level: 4,
    parentCode: '5230',
  },
  {
    code: '5240',
    name: { ar: 'مستلزمات ومواد طبية', en: 'Medical Supplies & Materials' },
    type: 'expense',
    normalBalance: 'debit',
    isParent: false,
    level: 3,
    parentCode: '5200',
  },
  {
    code: '5250',
    name: { ar: 'مستلزمات مكتبية', en: 'Office Supplies' },
    type: 'expense',
    normalBalance: 'debit',
    isParent: false,
    level: 3,
    parentCode: '5200',
  },

  {
    code: '5300',
    name: { ar: 'مصروفات إدارية وعمومية', en: 'General & Administrative Expenses' },
    type: 'expense',
    normalBalance: 'debit',
    isParent: true,
    level: 2,
    parentCode: '5000',
  },
  {
    code: '5310',
    name: { ar: 'رسوم ترخيص وتسجيل', en: 'Licensing & Registration Fees' },
    type: 'expense',
    normalBalance: 'debit',
    isParent: false,
    level: 3,
    parentCode: '5300',
  },
  {
    code: '5320',
    name: { ar: 'أتعاب قانونية ومحاسبية', en: 'Legal & Accounting Fees' },
    type: 'expense',
    normalBalance: 'debit',
    isParent: false,
    level: 3,
    parentCode: '5300',
  },
  {
    code: '5330',
    name: { ar: 'تأمين المنشأة والمعدات', en: 'Facility & Equipment Insurance' },
    type: 'expense',
    normalBalance: 'debit',
    isParent: false,
    level: 3,
    parentCode: '5300',
  },
  {
    code: '5340',
    name: { ar: 'مصروفات التسويق والإعلان', en: 'Marketing & Advertising' },
    type: 'expense',
    normalBalance: 'debit',
    isParent: false,
    level: 3,
    parentCode: '5300',
  },
  {
    code: '5350',
    name: { ar: 'صيانة المبنى والمعدات', en: 'Building & Equipment Maintenance' },
    type: 'expense',
    normalBalance: 'debit',
    isParent: false,
    level: 3,
    parentCode: '5300',
  },
  {
    code: '5360',
    name: { ar: 'تكنولوجيا المعلومات والبرمجيات', en: 'IT & Software Expenses' },
    type: 'expense',
    normalBalance: 'debit',
    isParent: false,
    level: 3,
    parentCode: '5300',
  },

  {
    code: '5400',
    name: { ar: 'مصروفات التدريب والتطوير', en: 'Training & Development Expenses' },
    type: 'expense',
    normalBalance: 'debit',
    isParent: true,
    level: 2,
    parentCode: '5000',
  },
  {
    code: '5410',
    name: { ar: 'تدريب الموظفين', en: 'Employee Training' },
    type: 'expense',
    normalBalance: 'debit',
    isParent: false,
    level: 3,
    parentCode: '5400',
  },
  {
    code: '5420',
    name: { ar: 'مؤتمرات وندوات', en: 'Conferences & Seminars' },
    type: 'expense',
    normalBalance: 'debit',
    isParent: false,
    level: 3,
    parentCode: '5400',
  },

  {
    code: '5500',
    name: { ar: 'الإهلاك والاستهلاك', en: 'Depreciation & Amortization' },
    type: 'expense',
    normalBalance: 'debit',
    isParent: true,
    level: 2,
    parentCode: '5000',
  },
  {
    code: '5510',
    name: { ar: 'إهلاك الأصول الثابتة', en: 'Fixed Assets Depreciation' },
    type: 'expense',
    normalBalance: 'debit',
    isParent: false,
    level: 3,
    parentCode: '5500',
  },
  {
    code: '5520',
    name: { ar: 'استهلاك الأصول غير الملموسة', en: 'Intangible Assets Amortization' },
    type: 'expense',
    normalBalance: 'debit',
    isParent: false,
    level: 3,
    parentCode: '5500',
  },

  {
    code: '5600',
    name: { ar: 'مصروفات مالية', en: 'Financial Expenses' },
    type: 'expense',
    normalBalance: 'debit',
    isParent: true,
    level: 2,
    parentCode: '5000',
  },
  {
    code: '5610',
    name: { ar: 'فوائد بنكية', en: 'Bank Interest' },
    type: 'expense',
    normalBalance: 'debit',
    isParent: false,
    level: 3,
    parentCode: '5600',
  },
  {
    code: '5620',
    name: { ar: 'رسوم بنكية', en: 'Bank Charges' },
    type: 'expense',
    normalBalance: 'debit',
    isParent: false,
    level: 3,
    parentCode: '5600',
  },
  {
    code: '5630',
    name: { ar: 'خسائر ديون معدومة', en: 'Bad Debt Losses' },
    type: 'expense',
    normalBalance: 'debit',
    isParent: false,
    level: 3,
    parentCode: '5600',
  },

  {
    code: '5900',
    name: { ar: 'مصروفات أخرى', en: 'Other Expenses' },
    type: 'expense',
    normalBalance: 'debit',
    isParent: false,
    level: 2,
    parentCode: '5000',
  },
];

async function seed(connection) {
  const db = connection.db || connection;
  const col = db.collection('chartofaccounts');

  // Build code→_id map for parent references
  const idMap = {};

  let upserted = 0;
  let skipped = 0;

  for (const acct of accounts) {
    const { parentCode, ...acctData } = acct;

    const doc = {
      ...acctData,
      parentAccount: null,
      balance: 0,
      isActive: true,
      metadata: { isSystem: true },
      createdAt: new Date(),
      updatedAt: new Date(),
    };

    if (parentCode && idMap[parentCode]) {
      doc.parentAccount = idMap[parentCode];
    }

    const result = await col.updateOne(
      { code: acct.code },
      {
        $setOnInsert: doc,
        $set: {
          updatedAt: new Date(),
          name: acctData.name,
          isParent: acctData.isParent,
        },
      },
      { upsert: true }
    );

    if (result.upsertedId) {
      idMap[acct.code] = result.upsertedId;
      upserted++;
    } else {
      const existing = await col.findOne({ code: acct.code }, { projection: { _id: 1 } });
      if (existing) idMap[acct.code] = existing._id;
      skipped++;
    }
  }

  console.log(`  ✔ chart-of-accounts: ${upserted} inserted, ${skipped} already existed`);
}

async function down(connection) {
  const db = connection.db || connection;
  const result = await db.collection('chartofaccounts').deleteMany({ 'metadata.isSystem': true });
  console.log(`  ✔ chart-of-accounts: removed ${result.deletedCount} system accounts`);
}

module.exports = { seed, down };
