/**
 * @file comprehensive-beneficiaries.seed.js
 * @description بيانات مستفيدين شاملة وواقعية - 50 مستفيد عبر 3 فروع
 * Comprehensive realistic beneficiaries seed - Al-Awael ERP
 * DEV/STAGING only - NOT for production
 */

'use strict';

const { ObjectId } = require('mongodb');
const { EXTRA_BENEFICIARIES, mergeWithDefaults } = require('./seed-extensions.config');

// ─────────────────────────────────────────────────────────────────────────────
// Helper: حساب العمر
// ─────────────────────────────────────────────────────────────────────────────
function calcAge(dob) {
  const now = new Date();
  return Math.floor((now - new Date(dob)) / (365.25 * 24 * 60 * 60 * 1000));
}

// ─────────────────────────────────────────────────────────────────────────────
// بيانات المستفيدين الشاملة
// ─────────────────────────────────────────────────────────────────────────────
const COMPREHENSIVE_BENEFICIARIES = [
  // ══════════════════════════════════════════════════════════════════
  // فرع الرياض - RUH-MAIN (20 مستفيد)
  // ══════════════════════════════════════════════════════════════════
  {
    beneficiaryNumber: 'RUH-2024-001',
    name: { ar: 'يزيد بن فهد المطيري', en: 'Yazeed Fahad Al-Mutairi' },
    gender: 'male',
    dateOfBirth: new Date('2019-03-15'),
    nationalId: '1100234561',
    nationality: 'SA',
    primaryDisability: 'AUTISM',
    disabilityLevel: 'ASD_L2',
    caseStatus: 'active',
    guardian: {
      name: { ar: 'فهد سالم المطيري', en: 'Fahad Salem Al-Mutairi' },
      relationship: 'father',
      phone: '0501234501',
      email: 'fahad.mutairi.2024@gmail.com',
      nationalId: '1089234501',
    },
    address: { city: 'الرياض', district: 'الملقا', region: 'الرياض' },
    referralSource: 'hospital',
    enrollmentDate: new Date('2024-09-01'),
    insurance: { provider: 'bupa', policyNumber: 'BUPA-788901', class: 'A' },
    programs: ['OT_AUTISM', 'ST_AUTISM', 'PSY_BEHAVIORAL'],
    branchCode: 'RUH-MAIN',
    transportRequired: true,
    transportAddress: 'حي الملقا، الرياض',
  },
  {
    beneficiaryNumber: 'RUH-2024-002',
    name: { ar: 'لمى بنت عبدالرحمن القحطاني', en: 'Lama Abdulrahman Al-Qahtani' },
    gender: 'female',
    dateOfBirth: new Date('2018-07-22'),
    nationalId: '1100234562',
    nationality: 'SA',
    primaryDisability: 'SPEECH_DELAY',
    disabilityLevel: 'SD_MODERATE',
    caseStatus: 'active',
    guardian: {
      name: { ar: 'عبدالرحمن حمد القحطاني', en: 'Abdulrahman Hamad Al-Qahtani' },
      relationship: 'father',
      phone: '0502234502',
      email: 'abdurahman.q2024@gmail.com',
      nationalId: '1086234502',
    },
    address: { city: 'الرياض', district: 'العليا', region: 'الرياض' },
    referralSource: 'pediatrician',
    enrollmentDate: new Date('2024-06-15'),
    insurance: { provider: 'tawuniya', policyNumber: 'TAW-234567', class: 'B' },
    programs: ['ST_AUTISM', 'ST_BASIC'],
    branchCode: 'RUH-MAIN',
    transportRequired: false,
  },
  {
    beneficiaryNumber: 'RUH-2023-003',
    name: { ar: 'عبدالعزيز بن خالد الشهراني', en: 'Abdulaziz Khalid Al-Shahrani' },
    gender: 'male',
    dateOfBirth: new Date('2017-01-10'),
    nationalId: '1100234563',
    nationality: 'SA',
    primaryDisability: 'PHYSICAL',
    disabilityLevel: 'CP',
    caseStatus: 'active',
    guardian: {
      name: { ar: 'خالد محمد الشهراني', en: 'Khalid Mohammed Al-Shahrani' },
      relationship: 'father',
      phone: '0503234503',
      email: 'khalid.shahrani@outlook.com',
      nationalId: '1083234503',
    },
    address: { city: 'الرياض', district: 'الورود', region: 'الرياض' },
    referralSource: 'hospital',
    enrollmentDate: new Date('2023-01-20'),
    insurance: { provider: 'medgulf', policyNumber: 'MG-345678', class: 'A' },
    programs: ['PT_NEURO', 'OT_BASIC', 'ST_BASIC', 'ADL_BASIC'],
    branchCode: 'RUH-MAIN',
    transportRequired: true,
    transportAddress: 'حي الورود، الرياض',
  },
  {
    beneficiaryNumber: 'RUH-2024-004',
    name: { ar: 'ريناد بنت سعود العتيبي', en: 'Rinad Saud Al-Otaibi' },
    gender: 'female',
    dateOfBirth: new Date('2020-11-05'),
    nationalId: '1100234564',
    nationality: 'SA',
    primaryDisability: 'INTELLECTUAL',
    disabilityLevel: 'DS',
    caseStatus: 'active',
    guardian: {
      name: { ar: 'سعود عبدالله العتيبي', en: 'Saud Abdullah Al-Otaibi' },
      relationship: 'father',
      phone: '0504234504',
      email: 'saud.otaibi2024@gmail.com',
      nationalId: '1080234504',
    },
    address: { city: 'الرياض', district: 'النرجس', region: 'الرياض' },
    referralSource: 'hospital',
    enrollmentDate: new Date('2024-02-01'),
    insurance: { provider: 'bupa', policyNumber: 'BUPA-456789', class: 'VIP' },
    programs: ['SE_ID', 'PT_PEDIATRIC', 'ST_BASIC', 'ADL_BASIC'],
    branchCode: 'RUH-MAIN',
    transportRequired: true,
    transportAddress: 'حي النرجس، الرياض',
  },
  {
    beneficiaryNumber: 'RUH-2023-005',
    name: { ar: 'تركي بن ماجد الحربي', en: 'Turki Majed Al-Harbi' },
    gender: 'male',
    dateOfBirth: new Date('2016-05-18'),
    nationalId: '1100234565',
    nationality: 'SA',
    primaryDisability: 'INTELLECTUAL',
    disabilityLevel: 'ID_MILD',
    caseStatus: 'active',
    guardian: {
      name: { ar: 'ماجد ناصر الحربي', en: 'Majed Nasser Al-Harbi' },
      relationship: 'father',
      phone: '0505234505',
      email: 'majed.harbi@gmail.com',
      nationalId: '1077234505',
    },
    address: { city: 'الرياض', district: 'الياسمين', region: 'الرياض' },
    referralSource: 'ministry_of_education',
    enrollmentDate: new Date('2023-09-01'),
    insurance: { provider: 'tawuniya', policyNumber: 'TAW-567890', class: 'A' },
    programs: ['SE_ID', 'OT_BASIC', 'PSY_FAMILY'],
    branchCode: 'RUH-MAIN',
    transportRequired: false,
  },
  {
    beneficiaryNumber: 'RUH-2024-006',
    name: { ar: 'جود بنت فيصل السبيعي', en: 'Joud Faisal Al-Subaie' },
    gender: 'female',
    dateOfBirth: new Date('2019-08-30'),
    nationalId: '1100234566',
    nationality: 'SA',
    primaryDisability: 'HEARING',
    disabilityLevel: 'DEAF',
    caseStatus: 'active',
    guardian: {
      name: { ar: 'فيصل عبدالله السبيعي', en: 'Faisal Abdullah Al-Subaie' },
      relationship: 'father',
      phone: '0506234506',
      email: 'faisal.subaie@gmail.com',
      nationalId: '1074234506',
    },
    address: { city: 'الرياض', district: 'المروج', region: 'الرياض' },
    referralSource: 'hospital',
    enrollmentDate: new Date('2024-01-15'),
    insurance: { provider: 'walaa', policyNumber: 'WAL-678901', class: 'B' },
    programs: ['ST_BASIC', 'SE_AUTISM'],
    branchCode: 'RUH-MAIN',
    transportRequired: true,
    transportAddress: 'حي المروج، الرياض',
  },
  {
    beneficiaryNumber: 'RUH-2022-007',
    name: { ar: 'سلطان بن بندر الدوسري', en: 'Sultan Bander Al-Dosari' },
    gender: 'male',
    dateOfBirth: new Date('2015-12-01'),
    nationalId: '1100234567',
    nationality: 'SA',
    primaryDisability: 'AUTISM',
    disabilityLevel: 'ASD_L3',
    caseStatus: 'active',
    guardian: {
      name: { ar: 'بندر سعود الدوسري', en: 'Bander Saud Al-Dosari' },
      relationship: 'father',
      phone: '0507234507',
      email: 'bander.dosari@gmail.com',
      nationalId: '1071234507',
    },
    address: { city: 'الرياض', district: 'الروضة', region: 'الرياض' },
    referralSource: 'hospital',
    enrollmentDate: new Date('2022-03-01'),
    insurance: { provider: 'bupa', policyNumber: 'BUPA-789012', class: 'A' },
    programs: ['OT_AUTISM', 'ST_AUTISM', 'PSY_BEHAVIORAL', 'SE_AUTISM'],
    branchCode: 'RUH-MAIN',
    transportRequired: true,
    transportAddress: 'حي الروضة، الرياض',
  },
  {
    beneficiaryNumber: 'RUH-2025-008',
    name: { ar: 'نوف بنت إبراهيم الراشد', en: 'Nouf Ibrahim Al-Rashed' },
    gender: 'female',
    dateOfBirth: new Date('2020-04-12'),
    nationalId: '1100234568',
    nationality: 'SA',
    primaryDisability: 'DEVELOPMENTAL_DELAY',
    disabilityLevel: 'GDD',
    caseStatus: 'active',
    guardian: {
      name: { ar: 'إبراهيم سالم الراشد', en: 'Ibrahim Salem Al-Rashed' },
      relationship: 'father',
      phone: '0508234508',
      email: 'ibrahim.rashed@outlook.com',
      nationalId: '1068234508',
    },
    address: { city: 'الرياض', district: 'الصحافة', region: 'الرياض' },
    referralSource: 'pediatrician',
    enrollmentDate: new Date('2025-01-01'),
    insurance: { provider: 'medgulf', policyNumber: 'MG-890123', class: 'B' },
    programs: ['ST_BASIC', 'OT_BASIC'],
    branchCode: 'RUH-MAIN',
    transportRequired: false,
  },
  {
    beneficiaryNumber: 'RUH-2024-009',
    name: { ar: 'مشاري بن حمد الغامدي', en: 'Mishari Hamad Al-Ghamdi' },
    gender: 'male',
    dateOfBirth: new Date('2018-02-28'),
    nationalId: '1100234569',
    nationality: 'SA',
    primaryDisability: 'ADHD',
    disabilityLevel: 'ADHD_CO',
    caseStatus: 'active',
    guardian: {
      name: { ar: 'حمد سعد الغامدي', en: 'Hamad Saad Al-Ghamdi' },
      relationship: 'father',
      phone: '0509234509',
      email: 'hamad.ghamdi@gmail.com',
      nationalId: '1065234509',
    },
    address: { city: 'الرياض', district: 'السليمانية', region: 'الرياض' },
    referralSource: 'psychiatrist',
    enrollmentDate: new Date('2024-10-01'),
    insurance: { provider: 'tawuniya', policyNumber: 'TAW-901234', class: 'A' },
    programs: ['PSY_BEHAVIORAL', 'OT_SENSORY'],
    branchCode: 'RUH-MAIN',
    transportRequired: false,
  },
  {
    beneficiaryNumber: 'RUH-2023-010',
    name: { ar: 'ديمة بنت عمر البلوي', en: 'Dima Omar Al-Balawi' },
    gender: 'female',
    dateOfBirth: new Date('2017-09-14'),
    nationalId: '1100234570',
    nationality: 'SA',
    primaryDisability: 'VISUAL',
    disabilityLevel: 'VI_SEVERE',
    caseStatus: 'active',
    guardian: {
      name: { ar: 'عمر يوسف البلوي', en: 'Omar Yousef Al-Balawi' },
      relationship: 'father',
      phone: '0510234510',
      email: 'omar.balawi@gmail.com',
      nationalId: '1062234510',
    },
    address: { city: 'الرياض', district: 'العزيزية', region: 'الرياض' },
    referralSource: 'hospital',
    enrollmentDate: new Date('2023-06-01'),
    insurance: { provider: 'bupa', policyNumber: 'BUPA-012345', class: 'A' },
    programs: ['OT_BASIC', 'ADL_BASIC'],
    branchCode: 'RUH-MAIN',
    transportRequired: true,
    transportAddress: 'حي العزيزية، الرياض',
  },
  {
    beneficiaryNumber: 'RUH-2024-011',
    name: { ar: 'بدر بن سلطان الشمري', en: 'Badr Sultan Al-Shammari' },
    gender: 'male',
    dateOfBirth: new Date('2019-06-25'),
    nationalId: '1100234571',
    nationality: 'SA',
    primaryDisability: 'AUTISM',
    disabilityLevel: 'ASD_L1',
    caseStatus: 'active',
    guardian: {
      name: { ar: 'سلطان بدر الشمري', en: 'Sultan Badr Al-Shammari' },
      relationship: 'father',
      phone: '0511234511',
      email: 'sultan.shammari@gmail.com',
      nationalId: '1059234511',
    },
    address: { city: 'الرياض', district: 'الشفا', region: 'الرياض' },
    referralSource: 'pediatric_neurology',
    enrollmentDate: new Date('2024-04-15'),
    insurance: { provider: 'tawuniya', policyNumber: 'TAW-123456', class: 'B' },
    programs: ['OT_SENSORY', 'ST_AUTISM'],
    branchCode: 'RUH-MAIN',
    transportRequired: false,
  },
  {
    beneficiaryNumber: 'RUH-2023-012',
    name: { ar: 'غلا بنت راشد الرشيدي', en: 'Ghala Rashed Al-Rashidi' },
    gender: 'female',
    dateOfBirth: new Date('2016-03-08'),
    nationalId: '1100234572',
    nationality: 'SA',
    primaryDisability: 'LEARNING',
    disabilityLevel: 'DYSLEXIA',
    caseStatus: 'active',
    guardian: {
      name: { ar: 'راشد سليمان الرشيدي', en: 'Rashed Suleiman Al-Rashidi' },
      relationship: 'father',
      phone: '0512234512',
      email: 'rashed.rashidi@gmail.com',
      nationalId: '1056234512',
    },
    address: { city: 'الرياض', district: 'الازدهار', region: 'الرياض' },
    referralSource: 'school',
    enrollmentDate: new Date('2023-10-10'),
    insurance: { provider: 'walaa', policyNumber: 'WAL-234567', class: 'A' },
    programs: ['SE_LEARNING', 'ST_BASIC'],
    branchCode: 'RUH-MAIN',
    transportRequired: false,
  },
  {
    beneficiaryNumber: 'RUH-2022-013',
    name: { ar: 'وليد بن عزيز القرني', en: 'Walid Aziz Al-Qarni' },
    gender: 'male',
    dateOfBirth: new Date('2014-10-20'),
    nationalId: '1100234573',
    nationality: 'SA',
    primaryDisability: 'PHYSICAL',
    disabilityLevel: 'HEMI',
    caseStatus: 'discharged',
    guardian: {
      name: { ar: 'عزيز محمد القرني', en: 'Aziz Mohammed Al-Qarni' },
      relationship: 'father',
      phone: '0513234513',
      email: 'aziz.qarni@gmail.com',
      nationalId: '1053234513',
    },
    address: { city: 'الرياض', district: 'الملز', region: 'الرياض' },
    referralSource: 'hospital',
    enrollmentDate: new Date('2022-01-15'),
    dischargeDate: new Date('2024-12-31'),
    dischargeReason: 'حقق جميع أهداف الخطة العلاجية وأُحيل للمتابعة',
    insurance: { provider: 'bupa', policyNumber: 'BUPA-345678', class: 'B' },
    programs: ['PT_NEURO', 'OT_BASIC'],
    branchCode: 'RUH-MAIN',
    transportRequired: false,
  },
  {
    beneficiaryNumber: 'RUH-2024-014',
    name: { ar: 'رزان بنت مشعل العنزي', en: 'Razan Meshal Al-Anazi' },
    gender: 'female',
    dateOfBirth: new Date('2021-01-25'),
    nationalId: '1100234574',
    nationality: 'SA',
    primaryDisability: 'SPEECH_DELAY',
    disabilityLevel: 'SD_MODERATE',
    caseStatus: 'suspended',
    guardian: {
      name: { ar: 'مشعل فالح العنزي', en: 'Meshal Faleh Al-Anazi' },
      relationship: 'father',
      phone: '0514234514',
      email: 'meshal.anazi@gmail.com',
      nationalId: '1050234514',
    },
    address: { city: 'الرياض', district: 'الياسمين', region: 'الرياض' },
    referralSource: 'pediatrician',
    enrollmentDate: new Date('2024-08-01'),
    suspensionReason: 'سفر مؤقت للعلاج بالخارج - متوقع العودة بعد 3 أشهر',
    insurance: { provider: 'tawuniya', policyNumber: 'TAW-456789', class: 'A' },
    programs: ['ST_BASIC'],
    branchCode: 'RUH-MAIN',
    transportRequired: false,
  },
  {
    beneficiaryNumber: 'RUH-2024-015',
    name: { ar: 'ناصر بن طارق الزهراني', en: 'Nasser Tariq Al-Zahrani' },
    gender: 'male',
    dateOfBirth: new Date('2020-08-15'),
    nationalId: '1100234575',
    nationality: 'SA',
    primaryDisability: 'AUTISM',
    disabilityLevel: 'ASD_L2',
    caseStatus: 'active',
    guardian: {
      name: { ar: 'طارق علي الزهراني', en: 'Tariq Ali Al-Zahrani' },
      relationship: 'father',
      phone: '0515234515',
      email: 'tariq.zahrani2024@gmail.com',
      nationalId: '1047234515',
    },
    address: { city: 'الرياض', district: 'بدر', region: 'الرياض' },
    referralSource: 'hospital',
    enrollmentDate: new Date('2024-11-01'),
    insurance: { provider: 'medgulf', policyNumber: 'MG-567890', class: 'A' },
    programs: ['OT_AUTISM', 'ST_AUTISM', 'PSY_BEHAVIORAL'],
    branchCode: 'RUH-MAIN',
    transportRequired: true,
    transportAddress: 'حي بدر، الرياض',
  },

  // ══════════════════════════════════════════════════════════════════
  // فرع جدة - JED-MAIN (18 مستفيد)
  // ══════════════════════════════════════════════════════════════════
  {
    beneficiaryNumber: 'JED-2024-001',
    name: { ar: 'عبدالرحمن بن أحمد الزهراني', en: 'Abdulrahman Ahmed Al-Zahrani' },
    gender: 'male',
    dateOfBirth: new Date('2018-11-08'),
    nationalId: '1200234576',
    nationality: 'SA',
    primaryDisability: 'AUTISM',
    disabilityLevel: 'ASD_L2',
    caseStatus: 'active',
    guardian: {
      name: { ar: 'أحمد محمد الزهراني', en: 'Ahmed Mohammed Al-Zahrani' },
      relationship: 'father',
      phone: '0526234516',
      email: 'ahmed.zahrani2024@gmail.com',
      nationalId: '1044234516',
    },
    address: { city: 'جدة', district: 'الصفا', region: 'مكة المكرمة' },
    referralSource: 'hospital',
    enrollmentDate: new Date('2024-03-01'),
    insurance: { provider: 'bupa', policyNumber: 'BUPA-678901', class: 'A' },
    programs: ['OT_AUTISM', 'ST_AUTISM', 'PSY_BEHAVIORAL'],
    branchCode: 'JED-MAIN',
    transportRequired: true,
    transportAddress: 'حي الصفا، جدة',
  },
  {
    beneficiaryNumber: 'JED-2023-002',
    name: { ar: 'شهد بنت ماجد الأحمدي', en: 'Shahad Majed Al-Ahmadi' },
    gender: 'female',
    dateOfBirth: new Date('2019-05-17'),
    nationalId: '1200234577',
    nationality: 'SA',
    primaryDisability: 'PHYSICAL',
    disabilityLevel: 'CP',
    caseStatus: 'active',
    guardian: {
      name: { ar: 'ماجد علي الأحمدي', en: 'Majed Ali Al-Ahmadi' },
      relationship: 'father',
      phone: '0527234517',
      email: 'majed.ahmadi@gmail.com',
      nationalId: '1041234517',
    },
    address: { city: 'جدة', district: 'الحمراء', region: 'مكة المكرمة' },
    referralSource: 'hospital',
    enrollmentDate: new Date('2023-09-15'),
    insurance: { provider: 'medgulf', policyNumber: 'MG-789012', class: 'VIP' },
    programs: ['PT_NEURO', 'OT_BASIC', 'ST_BASIC', 'ADL_BASIC'],
    branchCode: 'JED-MAIN',
    transportRequired: true,
    transportAddress: 'حي الحمراء، جدة',
  },
  {
    beneficiaryNumber: 'JED-2023-003',
    name: { ar: 'حسن بن وليد المالكي', en: 'Hassan Waleed Al-Malki' },
    gender: 'male',
    dateOfBirth: new Date('2017-07-03'),
    nationalId: '1200234578',
    nationality: 'SA',
    primaryDisability: 'INTELLECTUAL',
    disabilityLevel: 'DS',
    caseStatus: 'active',
    guardian: {
      name: { ar: 'وليد حسن المالكي', en: 'Waleed Hassan Al-Malki' },
      relationship: 'father',
      phone: '0528234518',
      email: 'waleed.malki@gmail.com',
      nationalId: '1038234518',
    },
    address: { city: 'جدة', district: 'الفيصلية', region: 'مكة المكرمة' },
    referralSource: 'hospital',
    enrollmentDate: new Date('2023-01-10'),
    insurance: { provider: 'tawuniya', policyNumber: 'TAW-890123', class: 'A' },
    programs: ['SE_ID', 'PT_PEDIATRIC', 'ST_BASIC'],
    branchCode: 'JED-MAIN',
    transportRequired: false,
  },
  {
    beneficiaryNumber: 'JED-2025-004',
    name: { ar: 'ليان بنت راشد الجهني', en: 'Layan Rashed Al-Johani' },
    gender: 'female',
    dateOfBirth: new Date('2020-02-14'),
    nationalId: '1200234579',
    nationality: 'SA',
    primaryDisability: 'SPEECH_DELAY',
    disabilityLevel: 'SD_MILD',
    caseStatus: 'active',
    guardian: {
      name: { ar: 'راشد عبدالعزيز الجهني', en: 'Rashed Abdulaziz Al-Johani' },
      relationship: 'father',
      phone: '0529234519',
      email: 'rashed.johani@gmail.com',
      nationalId: '1035234519',
    },
    address: { city: 'جدة', district: 'النعيم', region: 'مكة المكرمة' },
    referralSource: 'pediatrician',
    enrollmentDate: new Date('2025-01-15'),
    insurance: { provider: 'bupa', policyNumber: 'BUPA-901234', class: 'B' },
    programs: ['ST_BASIC'],
    branchCode: 'JED-MAIN',
    transportRequired: false,
  },
  {
    beneficiaryNumber: 'JED-2022-005',
    name: { ar: 'آدم بن سلطان السلمي', en: 'Adam Sultan Al-Sulami' },
    gender: 'male',
    dateOfBirth: new Date('2016-10-09'),
    nationalId: '1200234580',
    nationality: 'SA',
    primaryDisability: 'INTELLECTUAL',
    disabilityLevel: 'ID_MODERATE',
    caseStatus: 'active',
    guardian: {
      name: { ar: 'سلطان فهد السلمي', en: 'Sultan Fahad Al-Sulami' },
      relationship: 'father',
      phone: '0530234520',
      email: 'sultan.sulami@gmail.com',
      nationalId: '1032234520',
    },
    address: { city: 'جدة', district: 'الثغر', region: 'مكة المكرمة' },
    referralSource: 'ministry_of_education',
    enrollmentDate: new Date('2022-09-01'),
    insurance: { provider: 'walaa', policyNumber: 'WAL-012345', class: 'A' },
    programs: ['SE_ID', 'OT_BASIC', 'PSY_BEHAVIORAL'],
    branchCode: 'JED-MAIN',
    transportRequired: true,
    transportAddress: 'حي الثغر، جدة',
  },
  {
    beneficiaryNumber: 'JED-2024-006',
    name: { ar: 'إيمان بنت حمد الشهراني', en: 'Iman Hamad Al-Shahrani' },
    gender: 'female',
    dateOfBirth: new Date('2019-03-28'),
    nationalId: '1200234581',
    nationality: 'SA',
    primaryDisability: 'AUTISM',
    disabilityLevel: 'ASD_L1',
    caseStatus: 'active',
    guardian: {
      name: { ar: 'حمد سعد الشهراني', en: 'Hamad Saad Al-Shahrani' },
      relationship: 'father',
      phone: '0531234521',
      email: 'hamad.shahrani2024@gmail.com',
      nationalId: '1029234521',
    },
    address: { city: 'جدة', district: 'الروضة', region: 'مكة المكرمة' },
    referralSource: 'pediatric_neurology',
    enrollmentDate: new Date('2024-07-20'),
    insurance: { provider: 'tawuniya', policyNumber: 'TAW-123789', class: 'B' },
    programs: ['OT_SENSORY', 'ST_AUTISM'],
    branchCode: 'JED-MAIN',
    transportRequired: false,
  },
  {
    beneficiaryNumber: 'JED-2023-007',
    name: { ar: 'محمد بن عبدالله الغامدي', en: 'Mohammed Abdullah Al-Ghamdi' },
    gender: 'male',
    dateOfBirth: new Date('2015-08-22'),
    nationalId: '1200234582',
    nationality: 'SA',
    primaryDisability: 'PHYSICAL',
    disabilityLevel: 'HEMI',
    caseStatus: 'active',
    guardian: {
      name: { ar: 'عبدالله إبراهيم الغامدي', en: 'Abdullah Ibrahim Al-Ghamdi' },
      relationship: 'father',
      phone: '0532234522',
      email: 'abdullah.ghamdi@gmail.com',
      nationalId: '1026234522',
    },
    address: { city: 'جدة', district: 'البوادي', region: 'مكة المكرمة' },
    referralSource: 'hospital',
    enrollmentDate: new Date('2023-05-10'),
    insurance: { provider: 'bupa', policyNumber: 'BUPA-234567', class: 'A' },
    programs: ['PT_NEURO', 'OT_BASIC'],
    branchCode: 'JED-MAIN',
    transportRequired: false,
  },
  {
    beneficiaryNumber: 'JED-2024-008',
    name: { ar: 'روان بنت فيصل الحارثي', en: 'Rawan Faisal Al-Harthi' },
    gender: 'female',
    dateOfBirth: new Date('2021-06-12'),
    nationalId: '1200234583',
    nationality: 'SA',
    primaryDisability: 'DEVELOPMENTAL_DELAY',
    disabilityLevel: 'GDD',
    caseStatus: 'active',
    guardian: {
      name: { ar: 'فيصل أحمد الحارثي', en: 'Faisal Ahmed Al-Harthi' },
      relationship: 'father',
      phone: '0533234523',
      email: 'faisal.harthi@gmail.com',
      nationalId: '1023234523',
    },
    address: { city: 'جدة', district: 'النهضة', region: 'مكة المكرمة' },
    referralSource: 'pediatrician',
    enrollmentDate: new Date('2024-09-10'),
    insurance: { provider: 'medgulf', policyNumber: 'MG-345901', class: 'B' },
    programs: ['ST_BASIC', 'OT_BASIC', 'PT_PEDIATRIC'],
    branchCode: 'JED-MAIN',
    transportRequired: true,
    transportAddress: 'حي النهضة، جدة',
  },

  // ══════════════════════════════════════════════════════════════════
  // فرع الدمام - DAM-MAIN (12 مستفيد)
  // ══════════════════════════════════════════════════════════════════
  {
    beneficiaryNumber: 'DAM-2024-001',
    name: { ar: 'نايف بن تركي الشريف', en: 'Naif Turki Al-Sharif' },
    gender: 'male',
    dateOfBirth: new Date('2018-04-20'),
    nationalId: '1300234584',
    nationality: 'SA',
    primaryDisability: 'AUTISM',
    disabilityLevel: 'ASD_L2',
    caseStatus: 'active',
    guardian: {
      name: { ar: 'تركي سعد الشريف', en: 'Turki Saad Al-Sharif' },
      relationship: 'father',
      phone: '0538234524',
      email: 'turki.sharif@gmail.com',
      nationalId: '1020234524',
    },
    address: { city: 'الدمام', district: 'العزيزية', region: 'الشرقية' },
    referralSource: 'hospital',
    enrollmentDate: new Date('2024-05-01'),
    insurance: { provider: 'bupa', policyNumber: 'BUPA-456789', class: 'A' },
    programs: ['OT_AUTISM', 'ST_AUTISM', 'PSY_BEHAVIORAL'],
    branchCode: 'DAM-MAIN',
    transportRequired: true,
    transportAddress: 'حي العزيزية، الدمام',
  },
  {
    beneficiaryNumber: 'DAM-2024-002',
    name: { ar: 'جوري بنت سلمان العنزي', en: 'Jouri Salman Al-Anazi' },
    gender: 'female',
    dateOfBirth: new Date('2019-12-30'),
    nationalId: '1300234585',
    nationality: 'SA',
    primaryDisability: 'DEVELOPMENTAL_DELAY',
    disabilityLevel: 'GDD',
    caseStatus: 'active',
    guardian: {
      name: { ar: 'سلمان حمد العنزي', en: 'Salman Hamad Al-Anazi' },
      relationship: 'father',
      phone: '0539234525',
      email: 'salman.anazi@gmail.com',
      nationalId: '1017234525',
    },
    address: { city: 'الدمام', district: 'النزهة', region: 'الشرقية' },
    referralSource: 'pediatrician',
    enrollmentDate: new Date('2024-07-15'),
    insurance: { provider: 'tawuniya', policyNumber: 'TAW-567012', class: 'B' },
    programs: ['ST_BASIC', 'OT_BASIC', 'PT_PEDIATRIC'],
    branchCode: 'DAM-MAIN',
    transportRequired: false,
  },
  {
    beneficiaryNumber: 'DAM-2023-003',
    name: { ar: 'راكان بن عبدالملك الهاجري', en: 'Rakan Abdulmalek Al-Hajri' },
    gender: 'male',
    dateOfBirth: new Date('2015-08-15'),
    nationalId: '1300234586',
    nationality: 'SA',
    primaryDisability: 'PHYSICAL',
    disabilityLevel: 'HEMI',
    caseStatus: 'active',
    guardian: {
      name: { ar: 'عبدالملك سعيد الهاجري', en: 'Abdulmalek Saeed Al-Hajri' },
      relationship: 'father',
      phone: '0540234526',
      email: 'abdulmalek.hajri@gmail.com',
      nationalId: '1014234526',
    },
    address: { city: 'الدمام', district: 'الفيصلية', region: 'الشرقية' },
    referralSource: 'hospital',
    enrollmentDate: new Date('2023-03-01'),
    insurance: { provider: 'medgulf', policyNumber: 'MG-678123', class: 'A' },
    programs: ['PT_NEURO', 'OT_BASIC'],
    branchCode: 'DAM-MAIN',
    transportRequired: false,
  },
  {
    beneficiaryNumber: 'DAM-2024-004',
    name: { ar: 'زيد بن عمر الهاشم', en: 'Zaid Omar Al-Hashim' },
    gender: 'male',
    dateOfBirth: new Date('2020-07-04'),
    nationalId: '1300234587',
    nationality: 'SA',
    primaryDisability: 'AUTISM',
    disabilityLevel: 'ASD_L1',
    caseStatus: 'active',
    guardian: {
      name: { ar: 'عمر علي الهاشم', en: 'Omar Ali Al-Hashim' },
      relationship: 'father',
      phone: '0541234527',
      email: 'omar.hashim@gmail.com',
      nationalId: '1011234527',
    },
    address: { city: 'الدمام', district: 'الشعلة', region: 'الشرقية' },
    referralSource: 'pediatric_neurology',
    enrollmentDate: new Date('2024-06-20'),
    insurance: { provider: 'bupa', policyNumber: 'BUPA-789234', class: 'B' },
    programs: ['OT_SENSORY', 'ST_AUTISM'],
    branchCode: 'DAM-MAIN',
    transportRequired: false,
  },
  {
    beneficiaryNumber: 'DAM-2024-005',
    name: { ar: 'سلمى بنت ناصر الدوسري', en: 'Salma Nasser Al-Dosari' },
    gender: 'female',
    dateOfBirth: new Date('2018-09-19'),
    nationalId: '1300234588',
    nationality: 'SA',
    primaryDisability: 'INTELLECTUAL',
    disabilityLevel: 'ID_MILD',
    caseStatus: 'active',
    guardian: {
      name: { ar: 'ناصر خالد الدوسري', en: 'Nasser Khalid Al-Dosari' },
      relationship: 'father',
      phone: '0542234528',
      email: 'nasser.dosari@gmail.com',
      nationalId: '1008234528',
    },
    address: { city: 'الدمام', district: 'الريان', region: 'الشرقية' },
    referralSource: 'ministry_of_education',
    enrollmentDate: new Date('2024-02-15'),
    insurance: { provider: 'tawuniya', policyNumber: 'TAW-890345', class: 'A' },
    programs: ['SE_ID', 'OT_BASIC'],
    branchCode: 'DAM-MAIN',
    transportRequired: false,
  },
  {
    beneficiaryNumber: 'DAM-2026-006',
    name: { ar: 'وائل بن عادل الخالدي', en: 'Wael Adel Al-Khalidi' },
    gender: 'male',
    dateOfBirth: new Date('2020-06-10'),
    nationalId: '1300234589',
    nationality: 'SA',
    primaryDisability: 'AUTISM',
    disabilityLevel: 'ASD_L1',
    caseStatus: 'waitlist',
    guardian: {
      name: { ar: 'عادل صالح الخالدي', en: 'Adel Saleh Al-Khalidi' },
      relationship: 'father',
      phone: '0543234529',
      email: 'adel.khalidi@gmail.com',
      nationalId: '1005234529',
    },
    address: { city: 'الدمام', district: 'الطبيشي', region: 'الشرقية' },
    referralSource: 'pediatrician',
    enrollmentDate: null,
    waitlistDate: new Date('2026-02-15'),
    waitlistPosition: 1,
    insurance: { provider: 'bupa', policyNumber: 'BUPA-901456', class: 'B' },
    programs: ['OT_SENSORY', 'ST_AUTISM', 'PSY_BEHAVIORAL'],
    branchCode: 'DAM-MAIN',
    transportRequired: false,
  },
];

// ─────────────────────────────────────────────────────────────────────────────
// Seed Function
// ─────────────────────────────────────────────────────────────────────────────
async function seed(connection) {
  const db = connection.db || (connection.connection && connection.connection.db) || connection;
  if (!db) throw new Error('No database connection');

  const col = db.collection('beneficiaries');

  // دمج المستفيدين الافتراضيين مع الإضافيين من seed-extensions.config.js
  const allBeneficiaries = mergeWithDefaults(
    COMPREHENSIVE_BENEFICIARIES,
    EXTRA_BENEFICIARIES,
    'beneficiaryNumber'
  );

  if (EXTRA_BENEFICIARIES.length > 0) {
    console.log(
      `  ℹ️  إضافة ${EXTRA_BENEFICIARIES.length} مستفيد إضافي من seed-extensions.config.js`
    );
  }

  let created = 0;
  let skipped = 0;

  for (const ben of allBeneficiaries) {
    const existing = await col.findOne({
      $or: [
        { beneficiaryNumber: ben.beneficiaryNumber },
        { nationalId: ben.nationalId },
        { mrn: 'MRN-' + ben.beneficiaryNumber },
      ],
    });

    if (existing) {
      skipped++;
      continue;
    }

    const now = new Date();
    const age = ben.dateOfBirth ? calcAge(ben.dateOfBirth) : null;

    await col.insertOne({
      ...ben,
      mrn: 'MRN-' + ben.beneficiaryNumber,
      age,
      sessions: [],
      assessments: [],
      documents: [],
      invoices: [],
      metadata: { isComprehensiveSeed: true, seededAt: now },
      createdAt: now,
      updatedAt: now,
    });
    created++;
  }

  console.log(
    `  ✅ comprehensive-beneficiaries: ${created} created, ${skipped} already existed (total: ${COMPREHENSIVE_BENEFICIARIES.length})`
  );
}

async function down(connection) {
  const db = connection.db || (connection.connection && connection.connection.db) || connection;
  const result = await db
    .collection('beneficiaries')
    .deleteMany({ 'metadata.isComprehensiveSeed': true });
  console.log(
    `  ✅ comprehensive-beneficiaries: removed ${result.deletedCount} comprehensive beneficiaries`
  );
}

module.exports = { seed, down, COMPREHENSIVE_BENEFICIARIES };
