#!/usr/bin/env bash
#
# W1437 Blue-Green Deployment (run ON THE PRODUCTION HOST)
#
# Deploys the release to the inactive color, verifies it, then swaps nginx
# upstream to make it active. The previous active color remains in place for
# instant rollback.
#
# Prerequisites:
#   - Two app roots: $DEPLOY_ROOT-blue and $DEPLOY_ROOT-green
#   - nginx upstream named "alawael_app" with config in $NGINX_COLOR_CONFIG
#   - Inactive color reachable on a private port/hostname for smoke tests
#
# Usage on production host:
#   export MONGODB_URI="mongodb+srv://..."
#   export DEPLOY_ROOT=/home/alawael/app
#   export NGINX_COLOR_CONFIG=/etc/nginx/conf.d/alawael-color.conf
#   export SMOKE_URL_INACTIVE=http://localhost:3002
#   export SMOKE_URL_ACTIVE=https://alaweal.org
#   ./scripts/deploy-bluegreen-w1437.sh
#

set -euo pipefail

MONGODB_URI="${MONGODB_URI:-${MONGO_URI:-}}"
DEPLOY_ROOT="${DEPLOY_ROOT:-/home/alawael/app}"
NGINX_COLOR_CONFIG="${NGINX_COLOR_CONFIG:-/etc/nginx/conf.d/alawael-color.conf}"
SMOKE_URL_INACTIVE="${SMOKE_URL_INACTIVE:-}"
SMOKE_URL_ACTIVE="${SMOKE_URL_ACTIVE:-https://alaweal.org}"
ACTIVE_PORT="${ACTIVE_PORT:-3001}"
INACTIVE_PORT="${INACTIVE_PORT:-3002}"

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

log()  { echo -e "${GREEN}[$(date -u +%Y-%m-%dT%H:%M:%SZ)] INFO:${NC} $*"; }
warn() { echo -e "${YELLOW}[$(date -u +%Y:%M:%SZ)] WARN:${NC} $*"; }
fail() { echo -e "${RED}[$(date -u +%Y-%m-%dT%H:%M:%SZ)] FAIL:${NC} $*"; exit 1; }

[[ -n "$MONGODB_URI" ]] || fail "MONGODB_URI is required"

# --- Determine active/inactive colors ---------------------------------------
if [[ -f "$NGINX_COLOR_CONFIG" ]]; then
  CURRENT_COLOR=$(grep -oE 'blue|green' "$NGINX_COLOR_CONFIG" | head -1 || true)
else
  CURRENT_COLOR=""
fi

if [[ "$CURRENT_COLOR" == "blue" ]]; then
  ACTIVE_COLOR="blue"
  INACTIVE_COLOR="green"
elif [[ "$CURRENT_COLOR" == "green" ]]; then
  ACTIVE_COLOR="green"
  INACTIVE_COLOR="blue"
else
  warn "Could not determine active color from $NGINX_COLOR_CONFIG; defaulting to blue active, green inactive"
  ACTIVE_COLOR="blue"
  INACTIVE_COLOR="green"
fi

ACTIVE_DIR="${DEPLOY_ROOT}-${ACTIVE_COLOR}"
INACTIVE_DIR="${DEPLOY_ROOT}-${INACTIVE_COLOR}"

log "Active color: $ACTIVE_COLOR ($ACTIVE_DIR) on port $ACTIVE_PORT"
log "Inactive color: $INACTIVE_COLOR ($INACTIVE_DIR) on port $INACTIVE_PORT"

# --- Pre-flight checks ------------------------------------------------------
[[ -d "$ACTIVE_DIR" ]] || fail "Active directory missing: $ACTIVE_DIR"
[[ -d "$INACTIVE_DIR" ]] || fail "Inactive directory missing: $INACTIVE_DIR"

# --- Deploy W1437 to inactive color -----------------------------------------
log "Deploying W1437 to inactive color ($INACTIVE_COLOR)..."
(
  cd "$INACTIVE_DIR"
  git fetch origin main
  git checkout main
  git reset --hard origin/main
  export MONGODB_URI="$MONGODB_URI"
  export NODE_ENV=production
  export DEPLOY_ROOT="$INACTIVE_DIR"
  ./scripts/deploy-w1437.sh --force
)

# --- Start inactive backend -------------------------------------------------
log "Starting inactive backend on port $INACTIVE_PORT..."
(
  cd "$INACTIVE_DIR/backend"
  # Assumes pm2 ecosystem config can be parameterized by port/color.
  # If you use a different process manager, adjust this block.
  if command -v pm2 &>/dev/null && [[ -f "../ecosystem.config.js" ]]; then
    PM2_PROC="alawael-api-${INACTIVE_COLOR}"
    pm2 delete "$PM2_PROC" &>/dev/null || true
    PORT="$INACTIVE_PORT" pm2 start ../ecosystem.config.js --name "$PM2_PROC" || fail "Failed to start inactive backend"
  else
    warn "pm2 not configured; please start inactive backend manually on port $INACTIVE_PORT"
  fi
)

# --- Smoke test inactive color ----------------------------------------------
if [[ -n "$SMOKE_URL_INACTIVE" ]]; then
  log "Waiting for inactive backend to be ready..."
  for i in 1 2 3 4 5 6; do
    if curl -sf "$SMOKE_URL_INACTIVE/health" &>/dev/null; then
      break
    fi
    sleep 5
  done

  log "Smoke testing inactive color at $SMOKE_URL_INACTIVE..."
  ./scripts/smoke-test-w1437.sh "$SMOKE_URL_INACTIVE" || fail "Inactive color smoke tests failed"
  log "✅ Inactive color smoke tests passed"
else
  warn "SMOKE_URL_INACTIVE not set; skipping inactive color smoke tests"
fi

# --- Swap colors ------------------------------------------------------------
warn "About to swap nginx upstream from $ACTIVE_COLOR to $INACTIVE_COLOR"
read -rp "Continue? [y/N] " ans
[[ "$ans" == "y" || "$ans" == "Y" ]] || fail "Swap cancelled by user"

log "Updating nginx upstream..."
cat > "$NGINX_COLOR_CONFIG" <<EOF
# Auto-generated by deploy-bluegreen-w1437.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
upstream alawael_app {
    server 127.0.0.1:${INACTIVE_PORT};
}
EOF

if command -v nginx &>/dev/null || command -v nginx-debug &>/dev/null; then
  nginx -t || fail "nginx config test failed"
  nginx -s reload || fail "nginx reload failed"
  log "✅ nginx reloaded"
else
  warn "nginx not found locally; please reload nginx manually on the host"
fi

# --- Verify active color ----------------------------------------------------
log "Smoke testing active (now $INACTIVE_COLOR) at $SMOKE_URL_ACTIVE..."
./scripts/smoke-test-w1437.sh "$SMOKE_URL_ACTIVE" || fail "Active color smoke tests failed after swap"
log "✅ Active color smoke tests passed"

# --- Summary ----------------------------------------------------------------
log "================================================================"
log "W1437 blue-green deployment COMPLETE"
log "Previous active: $ACTIVE_COLOR ($ACTIVE_DIR) on port $ACTIVE_PORT"
log "Current active: $INACTIVE_COLOR ($INACTIVE_DIR) on port $INACTIVE_PORT"
log "================================================================"
log "To rollback instantly:"
log "  echo 'upstream alawael_app { server 127.0.0.1:${ACTIVE_PORT}; }' > $NGINX_COLOR_CONFIG"
log "  nginx -s reload"
log "To cleanup: stop pm2 process alawael-api-${ACTIVE_COLOR} after monitoring period"
