'use strict';

const mongoose = require('mongoose');
const { Schema } = mongoose;
const { AUDIT_STATUSES } = require('../../config/audit-schedule.registry');

const findingSchema = new Schema(
  {
    type: {
      type: String,
      enum: ['major_nc', 'minor_nc', 'opportunity', 'observation', 'commendation'],
      required: true,
    },
    description: { type: String, required: true },
    clauseRef: { type: String, default: null },
    evidence: { type: String, default: null },
    ownerUserId: { type: Schema.Types.ObjectId, ref: 'User', default: null },
    capaCreated: { type: Boolean, default: false },
    linkedCapaId: { type: Schema.Types.ObjectId, ref: 'CapaItem', default: null },
  },
  { _id: true, timestamps: true }
);

const occurrenceSchema = new Schema(
  {
    auditNumber: { type: String, unique: true, index: true },
    scopeId: { type: Schema.Types.ObjectId, ref: 'AuditScope', required: true, index: true },
    type: {
      type: String,
      enum: ['internal', 'surprise', 'follow_up', 'pre_audit'],
      default: 'internal',
    },

    plannedFor: { type: Date, required: true },
    scheduledFor: { type: Date, default: null },
    startedAt: { type: Date, default: null },
    endedAt: { type: Date, default: null },

    leadAuditorUserId: { type: Schema.Types.ObjectId, ref: 'User', default: null },
    teamMembers: [{ type: Schema.Types.ObjectId, ref: 'User' }],

    status: { type: String, enum: AUDIT_STATUSES, default: 'planned', index: true },
    findings: { type: [findingSchema], default: [] },
    summary: { type: String, default: null },
    overallOutcome: {
      type: String,
      enum: ['conform', 'minor_nc', 'major_nc', null],
      default: null,
    },

    branchId: { type: Schema.Types.ObjectId, ref: 'Branch', default: null, index: true },
    tenantId: { type: Schema.Types.ObjectId, ref: 'Tenant', default: null },

    autoGenerated: { type: Boolean, default: false },
    cancelledReason: { type: String, default: null },

    createdBy: { type: Schema.Types.ObjectId, ref: 'User', required: true },
    updatedBy: { type: Schema.Types.ObjectId, ref: 'User', default: null },
    deleted_at: { type: Date, default: null },
  },
  { timestamps: true, collection: 'audit_occurrences' }
);

occurrenceSchema.index({ scopeId: 1, plannedFor: 1 });
occurrenceSchema.index({ status: 1, plannedFor: 1 });

occurrenceSchema.pre('validate', async function () {
  if (!this.auditNumber) {
    const year = new Date().getUTCFullYear();
    const Model = mongoose.model('AuditOccurrence');
    const count = await Model.countDocuments({ auditNumber: { $regex: `^AUD-${year}-` } });
    this.auditNumber = `AUD-${year}-${String(count + 1).padStart(4, '0')}`;
  }
});

module.exports =
  mongoose.models.AuditOccurrence || mongoose.model('AuditOccurrence', occurrenceSchema);
