/**
 * Operations demo data — fallback when API unavailable
 */
const demoData = {
  assets: [
    {
      _id: '1',
      name: 'مبنى الإدارة الرئيسي',
      type: 'عقار',
      location: 'الرياض',
      value: '5,000,000 ريال',
      status: 'active',
      acquisitionDate: '2020-01-15',
    },
    {
      _id: '2',
      name: 'سيارة نقل - 01',
      type: 'مركبة',
      location: 'الرياض',
      value: '150,000 ريال',
      status: 'active',
      acquisitionDate: '2023-06-01',
    },
    {
      _id: '3',
      name: 'أجهزة حاسب - مختبر',
      type: 'معدات تقنية',
      location: 'فرع جدة',
      value: '85,000 ريال',
      status: 'active',
      acquisitionDate: '2024-03-10',
    },
  ],
  equipment: [
    {
      _id: '1',
      name: 'جهاز العلاج الطبيعي',
      serialNumber: 'EQ-001',
      department: 'التأهيل',
      status: 'operational',
      lastMaintenance: '2026-02-01',
      nextMaintenance: '2026-05-01',
    },
    {
      _id: '2',
      name: 'معدات التدريب المهني',
      serialNumber: 'EQ-002',
      department: 'التدريب',
      status: 'operational',
      lastMaintenance: '2026-01-15',
      nextMaintenance: '2026-04-15',
    },
    {
      _id: '3',
      name: 'طابعة متعددة الوظائف',
      serialNumber: 'EQ-003',
      department: 'الإدارة',
      status: 'out-of-service',
      lastMaintenance: '2025-12-01',
      nextMaintenance: '2026-03-01',
    },
  ],
  maintenance: [
    {
      _id: '1',
      title: 'صيانة دورية - مكيفات',
      equipment: 'نظام التكييف المركزي',
      priority: 'عالية',
      status: 'pending',
      scheduledDate: '2026-03-15',
      assignedTo: 'فريق الصيانة',
    },
    {
      _id: '2',
      title: 'إصلاح طابعة',
      equipment: 'طابعة متعددة الوظائف',
      priority: 'متوسطة',
      status: 'in-progress',
      scheduledDate: '2026-03-10',
      assignedTo: 'أحمد',
    },
    {
      _id: '3',
      title: 'فحص كهربائي',
      equipment: 'النظام الكهربائي',
      priority: 'عالية',
      status: 'completed',
      scheduledDate: '2026-03-05',
      assignedTo: 'شركة الكهرباء',
    },
  ],
  schedules: [
    {
      _id: '1',
      title: 'جدول الصيانة الشهري',
      type: 'صيانة',
      frequency: 'شهري',
      nextRun: '2026-04-01',
      status: 'active',
      department: 'الصيانة',
    },
    {
      _id: '2',
      title: 'جدول التنظيف اليومي',
      type: 'نظافة',
      frequency: 'يومي',
      nextRun: '2026-03-09',
      status: 'active',
      department: 'الخدمات',
    },
    {
      _id: '3',
      title: 'جدول الجرد الربعي',
      type: 'جرد',
      frequency: 'ربع سنوي',
      nextRun: '2026-04-01',
      status: 'active',
      department: 'المالية',
    },
  ],
  licenses: [
    {
      _id: '1',
      name: 'رخصة تشغيل المركز',
      issuer: 'وزارة العمل',
      number: 'LIC-2026-001',
      issueDate: '2026-01-01',
      expiryDate: '2027-01-01',
      status: 'active',
    },
    {
      _id: '2',
      name: 'رخصة الدفاع المدني',
      issuer: 'الدفاع المدني',
      number: 'CD-2025-045',
      issueDate: '2025-06-01',
      expiryDate: '2026-06-01',
      status: 'active',
    },
    {
      _id: '3',
      name: 'شهادة السلامة',
      issuer: 'هيئة السلامة',
      number: 'SAF-2025-012',
      issueDate: '2025-03-01',
      expiryDate: '2026-03-01',
      status: 'expired',
    },
  ],
  branches: [
    {
      _id: '1',
      name: 'الفرع الرئيسي - الرياض',
      city: 'الرياض',
      address: 'شارع الملك فهد',
      manager: 'محمد أحمد',
      employees: 45,
      status: 'active',
    },
    {
      _id: '2',
      name: 'فرع جدة',
      city: 'جدة',
      address: 'شارع التحلية',
      manager: 'خالد سعود',
      employees: 28,
      status: 'active',
    },
    {
      _id: '3',
      name: 'فرع الدمام',
      city: 'الدمام',
      address: 'شارع الأمير محمد',
      manager: 'سعد عبدالله',
      employees: 22,
      status: 'active',
    },
  ],
};

export default demoData;
