/**
 * Assessment Mock Data — بيانات تجريبية للمستفيدين والنتائج
 */
import { assessmentColors } from 'theme/palette';

/* ─────────────────────── Mock beneficiary helpers ─────────────────────── */

export const MOCK_BENEFICIARIES = [
  {
    id: 'BEN001',
    name: 'أحمد محمد علي',
    age: 14,
    disabilityType: 'physical',
    therapist: 'د. سارة أحمد',
  },
  {
    id: 'BEN002',
    name: 'فاطمة أحمد حسن',
    age: 10,
    disabilityType: 'mental',
    therapist: 'أ. نورة خالد',
  },
  {
    id: 'BEN003',
    name: 'خالد سعيد محمود',
    age: 17,
    disabilityType: 'sensory',
    therapist: 'د. محمد صالح',
  },
  {
    id: 'BEN004',
    name: 'نورة عبدالله',
    age: 12,
    disabilityType: 'multiple',
    therapist: 'د. سارة أحمد',
  },
  {
    id: 'BEN005',
    name: 'يوسف إبراهيم',
    age: 8,
    disabilityType: 'autism',
    therapist: 'أ. هند العتيبي',
  },
  {
    id: 'BEN006',
    name: 'لمى سلطان',
    age: 6,
    disabilityType: 'intellectual',
    therapist: 'أ. نورة خالد',
  },
];

export const DISABILITY_TYPES = {
  physical: 'إعاقة حركية',
  visual: 'إعاقة بصرية',
  hearing: 'إعاقة سمعية',
  intellectual: 'إعاقة ذهنية',
  autism: 'اضطراب طيف التوحد',
  learning: 'صعوبات تعلم',
  multiple: 'إعاقة متعددة',
  speech: 'اضطرابات النطق والكلام',
  behavioral: 'اضطرابات سلوكية',
  developmental: 'تأخر نمائي',
  mental: 'إعاقة نفسية',
  sensory: 'إعاقة حسية',
};

/* ─────────────────────── Mock completed assessments ─────────────────────── */

export const generateMockScaleResults = () => [
  {
    id: 'SR001',
    beneficiaryId: 'BEN001',
    beneficiaryName: 'أحمد محمد علي',
    scaleId: 'motorFunction',
    scaleName: 'مقياس الوظائف الحركية',
    assessorName: 'د. سارة أحمد',
    date: '2026-02-15',
    totalScore: 58,
    maxScore: 100,
    percentage: 58,
    level: 'معتدل',
    levelColor: assessmentColors.mild,
    domainScores: { grossMotor: 18, fineMotor: 12, balance: 15, coordination: 13 },
    notes: 'تحسن ملحوظ في الحركة الكبرى مقارنة بالتقييم السابق',
    recommendations: ['زيادة تمارين الحركة الدقيقة', 'إضافة تمارين التوازن الديناميكي'],
  },
  {
    id: 'SR002',
    beneficiaryId: 'BEN001',
    beneficiaryName: 'أحمد محمد علي',
    scaleId: 'dailyLiving',
    scaleName: 'مقياس نشاط الحياة اليومية',
    assessorName: 'أ. نورة خالد',
    date: '2026-02-18',
    totalScore: 72,
    maxScore: 100,
    percentage: 72,
    level: 'مستقل جزئياً',
    levelColor: assessmentColors.mild,
    domainScores: { eating: 18, bathing: 14, dressing: 16, mobility: 12, hygiene: 12 },
    notes: 'يحتاج مساعدة في التنقل واللبس',
    recommendations: ['تدريب على ارتداء الملابس بشكل مستقل', 'تمارين التنقل الآمن'],
  },
  {
    id: 'SR003',
    beneficiaryId: 'BEN002',
    beneficiaryName: 'فاطمة أحمد حسن',
    scaleId: 'communication',
    scaleName: 'مقياس التواصل',
    assessorName: 'أ. نورة خالد',
    date: '2026-02-20',
    totalScore: 65,
    maxScore: 100,
    percentage: 65,
    level: 'صعوبة خفيفة',
    levelColor: assessmentColors.mild,
    domainScores: { comprehension: 16, expression: 12, reading: 14, writing: 10, nonVerbal: 13 },
    notes: 'التعبير والكتابة بحاجة لتطوير إضافي',
    recommendations: ['تدريب على التعبير اللفظي', 'أنشطة الكتابة الوظيفية'],
  },
  {
    id: 'SR004',
    beneficiaryId: 'BEN005',
    beneficiaryName: 'يوسف إبراهيم',
    scaleId: 'adaptiveBehavior',
    scaleName: 'مقياس السلوك التكيفي',
    assessorName: 'أ. هند العتيبي',
    date: '2026-03-01',
    totalScore: 42,
    maxScore: 100,
    percentage: 42,
    level: 'قصور متوسط',
    levelColor: assessmentColors.moderate,
    domainScores: { socialSkills: 12, academicSkills: 16, practicalSkills: 14 },
    notes: 'يظهر تفاعل اجتماعي محدود مع الأقران',
    recommendations: ['برنامج مهارات اجتماعية مكثف', 'تدريب على المهارات الأكاديمية الوظيفية'],
  },
  {
    id: 'SR005',
    beneficiaryId: 'BEN006',
    beneficiaryName: 'لمى سلطان',
    scaleId: 'qualityOfLife',
    scaleName: 'مقياس جودة الحياة',
    assessorName: 'أ. نورة خالد',
    date: '2026-03-03',
    totalScore: 55,
    maxScore: 100,
    percentage: 55,
    level: 'متوسطة',
    levelColor: assessmentColors.mild,
    domainScores: { physicalHealth: 16, mentalHealth: 12, socialRelations: 14, environment: 13 },
    notes: 'تحتاج دعم نفسي إضافي',
    recommendations: ['جلسات دعم نفسي أسبوعية', 'تعزيز العلاقات الاجتماعية'],
  },
  {
    id: 'SR006',
    beneficiaryId: 'BEN005',
    beneficiaryName: 'يوسف إبراهيم',
    scaleId: 'sensoryProfile',
    scaleName: 'مقياس الملف الحسي',
    assessorName: 'أ. هند العتيبي',
    date: '2026-03-05',
    totalScore: 38,
    maxScore: 100,
    percentage: 38,
    level: 'اختلاف محتمل',
    levelColor: assessmentColors.moderate,
    domainScores: {
      auditory: 5,
      visual: 8,
      tactile: 4,
      vestibular: 7,
      proprioceptive: 8,
      oralSensory: 6,
    },
    notes: 'حساسية مفرطة للمثيرات السمعية واللمسية — يحتاج بيئة حسية منظمة',
    recommendations: [
      'برنامج حمية حسية يومي',
      'تعديل البيئة الصفية لتقليل المثيرات',
      'أنشطة الحس العميق المنظمة',
    ],
  },
  {
    id: 'SR007',
    beneficiaryId: 'BEN002',
    beneficiaryName: 'فاطمة أحمد حسن',
    scaleId: 'cognitiveSkills',
    scaleName: 'مقياس المهارات المعرفية',
    assessorName: 'أ. نورة خالد',
    date: '2026-03-08',
    totalScore: 61,
    maxScore: 100,
    percentage: 61,
    level: 'حدّي',
    levelColor: assessmentColors.mild,
    domainScores: {
      attention: 14,
      memory: 12,
      reasoning: 13,
      problemSolving: 11,
      executiveFunction: 11,
    },
    notes: 'الذاكرة وحل المشكلات بحاجة لتعزيز — الانتباه أفضل المجالات',
    recommendations: [
      'تمارين تعزيز الذاكرة العاملة',
      'أنشطة حل المشكلات التطبيقية',
      'برنامج التنظيم الذاتي',
    ],
  },
  {
    id: 'SR008',
    beneficiaryId: 'BEN006',
    beneficiaryName: 'لمى سلطان',
    scaleId: 'developmentalIntegration',
    scaleName: 'مقياس التكامل النمائي',
    assessorName: 'أ. نورة خالد',
    date: '2026-03-10',
    totalScore: 45,
    maxScore: 100,
    percentage: 45,
    level: 'تأخر متوسط',
    levelColor: assessmentColors.moderate,
    domainScores: {
      motorDev: 12,
      languageDev: 8,
      cognitiveDev: 9,
      socialEmotional: 10,
      selfHelp: 6,
    },
    notes: 'النمو اللغوي والمساعدة الذاتية هما الأكثر تأخراً',
    recommendations: [
      'جلسات نطق وتخاطب مكثفة',
      'برنامج تدريب على المهارات الاستقلالية',
      'خطة تدخل مبكر شاملة',
    ],
  },
];

export const generateMockTestResults = () => [
  {
    id: 'TR001',
    beneficiaryId: 'BEN005',
    beneficiaryName: 'يوسف إبراهيم',
    testId: 'social_development',
    testName: 'مقياس التطور الاجتماعي',
    assessorName: 'أ. هند العتيبي',
    date: '2026-02-10',
    status: 'completed',
    scores: {
      socialInteraction: { eye_contact: 2, sharing: 1, turn_taking: 1, cooperation: 1, empathy: 0 },
      communication: { verbal_requests: 2, comprehension: 3, expression: 1, conversation: 1 },
      playSkills: { solitary_play: 3, parallel_play: 2, group_play: 1, imaginative_play: 1 },
    },
    totalItems: 13,
    totalScore: 19,
    maxPossible: 52,
    percentage: 36.5,
    overallLevel: 'ضعيف',
    notes: 'يظهر تحسن في الفهم ولكن لا يزال التفاعل الاجتماعي المباشر صعباً',
    recommendations: ['تطبيق برنامج ABA مكثف', 'تدريب على التواصل البصري', 'مجموعات اللعب المنظم'],
  },
  {
    id: 'TR002',
    beneficiaryId: 'BEN004',
    beneficiaryName: 'نورة عبدالله',
    testId: 'daily_living_skills',
    testName: 'اختبار مهارات الحياة اليومية',
    assessorName: 'د. سارة أحمد',
    date: '2026-02-12',
    status: 'completed',
    scores: {
      selfCare: { dressing: 2, eating: 3, toileting: 2, grooming: 1, bathing: 1 },
      mobility: { walking: 2, stairs: 1, transfers: 2, wheelchair_use: 0 },
      homeLiving: { meal_prep: 0, cleaning: 1, laundry: 0, money_management: 0 },
    },
    totalItems: 14,
    totalScore: 15,
    maxPossible: 42,
    percentage: 35.7,
    overallLevel: 'مساعدة جزئية',
    notes: 'تحتاج دعم مستمر في المعيشة المنزلية',
    recommendations: ['تدريب يومي على العناية الذاتية', 'برنامج تدريب منزلي'],
  },
  {
    id: 'TR003',
    beneficiaryId: 'BEN006',
    beneficiaryName: 'لمى سلطان',
    testId: 'adaptive_behavior',
    testName: 'اختبار السلوك التكيفي',
    assessorName: 'أ. نورة خالد',
    date: '2026-02-25',
    status: 'completed',
    scores: {
      conceptual: { communication: 2, functional_academics: 1, self_direction: 1 },
      social: { leisure: 3, social_skills: 2, social_responsibility: 1 },
      practical: { self_care: 2, home_living: 1, community_use: 1, health_safety: 2, work: 0 },
    },
    totalItems: 11,
    totalScore: 16,
    maxPossible: 44,
    percentage: 36.4,
    overallLevel: 'ضعيف',
    notes: 'المجال الاجتماعي هو الأقوى نسبياً',
    recommendations: [
      'تعزيز مهارات التوجيه الذاتي',
      'تدريب على المهارات العملية',
      'برنامج التأهيل المهني المبكر',
    ],
  },
  {
    id: 'TR004',
    beneficiaryId: 'BEN002',
    beneficiaryName: 'فاطمة أحمد حسن',
    testId: 'social_development',
    testName: 'مقياس التطور الاجتماعي',
    assessorName: 'أ. نورة خالد',
    date: '2026-03-02',
    status: 'completed',
    scores: {
      socialInteraction: { eye_contact: 4, sharing: 3, turn_taking: 3, cooperation: 3, empathy: 2 },
      communication: { verbal_requests: 3, comprehension: 4, expression: 3, conversation: 3 },
      playSkills: { solitary_play: 4, parallel_play: 3, group_play: 3, imaginative_play: 3 },
    },
    totalItems: 13,
    totalScore: 41,
    maxPossible: 52,
    percentage: 78.8,
    overallLevel: 'جيد',
    notes: 'تفاعل اجتماعي ممتاز — تتقدم بشكل سريع',
    recommendations: ['الحفاظ على البرنامج الحالي', 'إدراج أنشطة اجتماعية جماعية أكثر تعقيداً'],
  },
  {
    id: 'TR005',
    beneficiaryId: 'BEN006',
    beneficiaryName: 'لمى سلطان',
    testId: 'language_skills',
    testName: 'اختبار المهارات اللغوية',
    assessorName: 'أ. نورة خالد',
    date: '2026-03-06',
    status: 'completed',
    scores: {
      receptiveLanguage: {
        word_comprehension: 2,
        sentence_comprehension: 1,
        instruction_following: 2,
        story_comprehension: 1,
      },
      expressiveLanguage: { naming: 2, sentence_formation: 1, narration: 0, vocabulary_use: 1 },
      pragmaticLanguage: {
        greetings: 3,
        topic_maintenance: 1,
        turn_taking_verbal: 1,
        context_adaptation: 1,
      },
      phonologicalAwareness: {
        rhyming: 1,
        syllable_segmenting: 1,
        sound_blending: 0,
        sound_discrimination: 2,
      },
    },
    totalItems: 16,
    totalScore: 20,
    maxPossible: 64,
    percentage: 31.3,
    overallLevel: 'ضعيف',
    notes: 'اللغة التعبيرية والسرد هما الأكثر ضعفاً — الوعي الصوتي يحتاج تأسيساً',
    recommendations: [
      'برنامج تنمية لغوية مكثف',
      'تدريب على بناء الجمل',
      'أنشطة الوعي الصوتي اليومية',
      'قصص مصورة تفاعلية',
    ],
  },
  {
    id: 'TR006',
    beneficiaryId: 'BEN005',
    beneficiaryName: 'يوسف إبراهيم',
    testId: 'sensory_integration',
    testName: 'اختبار التكامل الحسي',
    assessorName: 'أ. هند العتيبي',
    date: '2026-03-07',
    status: 'completed',
    scores: {
      tactileProcessing: {
        light_touch: 0,
        texture_tolerance: 0,
        temperature_response: 1,
        pain_response: 3,
      },
      vestibularProcessing: {
        motion_tolerance: 2,
        balance_static: 1,
        balance_dynamic: 1,
        gravitational_security: 1,
      },
      proprioceptiveProcessing: {
        body_awareness: 1,
        force_grading: 1,
        motor_planning: 1,
        postural_control: 2,
      },
      sensoryModulation: {
        arousal_regulation: 0,
        attention_focus: 1,
        emotional_regulation: 1,
        transition_handling: 0,
      },
    },
    totalItems: 16,
    totalScore: 16,
    maxPossible: 48,
    percentage: 33.3,
    overallLevel: 'اختلاف محدد',
    notes: 'دفاعية لمسية واضحة — صعوبة في التنظيم الحسي والانتقالات',
    recommendations: [
      'برنامج تكامل حسي يومي مع معالج وظيفي',
      'حمية حسية شخصية',
      'تقنيات الضغط العميق',
      'جدول بصري للانتقالات',
    ],
  },
];
