/**
 * Assessment Scales — المقاييس المعتمدة (22 مقياساً)
 * Matches backend unified-assessment-service._initializeScales
 */
import { statusColors, assessmentColors, scaleAccentColors } from 'theme/palette';

const ASSESSMENT_SCALES = [
  {
    id: 'motorFunction',
    name: 'مقياس الوظائف الحركية',
    nameEn: 'Motor Function Scale',
    description: 'تقييم شامل للقدرات الحركية الكبرى والدقيقة والتوازن والتنسيق',
    maxScore: 100,
    icon: 'DirectionsRun',
    color: statusColors.primaryBlue,
    domains: [
      { key: 'grossMotor', name: 'الحركة الكبرى', maxScore: 25 },
      { key: 'fineMotor', name: 'الحركة الدقيقة', maxScore: 25 },
      { key: 'balance', name: 'التوازن', maxScore: 25 },
      { key: 'coordination', name: 'التنسيق', maxScore: 25 },
    ],
    interpretation: [
      { min: 0, max: 24, level: 'severe', label: 'شديد', color: assessmentColors.severe },
      { min: 25, max: 49, level: 'moderate', label: 'متوسط', color: assessmentColors.moderate },
      { min: 50, max: 74, level: 'mild', label: 'معتدل', color: assessmentColors.mild },
      { min: 75, max: 100, level: 'normal', label: 'طبيعي', color: assessmentColors.normal },
    ],
  },
  {
    id: 'dailyLiving',
    name: 'مقياس نشاط الحياة اليومية',
    nameEn: 'Daily Living Activities Scale',
    description: 'تقييم مستوى الاستقلالية في أنشطة الحياة اليومية الأساسية',
    maxScore: 100,
    icon: 'Home',
    color: assessmentColors.normal,
    domains: [
      { key: 'eating', name: 'تناول الطعام', maxScore: 20 },
      { key: 'bathing', name: 'الاستحمام', maxScore: 20 },
      { key: 'dressing', name: 'اللبس', maxScore: 20 },
      { key: 'mobility', name: 'التنقل', maxScore: 20 },
      { key: 'hygiene', name: 'النظافة', maxScore: 20 },
    ],
    interpretation: [
      { min: 0, max: 24, level: 'dependent', label: 'معتمد كلياً', color: assessmentColors.severe },
      {
        min: 25,
        max: 49,
        level: 'partiallyDependent',
        label: 'معتمد جزئياً',
        color: assessmentColors.moderate,
      },
      {
        min: 50,
        max: 74,
        level: 'partiallyIndependent',
        label: 'مستقل جزئياً',
        color: assessmentColors.mild,
      },
      { min: 75, max: 100, level: 'independent', label: 'مستقل', color: assessmentColors.normal },
    ],
  },
  {
    id: 'communication',
    name: 'مقياس التواصل',
    nameEn: 'Communication Scale',
    description: 'تقييم مهارات التواصل اللفظي وغير اللفظي والكتابي',
    maxScore: 100,
    icon: 'RecordVoiceOver',
    color: statusColors.purple,
    domains: [
      { key: 'comprehension', name: 'الفهم', maxScore: 20 },
      { key: 'expression', name: 'التعبير', maxScore: 20 },
      { key: 'reading', name: 'القراءة', maxScore: 20 },
      { key: 'writing', name: 'الكتابة', maxScore: 20 },
      { key: 'nonVerbal', name: 'التواصل غير اللفظي', maxScore: 20 },
    ],
    interpretation: [
      { min: 0, max: 24, level: 'severe', label: 'صعوبة شديدة', color: assessmentColors.severe },
      {
        min: 25,
        max: 49,
        level: 'moderate',
        label: 'صعوبة متوسطة',
        color: assessmentColors.moderate,
      },
      { min: 50, max: 74, level: 'mild', label: 'صعوبة خفيفة', color: assessmentColors.mild },
      { min: 75, max: 100, level: 'functional', label: 'وظيفي', color: assessmentColors.normal },
    ],
  },
  {
    id: 'adaptiveBehavior',
    name: 'مقياس السلوك التكيفي',
    nameEn: 'Adaptive Behavior Scale',
    description: 'تقييم المهارات الاجتماعية والأكاديمية والعملية',
    maxScore: 100,
    icon: 'Psychology',
    color: assessmentColors.moderate,
    domains: [
      { key: 'socialSkills', name: 'المهارات الاجتماعية', maxScore: 34 },
      { key: 'academicSkills', name: 'المهارات الأكاديمية', maxScore: 33 },
      { key: 'practicalSkills', name: 'المهارات العملية', maxScore: 33 },
    ],
    interpretation: [
      {
        min: 0,
        max: 24,
        level: 'significantDeficit',
        label: 'قصور كبير',
        color: assessmentColors.severe,
      },
      {
        min: 25,
        max: 49,
        level: 'moderateDeficit',
        label: 'قصور متوسط',
        color: assessmentColors.moderate,
      },
      { min: 50, max: 74, level: 'mildDeficit', label: 'قصور خفيف', color: assessmentColors.mild },
      { min: 75, max: 100, level: 'adequate', label: 'كافٍ', color: assessmentColors.normal },
    ],
  },
  {
    id: 'qualityOfLife',
    name: 'مقياس جودة الحياة',
    nameEn: 'Quality of Life Scale',
    description: 'تقييم مستوى جودة الحياة من الجوانب البدنية والنفسية والاجتماعية',
    maxScore: 100,
    icon: 'Favorite',
    color: assessmentColors.severe,
    domains: [
      { key: 'physicalHealth', name: 'الصحة البدنية', maxScore: 25 },
      { key: 'mentalHealth', name: 'الصحة النفسية', maxScore: 25 },
      { key: 'socialRelations', name: 'العلاقات الاجتماعية', maxScore: 25 },
      { key: 'environment', name: 'البيئة', maxScore: 25 },
    ],
    interpretation: [
      { min: 0, max: 24, level: 'poor', label: 'ضعيفة', color: assessmentColors.severe },
      {
        min: 25,
        max: 49,
        level: 'belowAverage',
        label: 'دون المتوسط',
        color: assessmentColors.moderate,
      },
      { min: 50, max: 74, level: 'average', label: 'متوسطة', color: assessmentColors.mild },
      { min: 75, max: 100, level: 'good', label: 'جيدة', color: assessmentColors.normal },
    ],
  },

  /* ────────────────── 6. Sensory Profile Scale ────────────────── */
  {
    id: 'sensoryProfile',
    name: 'مقياس الملف الحسي',
    nameEn: 'Sensory Profile Scale',
    description: 'تقييم شامل لأنماط المعالجة الحسية واستجابات الجهاز الحسي في البيئات المختلفة',
    maxScore: 100,
    icon: 'Visibility',
    color: scaleAccentColors.sensoryProfile,
    domains: [
      { key: 'auditory', name: 'المعالجة السمعية', maxScore: 17 },
      { key: 'visual', name: 'المعالجة البصرية', maxScore: 17 },
      { key: 'tactile', name: 'المعالجة اللمسية', maxScore: 17 },
      { key: 'vestibular', name: 'الجهاز الدهليزي', maxScore: 17 },
      { key: 'proprioceptive', name: 'الحس العميق', maxScore: 16 },
      { key: 'oralSensory', name: 'الحس الفموي', maxScore: 16 },
    ],
    interpretation: [
      { min: 0, max: 24, level: 'definite', label: 'اختلاف محدد', color: assessmentColors.severe },
      {
        min: 25,
        max: 49,
        level: 'probable',
        label: 'اختلاف محتمل',
        color: assessmentColors.moderate,
      },
      { min: 50, max: 74, level: 'typical', label: 'نمطي', color: assessmentColors.mild },
      { min: 75, max: 100, level: 'enhanced', label: 'أداء متميز', color: assessmentColors.normal },
    ],
  },

  /* ────────────────── 7. Cognitive Skills Scale ────────────────── */
  {
    id: 'cognitiveSkills',
    name: 'مقياس المهارات المعرفية',
    nameEn: 'Cognitive Skills Scale',
    description: 'تقييم القدرات المعرفية الأساسية: الانتباه والذاكرة والتفكير وحل المشكلات',
    maxScore: 100,
    icon: 'Lightbulb',
    color: scaleAccentColors.cognitive,
    domains: [
      { key: 'attention', name: 'الانتباه والتركيز', maxScore: 20 },
      { key: 'memory', name: 'الذاكرة', maxScore: 20 },
      { key: 'reasoning', name: 'التفكير والاستدلال', maxScore: 20 },
      { key: 'problemSolving', name: 'حل المشكلات', maxScore: 20 },
      { key: 'executiveFunction', name: 'الوظائف التنفيذية', maxScore: 20 },
    ],
    interpretation: [
      {
        min: 0,
        max: 24,
        level: 'severeDeficit',
        label: 'قصور شديد',
        color: assessmentColors.severe,
      },
      {
        min: 25,
        max: 49,
        level: 'moderateDeficit',
        label: 'قصور متوسط',
        color: assessmentColors.moderate,
      },
      { min: 50, max: 74, level: 'borderline', label: 'حدّي', color: assessmentColors.mild },
      {
        min: 75,
        max: 100,
        level: 'ageAppropriate',
        label: 'مناسب للعمر',
        color: assessmentColors.normal,
      },
    ],
  },

  /* ────────────────── 8. Developmental Integration Scale ────────────────── */
  {
    id: 'developmentalIntegration',
    name: 'مقياس التكامل النمائي',
    nameEn: 'Developmental Integration Scale',
    description:
      'تقييم متعدد المحاور وفق التصنيف الدولي للأداء والإعاقة (ICF) يشمل النمو الحركي واللغوي والمعرفي والاجتماعي',
    maxScore: 100,
    icon: 'AccountTree',
    color: scaleAccentColors.developmental,
    domains: [
      { key: 'motorDev', name: 'النمو الحركي', maxScore: 20 },
      { key: 'languageDev', name: 'النمو اللغوي', maxScore: 20 },
      { key: 'cognitiveDev', name: 'النمو المعرفي', maxScore: 20 },
      { key: 'socialEmotional', name: 'النمو الاجتماعي العاطفي', maxScore: 20 },
      { key: 'selfHelp', name: 'مهارات المساعدة الذاتية', maxScore: 20 },
    ],
    interpretation: [
      {
        min: 0,
        max: 24,
        level: 'significantDelay',
        label: 'تأخر كبير',
        color: assessmentColors.severe,
      },
      {
        min: 25,
        max: 49,
        level: 'moderateDelay',
        label: 'تأخر متوسط',
        color: assessmentColors.moderate,
      },
      { min: 50, max: 74, level: 'mildDelay', label: 'تأخر طفيف', color: assessmentColors.mild },
      { min: 75, max: 100, level: 'onTrack', label: 'ضمن المعدل', color: assessmentColors.normal },
    ],
  },

  /* ────────────────── 9. Emotional Well-being Scale ────────────────── */
  {
    id: 'emotionalWellbeing',
    name: 'مقياس الصحة النفسية والعاطفية',
    nameEn: 'Emotional Well-being Scale',
    description:
      'تقييم شامل للحالة النفسية والعاطفية يشمل القلق والاكتئاب والتنظيم الانفعالي ومفهوم الذات والتكيف النفسي',
    maxScore: 100,
    icon: 'SelfImprovement',
    color: scaleAccentColors.emotionalWellbeing,
    domains: [
      { key: 'anxiety', name: 'مستوى القلق', maxScore: 20 },
      { key: 'depression', name: 'مؤشرات الاكتئاب', maxScore: 20 },
      { key: 'emotionalRegulation', name: 'التنظيم الانفعالي', maxScore: 20 },
      { key: 'selfConcept', name: 'مفهوم الذات', maxScore: 20 },
      { key: 'copingStrategies', name: 'استراتيجيات التكيف', maxScore: 20 },
    ],
    interpretation: [
      {
        min: 0,
        max: 24,
        level: 'critical',
        label: 'حرج — يحتاج تدخل فوري',
        color: assessmentColors.severe,
      },
      { min: 25, max: 49, level: 'atRisk', label: 'معرّض للخطر', color: assessmentColors.moderate },
      { min: 50, max: 74, level: 'moderate', label: 'مقبول', color: assessmentColors.mild },
      { min: 75, max: 100, level: 'healthy', label: 'صحي', color: assessmentColors.normal },
    ],
  },

  /* ────────────────── 10. Community Participation Scale ────────────────── */
  {
    id: 'communityParticipation',
    name: 'مقياس المشاركة المجتمعية',
    nameEn: 'Community Participation Scale',
    description:
      'تقييم مستوى الاندماج والمشاركة في الأنشطة المجتمعية والوصول إلى الخدمات العامة وفق إطار ICF',
    maxScore: 100,
    icon: 'Groups',
    color: scaleAccentColors.communityParticipation,
    domains: [
      { key: 'socialInclusion', name: 'الاندماج الاجتماعي', maxScore: 20 },
      { key: 'publicServices', name: 'الوصول للخدمات العامة', maxScore: 20 },
      { key: 'recreation', name: 'الأنشطة الترفيهية', maxScore: 20 },
      { key: 'education', name: 'المشاركة التعليمية', maxScore: 20 },
      { key: 'civilRights', name: 'الحقوق المدنية والمناصرة', maxScore: 20 },
    ],
    interpretation: [
      {
        min: 0,
        max: 24,
        level: 'isolated',
        label: 'عزلة شبه كاملة',
        color: assessmentColors.severe,
      },
      {
        min: 25,
        max: 49,
        level: 'limited',
        label: 'مشاركة محدودة',
        color: assessmentColors.moderate,
      },
      { min: 50, max: 74, level: 'partial', label: 'مشاركة جزئية', color: assessmentColors.mild },
      { min: 75, max: 100, level: 'full', label: 'مشاركة فعّالة', color: assessmentColors.normal },
    ],
  },

  /* ────────────────── 11. Vocational Rehabilitation Scale ────────────────── */
  {
    id: 'vocationalRehabilitation',
    name: 'مقياس التأهيل المهني',
    nameEn: 'Vocational Rehabilitation Scale',
    description:
      'تقييم الجاهزية والقدرات المهنية ومهارات العمل والاستعداد للتوظيف أو التدريب المهني',
    maxScore: 100,
    icon: 'Work',
    color: scaleAccentColors.vocationalRehab,
    domains: [
      { key: 'workReadiness', name: 'الجاهزية للعمل', maxScore: 20 },
      { key: 'vocationalSkills', name: 'المهارات المهنية', maxScore: 20 },
      { key: 'workBehavior', name: 'السلوك المهني', maxScore: 20 },
      { key: 'physicalCapacity', name: 'القدرة البدنية للعمل', maxScore: 20 },
      { key: 'workplaceIntegration', name: 'الاندماج في بيئة العمل', maxScore: 20 },
    ],
    interpretation: [
      { min: 0, max: 24, level: 'notReady', label: 'غير جاهز', color: assessmentColors.severe },
      {
        min: 25,
        max: 49,
        level: 'needsPrep',
        label: 'يحتاج تأهيل مكثف',
        color: assessmentColors.moderate,
      },
      { min: 50, max: 74, level: 'developing', label: 'قيد التطوير', color: assessmentColors.mild },
      {
        min: 75,
        max: 100,
        level: 'employable',
        label: 'جاهز للتوظيف',
        color: assessmentColors.normal,
      },
    ],
  },

  /* ────────────────── 12. Family Support Scale ────────────────── */
  {
    id: 'familySupport',
    name: 'مقياس دعم الأسرة',
    nameEn: 'Family Support Scale',
    description:
      'تقييم مستوى الدعم الأسري وقدرة مقدّمي الرعاية والبيئة المنزلية ومشاركة الأسرة في خطة التأهيل',
    maxScore: 100,
    icon: 'FamilyRestroom',
    color: scaleAccentColors.familySupport,
    domains: [
      { key: 'caregiverCapacity', name: 'قدرة مقدّم الرعاية', maxScore: 20 },
      { key: 'homeEnvironment', name: 'البيئة المنزلية', maxScore: 20 },
      { key: 'familyInvolvement', name: 'مشاركة الأسرة في التأهيل', maxScore: 20 },
      { key: 'financialResources', name: 'الموارد المالية', maxScore: 20 },
      { key: 'emotionalSupport', name: 'الدعم العاطفي الأسري', maxScore: 20 },
    ],
    interpretation: [
      { min: 0, max: 24, level: 'minimal', label: 'دعم ضعيف جداً', color: assessmentColors.severe },
      {
        min: 25,
        max: 49,
        level: 'inadequate',
        label: 'دعم غير كافٍ',
        color: assessmentColors.moderate,
      },
      { min: 50, max: 74, level: 'moderate', label: 'دعم متوسط', color: assessmentColors.mild },
      { min: 75, max: 100, level: 'strong', label: 'دعم قوي', color: assessmentColors.normal },
    ],
  },

  /* ────────────────── 13. Assistive Technology Assessment Scale ────────────────── */
  {
    id: 'assistiveTechnology',
    name: 'مقياس التقنيات المساعدة',
    nameEn: 'Assistive Technology Assessment Scale',
    description:
      'تقييم الحاجة للأجهزة والتقنيات المساعدة ومدى ملاءمتها وفعاليتها وقدرة المستفيد على استخدامها',
    maxScore: 100,
    icon: 'Devices',
    color: scaleAccentColors.assistiveTech,
    domains: [
      { key: 'mobilityAids', name: 'أجهزة المساعدة الحركية', maxScore: 20 },
      { key: 'communicationAids', name: 'أجهزة التواصل المعزز', maxScore: 20 },
      { key: 'computerAccess', name: 'إمكانية الوصول الحاسوبي', maxScore: 20 },
      { key: 'dailyLivingAids', name: 'أدوات الحياة اليومية', maxScore: 20 },
      { key: 'environmentalControl', name: 'التحكم البيئي', maxScore: 20 },
    ],
    interpretation: [
      {
        min: 0,
        max: 24,
        level: 'highNeed',
        label: 'حاجة عالية — لا يوجد دعم تقني',
        color: assessmentColors.severe,
      },
      {
        min: 25,
        max: 49,
        level: 'partialNeed',
        label: 'حاجة جزئية',
        color: assessmentColors.moderate,
      },
      { min: 50, max: 74, level: 'adequate', label: 'تغطية كافية', color: assessmentColors.mild },
      {
        min: 75,
        max: 100,
        level: 'optimal',
        label: 'تغطية مثالية',
        color: assessmentColors.normal,
      },
    ],
  },

  /* ────────────────── 14. Functional Independence Measure (FIM) ────────────────── */
  {
    id: 'functionalIndependence',
    name: 'مقياس الاستقلالية الوظيفية (FIM)',
    nameEn: 'Functional Independence Measure',
    description:
      'تقييم مستوى الاستقلالية الوظيفية بناءً على مقياس FIM الدولي المعتمد في العناية الذاتية والتنقل والتواصل والإدراك',
    maxScore: 126,
    icon: 'Accessibility',
    color: scaleAccentColors.functionalIndependence,
    domains: [
      { key: 'selfCare', name: 'العناية الذاتية', maxScore: 42 },
      { key: 'sphincterControl', name: 'التحكم بالمصرّات', maxScore: 14 },
      { key: 'transfers', name: 'الانتقال', maxScore: 21 },
      { key: 'locomotion', name: 'التنقل', maxScore: 14 },
      { key: 'communicationFIM', name: 'التواصل', maxScore: 14 },
      { key: 'socialCognition', name: 'الإدراك الاجتماعي', maxScore: 21 },
    ],
    interpretation: [
      {
        min: 0,
        max: 35,
        level: 'totalAssist',
        label: 'مساعدة كاملة',
        color: assessmentColors.severe,
      },
      {
        min: 36,
        max: 71,
        level: 'modAssist',
        label: 'مساعدة متوسطة',
        color: assessmentColors.moderate,
      },
      {
        min: 72,
        max: 107,
        level: 'minAssist',
        label: 'مساعدة بسيطة',
        color: assessmentColors.mild,
      },
      { min: 108, max: 126, level: 'independent', label: 'مستقل', color: assessmentColors.normal },
    ],
  },

  /* ────────────────── 15. Behavioral Assessment Scale ────────────────── */
  {
    id: 'behavioralAssessment',
    name: 'مقياس التقييم السلوكي',
    nameEn: 'Behavioral Assessment Scale',
    description:
      'تقييم شامل للأنماط السلوكية يشمل السلوكيات التكيفية وغير التكيفية والمحفزات والتدخلات المناسبة',
    maxScore: 100,
    icon: 'TrackChanges',
    color: scaleAccentColors.behavioralAssessment,
    domains: [
      { key: 'adaptiveBehaviors', name: 'السلوكيات التكيفية', maxScore: 20 },
      { key: 'challengingBehaviors', name: 'السلوكيات التحدّية', maxScore: 20 },
      { key: 'selfRegulation', name: 'التنظيم الذاتي', maxScore: 20 },
      { key: 'socialBehavior', name: 'السلوك الاجتماعي', maxScore: 20 },
      { key: 'safetyAwareness', name: 'الوعي بالسلامة', maxScore: 20 },
    ],
    interpretation: [
      {
        min: 0,
        max: 24,
        level: 'severe',
        label: 'سلوك يحتاج تدخل مكثف',
        color: assessmentColors.severe,
      },
      {
        min: 25,
        max: 49,
        level: 'moderate',
        label: 'سلوك يحتاج دعم متوسط',
        color: assessmentColors.moderate,
      },
      {
        min: 50,
        max: 74,
        level: 'mild',
        label: 'سلوك مقبول مع دعم خفيف',
        color: assessmentColors.mild,
      },
      { min: 75, max: 100, level: 'adaptive', label: 'سلوك تكيفي', color: assessmentColors.normal },
    ],
  },

  // ──────── 16. مقياس تقييم الألم ────────
  {
    id: 'painAssessment',
    name: 'مقياس تقييم الألم',
    nameEn: 'Pain Assessment Scale',
    description: 'تقييم شامل لمستوى الألم وتأثيره على الأنشطة اليومية والحالة النفسية',
    maxScore: 100,
    icon: 'LocalHospital',
    color: scaleAccentColors.painAssessment,
    domains: [
      { key: 'intensity', name: 'شدة الألم', nameEn: 'Pain Intensity', maxScore: 20, weight: 0.25 },
      {
        key: 'frequency',
        name: 'تكرار الألم',
        nameEn: 'Pain Frequency',
        maxScore: 20,
        weight: 0.2,
      },
      {
        key: 'dailyImpact',
        name: 'التأثير على الأنشطة اليومية',
        nameEn: 'Daily Activity Impact',
        maxScore: 20,
        weight: 0.25,
      },
      {
        key: 'psychologicalImpact',
        name: 'التأثير النفسي',
        nameEn: 'Psychological Impact',
        maxScore: 20,
        weight: 0.15,
      },
      {
        key: 'copingStrategies',
        name: 'استراتيجيات التعامل',
        nameEn: 'Coping Strategies',
        maxScore: 20,
        weight: 0.15,
      },
    ],
    interpretation: [
      {
        min: 0,
        max: 24,
        level: 'severe',
        label: 'ألم شديد يحتاج تدخل عاجل',
        color: assessmentColors.severe,
      },
      {
        min: 25,
        max: 49,
        level: 'moderate',
        label: 'ألم متوسط يحتاج خطة علاجية',
        color: assessmentColors.moderate,
      },
      {
        min: 50,
        max: 74,
        level: 'mild',
        label: 'ألم خفيف قابل للإدارة',
        color: assessmentColors.mild,
      },
      {
        min: 75,
        max: 100,
        level: 'minimal',
        label: 'ألم بسيط أو منعدم',
        color: assessmentColors.normal,
      },
    ],
  },

  // ──────── 17. مقياس النطق واللغة التفصيلي ────────
  {
    id: 'speechLanguageDetailed',
    name: 'مقياس النطق واللغة التفصيلي',
    nameEn: 'Detailed Speech & Language Scale',
    description: 'تقييم شامل لمهارات النطق واللغة والتواصل ومهارات البلع',
    maxScore: 120,
    icon: 'RecordVoiceOver',
    color: scaleAccentColors.speechLanguageDetailed,
    domains: [
      {
        key: 'articulation',
        name: 'النطق والإخراج',
        nameEn: 'Articulation',
        maxScore: 20,
        weight: 0.2,
      },
      {
        key: 'receptiveLanguage',
        name: 'اللغة الاستقبالية',
        nameEn: 'Receptive Language',
        maxScore: 20,
        weight: 0.18,
      },
      {
        key: 'expressiveLanguage',
        name: 'اللغة التعبيرية',
        nameEn: 'Expressive Language',
        maxScore: 20,
        weight: 0.18,
      },
      {
        key: 'pragmaticLanguage',
        name: 'اللغة الاستخدامية',
        nameEn: 'Pragmatic Language',
        maxScore: 20,
        weight: 0.16,
      },
      {
        key: 'voiceQuality',
        name: 'جودة الصوت',
        nameEn: 'Voice Quality',
        maxScore: 20,
        weight: 0.14,
      },
      {
        key: 'swallowingFunction',
        name: 'وظيفة البلع',
        nameEn: 'Swallowing Function',
        maxScore: 20,
        weight: 0.14,
      },
    ],
    interpretation: [
      {
        min: 0,
        max: 29,
        level: 'severe',
        label: 'اضطراب شديد في النطق واللغة',
        color: assessmentColors.severe,
      },
      {
        min: 30,
        max: 59,
        level: 'moderate',
        label: 'اضطراب متوسط يحتاج علاج مكثف',
        color: assessmentColors.moderate,
      },
      {
        min: 60,
        max: 89,
        level: 'mild',
        label: 'اضطراب خفيف يحتاج متابعة',
        color: assessmentColors.mild,
      },
      {
        min: 90,
        max: 120,
        level: 'normal',
        label: 'نطق ولغة ضمن المعدل الطبيعي',
        color: assessmentColors.normal,
      },
    ],
  },

  // ──────── 18. مقياس النمو للطفولة المبكرة 0-6 ────────
  {
    id: 'earlyChildhoodDevelopment',
    name: 'مقياس النمو للطفولة المبكرة 0-6',
    nameEn: 'Early Childhood Development Scale (0-6)',
    description: 'تقييم شامل لمراحل النمو الأساسية للأطفال من الولادة حتى 6 سنوات',
    maxScore: 140,
    icon: 'ChildCare',
    color: scaleAccentColors.earlyChildhoodDev,
    domains: [
      {
        key: 'grossMotor',
        name: 'الحركة الكبرى',
        nameEn: 'Gross Motor',
        maxScore: 20,
        weight: 0.15,
      },
      {
        key: 'fineMotor',
        name: 'الحركة الدقيقة',
        nameEn: 'Fine Motor',
        maxScore: 20,
        weight: 0.15,
      },
      {
        key: 'cognitiveDev',
        name: 'النمو المعرفي',
        nameEn: 'Cognitive Development',
        maxScore: 20,
        weight: 0.16,
      },
      {
        key: 'languageDev',
        name: 'النمو اللغوي',
        nameEn: 'Language Development',
        maxScore: 20,
        weight: 0.16,
      },
      {
        key: 'socialEmotionalDev',
        name: 'النمو الاجتماعي العاطفي',
        nameEn: 'Social-Emotional',
        maxScore: 20,
        weight: 0.14,
      },
      { key: 'selfCare', name: 'العناية بالذات', nameEn: 'Self-Care', maxScore: 20, weight: 0.12 },
      {
        key: 'playSkills',
        name: 'مهارات اللعب',
        nameEn: 'Play Skills',
        maxScore: 20,
        weight: 0.12,
      },
    ],
    interpretation: [
      {
        min: 0,
        max: 34,
        level: 'severe',
        label: 'تأخر نمائي شديد',
        color: assessmentColors.severe,
      },
      {
        min: 35,
        max: 69,
        level: 'moderate',
        label: 'تأخر نمائي متوسط',
        color: assessmentColors.moderate,
      },
      { min: 70, max: 104, level: 'mild', label: 'تأخر نمائي خفيف', color: assessmentColors.mild },
      {
        min: 105,
        max: 140,
        level: 'normal',
        label: 'نمو طبيعي مناسب للعمر',
        color: assessmentColors.normal,
      },
    ],
  },

  // ──────── 19. مقياس الاحتياجات التعليمية الخاصة ────────
  {
    id: 'specialEducationNeeds',
    name: 'مقياس الاحتياجات التعليمية الخاصة',
    nameEn: 'Special Education Needs Scale',
    description: 'تقييم شامل للاحتياجات التعليمية والدعم الأكاديمي المطلوب',
    maxScore: 120,
    icon: 'School',
    color: scaleAccentColors.specialEducationNeeds,
    domains: [
      {
        key: 'academicSkills',
        name: 'المهارات الأكاديمية',
        nameEn: 'Academic Skills',
        maxScore: 20,
        weight: 0.2,
      },
      {
        key: 'learningProcess',
        name: 'عمليات التعلم',
        nameEn: 'Learning Processes',
        maxScore: 20,
        weight: 0.18,
      },
      {
        key: 'classroomBehavior',
        name: 'السلوك الصفي',
        nameEn: 'Classroom Behavior',
        maxScore: 20,
        weight: 0.16,
      },
      {
        key: 'socialInteraction',
        name: 'التفاعل الاجتماعي',
        nameEn: 'Social Interaction',
        maxScore: 20,
        weight: 0.16,
      },
      {
        key: 'accommodationNeeds',
        name: 'التعديلات المطلوبة',
        nameEn: 'Accommodation Needs',
        maxScore: 20,
        weight: 0.15,
      },
      {
        key: 'transitionPlanning',
        name: 'التخطيط الانتقالي',
        nameEn: 'Transition Planning',
        maxScore: 20,
        weight: 0.15,
      },
    ],
    interpretation: [
      {
        min: 0,
        max: 29,
        level: 'severe',
        label: 'احتياجات تعليمية خاصة شديدة',
        color: assessmentColors.severe,
      },
      {
        min: 30,
        max: 59,
        level: 'moderate',
        label: 'احتياجات تعليمية خاصة متوسطة',
        color: assessmentColors.moderate,
      },
      {
        min: 60,
        max: 89,
        level: 'mild',
        label: 'احتياجات تعليمية خاصة خفيفة',
        color: assessmentColors.mild,
      },
      {
        min: 90,
        max: 120,
        level: 'normal',
        label: 'أداء تعليمي ضمن المعدل الطبيعي',
        color: assessmentColors.normal,
      },
    ],
  },

  // ──────── 20. مقياس فعالية التقنيات المساعدة ────────
  {
    id: 'assistiveTechEffectiveness',
    name: 'مقياس فعالية التقنيات المساعدة',
    nameEn: 'Assistive Technology Effectiveness Scale',
    description: 'تقييم مدى فعالية التقنيات المساعدة المستخدمة ورضا المستفيد',
    maxScore: 120,
    icon: 'Devices',
    color: scaleAccentColors.assistiveTechEffectiveness,
    domains: [
      {
        key: 'deviceUsability',
        name: 'سهولة الاستخدام',
        nameEn: 'Device Usability',
        maxScore: 20,
        weight: 0.18,
      },
      {
        key: 'functionalImprovement',
        name: 'التحسن الوظيفي',
        nameEn: 'Functional Improvement',
        maxScore: 20,
        weight: 0.22,
      },
      {
        key: 'userSatisfaction',
        name: 'رضا المستخدم',
        nameEn: 'User Satisfaction',
        maxScore: 20,
        weight: 0.16,
      },
      {
        key: 'independenceGain',
        name: 'زيادة الاستقلالية',
        nameEn: 'Independence Gain',
        maxScore: 20,
        weight: 0.18,
      },
      {
        key: 'maintenanceAccess',
        name: 'الصيانة والوصول',
        nameEn: 'Maintenance & Access',
        maxScore: 20,
        weight: 0.13,
      },
      {
        key: 'trainingAdequacy',
        name: 'كفاية التدريب',
        nameEn: 'Training Adequacy',
        maxScore: 20,
        weight: 0.13,
      },
    ],
    interpretation: [
      {
        min: 0,
        max: 29,
        level: 'ineffective',
        label: 'تقنية غير فعالة تحتاج استبدال',
        color: assessmentColors.severe,
      },
      {
        min: 30,
        max: 59,
        level: 'partial',
        label: 'فعالية جزئية تحتاج تعديل',
        color: assessmentColors.moderate,
      },
      {
        min: 60,
        max: 89,
        level: 'effective',
        label: 'فعالية جيدة مع توصيات بسيطة',
        color: assessmentColors.mild,
      },
      {
        min: 90,
        max: 120,
        level: 'optimal',
        label: 'فعالية مثالية',
        color: assessmentColors.normal,
      },
    ],
  },

  // ──────── 21. مقياس إرهاق مقدّم الرعاية ────────
  {
    id: 'caregiverBurden',
    name: 'مقياس إرهاق مقدّم الرعاية',
    nameEn: 'Caregiver Burden Scale',
    description: 'تقييم مستوى الإرهاق الجسدي والنفسي والاجتماعي لمقدمي الرعاية',
    maxScore: 120,
    icon: 'VolunteerActivism',
    color: scaleAccentColors.caregiverBurden,
    domains: [
      {
        key: 'physicalBurden',
        name: 'الإرهاق الجسدي',
        nameEn: 'Physical Burden',
        maxScore: 20,
        weight: 0.2,
      },
      {
        key: 'emotionalBurden',
        name: 'الإرهاق النفسي',
        nameEn: 'Emotional Burden',
        maxScore: 20,
        weight: 0.2,
      },
      {
        key: 'socialImpact',
        name: 'التأثير الاجتماعي',
        nameEn: 'Social Impact',
        maxScore: 20,
        weight: 0.16,
      },
      {
        key: 'financialStress',
        name: 'الضغط المالي',
        nameEn: 'Financial Stress',
        maxScore: 20,
        weight: 0.16,
      },
      {
        key: 'timeConstraints',
        name: 'قيود الوقت',
        nameEn: 'Time Constraints',
        maxScore: 20,
        weight: 0.14,
      },
      {
        key: 'supportSatisfaction',
        name: 'الرضا عن الدعم المتاح',
        nameEn: 'Support Satisfaction',
        maxScore: 20,
        weight: 0.14,
      },
    ],
    interpretation: [
      {
        min: 0,
        max: 29,
        level: 'severe',
        label: 'إرهاق شديد يحتاج تدخل فوري',
        color: assessmentColors.severe,
      },
      {
        min: 30,
        max: 59,
        level: 'moderate',
        label: 'إرهاق متوسط يحتاج دعم',
        color: assessmentColors.moderate,
      },
      {
        min: 60,
        max: 89,
        level: 'mild',
        label: 'إرهاق خفيف قابل للإدارة',
        color: assessmentColors.mild,
      },
      {
        min: 90,
        max: 120,
        level: 'minimal',
        label: 'مستوى إرهاق منخفض',
        color: assessmentColors.normal,
      },
    ],
  },

  // ──────── 22. مقياس الجاهزية للدمج الاجتماعي ────────
  {
    id: 'socialIntegrationReadiness',
    name: 'مقياس الجاهزية للدمج الاجتماعي',
    nameEn: 'Social Integration Readiness Scale',
    description: 'تقييم مدى جاهزية المستفيد للاندماج في المجتمع والمشاركة الفاعلة',
    maxScore: 120,
    icon: 'Groups',
    color: scaleAccentColors.socialIntegrationReadiness,
    domains: [
      {
        key: 'communicationReadiness',
        name: 'جاهزية التواصل',
        nameEn: 'Communication Readiness',
        maxScore: 20,
        weight: 0.18,
      },
      {
        key: 'socialSkills',
        name: 'المهارات الاجتماعية',
        nameEn: 'Social Skills',
        maxScore: 20,
        weight: 0.18,
      },
      {
        key: 'communityAccess',
        name: 'الوصول المجتمعي',
        nameEn: 'Community Access',
        maxScore: 20,
        weight: 0.16,
      },
      {
        key: 'selfAdvocacy',
        name: 'المناصرة الذاتية',
        nameEn: 'Self-Advocacy',
        maxScore: 20,
        weight: 0.16,
      },
      {
        key: 'environmentalSupport',
        name: 'الدعم البيئي',
        nameEn: 'Environmental Support',
        maxScore: 20,
        weight: 0.16,
      },
      {
        key: 'culturalParticipation',
        name: 'المشاركة الثقافية',
        nameEn: 'Cultural Participation',
        maxScore: 20,
        weight: 0.16,
      },
    ],
    interpretation: [
      {
        min: 0,
        max: 29,
        level: 'notReady',
        label: 'غير جاهز – يحتاج تأهيل مكثف',
        color: assessmentColors.severe,
      },
      {
        min: 30,
        max: 59,
        level: 'developing',
        label: 'قيد التطوير – يحتاج دعم مستمر',
        color: assessmentColors.moderate,
      },
      {
        min: 60,
        max: 89,
        level: 'approaching',
        label: 'قريب من الجاهزية – دعم خفيف',
        color: assessmentColors.mild,
      },
      {
        min: 90,
        max: 120,
        level: 'ready',
        label: 'جاهز للدمج الاجتماعي',
        color: assessmentColors.normal,
      },
    ],
  },

  // ════════════════════════════════════════════════════════════
  // ── NEW: 10 Enhanced Assessment Scales (مقاييس محسّنة جديدة)
  // ════════════════════════════════════════════════════════════

  {
    id: 'executiveFunction',
    name: 'مقياس الوظائف التنفيذية',
    nameEn: 'Executive Function Scale',
    description:
      'تقييم مهارات التخطيط والتنظيم والمرونة المعرفية والتحكم في الانفعالات والذاكرة العاملة',
    maxScore: 100,
    icon: 'AccountTree',
    color: '#5c6bc0',
    domains: [
      { key: 'planning', name: 'التخطيط والتنظيم', maxScore: 20 },
      { key: 'workingMemory', name: 'الذاكرة العاملة', maxScore: 20 },
      { key: 'inhibition', name: 'التحكم في الانفعالات', maxScore: 20 },
      { key: 'cognitiveFlexibility', name: 'المرونة المعرفية', maxScore: 20 },
      { key: 'taskInitiation', name: 'المبادرة وبدء المهام', maxScore: 20 },
    ],
    interpretation: [
      { min: 0, max: 24, level: 'severe', label: 'ضعف شديد', color: assessmentColors.severe },
      { min: 25, max: 49, level: 'moderate', label: 'ضعف متوسط', color: assessmentColors.moderate },
      { min: 50, max: 74, level: 'mild', label: 'ضعف خفيف', color: assessmentColors.mild },
      { min: 75, max: 100, level: 'normal', label: 'طبيعي', color: assessmentColors.normal },
    ],
  },
  {
    id: 'sensoryProcessing',
    name: 'مقياس المعالجة الحسية',
    nameEn: 'Sensory Processing Scale',
    description:
      'تقييم استجابة الجهاز الحسي للمثيرات البصرية والسمعية واللمسية والحركية والدهليزية',
    maxScore: 120,
    icon: 'Sensors',
    color: '#00897b',
    domains: [
      { key: 'visual', name: 'المعالجة البصرية', maxScore: 20 },
      { key: 'auditory', name: 'المعالجة السمعية', maxScore: 20 },
      { key: 'tactile', name: 'المعالجة اللمسية', maxScore: 20 },
      { key: 'vestibular', name: 'الجهاز الدهليزي', maxScore: 20 },
      { key: 'proprioceptive', name: 'الحس العميق', maxScore: 20 },
      { key: 'oralSensory', name: 'الحس الفموي', maxScore: 20 },
    ],
    interpretation: [
      {
        min: 0,
        max: 29,
        level: 'definite',
        label: 'صعوبة حسية مؤكدة',
        color: assessmentColors.severe,
      },
      {
        min: 30,
        max: 59,
        level: 'probable',
        label: 'صعوبة حسية محتملة',
        color: assessmentColors.moderate,
      },
      {
        min: 60,
        max: 89,
        level: 'typical',
        label: 'أداء حسي نموذجي',
        color: assessmentColors.mild,
      },
      {
        min: 90,
        max: 120,
        level: 'enhanced',
        label: 'معالجة حسية متميزة',
        color: assessmentColors.normal,
      },
    ],
  },
  {
    id: 'emotionalRegulation',
    name: 'مقياس التنظيم الانفعالي',
    nameEn: 'Emotional Regulation Scale',
    description: 'تقييم القدرة على التعرف على المشاعر وتنظيمها والتعبير عنها والتعامل مع الإحباط',
    maxScore: 100,
    icon: 'SelfImprovement',
    color: '#e91e63',
    domains: [
      { key: 'emotionRecognition', name: 'التعرف على المشاعر', maxScore: 20 },
      { key: 'selfRegulation', name: 'تنظيم الذات', maxScore: 20 },
      { key: 'copingStrategies', name: 'استراتيجيات التأقلم', maxScore: 20 },
      { key: 'frustrationTolerance', name: 'تحمل الإحباط', maxScore: 20 },
      { key: 'emotionalExpression', name: 'التعبير الانفعالي', maxScore: 20 },
    ],
    interpretation: [
      {
        min: 0,
        max: 24,
        level: 'severe',
        label: 'صعوبة شديدة في التنظيم',
        color: assessmentColors.severe,
      },
      {
        min: 25,
        max: 49,
        level: 'moderate',
        label: 'صعوبة متوسطة',
        color: assessmentColors.moderate,
      },
      {
        min: 50,
        max: 74,
        level: 'developing',
        label: 'قيد التطور',
        color: assessmentColors.mild,
      },
      {
        min: 75,
        max: 100,
        level: 'regulated',
        label: 'تنظيم انفعالي جيد',
        color: assessmentColors.normal,
      },
    ],
  },
  {
    id: 'familyNeedsAssessment',
    name: 'مقياس احتياجات الأسرة',
    nameEn: 'Family Needs Assessment Scale',
    description: 'تقييم شامل لاحتياجات الأسرة من الدعم النفسي والمعلوماتي والمادي والاجتماعي',
    maxScore: 100,
    icon: 'FamilyRestroom',
    color: '#6d4c41',
    domains: [
      { key: 'informationNeeds', name: 'احتياجات معلوماتية', maxScore: 20 },
      { key: 'supportNeeds', name: 'الدعم النفسي والاجتماعي', maxScore: 20 },
      { key: 'financialNeeds', name: 'الاحتياجات المادية', maxScore: 20 },
      { key: 'communityService', name: 'الخدمات المجتمعية', maxScore: 20 },
      { key: 'familyFunction', name: 'وظائف الأسرة', maxScore: 20 },
    ],
    interpretation: [
      {
        min: 0,
        max: 24,
        level: 'critical',
        label: 'احتياجات حرجة',
        color: assessmentColors.severe,
      },
      {
        min: 25,
        max: 49,
        level: 'significant',
        label: 'احتياجات كبيرة',
        color: assessmentColors.moderate,
      },
      {
        min: 50,
        max: 74,
        level: 'moderate',
        label: 'احتياجات متوسطة',
        color: assessmentColors.mild,
      },
      {
        min: 75,
        max: 100,
        level: 'supported',
        label: 'مدعومة بشكل كافٍ',
        color: assessmentColors.normal,
      },
    ],
  },
  {
    id: 'functionalIndependence',
    name: 'مقياس الاستقلالية الوظيفية (FIM)',
    nameEn: 'Functional Independence Measure',
    description: 'تقييم مستوى الاستقلالية في الرعاية الذاتية والتنقل والتواصل والإدراك الاجتماعي',
    maxScore: 126,
    icon: 'Accessibility',
    color: '#00838f',
    domains: [
      { key: 'selfCare', name: 'العناية الذاتية', maxScore: 42 },
      { key: 'sphincter', name: 'التحكم في الإخراج', maxScore: 14 },
      { key: 'mobility', name: 'التنقل', maxScore: 21 },
      { key: 'locomotion', name: 'الحركة الانتقالية', maxScore: 14 },
      { key: 'communicationFIM', name: 'التواصل', maxScore: 14 },
      { key: 'socialCognition', name: 'الإدراك الاجتماعي', maxScore: 21 },
    ],
    interpretation: [
      {
        min: 18,
        max: 35,
        level: 'totalAssist',
        label: 'يحتاج مساعدة كاملة',
        color: assessmentColors.severe,
      },
      {
        min: 36,
        max: 71,
        level: 'maxAssist',
        label: 'يحتاج مساعدة كبيرة',
        color: assessmentColors.moderate,
      },
      {
        min: 72,
        max: 107,
        level: 'modAssist',
        label: 'يحتاج مساعدة متوسطة',
        color: assessmentColors.mild,
      },
      {
        min: 108,
        max: 126,
        level: 'independent',
        label: 'مستقل',
        color: assessmentColors.normal,
      },
    ],
  },
  {
    id: 'qualityOfLife',
    name: 'مقياس جودة الحياة',
    nameEn: 'Quality of Life Scale',
    description: 'تقييم جودة الحياة في الجوانب الجسدية والنفسية والاجتماعية والبيئية والروحية',
    maxScore: 100,
    icon: 'Favorite',
    color: '#c62828',
    domains: [
      { key: 'physicalHealth', name: 'الصحة الجسدية', maxScore: 20 },
      { key: 'psychologicalWellbeing', name: 'الصحة النفسية', maxScore: 20 },
      { key: 'socialRelationships', name: 'العلاقات الاجتماعية', maxScore: 20 },
      { key: 'environmentQuality', name: 'البيئة المحيطة', maxScore: 20 },
      { key: 'personalSatisfaction', name: 'الرضا الشخصي', maxScore: 20 },
    ],
    interpretation: [
      { min: 0, max: 24, level: 'poor', label: 'جودة ضعيفة', color: assessmentColors.severe },
      {
        min: 25,
        max: 49,
        level: 'moderate',
        label: 'جودة متوسطة',
        color: assessmentColors.moderate,
      },
      { min: 50, max: 74, level: 'good', label: 'جودة جيدة', color: assessmentColors.mild },
      {
        min: 75,
        max: 100,
        level: 'excellent',
        label: 'جودة ممتازة',
        color: assessmentColors.normal,
      },
    ],
  },
  {
    id: 'autismSeverity',
    name: 'مقياس شدة أعراض التوحد (CARS)',
    nameEn: 'Childhood Autism Rating Scale',
    description:
      'تقييم شدة أعراض التوحد في العلاقات الاجتماعية والتقليد والاستجابة العاطفية والتواصل',
    maxScore: 60,
    icon: 'Extension',
    color: '#7b1fa2',
    domains: [
      { key: 'socialRelating', name: 'العلاقات الاجتماعية', maxScore: 8 },
      { key: 'imitation', name: 'التقليد', maxScore: 8 },
      { key: 'emotionalResponse', name: 'الاستجابة العاطفية', maxScore: 8 },
      { key: 'bodyUse', name: 'استخدام الجسم', maxScore: 8 },
      { key: 'objectUse', name: 'استخدام الأشياء', maxScore: 8 },
      { key: 'verbalCommunication', name: 'التواصل اللفظي', maxScore: 8 },
      { key: 'nonverbalCommunication', name: 'التواصل غير اللفظي', maxScore: 12 },
    ],
    interpretation: [
      {
        min: 15,
        max: 29,
        level: 'nonAutistic',
        label: 'لا يوجد توحد',
        color: assessmentColors.normal,
      },
      {
        min: 30,
        max: 36,
        level: 'mildModerate',
        label: 'توحد خفيف إلى متوسط',
        color: assessmentColors.mild,
      },
      {
        min: 37,
        max: 60,
        level: 'severe',
        label: 'توحد شديد',
        color: assessmentColors.severe,
      },
    ],
  },
  {
    id: 'attentionDeficit',
    name: 'مقياس نقص الانتباه وفرط الحركة',
    nameEn: 'ADHD Rating Scale',
    description: 'تقييم أعراض نقص الانتباه وفرط الحركة والاندفاعية حسب معايير DSM-5',
    maxScore: 54,
    icon: 'FlashOn',
    color: '#f57c00',
    domains: [
      { key: 'inattention', name: 'نقص الانتباه', maxScore: 27 },
      { key: 'hyperactivity', name: 'فرط الحركة والاندفاعية', maxScore: 27 },
    ],
    interpretation: [
      {
        min: 0,
        max: 13,
        level: 'minimal',
        label: 'أعراض ضمن الحدود الطبيعية',
        color: assessmentColors.normal,
      },
      {
        min: 14,
        max: 27,
        level: 'mild',
        label: 'أعراض خفيفة',
        color: assessmentColors.mild,
      },
      {
        min: 28,
        max: 40,
        level: 'moderate',
        label: 'أعراض متوسطة',
        color: assessmentColors.moderate,
      },
      {
        min: 41,
        max: 54,
        level: 'severe',
        label: 'أعراض شديدة',
        color: assessmentColors.severe,
      },
    ],
  },
  {
    id: 'speechLanguage',
    name: 'مقياس النطق واللغة الشامل',
    nameEn: 'Comprehensive Speech-Language Scale',
    description: 'تقييم مهارات النطق والطلاقة والفهم اللغوي والتعبير اللغوي والبراغماتية',
    maxScore: 100,
    icon: 'Campaign',
    color: '#0277bd',
    domains: [
      { key: 'articulation', name: 'النطق والمخارج', maxScore: 20 },
      { key: 'fluency', name: 'الطلاقة', maxScore: 20 },
      { key: 'receptiveLanguage', name: 'الفهم اللغوي', maxScore: 20 },
      { key: 'expressiveLanguage', name: 'التعبير اللغوي', maxScore: 20 },
      { key: 'pragmatics', name: 'البراغماتية', maxScore: 20 },
    ],
    interpretation: [
      {
        min: 0,
        max: 24,
        level: 'severe',
        label: 'اضطراب شديد',
        color: assessmentColors.severe,
      },
      {
        min: 25,
        max: 49,
        level: 'moderate',
        label: 'اضطراب متوسط',
        color: assessmentColors.moderate,
      },
      {
        min: 50,
        max: 74,
        level: 'mild',
        label: 'اضطراب خفيف',
        color: assessmentColors.mild,
      },
      {
        min: 75,
        max: 100,
        level: 'normal',
        label: 'مستوى طبيعي',
        color: assessmentColors.normal,
      },
    ],
  },
  {
    id: 'transitionReadiness',
    name: 'مقياس الجاهزية للانتقال المرحلي',
    nameEn: 'Transition Readiness Assessment',
    description:
      'تقييم جاهزية المستفيد للانتقال بين المراحل (مثل: من التعليم إلى العمل، أو من المركز إلى المجتمع)',
    maxScore: 100,
    icon: 'TrendingUp',
    color: '#2e7d32',
    domains: [
      { key: 'selfAdvocacy', name: 'المناصرة الذاتية', maxScore: 20 },
      { key: 'dailyLivingSkills', name: 'مهارات الحياة اليومية', maxScore: 20 },
      { key: 'socialCompetence', name: 'الكفاءة الاجتماعية', maxScore: 20 },
      { key: 'workReadiness', name: 'الجاهزية المهنية', maxScore: 20 },
      { key: 'communityNavigation', name: 'التنقل المجتمعي', maxScore: 20 },
    ],
    interpretation: [
      {
        min: 0,
        max: 24,
        level: 'notReady',
        label: 'غير جاهز – تدخل مكثف',
        color: assessmentColors.severe,
      },
      {
        min: 25,
        max: 49,
        level: 'emerging',
        label: 'بداية الاستعداد',
        color: assessmentColors.moderate,
      },
      {
        min: 50,
        max: 74,
        level: 'developing',
        label: 'قيد التطوير',
        color: assessmentColors.mild,
      },
      {
        min: 75,
        max: 100,
        level: 'ready',
        label: 'جاهز للانتقال',
        color: assessmentColors.normal,
      },
    ],
  },

  /* ───────────────────────────────────────────────────────────
   *  مقاييس متخصصة لذوي الإعاقة  (8 مقاييس – 33‑40)
   * ─────────────────────────────────────────────────────────── */

  // 33 — Barthel Index (مؤشر بارثل للأنشطة اليومية)
  {
    id: 'barthelIndex',
    name: 'مؤشر بارثل للأنشطة اليومية',
    nameEn: 'Barthel Index of ADL',
    description:
      'مقياس معياري دولي لتقييم مستوى الاستقلالية في الأنشطة اليومية الأساسية العشر لذوي الإعاقة الجسدية',
    maxScore: 100,
    icon: 'Accessibility',
    color: '#1565c0',
    domains: [
      { key: 'feeding', name: 'تناول الطعام', maxScore: 10 },
      { key: 'bathing', name: 'الاستحمام', maxScore: 5 },
      { key: 'grooming', name: 'العناية الشخصية', maxScore: 5 },
      { key: 'dressing', name: 'ارتداء الملابس', maxScore: 10 },
      { key: 'bowels', name: 'التحكم بالأمعاء', maxScore: 10 },
      { key: 'bladder', name: 'التحكم بالمثانة', maxScore: 10 },
      { key: 'toiletUse', name: 'استخدام المرحاض', maxScore: 10 },
      { key: 'transfers', name: 'الانتقال (سرير/كرسي)', maxScore: 15 },
      { key: 'mobilityLevel', name: 'التنقل', maxScore: 15 },
      { key: 'stairs', name: 'صعود الدرج', maxScore: 10 },
    ],
    interpretation: [
      {
        min: 0,
        max: 20,
        level: 'totalDependence',
        label: 'اعتماد كلي',
        color: assessmentColors.severe,
      },
      {
        min: 21,
        max: 60,
        level: 'severeDependence',
        label: 'اعتماد شديد',
        color: '#e65100',
      },
      {
        min: 61,
        max: 90,
        level: 'moderateDependence',
        label: 'اعتماد متوسط',
        color: assessmentColors.moderate,
      },
      {
        min: 91,
        max: 99,
        level: 'slightDependence',
        label: 'اعتماد طفيف',
        color: assessmentColors.mild,
      },
      {
        min: 100,
        max: 100,
        level: 'independent',
        label: 'مستقل تماماً',
        color: assessmentColors.normal,
      },
    ],
  },

  // 34 — WHODAS 2.0 (مقياس تقييم الإعاقة – منظمة الصحة العالمية)
  {
    id: 'whodas2',
    name: 'مقياس تقييم الإعاقة (WHODAS 2.0)',
    nameEn: 'WHO Disability Assessment Schedule 2.0',
    description:
      'مقياس منظمة الصحة العالمية لتقييم مستوى الإعاقة عبر ستة مجالات وظيفية حسب التصنيف الدولي ICF',
    maxScore: 100,
    icon: 'Public',
    color: '#00695c',
    domains: [
      { key: 'cognition', name: 'الإدراك والفهم', maxScore: 17 },
      { key: 'mobility', name: 'التنقل والحركة', maxScore: 17 },
      { key: 'selfCare', name: 'الرعاية الذاتية', maxScore: 17 },
      { key: 'gettingAlong', name: 'التعامل مع الآخرين', maxScore: 17 },
      { key: 'lifeActivities', name: 'أنشطة الحياة', maxScore: 16 },
      { key: 'participation', name: 'المشاركة المجتمعية', maxScore: 16 },
    ],
    interpretation: [
      {
        min: 0,
        max: 4,
        level: 'none',
        label: 'لا توجد إعاقة',
        color: assessmentColors.normal,
      },
      {
        min: 5,
        max: 24,
        level: 'mild',
        label: 'إعاقة خفيفة',
        color: assessmentColors.mild,
      },
      {
        min: 25,
        max: 49,
        level: 'moderate',
        label: 'إعاقة متوسطة',
        color: assessmentColors.moderate,
      },
      {
        min: 50,
        max: 95,
        level: 'severe',
        label: 'إعاقة شديدة',
        color: assessmentColors.severe,
      },
      {
        min: 96,
        max: 100,
        level: 'complete',
        label: 'إعاقة كاملة',
        color: '#b71c1c',
      },
    ],
  },

  // 35 — Gross Motor Function Classification System (GMFCS)
  {
    id: 'gmfcs',
    name: 'مقياس تصنيف الوظائف الحركية الكبرى (GMFCS)',
    nameEn: 'Gross Motor Function Classification System',
    description:
      'تصنيف القدرات الحركية الكبرى للأطفال ذوي الشلل الدماغي عبر خمسة مستويات وظيفية معيارية',
    maxScore: 100,
    icon: 'DirectionsWalk',
    color: '#4a148c',
    domains: [
      { key: 'selfInitiatedMovement', name: 'الحركة الذاتية', maxScore: 20 },
      { key: 'sitting', name: 'الجلوس والتوازن', maxScore: 20 },
      { key: 'standing', name: 'الوقوف', maxScore: 20 },
      { key: 'walking', name: 'المشي', maxScore: 20 },
      { key: 'wheeledMobility', name: 'التنقل بالكرسي المتحرك', maxScore: 20 },
    ],
    interpretation: [
      {
        min: 0,
        max: 20,
        level: 'levelV',
        label: 'المستوى V – نقل يدوي بالكامل',
        color: assessmentColors.severe,
      },
      {
        min: 21,
        max: 40,
        level: 'levelIV',
        label: 'المستوى IV – تنقل محدود بمساعدة',
        color: '#e65100',
      },
      {
        min: 41,
        max: 60,
        level: 'levelIII',
        label: 'المستوى III – مشي بأدوات مساعدة',
        color: assessmentColors.moderate,
      },
      {
        min: 61,
        max: 80,
        level: 'levelII',
        label: 'المستوى II – مشي مع صعوبات',
        color: assessmentColors.mild,
      },
      {
        min: 81,
        max: 100,
        level: 'levelI',
        label: 'المستوى I – مشي دون قيود',
        color: assessmentColors.normal,
      },
    ],
  },

  // 36 — Vineland Adaptive Behavior (مقياس فاينلاند للسلوك التكيفي)
  {
    id: 'vinelandAdaptive',
    name: 'مقياس فاينلاند للسلوك التكيفي',
    nameEn: 'Vineland Adaptive Behavior Scale (VABS-3)',
    description:
      'تقييم السلوك التكيفي في مجالات التواصل والحياة اليومية والتنشئة الاجتماعية والمهارات الحركية للأفراد ذوي الإعاقة الذهنية والنمائية',
    maxScore: 100,
    icon: 'Psychology',
    color: '#ad1457',
    domains: [
      { key: 'communicationDomain', name: 'التواصل (استقبالي/تعبيري/كتابي)', maxScore: 25 },
      { key: 'dailyLivingSkills', name: 'مهارات الحياة اليومية', maxScore: 25 },
      { key: 'socialization', name: 'التنشئة الاجتماعية', maxScore: 25 },
      { key: 'motorSkills', name: 'المهارات الحركية', maxScore: 25 },
    ],
    interpretation: [
      {
        min: 0,
        max: 20,
        level: 'low',
        label: 'مستوى تكيفي منخفض',
        color: assessmentColors.severe,
      },
      {
        min: 21,
        max: 40,
        level: 'belowAverage',
        label: 'أقل من المتوسط',
        color: assessmentColors.moderate,
      },
      {
        min: 41,
        max: 60,
        level: 'adequate',
        label: 'مستوى تكيفي ملائم',
        color: assessmentColors.mild,
      },
      {
        min: 61,
        max: 80,
        level: 'aboveAverage',
        label: 'فوق المتوسط',
        color: assessmentColors.normal,
      },
      {
        min: 81,
        max: 100,
        level: 'high',
        label: 'مستوى تكيفي مرتفع',
        color: '#1b5e20',
      },
    ],
  },

  // 37 — Spinal Cord Independence Measure (مقياس استقلالية إصابات الحبل الشوكي)
  {
    id: 'scim',
    name: 'مقياس استقلالية إصابات الحبل الشوكي (SCIM III)',
    nameEn: 'Spinal Cord Independence Measure III',
    description:
      'مقياس متخصص لتقييم مستوى الاستقلالية الوظيفية لمصابي الحبل الشوكي في الرعاية الذاتية والتنفس والتنقل',
    maxScore: 100,
    icon: 'Accessible',
    color: '#0d47a1',
    domains: [
      { key: 'selfCare', name: 'الرعاية الذاتية', maxScore: 20 },
      { key: 'respiration', name: 'التنفس والتحكم بالمصرّات', maxScore: 40 },
      { key: 'mobilityRoom', name: 'التنقل في الغرفة والمرحاض', maxScore: 10 },
      { key: 'mobilityIndoors', name: 'التنقل الداخلي والخارجي', maxScore: 30 },
    ],
    interpretation: [
      {
        min: 0,
        max: 25,
        level: 'totalDependence',
        label: 'اعتماد كلي – رعاية دائمة',
        color: assessmentColors.severe,
      },
      {
        min: 26,
        max: 50,
        level: 'highDependence',
        label: 'اعتماد مرتفع',
        color: '#e65100',
      },
      {
        min: 51,
        max: 75,
        level: 'moderateIndependence',
        label: 'استقلالية متوسطة',
        color: assessmentColors.moderate,
      },
      {
        min: 76,
        max: 90,
        level: 'highIndependence',
        label: 'استقلالية مرتفعة',
        color: assessmentColors.mild,
      },
      {
        min: 91,
        max: 100,
        level: 'fullIndependence',
        label: 'استقلالية كاملة',
        color: assessmentColors.normal,
      },
    ],
  },

  // 38 — Functional Independence Measure (مقياس الاستقلالية الوظيفية)
  {
    id: 'functionalIndependence',
    name: 'مقياس الاستقلالية الوظيفية (FIM)',
    nameEn: 'Functional Independence Measure',
    description:
      'مقياس دولي معتمد لتقييم مستوى الاستقلالية الوظيفية في المهارات الحركية والإدراكية لمرضى إعادة التأهيل',
    maxScore: 126,
    icon: 'EmojiPeople',
    color: '#283593',
    domains: [
      { key: 'selfCareMotor', name: 'الرعاية الذاتية', maxScore: 42 },
      { key: 'sphincterControl', name: 'التحكم بالمصرّات', maxScore: 14 },
      { key: 'transfers', name: 'الانتقال والتحويل', maxScore: 21 },
      { key: 'locomotion', name: 'التنقل', maxScore: 14 },
      { key: 'communicationCog', name: 'التواصل', maxScore: 14 },
      { key: 'socialCognition', name: 'الإدراك الاجتماعي', maxScore: 21 },
    ],
    interpretation: [
      {
        min: 18,
        max: 35,
        level: 'totalAssist',
        label: 'مساعدة كاملة',
        color: assessmentColors.severe,
      },
      {
        min: 36,
        max: 53,
        level: 'maxAssist',
        label: 'مساعدة قصوى',
        color: '#e65100',
      },
      {
        min: 54,
        max: 71,
        level: 'modAssist',
        label: 'مساعدة متوسطة',
        color: assessmentColors.moderate,
      },
      {
        min: 72,
        max: 89,
        level: 'minAssist',
        label: 'مساعدة بسيطة',
        color: assessmentColors.mild,
      },
      {
        min: 90,
        max: 107,
        level: 'supervision',
        label: 'إشراف فقط',
        color: '#66bb6a',
      },
      {
        min: 108,
        max: 126,
        level: 'independent',
        label: 'استقلال كامل',
        color: assessmentColors.normal,
      },
    ],
  },

  // 39 — Sensory Profile (مقياس الملف الحسي)
  {
    id: 'sensoryProfile',
    name: 'مقياس الملف الحسي',
    nameEn: 'Sensory Profile Assessment',
    description:
      'تقييم أنماط المعالجة الحسية ومستوى الاستجابة للمثيرات الحسية لدى الأطفال ذوي اضطرابات المعالجة الحسية والتوحد',
    maxScore: 100,
    icon: 'Visibility',
    color: '#e65100',
    domains: [
      { key: 'auditory', name: 'المعالجة السمعية', maxScore: 17 },
      { key: 'visual', name: 'المعالجة البصرية', maxScore: 17 },
      { key: 'tactile', name: 'المعالجة اللمسية', maxScore: 17 },
      { key: 'vestibular', name: 'المعالجة الدهليزية', maxScore: 17 },
      { key: 'oralSensory', name: 'المعالجة الحسية الفموية', maxScore: 16 },
      { key: 'multisensory', name: 'المعالجة متعددة الحواس', maxScore: 16 },
    ],
    interpretation: [
      {
        min: 0,
        max: 24,
        level: 'definite',
        label: 'اختلاف حسي واضح',
        color: assessmentColors.severe,
      },
      {
        min: 25,
        max: 39,
        level: 'probable',
        label: 'اختلاف حسي محتمل',
        color: assessmentColors.moderate,
      },
      {
        min: 40,
        max: 59,
        level: 'typical',
        label: 'معالجة حسية نمطية',
        color: assessmentColors.mild,
      },
      {
        min: 60,
        max: 79,
        level: 'aboveTypical',
        label: 'استجابة حسية جيدة',
        color: assessmentColors.normal,
      },
      {
        min: 80,
        max: 100,
        level: 'optimal',
        label: 'تكامل حسي ممتاز',
        color: '#1b5e20',
      },
    ],
  },

  // 40 — Assistive Technology Assessment (مقياس تقييم التقنيات المساعدة)
  {
    id: 'assistiveTech',
    name: 'مقياس تقييم التقنيات المساعدة',
    nameEn: 'Assistive Technology Assessment Scale',
    description:
      'تقييم مدى الحاجة والكفاءة في استخدام التقنيات المساعدة والأجهزة التعويضية لذوي الإعاقة',
    maxScore: 100,
    icon: 'Devices',
    color: '#37474f',
    domains: [
      { key: 'needsIdentification', name: 'تحديد الاحتياجات', maxScore: 20 },
      { key: 'deviceMatch', name: 'ملاءمة الجهاز/التقنية', maxScore: 20 },
      { key: 'userCompetence', name: 'كفاءة المستخدم', maxScore: 20 },
      { key: 'environmentFit', name: 'ملاءمة البيئة', maxScore: 20 },
      { key: 'functionalGain', name: 'المكسب الوظيفي', maxScore: 20 },
    ],
    interpretation: [
      {
        min: 0,
        max: 24,
        level: 'inadequate',
        label: 'حاجة ماسة للتدخل التقني',
        color: assessmentColors.severe,
      },
      {
        min: 25,
        max: 49,
        level: 'partial',
        label: 'تغطية جزئية للاحتياجات',
        color: assessmentColors.moderate,
      },
      {
        min: 50,
        max: 74,
        level: 'adequate',
        label: 'تغطية ملائمة',
        color: assessmentColors.mild,
      },
      {
        min: 75,
        max: 100,
        level: 'optimal',
        label: 'تكامل تقني ممتاز',
        color: assessmentColors.normal,
      },
    ],
  },
];

export default ASSESSMENT_SCALES;
