/**
 * Assessment Scales — المقاييس المعتمدة (22 مقياساً)
 * Matches backend unified-assessment-service._initializeScales
 */
import { statusColors, assessmentColors, scaleAccentColors } from 'theme/palette';

const ASSESSMENT_SCALES = [
  {
    id: 'motorFunction',
    name: 'مقياس الوظائف الحركية',
    nameEn: 'Motor Function Scale',
    description: 'تقييم شامل للقدرات الحركية الكبرى والدقيقة والتوازن والتنسيق',
    maxScore: 100,
    icon: 'DirectionsRun',
    color: statusColors.primaryBlue,
    domains: [
      { key: 'grossMotor', name: 'الحركة الكبرى', maxScore: 25 },
      { key: 'fineMotor', name: 'الحركة الدقيقة', maxScore: 25 },
      { key: 'balance', name: 'التوازن', maxScore: 25 },
      { key: 'coordination', name: 'التنسيق', maxScore: 25 },
    ],
    interpretation: [
      { min: 0, max: 24, level: 'severe', label: 'شديد', color: assessmentColors.severe },
      { min: 25, max: 49, level: 'moderate', label: 'متوسط', color: assessmentColors.moderate },
      { min: 50, max: 74, level: 'mild', label: 'معتدل', color: assessmentColors.mild },
      { min: 75, max: 100, level: 'normal', label: 'طبيعي', color: assessmentColors.normal },
    ],
  },
  {
    id: 'dailyLiving',
    name: 'مقياس نشاط الحياة اليومية',
    nameEn: 'Daily Living Activities Scale',
    description: 'تقييم مستوى الاستقلالية في أنشطة الحياة اليومية الأساسية',
    maxScore: 100,
    icon: 'Home',
    color: assessmentColors.normal,
    domains: [
      { key: 'eating', name: 'تناول الطعام', maxScore: 20 },
      { key: 'bathing', name: 'الاستحمام', maxScore: 20 },
      { key: 'dressing', name: 'اللبس', maxScore: 20 },
      { key: 'mobility', name: 'التنقل', maxScore: 20 },
      { key: 'hygiene', name: 'النظافة', maxScore: 20 },
    ],
    interpretation: [
      { min: 0, max: 24, level: 'dependent', label: 'معتمد كلياً', color: assessmentColors.severe },
      {
        min: 25,
        max: 49,
        level: 'partiallyDependent',
        label: 'معتمد جزئياً',
        color: assessmentColors.moderate,
      },
      {
        min: 50,
        max: 74,
        level: 'partiallyIndependent',
        label: 'مستقل جزئياً',
        color: assessmentColors.mild,
      },
      { min: 75, max: 100, level: 'independent', label: 'مستقل', color: assessmentColors.normal },
    ],
  },
  {
    id: 'communication',
    name: 'مقياس التواصل',
    nameEn: 'Communication Scale',
    description: 'تقييم مهارات التواصل اللفظي وغير اللفظي والكتابي',
    maxScore: 100,
    icon: 'RecordVoiceOver',
    color: statusColors.purple,
    domains: [
      { key: 'comprehension', name: 'الفهم', maxScore: 20 },
      { key: 'expression', name: 'التعبير', maxScore: 20 },
      { key: 'reading', name: 'القراءة', maxScore: 20 },
      { key: 'writing', name: 'الكتابة', maxScore: 20 },
      { key: 'nonVerbal', name: 'التواصل غير اللفظي', maxScore: 20 },
    ],
    interpretation: [
      { min: 0, max: 24, level: 'severe', label: 'صعوبة شديدة', color: assessmentColors.severe },
      {
        min: 25,
        max: 49,
        level: 'moderate',
        label: 'صعوبة متوسطة',
        color: assessmentColors.moderate,
      },
      { min: 50, max: 74, level: 'mild', label: 'صعوبة خفيفة', color: assessmentColors.mild },
      { min: 75, max: 100, level: 'functional', label: 'وظيفي', color: assessmentColors.normal },
    ],
  },
  {
    id: 'adaptiveBehavior',
    name: 'مقياس السلوك التكيفي',
    nameEn: 'Adaptive Behavior Scale',
    description: 'تقييم المهارات الاجتماعية والأكاديمية والعملية',
    maxScore: 100,
    icon: 'Psychology',
    color: assessmentColors.moderate,
    domains: [
      { key: 'socialSkills', name: 'المهارات الاجتماعية', maxScore: 34 },
      { key: 'academicSkills', name: 'المهارات الأكاديمية', maxScore: 33 },
      { key: 'practicalSkills', name: 'المهارات العملية', maxScore: 33 },
    ],
    interpretation: [
      {
        min: 0,
        max: 24,
        level: 'significantDeficit',
        label: 'قصور كبير',
        color: assessmentColors.severe,
      },
      {
        min: 25,
        max: 49,
        level: 'moderateDeficit',
        label: 'قصور متوسط',
        color: assessmentColors.moderate,
      },
      { min: 50, max: 74, level: 'mildDeficit', label: 'قصور خفيف', color: assessmentColors.mild },
      { min: 75, max: 100, level: 'adequate', label: 'كافٍ', color: assessmentColors.normal },
    ],
  },
  {
    id: 'qualityOfLife',
    name: 'مقياس جودة الحياة',
    nameEn: 'Quality of Life Scale',
    description: 'تقييم مستوى جودة الحياة من الجوانب البدنية والنفسية والاجتماعية',
    maxScore: 100,
    icon: 'Favorite',
    color: assessmentColors.severe,
    domains: [
      { key: 'physicalHealth', name: 'الصحة البدنية', maxScore: 25 },
      { key: 'mentalHealth', name: 'الصحة النفسية', maxScore: 25 },
      { key: 'socialRelations', name: 'العلاقات الاجتماعية', maxScore: 25 },
      { key: 'environment', name: 'البيئة', maxScore: 25 },
    ],
    interpretation: [
      { min: 0, max: 24, level: 'poor', label: 'ضعيفة', color: assessmentColors.severe },
      {
        min: 25,
        max: 49,
        level: 'belowAverage',
        label: 'دون المتوسط',
        color: assessmentColors.moderate,
      },
      { min: 50, max: 74, level: 'average', label: 'متوسطة', color: assessmentColors.mild },
      { min: 75, max: 100, level: 'good', label: 'جيدة', color: assessmentColors.normal },
    ],
  },

  /* ────────────────── 6. Sensory Profile Scale ────────────────── */
  {
    id: 'sensoryProfile',
    name: 'مقياس الملف الحسي',
    nameEn: 'Sensory Profile Scale',
    description: 'تقييم شامل لأنماط المعالجة الحسية واستجابات الجهاز الحسي في البيئات المختلفة',
    maxScore: 100,
    icon: 'Visibility',
    color: scaleAccentColors.sensoryProfile,
    domains: [
      { key: 'auditory', name: 'المعالجة السمعية', maxScore: 17 },
      { key: 'visual', name: 'المعالجة البصرية', maxScore: 17 },
      { key: 'tactile', name: 'المعالجة اللمسية', maxScore: 17 },
      { key: 'vestibular', name: 'الجهاز الدهليزي', maxScore: 17 },
      { key: 'proprioceptive', name: 'الحس العميق', maxScore: 16 },
      { key: 'oralSensory', name: 'الحس الفموي', maxScore: 16 },
    ],
    interpretation: [
      { min: 0, max: 24, level: 'definite', label: 'اختلاف محدد', color: assessmentColors.severe },
      {
        min: 25,
        max: 49,
        level: 'probable',
        label: 'اختلاف محتمل',
        color: assessmentColors.moderate,
      },
      { min: 50, max: 74, level: 'typical', label: 'نمطي', color: assessmentColors.mild },
      { min: 75, max: 100, level: 'enhanced', label: 'أداء متميز', color: assessmentColors.normal },
    ],
  },

  /* ────────────────── 7. Cognitive Skills Scale ────────────────── */
  {
    id: 'cognitiveSkills',
    name: 'مقياس المهارات المعرفية',
    nameEn: 'Cognitive Skills Scale',
    description: 'تقييم القدرات المعرفية الأساسية: الانتباه والذاكرة والتفكير وحل المشكلات',
    maxScore: 100,
    icon: 'Lightbulb',
    color: scaleAccentColors.cognitive,
    domains: [
      { key: 'attention', name: 'الانتباه والتركيز', maxScore: 20 },
      { key: 'memory', name: 'الذاكرة', maxScore: 20 },
      { key: 'reasoning', name: 'التفكير والاستدلال', maxScore: 20 },
      { key: 'problemSolving', name: 'حل المشكلات', maxScore: 20 },
      { key: 'executiveFunction', name: 'الوظائف التنفيذية', maxScore: 20 },
    ],
    interpretation: [
      {
        min: 0,
        max: 24,
        level: 'severeDeficit',
        label: 'قصور شديد',
        color: assessmentColors.severe,
      },
      {
        min: 25,
        max: 49,
        level: 'moderateDeficit',
        label: 'قصور متوسط',
        color: assessmentColors.moderate,
      },
      { min: 50, max: 74, level: 'borderline', label: 'حدّي', color: assessmentColors.mild },
      {
        min: 75,
        max: 100,
        level: 'ageAppropriate',
        label: 'مناسب للعمر',
        color: assessmentColors.normal,
      },
    ],
  },

  /* ────────────────── 8. Developmental Integration Scale ────────────────── */
  {
    id: 'developmentalIntegration',
    name: 'مقياس التكامل النمائي',
    nameEn: 'Developmental Integration Scale',
    description:
      'تقييم متعدد المحاور وفق التصنيف الدولي للأداء والإعاقة (ICF) يشمل النمو الحركي واللغوي والمعرفي والاجتماعي',
    maxScore: 100,
    icon: 'AccountTree',
    color: scaleAccentColors.developmental,
    domains: [
      { key: 'motorDev', name: 'النمو الحركي', maxScore: 20 },
      { key: 'languageDev', name: 'النمو اللغوي', maxScore: 20 },
      { key: 'cognitiveDev', name: 'النمو المعرفي', maxScore: 20 },
      { key: 'socialEmotional', name: 'النمو الاجتماعي العاطفي', maxScore: 20 },
      { key: 'selfHelp', name: 'مهارات المساعدة الذاتية', maxScore: 20 },
    ],
    interpretation: [
      {
        min: 0,
        max: 24,
        level: 'significantDelay',
        label: 'تأخر كبير',
        color: assessmentColors.severe,
      },
      {
        min: 25,
        max: 49,
        level: 'moderateDelay',
        label: 'تأخر متوسط',
        color: assessmentColors.moderate,
      },
      { min: 50, max: 74, level: 'mildDelay', label: 'تأخر طفيف', color: assessmentColors.mild },
      { min: 75, max: 100, level: 'onTrack', label: 'ضمن المعدل', color: assessmentColors.normal },
    ],
  },

  /* ────────────────── 9. Emotional Well-being Scale ────────────────── */
  {
    id: 'emotionalWellbeing',
    name: 'مقياس الصحة النفسية والعاطفية',
    nameEn: 'Emotional Well-being Scale',
    description:
      'تقييم شامل للحالة النفسية والعاطفية يشمل القلق والاكتئاب والتنظيم الانفعالي ومفهوم الذات والتكيف النفسي',
    maxScore: 100,
    icon: 'SelfImprovement',
    color: scaleAccentColors.emotionalWellbeing,
    domains: [
      { key: 'anxiety', name: 'مستوى القلق', maxScore: 20 },
      { key: 'depression', name: 'مؤشرات الاكتئاب', maxScore: 20 },
      { key: 'emotionalRegulation', name: 'التنظيم الانفعالي', maxScore: 20 },
      { key: 'selfConcept', name: 'مفهوم الذات', maxScore: 20 },
      { key: 'copingStrategies', name: 'استراتيجيات التكيف', maxScore: 20 },
    ],
    interpretation: [
      {
        min: 0,
        max: 24,
        level: 'critical',
        label: 'حرج — يحتاج تدخل فوري',
        color: assessmentColors.severe,
      },
      { min: 25, max: 49, level: 'atRisk', label: 'معرّض للخطر', color: assessmentColors.moderate },
      { min: 50, max: 74, level: 'moderate', label: 'مقبول', color: assessmentColors.mild },
      { min: 75, max: 100, level: 'healthy', label: 'صحي', color: assessmentColors.normal },
    ],
  },

  /* ────────────────── 10. Community Participation Scale ────────────────── */
  {
    id: 'communityParticipation',
    name: 'مقياس المشاركة المجتمعية',
    nameEn: 'Community Participation Scale',
    description:
      'تقييم مستوى الاندماج والمشاركة في الأنشطة المجتمعية والوصول إلى الخدمات العامة وفق إطار ICF',
    maxScore: 100,
    icon: 'Groups',
    color: scaleAccentColors.communityParticipation,
    domains: [
      { key: 'socialInclusion', name: 'الاندماج الاجتماعي', maxScore: 20 },
      { key: 'publicServices', name: 'الوصول للخدمات العامة', maxScore: 20 },
      { key: 'recreation', name: 'الأنشطة الترفيهية', maxScore: 20 },
      { key: 'education', name: 'المشاركة التعليمية', maxScore: 20 },
      { key: 'civilRights', name: 'الحقوق المدنية والمناصرة', maxScore: 20 },
    ],
    interpretation: [
      {
        min: 0,
        max: 24,
        level: 'isolated',
        label: 'عزلة شبه كاملة',
        color: assessmentColors.severe,
      },
      {
        min: 25,
        max: 49,
        level: 'limited',
        label: 'مشاركة محدودة',
        color: assessmentColors.moderate,
      },
      { min: 50, max: 74, level: 'partial', label: 'مشاركة جزئية', color: assessmentColors.mild },
      { min: 75, max: 100, level: 'full', label: 'مشاركة فعّالة', color: assessmentColors.normal },
    ],
  },

  /* ────────────────── 11. Vocational Rehabilitation Scale ────────────────── */
  {
    id: 'vocationalRehabilitation',
    name: 'مقياس التأهيل المهني',
    nameEn: 'Vocational Rehabilitation Scale',
    description:
      'تقييم الجاهزية والقدرات المهنية ومهارات العمل والاستعداد للتوظيف أو التدريب المهني',
    maxScore: 100,
    icon: 'Work',
    color: scaleAccentColors.vocationalRehab,
    domains: [
      { key: 'workReadiness', name: 'الجاهزية للعمل', maxScore: 20 },
      { key: 'vocationalSkills', name: 'المهارات المهنية', maxScore: 20 },
      { key: 'workBehavior', name: 'السلوك المهني', maxScore: 20 },
      { key: 'physicalCapacity', name: 'القدرة البدنية للعمل', maxScore: 20 },
      { key: 'workplaceIntegration', name: 'الاندماج في بيئة العمل', maxScore: 20 },
    ],
    interpretation: [
      { min: 0, max: 24, level: 'notReady', label: 'غير جاهز', color: assessmentColors.severe },
      {
        min: 25,
        max: 49,
        level: 'needsPrep',
        label: 'يحتاج تأهيل مكثف',
        color: assessmentColors.moderate,
      },
      { min: 50, max: 74, level: 'developing', label: 'قيد التطوير', color: assessmentColors.mild },
      {
        min: 75,
        max: 100,
        level: 'employable',
        label: 'جاهز للتوظيف',
        color: assessmentColors.normal,
      },
    ],
  },

  /* ────────────────── 12. Family Support Scale ────────────────── */
  {
    id: 'familySupport',
    name: 'مقياس دعم الأسرة',
    nameEn: 'Family Support Scale',
    description:
      'تقييم مستوى الدعم الأسري وقدرة مقدّمي الرعاية والبيئة المنزلية ومشاركة الأسرة في خطة التأهيل',
    maxScore: 100,
    icon: 'FamilyRestroom',
    color: scaleAccentColors.familySupport,
    domains: [
      { key: 'caregiverCapacity', name: 'قدرة مقدّم الرعاية', maxScore: 20 },
      { key: 'homeEnvironment', name: 'البيئة المنزلية', maxScore: 20 },
      { key: 'familyInvolvement', name: 'مشاركة الأسرة في التأهيل', maxScore: 20 },
      { key: 'financialResources', name: 'الموارد المالية', maxScore: 20 },
      { key: 'emotionalSupport', name: 'الدعم العاطفي الأسري', maxScore: 20 },
    ],
    interpretation: [
      { min: 0, max: 24, level: 'minimal', label: 'دعم ضعيف جداً', color: assessmentColors.severe },
      {
        min: 25,
        max: 49,
        level: 'inadequate',
        label: 'دعم غير كافٍ',
        color: assessmentColors.moderate,
      },
      { min: 50, max: 74, level: 'moderate', label: 'دعم متوسط', color: assessmentColors.mild },
      { min: 75, max: 100, level: 'strong', label: 'دعم قوي', color: assessmentColors.normal },
    ],
  },

  /* ────────────────── 13. Assistive Technology Assessment Scale ────────────────── */
  {
    id: 'assistiveTechnology',
    name: 'مقياس التقنيات المساعدة',
    nameEn: 'Assistive Technology Assessment Scale',
    description:
      'تقييم الحاجة للأجهزة والتقنيات المساعدة ومدى ملاءمتها وفعاليتها وقدرة المستفيد على استخدامها',
    maxScore: 100,
    icon: 'Devices',
    color: scaleAccentColors.assistiveTech,
    domains: [
      { key: 'mobilityAids', name: 'أجهزة المساعدة الحركية', maxScore: 20 },
      { key: 'communicationAids', name: 'أجهزة التواصل المعزز', maxScore: 20 },
      { key: 'computerAccess', name: 'إمكانية الوصول الحاسوبي', maxScore: 20 },
      { key: 'dailyLivingAids', name: 'أدوات الحياة اليومية', maxScore: 20 },
      { key: 'environmentalControl', name: 'التحكم البيئي', maxScore: 20 },
    ],
    interpretation: [
      {
        min: 0,
        max: 24,
        level: 'highNeed',
        label: 'حاجة عالية — لا يوجد دعم تقني',
        color: assessmentColors.severe,
      },
      {
        min: 25,
        max: 49,
        level: 'partialNeed',
        label: 'حاجة جزئية',
        color: assessmentColors.moderate,
      },
      { min: 50, max: 74, level: 'adequate', label: 'تغطية كافية', color: assessmentColors.mild },
      {
        min: 75,
        max: 100,
        level: 'optimal',
        label: 'تغطية مثالية',
        color: assessmentColors.normal,
      },
    ],
  },

  /* ────────────────── 14. Functional Independence Measure (FIM) ────────────────── */
  {
    id: 'functionalIndependence',
    name: 'مقياس الاستقلالية الوظيفية (FIM)',
    nameEn: 'Functional Independence Measure',
    description:
      'تقييم مستوى الاستقلالية الوظيفية بناءً على مقياس FIM الدولي المعتمد في العناية الذاتية والتنقل والتواصل والإدراك',
    maxScore: 126,
    icon: 'Accessibility',
    color: scaleAccentColors.functionalIndependence,
    domains: [
      { key: 'selfCare', name: 'العناية الذاتية', maxScore: 42 },
      { key: 'sphincterControl', name: 'التحكم بالمصرّات', maxScore: 14 },
      { key: 'transfers', name: 'الانتقال', maxScore: 21 },
      { key: 'locomotion', name: 'التنقل', maxScore: 14 },
      { key: 'communicationFIM', name: 'التواصل', maxScore: 14 },
      { key: 'socialCognition', name: 'الإدراك الاجتماعي', maxScore: 21 },
    ],
    interpretation: [
      {
        min: 0,
        max: 35,
        level: 'totalAssist',
        label: 'مساعدة كاملة',
        color: assessmentColors.severe,
      },
      {
        min: 36,
        max: 71,
        level: 'modAssist',
        label: 'مساعدة متوسطة',
        color: assessmentColors.moderate,
      },
      {
        min: 72,
        max: 107,
        level: 'minAssist',
        label: 'مساعدة بسيطة',
        color: assessmentColors.mild,
      },
      { min: 108, max: 126, level: 'independent', label: 'مستقل', color: assessmentColors.normal },
    ],
  },

  /* ────────────────── 15. Behavioral Assessment Scale ────────────────── */
  {
    id: 'behavioralAssessment',
    name: 'مقياس التقييم السلوكي',
    nameEn: 'Behavioral Assessment Scale',
    description:
      'تقييم شامل للأنماط السلوكية يشمل السلوكيات التكيفية وغير التكيفية والمحفزات والتدخلات المناسبة',
    maxScore: 100,
    icon: 'TrackChanges',
    color: scaleAccentColors.behavioralAssessment,
    domains: [
      { key: 'adaptiveBehaviors', name: 'السلوكيات التكيفية', maxScore: 20 },
      { key: 'challengingBehaviors', name: 'السلوكيات التحدّية', maxScore: 20 },
      { key: 'selfRegulation', name: 'التنظيم الذاتي', maxScore: 20 },
      { key: 'socialBehavior', name: 'السلوك الاجتماعي', maxScore: 20 },
      { key: 'safetyAwareness', name: 'الوعي بالسلامة', maxScore: 20 },
    ],
    interpretation: [
      {
        min: 0,
        max: 24,
        level: 'severe',
        label: 'سلوك يحتاج تدخل مكثف',
        color: assessmentColors.severe,
      },
      {
        min: 25,
        max: 49,
        level: 'moderate',
        label: 'سلوك يحتاج دعم متوسط',
        color: assessmentColors.moderate,
      },
      {
        min: 50,
        max: 74,
        level: 'mild',
        label: 'سلوك مقبول مع دعم خفيف',
        color: assessmentColors.mild,
      },
      { min: 75, max: 100, level: 'adaptive', label: 'سلوك تكيفي', color: assessmentColors.normal },
    ],
  },

  // ──────── 16. مقياس تقييم الألم ────────
  {
    id: 'painAssessment',
    name: 'مقياس تقييم الألم',
    nameEn: 'Pain Assessment Scale',
    description: 'تقييم شامل لمستوى الألم وتأثيره على الأنشطة اليومية والحالة النفسية',
    maxScore: 100,
    icon: 'LocalHospital',
    color: scaleAccentColors.painAssessment,
    domains: [
      { key: 'intensity', name: 'شدة الألم', nameEn: 'Pain Intensity', maxScore: 20, weight: 0.25 },
      {
        key: 'frequency',
        name: 'تكرار الألم',
        nameEn: 'Pain Frequency',
        maxScore: 20,
        weight: 0.2,
      },
      {
        key: 'dailyImpact',
        name: 'التأثير على الأنشطة اليومية',
        nameEn: 'Daily Activity Impact',
        maxScore: 20,
        weight: 0.25,
      },
      {
        key: 'psychologicalImpact',
        name: 'التأثير النفسي',
        nameEn: 'Psychological Impact',
        maxScore: 20,
        weight: 0.15,
      },
      {
        key: 'copingStrategies',
        name: 'استراتيجيات التعامل',
        nameEn: 'Coping Strategies',
        maxScore: 20,
        weight: 0.15,
      },
    ],
    interpretation: [
      {
        min: 0,
        max: 24,
        level: 'severe',
        label: 'ألم شديد يحتاج تدخل عاجل',
        color: assessmentColors.severe,
      },
      {
        min: 25,
        max: 49,
        level: 'moderate',
        label: 'ألم متوسط يحتاج خطة علاجية',
        color: assessmentColors.moderate,
      },
      {
        min: 50,
        max: 74,
        level: 'mild',
        label: 'ألم خفيف قابل للإدارة',
        color: assessmentColors.mild,
      },
      {
        min: 75,
        max: 100,
        level: 'minimal',
        label: 'ألم بسيط أو منعدم',
        color: assessmentColors.normal,
      },
    ],
  },

  // ──────── 17. مقياس النطق واللغة التفصيلي ────────
  {
    id: 'speechLanguageDetailed',
    name: 'مقياس النطق واللغة التفصيلي',
    nameEn: 'Detailed Speech & Language Scale',
    description: 'تقييم شامل لمهارات النطق واللغة والتواصل ومهارات البلع',
    maxScore: 120,
    icon: 'RecordVoiceOver',
    color: scaleAccentColors.speechLanguageDetailed,
    domains: [
      {
        key: 'articulation',
        name: 'النطق والإخراج',
        nameEn: 'Articulation',
        maxScore: 20,
        weight: 0.2,
      },
      {
        key: 'receptiveLanguage',
        name: 'اللغة الاستقبالية',
        nameEn: 'Receptive Language',
        maxScore: 20,
        weight: 0.18,
      },
      {
        key: 'expressiveLanguage',
        name: 'اللغة التعبيرية',
        nameEn: 'Expressive Language',
        maxScore: 20,
        weight: 0.18,
      },
      {
        key: 'pragmaticLanguage',
        name: 'اللغة الاستخدامية',
        nameEn: 'Pragmatic Language',
        maxScore: 20,
        weight: 0.16,
      },
      {
        key: 'voiceQuality',
        name: 'جودة الصوت',
        nameEn: 'Voice Quality',
        maxScore: 20,
        weight: 0.14,
      },
      {
        key: 'swallowingFunction',
        name: 'وظيفة البلع',
        nameEn: 'Swallowing Function',
        maxScore: 20,
        weight: 0.14,
      },
    ],
    interpretation: [
      {
        min: 0,
        max: 29,
        level: 'severe',
        label: 'اضطراب شديد في النطق واللغة',
        color: assessmentColors.severe,
      },
      {
        min: 30,
        max: 59,
        level: 'moderate',
        label: 'اضطراب متوسط يحتاج علاج مكثف',
        color: assessmentColors.moderate,
      },
      {
        min: 60,
        max: 89,
        level: 'mild',
        label: 'اضطراب خفيف يحتاج متابعة',
        color: assessmentColors.mild,
      },
      {
        min: 90,
        max: 120,
        level: 'normal',
        label: 'نطق ولغة ضمن المعدل الطبيعي',
        color: assessmentColors.normal,
      },
    ],
  },

  // ──────── 18. مقياس النمو للطفولة المبكرة 0-6 ────────
  {
    id: 'earlyChildhoodDevelopment',
    name: 'مقياس النمو للطفولة المبكرة 0-6',
    nameEn: 'Early Childhood Development Scale (0-6)',
    description: 'تقييم شامل لمراحل النمو الأساسية للأطفال من الولادة حتى 6 سنوات',
    maxScore: 140,
    icon: 'ChildCare',
    color: scaleAccentColors.earlyChildhoodDev,
    domains: [
      {
        key: 'grossMotor',
        name: 'الحركة الكبرى',
        nameEn: 'Gross Motor',
        maxScore: 20,
        weight: 0.15,
      },
      {
        key: 'fineMotor',
        name: 'الحركة الدقيقة',
        nameEn: 'Fine Motor',
        maxScore: 20,
        weight: 0.15,
      },
      {
        key: 'cognitiveDev',
        name: 'النمو المعرفي',
        nameEn: 'Cognitive Development',
        maxScore: 20,
        weight: 0.16,
      },
      {
        key: 'languageDev',
        name: 'النمو اللغوي',
        nameEn: 'Language Development',
        maxScore: 20,
        weight: 0.16,
      },
      {
        key: 'socialEmotionalDev',
        name: 'النمو الاجتماعي العاطفي',
        nameEn: 'Social-Emotional',
        maxScore: 20,
        weight: 0.14,
      },
      { key: 'selfCare', name: 'العناية بالذات', nameEn: 'Self-Care', maxScore: 20, weight: 0.12 },
      {
        key: 'playSkills',
        name: 'مهارات اللعب',
        nameEn: 'Play Skills',
        maxScore: 20,
        weight: 0.12,
      },
    ],
    interpretation: [
      {
        min: 0,
        max: 34,
        level: 'severe',
        label: 'تأخر نمائي شديد',
        color: assessmentColors.severe,
      },
      {
        min: 35,
        max: 69,
        level: 'moderate',
        label: 'تأخر نمائي متوسط',
        color: assessmentColors.moderate,
      },
      { min: 70, max: 104, level: 'mild', label: 'تأخر نمائي خفيف', color: assessmentColors.mild },
      {
        min: 105,
        max: 140,
        level: 'normal',
        label: 'نمو طبيعي مناسب للعمر',
        color: assessmentColors.normal,
      },
    ],
  },

  // ──────── 19. مقياس الاحتياجات التعليمية الخاصة ────────
  {
    id: 'specialEducationNeeds',
    name: 'مقياس الاحتياجات التعليمية الخاصة',
    nameEn: 'Special Education Needs Scale',
    description: 'تقييم شامل للاحتياجات التعليمية والدعم الأكاديمي المطلوب',
    maxScore: 120,
    icon: 'School',
    color: scaleAccentColors.specialEducationNeeds,
    domains: [
      {
        key: 'academicSkills',
        name: 'المهارات الأكاديمية',
        nameEn: 'Academic Skills',
        maxScore: 20,
        weight: 0.2,
      },
      {
        key: 'learningProcess',
        name: 'عمليات التعلم',
        nameEn: 'Learning Processes',
        maxScore: 20,
        weight: 0.18,
      },
      {
        key: 'classroomBehavior',
        name: 'السلوك الصفي',
        nameEn: 'Classroom Behavior',
        maxScore: 20,
        weight: 0.16,
      },
      {
        key: 'socialInteraction',
        name: 'التفاعل الاجتماعي',
        nameEn: 'Social Interaction',
        maxScore: 20,
        weight: 0.16,
      },
      {
        key: 'accommodationNeeds',
        name: 'التعديلات المطلوبة',
        nameEn: 'Accommodation Needs',
        maxScore: 20,
        weight: 0.15,
      },
      {
        key: 'transitionPlanning',
        name: 'التخطيط الانتقالي',
        nameEn: 'Transition Planning',
        maxScore: 20,
        weight: 0.15,
      },
    ],
    interpretation: [
      {
        min: 0,
        max: 29,
        level: 'severe',
        label: 'احتياجات تعليمية خاصة شديدة',
        color: assessmentColors.severe,
      },
      {
        min: 30,
        max: 59,
        level: 'moderate',
        label: 'احتياجات تعليمية خاصة متوسطة',
        color: assessmentColors.moderate,
      },
      {
        min: 60,
        max: 89,
        level: 'mild',
        label: 'احتياجات تعليمية خاصة خفيفة',
        color: assessmentColors.mild,
      },
      {
        min: 90,
        max: 120,
        level: 'normal',
        label: 'أداء تعليمي ضمن المعدل الطبيعي',
        color: assessmentColors.normal,
      },
    ],
  },

  // ──────── 20. مقياس فعالية التقنيات المساعدة ────────
  {
    id: 'assistiveTechEffectiveness',
    name: 'مقياس فعالية التقنيات المساعدة',
    nameEn: 'Assistive Technology Effectiveness Scale',
    description: 'تقييم مدى فعالية التقنيات المساعدة المستخدمة ورضا المستفيد',
    maxScore: 120,
    icon: 'Devices',
    color: scaleAccentColors.assistiveTechEffectiveness,
    domains: [
      {
        key: 'deviceUsability',
        name: 'سهولة الاستخدام',
        nameEn: 'Device Usability',
        maxScore: 20,
        weight: 0.18,
      },
      {
        key: 'functionalImprovement',
        name: 'التحسن الوظيفي',
        nameEn: 'Functional Improvement',
        maxScore: 20,
        weight: 0.22,
      },
      {
        key: 'userSatisfaction',
        name: 'رضا المستخدم',
        nameEn: 'User Satisfaction',
        maxScore: 20,
        weight: 0.16,
      },
      {
        key: 'independenceGain',
        name: 'زيادة الاستقلالية',
        nameEn: 'Independence Gain',
        maxScore: 20,
        weight: 0.18,
      },
      {
        key: 'maintenanceAccess',
        name: 'الصيانة والوصول',
        nameEn: 'Maintenance & Access',
        maxScore: 20,
        weight: 0.13,
      },
      {
        key: 'trainingAdequacy',
        name: 'كفاية التدريب',
        nameEn: 'Training Adequacy',
        maxScore: 20,
        weight: 0.13,
      },
    ],
    interpretation: [
      {
        min: 0,
        max: 29,
        level: 'ineffective',
        label: 'تقنية غير فعالة تحتاج استبدال',
        color: assessmentColors.severe,
      },
      {
        min: 30,
        max: 59,
        level: 'partial',
        label: 'فعالية جزئية تحتاج تعديل',
        color: assessmentColors.moderate,
      },
      {
        min: 60,
        max: 89,
        level: 'effective',
        label: 'فعالية جيدة مع توصيات بسيطة',
        color: assessmentColors.mild,
      },
      {
        min: 90,
        max: 120,
        level: 'optimal',
        label: 'فعالية مثالية',
        color: assessmentColors.normal,
      },
    ],
  },

  // ──────── 21. مقياس إرهاق مقدّم الرعاية ────────
  {
    id: 'caregiverBurden',
    name: 'مقياس إرهاق مقدّم الرعاية',
    nameEn: 'Caregiver Burden Scale',
    description: 'تقييم مستوى الإرهاق الجسدي والنفسي والاجتماعي لمقدمي الرعاية',
    maxScore: 120,
    icon: 'VolunteerActivism',
    color: scaleAccentColors.caregiverBurden,
    domains: [
      {
        key: 'physicalBurden',
        name: 'الإرهاق الجسدي',
        nameEn: 'Physical Burden',
        maxScore: 20,
        weight: 0.2,
      },
      {
        key: 'emotionalBurden',
        name: 'الإرهاق النفسي',
        nameEn: 'Emotional Burden',
        maxScore: 20,
        weight: 0.2,
      },
      {
        key: 'socialImpact',
        name: 'التأثير الاجتماعي',
        nameEn: 'Social Impact',
        maxScore: 20,
        weight: 0.16,
      },
      {
        key: 'financialStress',
        name: 'الضغط المالي',
        nameEn: 'Financial Stress',
        maxScore: 20,
        weight: 0.16,
      },
      {
        key: 'timeConstraints',
        name: 'قيود الوقت',
        nameEn: 'Time Constraints',
        maxScore: 20,
        weight: 0.14,
      },
      {
        key: 'supportSatisfaction',
        name: 'الرضا عن الدعم المتاح',
        nameEn: 'Support Satisfaction',
        maxScore: 20,
        weight: 0.14,
      },
    ],
    interpretation: [
      {
        min: 0,
        max: 29,
        level: 'severe',
        label: 'إرهاق شديد يحتاج تدخل فوري',
        color: assessmentColors.severe,
      },
      {
        min: 30,
        max: 59,
        level: 'moderate',
        label: 'إرهاق متوسط يحتاج دعم',
        color: assessmentColors.moderate,
      },
      {
        min: 60,
        max: 89,
        level: 'mild',
        label: 'إرهاق خفيف قابل للإدارة',
        color: assessmentColors.mild,
      },
      {
        min: 90,
        max: 120,
        level: 'minimal',
        label: 'مستوى إرهاق منخفض',
        color: assessmentColors.normal,
      },
    ],
  },

  // ──────── 22. مقياس الجاهزية للدمج الاجتماعي ────────
  {
    id: 'socialIntegrationReadiness',
    name: 'مقياس الجاهزية للدمج الاجتماعي',
    nameEn: 'Social Integration Readiness Scale',
    description: 'تقييم مدى جاهزية المستفيد للاندماج في المجتمع والمشاركة الفاعلة',
    maxScore: 120,
    icon: 'Groups',
    color: scaleAccentColors.socialIntegrationReadiness,
    domains: [
      {
        key: 'communicationReadiness',
        name: 'جاهزية التواصل',
        nameEn: 'Communication Readiness',
        maxScore: 20,
        weight: 0.18,
      },
      {
        key: 'socialSkills',
        name: 'المهارات الاجتماعية',
        nameEn: 'Social Skills',
        maxScore: 20,
        weight: 0.18,
      },
      {
        key: 'communityAccess',
        name: 'الوصول المجتمعي',
        nameEn: 'Community Access',
        maxScore: 20,
        weight: 0.16,
      },
      {
        key: 'selfAdvocacy',
        name: 'المناصرة الذاتية',
        nameEn: 'Self-Advocacy',
        maxScore: 20,
        weight: 0.16,
      },
      {
        key: 'environmentalSupport',
        name: 'الدعم البيئي',
        nameEn: 'Environmental Support',
        maxScore: 20,
        weight: 0.16,
      },
      {
        key: 'culturalParticipation',
        name: 'المشاركة الثقافية',
        nameEn: 'Cultural Participation',
        maxScore: 20,
        weight: 0.16,
      },
    ],
    interpretation: [
      {
        min: 0,
        max: 29,
        level: 'notReady',
        label: 'غير جاهز – يحتاج تأهيل مكثف',
        color: assessmentColors.severe,
      },
      {
        min: 30,
        max: 59,
        level: 'developing',
        label: 'قيد التطوير – يحتاج دعم مستمر',
        color: assessmentColors.moderate,
      },
      {
        min: 60,
        max: 89,
        level: 'approaching',
        label: 'قريب من الجاهزية – دعم خفيف',
        color: assessmentColors.mild,
      },
      {
        min: 90,
        max: 120,
        level: 'ready',
        label: 'جاهز للدمج الاجتماعي',
        color: assessmentColors.normal,
      },
    ],
  },
];

export default ASSESSMENT_SCALES;
