/**
 * WorkflowTask — نموذج المهام التلقائية
 *
 * المهام التي يولّدها محرك Workflow عند دخول مراحل جديدة.
 * تُسند تلقائياً للأدوار المناسبة مع تواريخ استحقاق.
 *
 * @module domains/workflow/models/WorkflowTask
 */

const mongoose = require('mongoose');

const workflowTaskSchema = new mongoose.Schema(
  {
    // ─── Context ────────────────────────────────────────────
    beneficiaryId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Beneficiary',
      required: true,
      index: true,
    },
    episodeId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'EpisodeOfCare',
      required: true,
      index: true,
    },

    // ─── Task Info ──────────────────────────────────────────
    type: {
      type: String,
      required: true,
      enum: [
        'collect_documents',
        'schedule_assessment',
        'complete_assessment',
        'mdt_review_meeting',
        'create_care_plan',
        'approve_care_plan',
        'start_sessions',
        'reassessment_due',
        'outcome_review',
        'prepare_discharge',
        'approve_discharge',
        'family_meeting',
        'followup_call',
        'custom',
      ],
      index: true,
    },
    title: { type: String, required: true },
    description: { type: String },

    // ─── Assignment ─────────────────────────────────────────
    assignedRole: {
      type: String,
      enum: [
        'coordinator',
        'social_worker',
        'physician',
        'lead_therapist',
        'therapist',
        'supervisor',
        'family_coordinator',
        'admin',
      ],
    },
    assignedTo: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      index: true,
    },

    // ─── Phase Link ─────────────────────────────────────────
    phase: {
      type: String,
      enum: [
        'referral',
        'intake',
        'triage',
        'initial_assessment',
        'mdt_review',
        'care_plan_approval',
        'active_treatment',
        'reassessment',
        'outcome_review',
        'discharge_planning',
        'discharge',
        'post_discharge_followup',
      ],
    },

    // ─── Priority ───────────────────────────────────────────
    priority: {
      type: String,
      enum: ['low', 'medium', 'high', 'urgent'],
      default: 'medium',
    },

    // ─── Status ─────────────────────────────────────────────
    status: {
      type: String,
      enum: ['pending', 'in_progress', 'completed', 'cancelled', 'overdue'],
      default: 'pending',
      index: true,
    },

    // ─── Dates ──────────────────────────────────────────────
    dueDate: { type: Date, index: true },
    startedAt: Date,
    completedAt: Date,
    cancelledAt: Date,

    // ─── Completion ─────────────────────────────────────────
    completedBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
    completionNotes: String,
    result: mongoose.Schema.Types.Mixed,

    // ─── Auto-Generated ─────────────────────────────────────
    isAutoGenerated: { type: Boolean, default: true },

    // ─── Reminders ──────────────────────────────────────────
    reminders: [
      {
        sentAt: Date,
        channel: { type: String, enum: ['system', 'email', 'sms'] },
      },
    ],

    // ─── Multi-tenant ───────────────────────────────────────
    branchId: { type: mongoose.Schema.Types.ObjectId, ref: 'Branch' },
    organizationId: { type: mongoose.Schema.Types.ObjectId, ref: 'Organization' },
    createdBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
  },
  {
    timestamps: true,
    toJSON: { virtuals: true },
    toObject: { virtuals: true },
  }
);

// ─── Indexes ──────────────────────────────────────────────────────────────

workflowTaskSchema.index({ status: 1, dueDate: 1 });
workflowTaskSchema.index({ assignedTo: 1, status: 1 });
workflowTaskSchema.index({ episodeId: 1, phase: 1 });
workflowTaskSchema.index({ type: 1, status: 1 });

// ─── Virtuals ─────────────────────────────────────────────────────────────

workflowTaskSchema.virtual('isOverdue').get(function () {
  return this.status === 'pending' && this.dueDate && new Date() > this.dueDate;
});

workflowTaskSchema.virtual('daysUntilDue').get(function () {
  if (!this.dueDate) return null;
  return Math.ceil((this.dueDate - Date.now()) / (1000 * 60 * 60 * 24));
});

// ─── Methods ──────────────────────────────────────────────────────────────

workflowTaskSchema.methods.complete = function (userId, notes, result) {
  this.status = 'completed';
  this.completedBy = userId;
  this.completedAt = new Date();
  this.completionNotes = notes;
  this.result = result;
  return this.save();
};

workflowTaskSchema.methods.cancel = function (reason) {
  this.status = 'cancelled';
  this.cancelledAt = new Date();
  this.completionNotes = reason;
  return this.save();
};

// ─── Statics ──────────────────────────────────────────────────────────────

workflowTaskSchema.statics.getTasksDashboard = async function (filters = {}) {
  const match = {};
  if (filters.assignedTo) match.assignedTo = new mongoose.Types.ObjectId(filters.assignedTo);
  if (filters.branchId) match.branchId = new mongoose.Types.ObjectId(filters.branchId);
  if (filters.status) match.status = filters.status;

  return this.aggregate([
    { $match: match },
    {
      $group: {
        _id: '$status',
        count: { $sum: 1 },
        tasks: {
          $push: {
            id: '$_id',
            title: '$title',
            type: '$type',
            dueDate: '$dueDate',
            priority: '$priority',
          },
        },
      },
    },
  ]);
};

workflowTaskSchema.statics.getOverdueTasks = function (branchId) {
  const query = {
    status: 'pending',
    dueDate: { $lt: new Date() },
  };
  if (branchId) query.branchId = branchId;

  return this.find(query)
    .populate('beneficiaryId', 'name fileNumber')
    .populate('assignedTo', 'name role')
    .sort({ dueDate: 1 });
};

const WorkflowTask =
  mongoose.models.WorkflowTask || mongoose.model('WorkflowTask', workflowTaskSchema);

module.exports = WorkflowTask;
